//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                          File 'controller-classes.swift'                                            *
//                                             Generated by version 0.0.1                                              *
//                                          august 30th, 2014, at 22h27'46"                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

import Cocoa

//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*
//   Controller Prefs mFirstName - PMTextField $value                                                                  *
//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*

@objc(Controller_Prefs_mFirstName_PMTextField_value)
class Controller_Prefs_mFirstName_PMTextField_value : NSObject, PMTriggerProtocol {

  weak var mObject : Prefs? = nil
  weak var mOutlet: PMTextField? = nil
  var mSendContinously : Bool

  //-------------------------------------------------------------------------------------------------------------------*

  init (object : Prefs, outlet : PMTextField?, file : String, line : Int, sendContinously : Bool) {
    mObject = object
    mOutlet = outlet
    mSendContinously = sendContinously
    super.init ()
    noteObjectAllocation (self)
    if let outlet = mOutlet {
      outlet.target = self
      outlet.action = "action:"
      if outlet.formatter != nil {
        presentErrorWindow (file, line, "the outlet has a formatter")
      }
      if mSendContinously {
        NSNotificationCenter.defaultCenter().addObserver (self,
          selector: "continouslySendAction:",
          name: NSControlTextDidChangeNotification,
          object: mOutlet
        )
      }
    }
    mObject?.addObserverOf_mFirstName (self)
  }

  //-------------------------------------------------------------------------------------------------------------------*
  
  deinit {
    if mSendContinously {
      NSNotificationCenter.defaultCenter().removeObserver (self,
        name: NSControlTextDidChangeNotification,
        object: mOutlet
      )
    }
    noteObjectDeallocation (self)
    mOutlet?.target = nil
    mOutlet?.action = nil
    mObject?.removeObserverOf_mFirstName (self)
  }
  
  //-------------------------------------------------------------------------------------------------------------------*

  func continouslySendAction (notification : NSNotification) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func trigger () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mFirstName) {
      mOutlet!.stringValue = mObject!.mFirstName
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func action (sender : AnyObject!) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func updateModel () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mFirstName) {
      mObject!.mFirstName = mOutlet!.stringValue
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  var mTransientIndex = kTriggerOutletDisplay

  //-------------------------------------------------------------------------------------------------------------------*

  func noteTransientChanged () {
  }
  
  //-------------------------------------------------------------------------------------------------------------------*
}

//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*
//   Controller Prefs mFullName - PMTextField $value                                                                   *
//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*

@objc(Controller_Prefs_mFullName_PMTextField_value)
class Controller_Prefs_mFullName_PMTextField_value : NSObject, PMTriggerProtocol {

  weak var mObject : Prefs? = nil
  weak var mOutlet: PMTextField? = nil
  var mSendContinously : Bool

  //-------------------------------------------------------------------------------------------------------------------*

  init (object : Prefs, outlet : PMTextField?, file : String, line : Int, sendContinously : Bool) {
    mObject = object
    mOutlet = outlet
    mSendContinously = sendContinously
    super.init ()
    noteObjectAllocation (self)
    if let outlet = mOutlet {
      outlet.target = self
      outlet.action = "action:"
      if outlet.formatter != nil {
        presentErrorWindow (file, line, "the outlet has a formatter")
      }
      if mSendContinously {
        NSNotificationCenter.defaultCenter().addObserver (self,
          selector: "continouslySendAction:",
          name: NSControlTextDidChangeNotification,
          object: mOutlet
        )
      }
    }
    mObject?.addObserverOf_mFullName (self)
  }

  //-------------------------------------------------------------------------------------------------------------------*
  
  deinit {
    if mSendContinously {
      NSNotificationCenter.defaultCenter().removeObserver (self,
        name: NSControlTextDidChangeNotification,
        object: mOutlet
      )
    }
    noteObjectDeallocation (self)
    mOutlet?.target = nil
    mOutlet?.action = nil
    mObject?.removeObserverOf_mFullName (self)
  }
  
  //-------------------------------------------------------------------------------------------------------------------*

  func continouslySendAction (notification : NSNotification) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func trigger () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mFullName) {
      mOutlet!.stringValue = mObject!.mFullName
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func action (sender : AnyObject!) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func updateModel () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mFullName) {
      mObject!.mFullName = mOutlet!.stringValue
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  var mTransientIndex = kTriggerOutletDisplay

  //-------------------------------------------------------------------------------------------------------------------*

  func noteTransientChanged () {
  }
  
  //-------------------------------------------------------------------------------------------------------------------*
}

//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*
//   Controller Prefs mName - PMTextField $value                                                                       *
//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*

@objc(Controller_Prefs_mName_PMTextField_value)
class Controller_Prefs_mName_PMTextField_value : NSObject, PMTriggerProtocol {

  weak var mObject : Prefs? = nil
  weak var mOutlet: PMTextField? = nil
  var mSendContinously : Bool

  //-------------------------------------------------------------------------------------------------------------------*

  init (object : Prefs, outlet : PMTextField?, file : String, line : Int, sendContinously : Bool) {
    mObject = object
    mOutlet = outlet
    mSendContinously = sendContinously
    super.init ()
    noteObjectAllocation (self)
    if let outlet = mOutlet {
      outlet.target = self
      outlet.action = "action:"
      if outlet.formatter != nil {
        presentErrorWindow (file, line, "the outlet has a formatter")
      }
      if mSendContinously {
        NSNotificationCenter.defaultCenter().addObserver (self,
          selector: "continouslySendAction:",
          name: NSControlTextDidChangeNotification,
          object: mOutlet
        )
      }
    }
    mObject?.addObserverOf_mName (self)
  }

  //-------------------------------------------------------------------------------------------------------------------*
  
  deinit {
    if mSendContinously {
      NSNotificationCenter.defaultCenter().removeObserver (self,
        name: NSControlTextDidChangeNotification,
        object: mOutlet
      )
    }
    noteObjectDeallocation (self)
    mOutlet?.target = nil
    mOutlet?.action = nil
    mObject?.removeObserverOf_mName (self)
  }
  
  //-------------------------------------------------------------------------------------------------------------------*

  func continouslySendAction (notification : NSNotification) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func trigger () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mName) {
      mOutlet!.stringValue = mObject!.mName
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func action (sender : AnyObject!) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func updateModel () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mName) {
      mObject!.mName = mOutlet!.stringValue
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  var mTransientIndex = kTriggerOutletDisplay

  //-------------------------------------------------------------------------------------------------------------------*

  func noteTransientChanged () {
  }
  
  //-------------------------------------------------------------------------------------------------------------------*
}

//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*
//   Controller Prefs mUpperCaseFullName - PMTextField $value                                                          *
//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*

@objc(Controller_Prefs_mUpperCaseFullName_PMTextField_value)
class Controller_Prefs_mUpperCaseFullName_PMTextField_value : NSObject, PMTriggerProtocol {

  weak var mObject : Prefs? = nil
  weak var mOutlet: PMTextField? = nil
  var mSendContinously : Bool

  //-------------------------------------------------------------------------------------------------------------------*

  init (object : Prefs, outlet : PMTextField?, file : String, line : Int, sendContinously : Bool) {
    mObject = object
    mOutlet = outlet
    mSendContinously = sendContinously
    super.init ()
    noteObjectAllocation (self)
    if let outlet = mOutlet {
      outlet.target = self
      outlet.action = "action:"
      if outlet.formatter != nil {
        presentErrorWindow (file, line, "the outlet has a formatter")
      }
      if mSendContinously {
        NSNotificationCenter.defaultCenter().addObserver (self,
          selector: "continouslySendAction:",
          name: NSControlTextDidChangeNotification,
          object: mOutlet
        )
      }
    }
    mObject?.addObserverOf_mUpperCaseFullName (self)
  }

  //-------------------------------------------------------------------------------------------------------------------*
  
  deinit {
    if mSendContinously {
      NSNotificationCenter.defaultCenter().removeObserver (self,
        name: NSControlTextDidChangeNotification,
        object: mOutlet
      )
    }
    noteObjectDeallocation (self)
    mOutlet?.target = nil
    mOutlet?.action = nil
    mObject?.removeObserverOf_mUpperCaseFullName (self)
  }
  
  //-------------------------------------------------------------------------------------------------------------------*

  func continouslySendAction (notification : NSNotification) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func trigger () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mUpperCaseFullName) {
      mOutlet!.stringValue = mObject!.mUpperCaseFullName
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func action (sender : AnyObject!) {
    updateModel ()
  }

  //-------------------------------------------------------------------------------------------------------------------*

  func updateModel () {
    if (mOutlet != nil) && (mObject != nil) && (mOutlet!.stringValue != mObject!.mUpperCaseFullName) {
      mObject!.mUpperCaseFullName = mOutlet!.stringValue
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

  var mTransientIndex = kTriggerOutletDisplay

  //-------------------------------------------------------------------------------------------------------------------*

  func noteTransientChanged () {
  }
  
  //-------------------------------------------------------------------------------------------------------------------*
}

//—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————*

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2



