//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                             File 'PMApplication.swift'                                              *
//                                         Generated by version 0.0.1 [debug]                                          *
//                                          september 5th, 2014, at 18h29'3"                                           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------------------------------------------------*

import Cocoa

//---------------------------------------------------------------------------------------------------------------------*

let TRACE_TRANSIENT_TRIGGER = false

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T O P O L O G I C A L    S O R T    O F    P R O P E R T I E S                                                   *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

// preference.Prefs.mUpperCaseFullName = 0
// preference.Prefs.mFullName = 1
// preference.Prefs.mName = 2
// preference.Prefs.mFirstName = 3


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T R A N S I E N T    I N D E X E S                                                                               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

let kTriggerOutletDisplay = 0
let k_preference_2E_Prefs_2E_mUpperCaseFullName = 1
let k_preference_2E_Prefs_2E_mFullName = 2

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T R A N S I E N T    T R I G G E R    C L A S S E S                                                              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTriggerProtocol)
protocol PMTriggerProtocol : NSObjectProtocol {
  var mTransientIndex : Int { get } // Note: we cannot use an enumeration here
  func noteTransientChanged ()
  func trigger ()
  func unregister ()
}


//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTrigger_preference_2E_Prefs_2E_mUpperCaseFullName)
class PMTrigger_preference_2E_Prefs_2E_mUpperCaseFullName : NSObject, PMTriggerProtocol {
  weak var mTriggerObject : Prefs? = nil
  
  var mTransientIndex : Int {
    get {
      return k_preference_2E_Prefs_2E_mUpperCaseFullName
    }
  }
  
  init (object : Prefs) {
    mTriggerObject = object
    super.init ()
    noteObjectAllocation (self) ;
  }

  func unregister () {
  }
  
  deinit {
    noteObjectDeallocation (self) ;
  }

  func noteTransientChanged () {
    if mTriggerObject != nil {
      mTriggerObject!.mUpperCaseFullName_cache = nil
    }
  }
  
  func trigger () {
    mTriggerObject?.preference_2E_Prefs_2E_mUpperCaseFullName_didChange ()
  }
}

//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTrigger_preference_2E_Prefs_2E_mFullName)
class PMTrigger_preference_2E_Prefs_2E_mFullName : NSObject, PMTriggerProtocol {
  weak var mTriggerObject : Prefs? = nil
  
  var mTransientIndex : Int {
    get {
      return k_preference_2E_Prefs_2E_mFullName
    }
  }
  
  init (object : Prefs) {
    mTriggerObject = object
    super.init ()
    noteObjectAllocation (self) ;
  }

  func unregister () {
  }
  
  deinit {
    noteObjectDeallocation (self) ;
  }

  func noteTransientChanged () {
    if mTriggerObject != nil {
      mTriggerObject!.mFullName_cache = nil
    }
  }
  
  func trigger () {
    mTriggerObject?.preference_2E_Prefs_2E_mFullName_didChange ()
  }
}


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T R A N S I E N T    T R I G G E R    F U N C T I O N                                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

func enterTriggerWithObject (inObject : PMTriggerProtocol) {
  var theApp = NSApp as PMApplication
  theApp.enterTriggerWithObject (inObject) ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    R U N    T R I G G E R S                                                                                         *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

func flushTriggers () {
  var theApp = NSApp as PMApplication
  theApp.runTriggers ()
  displayAllocation ()
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    A P P L I C A T I O N    C L A S S                                                                               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

@objc(PMApplication) class PMApplication : NSApplication {
  private var mLevel = 0
  private var mTriggerOutletDisplaySet = NSMutableSet ()
 
  //-------------------------------------------------------------------------------------------------------------------*

  private var mTriggerSet_preference_2E_Prefs_2E_mUpperCaseFullName = NSMutableSet () // 0
  private var mTriggerSet_preference_2E_Prefs_2E_mFullName = NSMutableSet () // 1
  //-------------------------------------------------------------------------------------------------------------------*

  private func enterTriggerWithObject (inObject : PMTriggerProtocol) {
    inObject.noteTransientChanged ()
    let transientIndex = inObject.mTransientIndex
    switch transientIndex {
    case kTriggerOutletDisplay :
      mTriggerOutletDisplaySet.addObject (inObject)
    case k_preference_2E_Prefs_2E_mUpperCaseFullName :
      mTriggerSet_preference_2E_Prefs_2E_mUpperCaseFullName.addObject (inObject)
      if TRACE_TRANSIENT_TRIGGER {
        NSLog ("Trigger preference.Prefs.mUpperCaseFullName, %d objects", mTriggerSet_preference_2E_Prefs_2E_mUpperCaseFullName.count)
      }
    case k_preference_2E_Prefs_2E_mFullName :
      mTriggerSet_preference_2E_Prefs_2E_mFullName.addObject (inObject)
      if TRACE_TRANSIENT_TRIGGER {
        NSLog ("Trigger preference.Prefs.mFullName, %d objects", mTriggerSet_preference_2E_Prefs_2E_mFullName.count)
      }
    default: break
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*
 
  override func sendEvent (inEvent : NSEvent!) {
    mLevel += 1
    // NSLog ("send event %d", mLevel)
    super.sendEvent (inEvent)
    mLevel -= 1
    // NSLog ("send event done %d", mLevel)
    if 0 == mLevel {
      runTriggers ()
      displayAllocation ()
    }
  }
  
  //-------------------------------------------------------------------------------------------------------------------*

  override func sendAction (theAction: Selector, to theTarget: AnyObject!, from sender: AnyObject!) -> Bool {
    mLevel += 1
    // NSLog ("send action %d", mLevel)
    let result = super.sendAction (theAction, to:theTarget, from:sender)
    mLevel -= 1
    // NSLog ("send action done %d", mLevel)
    if 0 == mLevel {
      runTriggers ()
      displayAllocation ()
    }
    return result
  }

  //-------------------------------------------------------------------------------------------------------------------*
  
  private func runTriggers () {
    if mTriggerSet_preference_2E_Prefs_2E_mFullName.count > 0 { // 2
      for anyObject in mTriggerSet_preference_2E_Prefs_2E_mFullName {
        let object = anyObject as PMTriggerProtocol
        object.trigger ()
      }
      mTriggerSet_preference_2E_Prefs_2E_mFullName = NSMutableSet ()
    }    
    if mTriggerSet_preference_2E_Prefs_2E_mUpperCaseFullName.count > 0 { // 1
      for anyObject in mTriggerSet_preference_2E_Prefs_2E_mUpperCaseFullName {
        let object = anyObject as PMTriggerProtocol
        object.trigger ()
      }
      mTriggerSet_preference_2E_Prefs_2E_mUpperCaseFullName = NSMutableSet ()
    }    
    if mTriggerOutletDisplaySet.count > 0 {
      for anyObject in mTriggerOutletDisplaySet {
        let object = anyObject as PMTriggerProtocol
        object.trigger ()
      }
      mTriggerOutletDisplaySet = NSMutableSet ()
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*

}

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

