@objc(protocol_preference_2E_MyPrefs_2E_myPrefString) protocol protocol_preference_2E_MyPrefs_2E_myPrefString {
  func preference_2E_MyPrefs_2E_myPrefString_didChange ()
}

@objc(protocol_preference_2E_MyPrefs_2E_prefTransientString) protocol protocol_preference_2E_MyPrefs_2E_prefTransientString {
  func preference_2E_MyPrefs_2E_prefTransientString_didChange ()
}

@objc(protocol_entity_2E_MyRootEntity_2E_docString) protocol protocol_entity_2E_MyRootEntity_2E_docString {
  func entity_2E_MyRootEntity_2E_docString_didChange ()
}

@objc(protocol_entity_2E_MyRootEntity_2E_otherTransientConcatString) protocol protocol_entity_2E_MyRootEntity_2E_otherTransientConcatString {
  func entity_2E_MyRootEntity_2E_otherTransientConcatString_didChange ()
}

@objc(protocol_entity_2E_MyRootEntity_2E_transientConcatString) protocol protocol_entity_2E_MyRootEntity_2E_transientConcatString {
  func entity_2E_MyRootEntity_2E_transientConcatString_didChange ()
}

