//-----------------------------------------------------------------------------*
//                                                                             *
//                         File 'PMApplication.swift'                          *
//                     Generated by version 0.0.1 [debug]                      *
//                       august 7th, 2014, at 23h59'13"                        *
//                                                                             *
//-----------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

//---------------------------------------------------------------------------------------------------------------------*

import Cocoa

//---------------------------------------------------------------------------------------------------------------------*

let TRACE_TRANSIENT_TRIGGER = false

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T O P O L O G I C A L    S O R T    O F    P R O P E R T I E S                                                   *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

// preference.MyPrefs.prefTransientString = 0
// preference.MyPrefs.myPrefString = 1
// entity.MyRootEntity.otherTransientConcatString = 2
// entity.MyRootEntity.transientConcatString = 3
// entity.MyRootEntity.docString = 4


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T R A N S I E N T    I N D E X E S                                                                               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

let k_preference_2E_MyPrefs_2E_prefTransientString = 0
let k_entity_2E_MyRootEntity_2E_otherTransientConcatString = 1
let k_entity_2E_MyRootEntity_2E_transientConcatString = 2

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T R A N S I E N T    T R I G G E R    C L A S S E S                                                              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTriggerProtocol)
protocol PMTriggerProtocol : NSObjectProtocol {
  var mTransientIndex : Int { get } // Note: we cannot use an enumeration here
  func noteTransientChanged ()
  func trigger ()
}


//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTrigger_preference_2E_MyPrefs_2E_prefTransientString)
class PMTrigger_preference_2E_MyPrefs_2E_prefTransientString : NSObject, PMTriggerProtocol {
  weak var mTriggerObject : MyPrefs? = nil
  
  var mTransientIndex : Int {
    get {
      return k_preference_2E_MyPrefs_2E_prefTransientString
    }
  }
  
  init (object : MyPrefs) {
    mTriggerObject = object
    super.init ()
    noteObjectAllocation (self) ;
  }
  
  deinit {
    noteObjectDeallocation (self) ;
  }

  func noteTransientChanged () {
    if mTriggerObject {
      mTriggerObject!.prefTransientString__cache = nil
    }
  }
  
  func trigger () {
    mTriggerObject?.preference_2E_MyPrefs_2E_prefTransientString_didChange ()
  }
}

//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTrigger_entity_2E_MyRootEntity_2E_otherTransientConcatString)
class PMTrigger_entity_2E_MyRootEntity_2E_otherTransientConcatString : NSObject, PMTriggerProtocol {
  weak var mTriggerObject : MyRootEntity? = nil
  
  var mTransientIndex : Int {
    get {
      return k_entity_2E_MyRootEntity_2E_otherTransientConcatString
    }
  }
  
  init (object : MyRootEntity) {
    mTriggerObject = object
    super.init ()
    noteObjectAllocation (self) ;
  }
  
  deinit {
    noteObjectDeallocation (self) ;
  }

  func noteTransientChanged () {
    if mTriggerObject {
      mTriggerObject!.otherTransientConcatString__cache = nil
    }
  }
  
  func trigger () {
    mTriggerObject?.entity_2E_MyRootEntity_2E_otherTransientConcatString_didChange ()
  }
}

//---------------------------------------------------------------------------------------------------------------------*

@objc(PMTrigger_entity_2E_MyRootEntity_2E_transientConcatString)
class PMTrigger_entity_2E_MyRootEntity_2E_transientConcatString : NSObject, PMTriggerProtocol {
  weak var mTriggerObject : MyRootEntity? = nil
  
  var mTransientIndex : Int {
    get {
      return k_entity_2E_MyRootEntity_2E_transientConcatString
    }
  }
  
  init (object : MyRootEntity) {
    mTriggerObject = object
    super.init ()
    noteObjectAllocation (self) ;
  }
  
  deinit {
    noteObjectDeallocation (self) ;
  }

  func noteTransientChanged () {
    if mTriggerObject {
      mTriggerObject!.transientConcatString__cache = nil
    }
  }
  
  func trigger () {
    mTriggerObject?.entity_2E_MyRootEntity_2E_transientConcatString_didChange ()
  }
}


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    T R A N S I E N T    T R I G G E R    F U N C T I O N                                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

func enterTriggerWithObject (inObject : PMTriggerProtocol) {
  var theApp = NSApp as PMApplication
  theApp.enterTriggerWithObject (inObject) ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//    A P P L I C A T I O N    C L A S S                                                                               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

@objc(PMApplication) class PMApplication : NSApplication {
  var mLevel = 0

  //-------------------------------------------------------------------------------------------------------------------*

  var mTriggerSet_preference_2E_MyPrefs_2E_prefTransientString = NSMutableSet () // 0
  var mTriggerSet_entity_2E_MyRootEntity_2E_otherTransientConcatString = NSMutableSet () // 1
  var mTriggerSet_entity_2E_MyRootEntity_2E_transientConcatString = NSMutableSet () // 2
  //-------------------------------------------------------------------------------------------------------------------*

  func enterTriggerWithObject (inObject : PMTriggerProtocol) {
    inObject.noteTransientChanged ()
    let transientIndex = inObject.mTransientIndex
    switch transientIndex {
    case k_preference_2E_MyPrefs_2E_prefTransientString :
      mTriggerSet_preference_2E_MyPrefs_2E_prefTransientString.addObject (inObject)
      if TRACE_TRANSIENT_TRIGGER {
        NSLog ("Trigger preference.MyPrefs.prefTransientString, %d objects", mTriggerSet_preference_2E_MyPrefs_2E_prefTransientString.count)
      }
    case k_entity_2E_MyRootEntity_2E_otherTransientConcatString :
      mTriggerSet_entity_2E_MyRootEntity_2E_otherTransientConcatString.addObject (inObject)
      if TRACE_TRANSIENT_TRIGGER {
        NSLog ("Trigger entity.MyRootEntity.otherTransientConcatString, %d objects", mTriggerSet_entity_2E_MyRootEntity_2E_otherTransientConcatString.count)
      }
    case k_entity_2E_MyRootEntity_2E_transientConcatString :
      mTriggerSet_entity_2E_MyRootEntity_2E_transientConcatString.addObject (inObject)
      if TRACE_TRANSIENT_TRIGGER {
        NSLog ("Trigger entity.MyRootEntity.transientConcatString, %d objects", mTriggerSet_entity_2E_MyRootEntity_2E_transientConcatString.count)
      }
    default: break
    }
  }

  //-------------------------------------------------------------------------------------------------------------------*
 
  override func sendEvent (inEvent : NSEvent!) {
    mLevel += 1
    // NSLog ("send event %d", mLevel)
    super.sendEvent (inEvent)
    mLevel -= 1
    // NSLog ("send event done %d", mLevel)
    if 0 == mLevel {
      triggerChange ()
      displayAllocation ()
    }
  }
  
  //-------------------------------------------------------------------------------------------------------------------*

  override func sendAction (theAction: Selector, to theTarget: AnyObject!, from sender: AnyObject!) -> Bool {
    mLevel += 1
    // NSLog ("send action %d", mLevel)
    let result = super.sendAction (theAction, to:theTarget, from:sender)
    mLevel -= 1
    // NSLog ("send action done %d", mLevel)
    if 0 == mLevel {
      triggerChange ()
      displayAllocation ()
    }
    return result
  }

  //-------------------------------------------------------------------------------------------------------------------*
  
  func triggerChange () {
    if mTriggerSet_preference_2E_MyPrefs_2E_prefTransientString.count > 0 { // 0
      let s = mTriggerSet_preference_2E_MyPrefs_2E_prefTransientString
      mTriggerSet_preference_2E_MyPrefs_2E_prefTransientString = NSMutableSet ()
      for anyObject in s {
        let object = anyObject as PMTriggerProtocol
        object.trigger ()
      }
    }    
    if mTriggerSet_entity_2E_MyRootEntity_2E_otherTransientConcatString.count > 0 { // 1
      let s = mTriggerSet_entity_2E_MyRootEntity_2E_otherTransientConcatString
      mTriggerSet_entity_2E_MyRootEntity_2E_otherTransientConcatString = NSMutableSet ()
      for anyObject in s {
        let object = anyObject as PMTriggerProtocol
        object.trigger ()
      }
    }    
    if mTriggerSet_entity_2E_MyRootEntity_2E_transientConcatString.count > 0 { // 2
      let s = mTriggerSet_entity_2E_MyRootEntity_2E_transientConcatString
      mTriggerSet_entity_2E_MyRootEntity_2E_transientConcatString = NSMutableSet ()
      for anyObject in s {
        let object = anyObject as PMTriggerProtocol
        object.trigger ()
      }
    }    
  }

  //-------------------------------------------------------------------------------------------------------------------*

}

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

