//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                           File 'MyRootEntity+transient+otherTransientConcatString.swift'                            *
//                                         Generated by version 0.0.1 [debug]                                          *
//                                           march 24th, 2015, at 19h10'53"                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

import Cocoa

//----------------------------------------------------------------------------*

func compute_MyRootEntity_otherTransientConcatString (g_Preferences_21__2E_myPrefString : String) -> String {

//--- START OF USER ZONE 2
  return g_Preferences_21__2E_myPrefString // ADD YOUR CODE HERE
//--- END OF USER ZONE 2

}

//----------------------------------------------------------------------------*
