//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'RootEntityClass.m'                          *
//                    Generated by version 0.0.1 [debug]                     *
//                     december 29th, 2012, at 22h6'46"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#import "easy-bindings-utilities.h"
#import "PMAllocationDebug.h"
#import "PMTransientDependancyManager.h"
#import "RootEntityClass.h"


//----------------------------------------------------------------------------*

@implementation RootEntityClass

//----------------------------------------------------------------------------*
//    Synthesize properties                                                   *
//----------------------------------------------------------------------------*

//--- Attributes

//--- To-one relationships

//--- To-many relationships
@dynamic mNames ; // Set of NameEntity entities

//----------------------------------------------------------------------------*
//    Creation Class Method                                                   *
//----------------------------------------------------------------------------*

+ (RootEntityClass *) pmInsertNewObjectIntoManagedObjectContext:(NSManagedObjectContext *) inContext {
  return [NSEntityDescription insertNewObjectForEntityForName:@"MyRootEntity" inManagedObjectContext:inContext] ;
}

//----------------------------------------------------------------------------*
//    initWithEntity:insertIntoManagedObjectContext:                          *
//----------------------------------------------------------------------------*

- (RootEntityClass *) initWithEntity:(NSEntityDescription *) inEntity
                    insertIntoManagedObjectContext:(NSManagedObjectContext *) inManagedObjectContext {
  self = [super 
    initWithEntity:inEntity
    insertIntoManagedObjectContext:inManagedObjectContext
  ] ;
  if (self) {
  //--- Add Transient observers
  }
  return self ;
}

//----------------------------------------------------------------------------*
//    didTurnIntoFault                                                        *
//----------------------------------------------------------------------------*

- (void) didTurnIntoFault {
//--- Remove Transient observers
//---
  [super didTurnIntoFault] ;
}

//----------------------------------------------------------------------------*
//    didChangeValueForKey:                                                   *
//----------------------------------------------------------------------------*

- (void) didChangeValueForKey: (NSString *) inKey {
  [super didChangeValueForKey:inKey] ;
  [self pmKeyDidChange:inKey] ;
}

//----------------------------------------------------------------------------*
//    didChangeValueForKey:withSetMutation:usingObjects:                      *
//----------------------------------------------------------------------------*

- (void) didChangeValueForKey: (NSString *) inKey
         withSetMutation: (NSKeyValueSetMutationKind) inMutationKind
         usingObjects: (NSSet *) inObjects {
  [super
    didChangeValueForKey:inKey
    withSetMutation: inMutationKind
    usingObjects: inObjects
  ] ;
  [self pmKeyDidChange:inKey] ;
}

//----------------------------------------------------------------------------*
//    pmKeyDidChange:                                                         *
//----------------------------------------------------------------------------*

- (void) pmKeyDidChange: (NSString *) inKey {
  if ([inKey isEqualToString:@"mNames"]) {
    [mNames_observers makeObjectsPerformSelector:@selector (entity_2E_MyRootEntity_2E_mNames_didChange)] ;
  }
}

//----------------------------------------------------------------------------*

- (void) addObserverOf_mNames: (NSObject *) inObserver {
  if (nil == mNames_observers) {
    mNames_observers = [NSMutableSet new] ;
  }
  [mNames_observers addObject:inObserver] ;
  [inObserver performSelector:@selector (entity_2E_MyRootEntity_2E_mNames_didChange)] ;
}

//----------------------------------------------------------------------------*

- (void) removeObserverOf_mNames: (NSObject *) inObserver {
  [mNames_observers removeObject:inObserver] ;
  [inObserver performSelector:@selector (entity_2E_MyRootEntity_2E_mNames_didChange)] ;
}

//----------------------------------------------------------------------------*

//--- START OF USER ZONE 2

//--- END OF USER ZONE 2

@end
