//---------------------------------------------------------------------------*
//                                                                           *
//                 File 'attributeDeclarationAnalysis.cpp'                   *
//                        Generated by version 2.5.0                         *
//                       july 19th, 2013, at 13h7'49"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "attributeDeclarationAnalysis.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "attributeDeclarationAnalysis.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//                   Routine 'buildObservablePropertyMap'                    *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_buildObservablePropertyMap (const GALGAS_attributeList constinArgument_inAttributeList,
                                         const GALGAS_classArrayList constinArgument_inArrayList,
                                         const GALGAS_transientList constinArgument_inTransientList,
                                         const GALGAS_controllerList constinArgument_inControllerList,
                                         const GALGAS_controllerObservablePropertyList constinArgument_inControllerObservablePropertyList,
                                         GALGAS_observablePropertyMapMap & /* ioArgument_ioObservablePropertyMapMap */,
                                         GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                         const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                         const GALGAS_string constinArgument_inObjectName,
                                         GALGAS_observablePropertyMap & ioArgument_ioSelfObservableAttributeMap,
                                         C_Compiler * inCompiler
                                         COMMA_UNUSED_LOCATION_ARGS) {
  cEnumerator_attributeList enumerator_3779 (constinArgument_inAttributeList, kEnumeration_up) ;
  while (enumerator_3779.hasCurrentObject ()) {
    GALGAS_ebType var_type ;
    GALGAS_astDeclaration joker_3848_0 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (enumerator_3779.current_mAttributeTypeName (HERE), var_type, joker_3848_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (115)) ;
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (constinArgument_inObjectName.operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (117)).operator_concat (enumerator_3779.current_mAttributeName (HERE).reader_string (SOURCE_FILE_AT_LINE (117)) COMMA_SOURCE_FILE_AT_LINE (117)), enumerator_3779.current_mAttributeName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (116)) ;
    {
    ioArgument_ioSelfObservableAttributeMap.modifier_insertKey (enumerator_3779.current_mAttributeName (HERE), var_type, GALGAS_bool (false), var_observationDependencyKey, GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE_AT_LINE (120)) ;
    }
    {
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (127)) ;
    }
    enumerator_3779.gotoNextObject () ;
  }
  cEnumerator_classArrayList enumerator_4344 (constinArgument_inArrayList, kEnumeration_up) ;
  while (enumerator_4344.hasCurrentObject ()) {
    GALGAS_ebType var_type ;
    GALGAS_astDeclaration joker_4412_0 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (enumerator_4344.current_mElementClassName (HERE), var_type, joker_4412_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (134)) ;
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (constinArgument_inObjectName.operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (136)).operator_concat (enumerator_4344.current_mArrayName (HERE).reader_string (SOURCE_FILE_AT_LINE (136)) COMMA_SOURCE_FILE_AT_LINE (136)), enumerator_4344.current_mArrayName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (135)) ;
    {
    ioArgument_ioSelfObservableAttributeMap.modifier_insertKey (enumerator_4344.current_mArrayName (HERE), var_type, GALGAS_bool (false), var_observationDependencyKey, GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE_AT_LINE (139)) ;
    }
    {
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (146)) ;
    }
    enumerator_4344.gotoNextObject () ;
  }
  cEnumerator_transientList enumerator_4903 (constinArgument_inTransientList, kEnumeration_up) ;
  while (enumerator_4903.hasCurrentObject ()) {
    GALGAS_ebType var_type ;
    GALGAS_astDeclaration joker_4972_0 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (enumerator_4903.current_mTransientTypeName (HERE), var_type, joker_4972_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (153)) ;
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (constinArgument_inObjectName.operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (155)).operator_concat (enumerator_4903.current_mTransientName (HERE).reader_string (SOURCE_FILE_AT_LINE (155)) COMMA_SOURCE_FILE_AT_LINE (155)), enumerator_4903.current_mTransientName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (154)) ;
    {
    ioArgument_ioSelfObservableAttributeMap.modifier_insertKey (enumerator_4903.current_mTransientName (HERE), var_type, GALGAS_bool (false), var_observationDependencyKey, GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE_AT_LINE (158)) ;
    }
    {
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (165)) ;
    }
    enumerator_4903.gotoNextObject () ;
  }
  cEnumerator_controllerList enumerator_5477 (constinArgument_inControllerList, kEnumeration_up) ;
  while (enumerator_5477.hasCurrentObject ()) {
    GALGAS_ebType var_type ;
    GALGAS_astDeclaration joker_5548_0 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (enumerator_5477.current_mControllerClassName (HERE), var_type, joker_5548_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (172)) ;
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (constinArgument_inObjectName.operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (174)).operator_concat (enumerator_5477.current_mControllerName (HERE).reader_string (SOURCE_FILE_AT_LINE (174)) COMMA_SOURCE_FILE_AT_LINE (174)), enumerator_5477.current_mControllerName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (173)) ;
    {
    ioArgument_ioSelfObservableAttributeMap.modifier_insertKey (enumerator_5477.current_mControllerName (HERE), var_type, GALGAS_bool (false), var_observationDependencyKey, GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE_AT_LINE (177)) ;
    }
    {
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (184)) ;
    }
    enumerator_5477.gotoNextObject () ;
  }
  cEnumerator_controllerObservablePropertyList enumerator_6084 (constinArgument_inControllerObservablePropertyList, kEnumeration_up) ;
  while (enumerator_6084.hasCurrentObject ()) {
    GALGAS_ebType var_type ;
    GALGAS_astDeclaration joker_6144_0 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (enumerator_6084.current_mTypeName (HERE), var_type, joker_6144_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (191)) ;
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (constinArgument_inObjectName.operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (193)).operator_concat (enumerator_6084.current_mPropertyName (HERE).reader_string (SOURCE_FILE_AT_LINE (193)) COMMA_SOURCE_FILE_AT_LINE (193)), enumerator_6084.current_mPropertyName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (192)) ;
    {
    ioArgument_ioSelfObservableAttributeMap.modifier_insertKey (enumerator_6084.current_mPropertyName (HERE), var_type, GALGAS_bool (false), var_observationDependencyKey, GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE_AT_LINE (196)) ;
    }
    {
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (203)) ;
    }
    enumerator_6084.gotoNextObject () ;
  }
}


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


