//---------------------------------------------------------------------------*
//                                                                           *
//                    File 'bindingSemanticAnalysis.cpp'                     *
//                        Generated by version 2.5.0                         *
//                       july 19th, 2013, at 19h22'6"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "bindingSemanticAnalysis.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "bindingSemanticAnalysis.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//                   Routine 'buildBindingCapabilitiesMap'                   *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_buildBindingCapabilitiesMap (const GALGAS_outletClassBindingList constinArgument_inBindingDeclarationList,
                                          GALGAS_unifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                          GALGAS_outletClassBindingMap & outArgument_outBindingMap,
                                          C_Compiler * inCompiler
                                          COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outBindingMap.drop () ; // Release 'out' argument
  outArgument_outBindingMap = GALGAS_outletClassBindingMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (11)) ;
  cEnumerator_outletClassBindingList enumerator_416 (constinArgument_inBindingDeclarationList, kEnumeration_up) ;
  while (enumerator_416.hasCurrentObject ()) {
    GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap = GALGAS_outletClassBindingOptionMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (13)) ;
    cEnumerator_bindingOptionList enumerator_524 (enumerator_416.current_mBindingOptionList (HERE), kEnumeration_up) ;
    while (enumerator_524.hasCurrentObject ()) {
      GALGAS_ebTypeList var_acceptableTypeList = GALGAS_ebTypeList::constructor_emptyList (SOURCE_FILE_AT_LINE (15)) ;
      cEnumerator_lstringlist enumerator_612 (enumerator_524.current_mAcceptableTypeList (HERE), kEnumeration_up) ;
      while (enumerator_612.hasCurrentObject ()) {
        GALGAS_unifiedTypeProxy var_type ;
        {
        GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_612.current_mValue (HERE), var_type COMMA_SOURCE_FILE_AT_LINE (17)) ;
        }
        var_acceptableTypeList.addAssign_operation (var_type.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE_AT_LINE (22)) COMMA_SOURCE_FILE_AT_LINE (22)) ;
        enumerator_612.gotoNextObject () ;
      }
      {
      var_outletClassBindingOptionMap.modifier_insertKey (enumerator_524.current_mBindingOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (24)) ;
      }
      enumerator_524.gotoNextObject () ;
    }
    GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList = GALGAS_ebTypeAndFormatterList::constructor_emptyList (SOURCE_FILE_AT_LINE (26)) ;
    cEnumerator_attributeASTTypeAndFormatterList enumerator_1034 (enumerator_416.current_mAcceptableTypeFormatterList (HERE), kEnumeration_up) ;
    while (enumerator_1034.hasCurrentObject ()) {
      GALGAS_unifiedTypeProxy var_type ;
      {
      GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_1034.current_mTypeName (HERE), var_type COMMA_SOURCE_FILE_AT_LINE (28)) ;
      }
      var_acceptableTypeFormatterList.addAssign_operation (var_type.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE_AT_LINE (33)), enumerator_1034.current_mRequiredFormatter (HERE) COMMA_SOURCE_FILE_AT_LINE (33)) ;
      enumerator_1034.gotoNextObject () ;
    }
    {
    outArgument_outBindingMap.modifier_insertKey (enumerator_416.current_mBindingName (HERE), var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (35)) ;
    }
    enumerator_416.gotoNextObject () ;
  }
}


//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'checkBindingOptions'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_checkBindingOptions (const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                  const GALGAS_outletBindingOptionList constinArgument_inBindingOptionListAST,
                                  const GALGAS_outletClassBindingOptionMap constinArgument_inAvailableBindingOptionMap,
                                  GALGAS__32_stringlist & outArgument_outBindingOptionListForGeneration,
                                  GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                  C_Compiler * inCompiler
                                  COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outBindingOptionListForGeneration.drop () ; // Release 'out' argument
  outArgument_outBindingOptionListForGeneration = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (759)) ;
  cEnumerator_outletBindingOptionList enumerator_29155 (constinArgument_inBindingOptionListAST, kEnumeration_up) ;
  while (enumerator_29155.hasCurrentObject ()) {
    GALGAS_ebTypeList var_acceptableTypeList ;
    constinArgument_inAvailableBindingOptionMap.method_searchKey (enumerator_29155.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (762)) ;
    GALGAS_string var_objectiveCDefaultValueAsString ;
    GALGAS_string joker_29380_0 ; // Joker input parameter
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_29155.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_29380_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (763)) ;
    outArgument_outBindingOptionListForGeneration.addAssign_operation (enumerator_29155.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (770)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (770)) ;
    enumerator_29155.gotoNextObject () ;
  }
}


//---------------------------------------------------------------------------*
//                                                                           *
//   Overriding category method '@tableValueBinding analyzeOutletBinding'    *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_tableValueBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                   const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                   const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                   const GALGAS_outletClassBindingMap /* constinArgument_inBoundObjectBindingMap */,
                                                                   const GALGAS_controllerMap constinArgument_inControllerMap,
                                                                   const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                   const GALGAS_bool constinArgument_inHasTableValueBinding,
                                                                   const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                   GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                   GALGAS_fileInclusionSet & /* ioArgument_ioFileInclusionSet */,
                                                                   C_Compiler * inCompiler
                                                                   COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_tableValueBinding * object = (const cPtr_tableValueBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_tableValueBinding) ;
  const enumGalgasBool test_0 = constinArgument_inHasTableValueBinding.operator_not (SOURCE_FILE_AT_LINE (52)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mControllerName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("this outlet does not support $tableValue binding") COMMA_SOURCE_FILE_AT_LINE (53)) ;
  }else if (kBoolFalse == test_0) {
    GALGAS_lstring var_controlledClassOrEntityName ;
    GALGAS_bool var_isEntity ;
    GALGAS_outletBindingListForGeneration var_controllerBindingList ;
    GALGAS_string joker_2174_0 ; // Joker input parameter
    GALGAS_actionMap joker_2310_0 ; // Joker input parameter
    GALGAS_observablePropertyMap joker_2319_0 ; // Joker input parameter
    constinArgument_inControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_2174_0, var_controlledClassOrEntityName, var_isEntity, var_controllerBindingList, joker_2310_0, joker_2319_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (55)) ;
    GALGAS_typeKind var_kind ;
    GALGAS_observablePropertyMap var_observablePropertyMap ;
    constinArgument_inContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (var_controlledClassOrEntityName, var_kind, var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (64)) ;
    const enumGalgasBool test_2 = var_isEntity.boolEnum () ;
    if (kBoolTrue == test_2) {
      const enumGalgasBool test_3 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_entityType (SOURCE_FILE_AT_LINE (70)))).boolEnum () ;
      if (kBoolTrue == test_3) {
        GALGAS_location location_4 (var_controlledClassOrEntityName.reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_4, GALGAS_string ("'").operator_concat (var_controlledClassOrEntityName.reader_string (SOURCE_FILE_AT_LINE (71)) COMMA_SOURCE_FILE_AT_LINE (71)).operator_concat (GALGAS_string ("' is not an entity") COMMA_SOURCE_FILE_AT_LINE (71)) COMMA_SOURCE_FILE_AT_LINE (71)) ;
      }
    }else if (kBoolFalse == test_2) {
      const enumGalgasBool test_5 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (73)))).boolEnum () ;
      if (kBoolTrue == test_5) {
        GALGAS_location location_6 (var_controlledClassOrEntityName.reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_6, GALGAS_string ("'").operator_concat (var_controlledClassOrEntityName.reader_string (SOURCE_FILE_AT_LINE (74)) COMMA_SOURCE_FILE_AT_LINE (74)).operator_concat (GALGAS_string ("' is not a class") COMMA_SOURCE_FILE_AT_LINE (74)) COMMA_SOURCE_FILE_AT_LINE (74)) ;
      }
    }
    GALGAS_columnBindingForTableValueBindingForGeneration var_columnBindingForTableValueBindingForGeneration = GALGAS_columnBindingForTableValueBindingForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (76)) ;
    cEnumerator_tableValueColumnBinding enumerator_3010 (object->mAttribute_mTableValueColumnBinding, kEnumeration_up) ;
    while (enumerator_3010.hasCurrentObject ()) {
      GALGAS_ebType var_type ;
      GALGAS_bool joker_3118_3 ; // Joker input parameter
      GALGAS_lstring joker_3118_2 ; // Joker input parameter
      GALGAS_bool joker_3118_1 ; // Joker input parameter
      var_observablePropertyMap.method_searchKey (enumerator_3010.current (HERE).mAttribute_mBoundPropertyName, var_type, joker_3118_3, joker_3118_2, joker_3118_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (78)) ;
      GALGAS_string var_requiredCellTypeInTableColumnBinding = categoryReader_requiredCellTypeInTableColumnBinding (var_type, inCompiler COMMA_SOURCE_FILE_AT_LINE (83)) ;
      const enumGalgasBool test_7 = GALGAS_bool (kIsEqual, var_requiredCellTypeInTableColumnBinding.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
      if (kBoolTrue == test_7) {
        GALGAS_location location_8 (enumerator_3010.current (HERE).mAttribute_mBoundPropertyName.reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_8, GALGAS_string ("this property cannot be named in a $tableValue binding") COMMA_SOURCE_FILE_AT_LINE (85)) ;
      }else if (kBoolFalse == test_7) {
        const enumGalgasBool test_9 = GALGAS_bool (kIsNotEqual, var_requiredCellTypeInTableColumnBinding.objectCompare (enumerator_3010.current (HERE).mAttribute_mCellTypeName.mAttribute_string)).boolEnum () ;
        if (kBoolTrue == test_9) {
          GALGAS_location location_10 (enumerator_3010.current (HERE).mAttribute_mCellTypeName.reader_location (HERE)) ; // Implicit use of 'location' reader
          inCompiler->emitSemanticError (location_10, GALGAS_string ("this property requires a ").operator_concat (var_requiredCellTypeInTableColumnBinding COMMA_SOURCE_FILE_AT_LINE (87)).operator_concat (GALGAS_string (" cell class") COMMA_SOURCE_FILE_AT_LINE (87)) COMMA_SOURCE_FILE_AT_LINE (87)) ;
        }
      }
      var_columnBindingForTableValueBindingForGeneration.addAssign_operation (enumerator_3010.current (HERE).mAttribute_mColumnName.mAttribute_string, var_requiredCellTypeInTableColumnBinding, enumerator_3010.current (HERE).mAttribute_mBoundPropertyName.mAttribute_string, GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (93)) COMMA_SOURCE_FILE_AT_LINE (89)) ;
      enumerator_3010.gotoNextObject () ;
    }
    ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_tableValueBindingForGeneration::constructor_new (object->mAttribute_mControllerName.mAttribute_string, var_columnBindingForTableValueBindingForGeneration COMMA_SOURCE_FILE_AT_LINE (96)) COMMA_SOURCE_FILE_AT_LINE (96)) ;
  }
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_tableValueBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_tableValueBinding.mSlotID,
                                            categoryMethod_tableValueBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_tableValueBinding_analyzeOutletBinding (defineCategoryMethod_tableValueBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//       Overriding category method '@runBinding analyzeOutletBinding'       *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_runBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                            const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                            const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                            const GALGAS_outletClassBindingMap /* constinArgument_inBoundObjectBindingMap */,
                                                            const GALGAS_controllerMap constinArgument_inControllerMap,
                                                            const GALGAS_actionMap constinArgument_inActionMap,
                                                            const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                            const GALGAS_contextAnalysisStruct /* constinArgument_inContextAnalysisStruct */,
                                                            GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                            GALGAS_fileInclusionSet & /* ioArgument_ioFileInclusionSet */,
                                                            C_Compiler * inCompiler
                                                            COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_runBinding * object = (const cPtr_runBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_runBinding) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsEqual, object->mAttribute_mTargetName.mAttribute_string.objectCompare (GALGAS_string ("self"))).boolEnum () ;
  if (kBoolTrue == test_0) {
    constinArgument_inActionMap.method_searchKey (object->mAttribute_mActionName, inCompiler COMMA_SOURCE_FILE_AT_LINE (117)) ;
  }else if (kBoolFalse == test_0) {
    GALGAS_actionMap var_actionMap ;
    GALGAS_string joker_4812_4 ; // Joker input parameter
    GALGAS_lstring joker_4812_3 ; // Joker input parameter
    GALGAS_bool joker_4812_2 ; // Joker input parameter
    GALGAS_outletBindingListForGeneration joker_4812_1 ; // Joker input parameter
    GALGAS_observablePropertyMap joker_4827_0 ; // Joker input parameter
    constinArgument_inControllerMap.method_searchKey (object->mAttribute_mTargetName, joker_4812_4, joker_4812_3, joker_4812_2, joker_4812_1, var_actionMap, joker_4827_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (120)) ;
    var_actionMap.method_searchKey (object->mAttribute_mActionName, inCompiler COMMA_SOURCE_FILE_AT_LINE (121)) ;
  }
  ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_runBindingForGeneration::constructor_new (object->mAttribute_mTargetName.mAttribute_string, object->mAttribute_mActionName.mAttribute_string COMMA_SOURCE_FILE_AT_LINE (123)) COMMA_SOURCE_FILE_AT_LINE (123)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_runBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_runBinding.mSlotID,
                                            categoryMethod_runBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_runBinding_analyzeOutletBinding (defineCategoryMethod_runBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//Overriding category method '@regularControllerBinding analyzeOutletBinding'*
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_regularControllerBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                          const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                          const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                          const GALGAS_outletClassBindingMap constinArgument_inBoundObjectBindingMap,
                                                                          const GALGAS_controllerMap constinArgument_inControllerMap,
                                                                          const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                          const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                                          const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                          GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                          GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                          C_Compiler * inCompiler
                                                                          COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_regularControllerBinding * object = (const cPtr_regularControllerBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_regularControllerBinding) ;
  GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList ;
  GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap ;
  constinArgument_inBoundObjectBindingMap.method_searchKey (object->mAttribute_mBindingName, var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (143)) ;
  GALGAS_observablePropertyMap var_observableAttributeMap ;
  GALGAS_string joker_5979_5 ; // Joker input parameter
  GALGAS_lstring joker_5979_4 ; // Joker input parameter
  GALGAS_bool joker_5979_3 ; // Joker input parameter
  GALGAS_outletBindingListForGeneration joker_5979_2 ; // Joker input parameter
  GALGAS_actionMap joker_5979_1 ; // Joker input parameter
  constinArgument_inControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_5979_5, joker_5979_4, joker_5979_3, joker_5979_2, joker_5979_1, var_observableAttributeMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (149)) ;
  GALGAS_ebType var_observablePropertyType ;
  GALGAS_bool var_isTransient ;
  GALGAS_lstring var_propertySignature ;
  GALGAS_bool var_isCollection ;
  var_observableAttributeMap.method_searchKey (object->mAttribute_mControllerAttributeName, var_observablePropertyType, var_isTransient, var_propertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE_AT_LINE (155)) ;
  GALGAS_string var_observedKeyPath = object->mAttribute_mControllerAttributeName.mAttribute_string ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.boolEnum () ;
  if (kBoolTrue == test_0) {
    var_observedKeyPath.dotAssign_operation (GALGAS_string (".@count") COMMA_SOURCE_FILE_AT_LINE (165)) ;
    const enumGalgasBool test_1 = var_isCollection.operator_not (SOURCE_FILE_AT_LINE (166)).boolEnum () ;
    if (kBoolTrue == test_1) {
      GALGAS_location location_2 (object->mAttribute_mControllerAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("the 'count' option is only allowed for to-many relationships") COMMA_SOURCE_FILE_AT_LINE (167)) ;
    }
  }
  GALGAS_bool var_found = GALGAS_bool (false) ;
  GALGAS_formatterEnum var_requiredFormatter = GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE_AT_LINE (173)) ;
  cEnumerator_ebTypeAndFormatterList enumerator_6842 (var_acceptableTypeFormatterList, kEnumeration_up) ;
  bool bool_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (174)).isValidAndTrue () ;
  if (enumerator_6842.hasCurrentObject () && bool_3) {
    while (enumerator_6842.hasCurrentObject () && bool_3) {
      var_requiredFormatter = enumerator_6842.current_mRequiredFormatter (HERE) ;
      var_found = GALGAS_bool (kIsEqual, enumerator_6842.current_mType (HERE).objectCompare (var_observablePropertyType)) ;
      enumerator_6842.gotoNextObject () ;
      if (enumerator_6842.hasCurrentObject ()) {
        bool_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (174)).isValidAndTrue () ;
      }
    }
  }
  const enumGalgasBool test_4 = var_found.operator_not (SOURCE_FILE_AT_LINE (178)).boolEnum () ;
  if (kBoolTrue == test_4) {
    GALGAS_string var_s = GALGAS_string ("the bound property has '").operator_concat (categoryReader_ebTypeName (var_observablePropertyType, inCompiler COMMA_SOURCE_FILE_AT_LINE (179)) COMMA_SOURCE_FILE_AT_LINE (179)).operator_concat (GALGAS_string ("' type, acceptable type(s):") COMMA_SOURCE_FILE_AT_LINE (179)) ;
    cEnumerator_ebTypeAndFormatterList enumerator_7146 (var_acceptableTypeFormatterList, kEnumeration_up) ;
    bool bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (180)).isValidAndTrue () ;
    if (enumerator_7146.hasCurrentObject () && bool_5) {
      while (enumerator_7146.hasCurrentObject () && bool_5) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "  - '").operator_concat (categoryReader_ebTypeName (enumerator_7146.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (181)) COMMA_SOURCE_FILE_AT_LINE (181)).operator_concat (GALGAS_string ("'") COMMA_SOURCE_FILE_AT_LINE (181)) COMMA_SOURCE_FILE_AT_LINE (181)) ;
        enumerator_7146.gotoNextObject () ;
        if (enumerator_7146.hasCurrentObject ()) {
          bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (180)).isValidAndTrue () ;
        }
      }
    }
    GALGAS_location location_6 (object->mAttribute_mControllerAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_6, var_s COMMA_SOURCE_FILE_AT_LINE (183)) ;
  }
  GALGAS__32_stringlist var_bindingOptionList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (186)) ;
  cEnumerator_outletBindingOptionList enumerator_7381 (object->mAttribute_mOutletBindingOptionList, kEnumeration_up) ;
  while (enumerator_7381.hasCurrentObject ()) {
    GALGAS_ebTypeList var_acceptableTypeList ;
    var_outletClassBindingOptionMap.method_searchKey (enumerator_7381.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (189)) ;
    GALGAS_bool var_found = GALGAS_bool (false) ;
    GALGAS_string var_objectiveCDefaultValueAsString ;
    GALGAS_string joker_7633_0 ; // Joker input parameter
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_7381.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_7633_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (191)) ;
    var_bindingOptionList.addAssign_operation (enumerator_7381.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (198)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (198)) ;
    enumerator_7381.gotoNextObject () ;
  }
  ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (object->mAttribute_mBindingName.reader_string (SOURCE_FILE_AT_LINE (201)), var_requiredFormatter, object->mAttribute_mControllerName.mAttribute_string, var_observedKeyPath, var_bindingOptionList COMMA_SOURCE_FILE_AT_LINE (200)) COMMA_SOURCE_FILE_AT_LINE (200)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_regularControllerBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_regularControllerBinding.mSlotID,
                                            categoryMethod_regularControllerBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_regularControllerBinding_analyzeOutletBinding (defineCategoryMethod_regularControllerBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//Overriding category method '@regularControllerSelectionBinding analyzeOutletBinding'*
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_regularControllerSelectionBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                                   const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                                   const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                                   const GALGAS_outletClassBindingMap constinArgument_inBoundObjectBindingMap,
                                                                                   const GALGAS_controllerMap constinArgument_inControllerMap,
                                                                                   const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                                   const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                                                   const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                                   GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                                   GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                                   C_Compiler * inCompiler
                                                                                   COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_regularControllerSelectionBinding * object = (const cPtr_regularControllerSelectionBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_regularControllerSelectionBinding) ;
  GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList ;
  GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap ;
  constinArgument_inBoundObjectBindingMap.method_searchKey (object->mAttribute_mBindingName, var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (223)) ;
  GALGAS_lstring var_controlledClassOrEntityName ;
  GALGAS_bool var_isEntity ;
  GALGAS_string joker_8994_0 ; // Joker input parameter
  GALGAS_outletBindingListForGeneration joker_9063_3 ; // Joker input parameter
  GALGAS_actionMap joker_9063_2 ; // Joker input parameter
  GALGAS_observablePropertyMap joker_9063_1 ; // Joker input parameter
  constinArgument_inControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_8994_0, var_controlledClassOrEntityName, var_isEntity, joker_9063_3, joker_9063_2, joker_9063_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (229)) ;
  GALGAS_typeKind var_kind ;
  GALGAS_observablePropertyMap var_observablePropertyMap ;
  constinArgument_inContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (var_controlledClassOrEntityName, var_kind, var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (237)) ;
  const enumGalgasBool test_0 = var_isEntity.boolEnum () ;
  if (kBoolTrue == test_0) {
    const enumGalgasBool test_1 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_entityType (SOURCE_FILE_AT_LINE (243)))).boolEnum () ;
    if (kBoolTrue == test_1) {
      GALGAS_location location_2 (var_controlledClassOrEntityName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("'").operator_concat (var_controlledClassOrEntityName.reader_string (SOURCE_FILE_AT_LINE (244)) COMMA_SOURCE_FILE_AT_LINE (244)).operator_concat (GALGAS_string ("' is not an entity") COMMA_SOURCE_FILE_AT_LINE (244)) COMMA_SOURCE_FILE_AT_LINE (244)) ;
    }
  }else if (kBoolFalse == test_0) {
    const enumGalgasBool test_3 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (246)))).boolEnum () ;
    if (kBoolTrue == test_3) {
      GALGAS_location location_4 (var_controlledClassOrEntityName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_4, GALGAS_string ("'").operator_concat (var_controlledClassOrEntityName.reader_string (SOURCE_FILE_AT_LINE (247)) COMMA_SOURCE_FILE_AT_LINE (247)).operator_concat (GALGAS_string ("' is not a class") COMMA_SOURCE_FILE_AT_LINE (247)) COMMA_SOURCE_FILE_AT_LINE (247)) ;
    }
  }
  GALGAS_ebType var_observablePropertyType ;
  GALGAS_bool var_isTransient ;
  GALGAS_lstring var_propertySignature ;
  GALGAS_bool var_isCollection ;
  var_observablePropertyMap.method_searchKey (object->mAttribute_mControllerAttributeName, var_observablePropertyType, var_isTransient, var_propertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE_AT_LINE (250)) ;
  GALGAS_string var_observedKeyPath = GALGAS_string ("selection.").operator_concat (object->mAttribute_mControllerAttributeName.mAttribute_string COMMA_SOURCE_FILE_AT_LINE (257)) ;
  GALGAS_bool var_found = GALGAS_bool (false) ;
  GALGAS_formatterEnum var_requiredFormatter = GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE_AT_LINE (260)) ;
  cEnumerator_ebTypeAndFormatterList enumerator_10181 (var_acceptableTypeFormatterList, kEnumeration_up) ;
  bool bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (261)).isValidAndTrue () ;
  if (enumerator_10181.hasCurrentObject () && bool_5) {
    while (enumerator_10181.hasCurrentObject () && bool_5) {
      var_requiredFormatter = enumerator_10181.current_mRequiredFormatter (HERE) ;
      var_found = GALGAS_bool (kIsEqual, enumerator_10181.current_mType (HERE).objectCompare (var_observablePropertyType)) ;
      enumerator_10181.gotoNextObject () ;
      if (enumerator_10181.hasCurrentObject ()) {
        bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (261)).isValidAndTrue () ;
      }
    }
  }
  const enumGalgasBool test_6 = var_found.operator_not (SOURCE_FILE_AT_LINE (265)).boolEnum () ;
  if (kBoolTrue == test_6) {
    GALGAS_string var_s = GALGAS_string ("the bound property has '").operator_concat (categoryReader_ebTypeName (var_observablePropertyType, inCompiler COMMA_SOURCE_FILE_AT_LINE (266)) COMMA_SOURCE_FILE_AT_LINE (266)).operator_concat (GALGAS_string ("' type, acceptable type(s):") COMMA_SOURCE_FILE_AT_LINE (266)) ;
    cEnumerator_ebTypeAndFormatterList enumerator_10485 (var_acceptableTypeFormatterList, kEnumeration_up) ;
    bool bool_7 = var_found.operator_not (SOURCE_FILE_AT_LINE (267)).isValidAndTrue () ;
    if (enumerator_10485.hasCurrentObject () && bool_7) {
      while (enumerator_10485.hasCurrentObject () && bool_7) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "  - '").operator_concat (categoryReader_ebTypeName (enumerator_10485.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (268)) COMMA_SOURCE_FILE_AT_LINE (268)).operator_concat (GALGAS_string ("'") COMMA_SOURCE_FILE_AT_LINE (268)) COMMA_SOURCE_FILE_AT_LINE (268)) ;
        enumerator_10485.gotoNextObject () ;
        if (enumerator_10485.hasCurrentObject ()) {
          bool_7 = var_found.operator_not (SOURCE_FILE_AT_LINE (267)).isValidAndTrue () ;
        }
      }
    }
    GALGAS_location location_8 (object->mAttribute_mControllerAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_8, var_s COMMA_SOURCE_FILE_AT_LINE (270)) ;
  }
  GALGAS__32_stringlist var_bindingOptionList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (273)) ;
  cEnumerator_outletBindingOptionList enumerator_10720 (object->mAttribute_mOutletBindingOptionList, kEnumeration_up) ;
  while (enumerator_10720.hasCurrentObject ()) {
    GALGAS_ebTypeList var_acceptableTypeList ;
    var_outletClassBindingOptionMap.method_searchKey (enumerator_10720.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (276)) ;
    GALGAS_bool var_found = GALGAS_bool (false) ;
    GALGAS_string var_objectiveCDefaultValueAsString ;
    GALGAS_string joker_10972_0 ; // Joker input parameter
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_10720.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_10972_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (278)) ;
    var_bindingOptionList.addAssign_operation (enumerator_10720.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (285)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (285)) ;
    enumerator_10720.gotoNextObject () ;
  }
  ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (object->mAttribute_mBindingName.reader_string (SOURCE_FILE_AT_LINE (288)), var_requiredFormatter, object->mAttribute_mControllerName.mAttribute_string, var_observedKeyPath, var_bindingOptionList COMMA_SOURCE_FILE_AT_LINE (287)) COMMA_SOURCE_FILE_AT_LINE (287)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_regularControllerSelectionBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_regularControllerSelectionBinding.mSlotID,
                                            categoryMethod_regularControllerSelectionBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_regularControllerSelectionBinding_analyzeOutletBinding (defineCategoryMethod_regularControllerSelectionBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//   Overriding category method '@regularRootBinding analyzeOutletBinding'   *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_regularRootBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                    const GALGAS_observablePropertyMap constinArgument_inRootEntityObservableAttributeMap,
                                                                    const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                    const GALGAS_outletClassBindingMap constinArgument_inBoundObjectBindingMap,
                                                                    const GALGAS_controllerMap /* constinArgument_inControllerMap */,
                                                                    const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                    const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                                    const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                    GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                    GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                    C_Compiler * inCompiler
                                                                    COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_regularRootBinding * object = (const cPtr_regularRootBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_regularRootBinding) ;
  GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList ;
  GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap ;
  constinArgument_inBoundObjectBindingMap.method_searchKey (object->mAttribute_mBindingName, var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (310)) ;
  GALGAS_ebType var_observablePropertyType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_12449_0 ; // Joker input parameter
  GALGAS_lstring joker_12456_0 ; // Joker input parameter
  constinArgument_inRootEntityObservableAttributeMap.method_searchKey (object->mAttribute_mObservableAttributeName, var_observablePropertyType, joker_12449_0, joker_12456_0, var_isCollection, inCompiler COMMA_SOURCE_FILE_AT_LINE (316)) ;
  GALGAS_string var_observableKeyPath = object->mAttribute_mObservableAttributeName.mAttribute_string ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.boolEnum () ;
  if (kBoolTrue == test_0) {
    const enumGalgasBool test_1 = var_isCollection.boolEnum () ;
    if (kBoolTrue == test_1) {
      var_observableKeyPath.dotAssign_operation (GALGAS_string (".@count") COMMA_SOURCE_FILE_AT_LINE (327)) ;
      var_observablePropertyType = GALGAS_ebType::constructor_new (GALGAS_string ("UInteger").reader_nowhere (SOURCE_FILE_AT_LINE (328)), GALGAS_typeKind::constructor_uintegerType (SOURCE_FILE_AT_LINE (328)) COMMA_SOURCE_FILE_AT_LINE (328)) ;
    }else if (kBoolFalse == test_1) {
      GALGAS_location location_2 (object->mAttribute_mObservableAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("the 'count' path is only allowed for to-many relationships") COMMA_SOURCE_FILE_AT_LINE (330)) ;
    }
  }
  GALGAS_bool var_found = GALGAS_bool (false) ;
  GALGAS_formatterEnum var_requiredFormatter = GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE_AT_LINE (335)) ;
  cEnumerator_ebTypeAndFormatterList enumerator_13135 (var_acceptableTypeFormatterList, kEnumeration_up) ;
  bool bool_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (336)).isValidAndTrue () ;
  if (enumerator_13135.hasCurrentObject () && bool_3) {
    while (enumerator_13135.hasCurrentObject () && bool_3) {
      var_requiredFormatter = enumerator_13135.current_mRequiredFormatter (HERE) ;
      var_found = GALGAS_bool (kIsEqual, enumerator_13135.current_mType (HERE).objectCompare (var_observablePropertyType)) ;
      enumerator_13135.gotoNextObject () ;
      if (enumerator_13135.hasCurrentObject ()) {
        bool_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (336)).isValidAndTrue () ;
      }
    }
  }
  const enumGalgasBool test_4 = var_found.operator_not (SOURCE_FILE_AT_LINE (341)).boolEnum () ;
  if (kBoolTrue == test_4) {
    GALGAS_string var_s = GALGAS_string ("the bound property has '").operator_concat (categoryReader_ebTypeName (var_observablePropertyType, inCompiler COMMA_SOURCE_FILE_AT_LINE (342)) COMMA_SOURCE_FILE_AT_LINE (342)).operator_concat (GALGAS_string ("' type, acceptable type(s):") COMMA_SOURCE_FILE_AT_LINE (342)) ;
    cEnumerator_ebTypeAndFormatterList enumerator_13570 (var_acceptableTypeFormatterList, kEnumeration_up) ;
    bool bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (343)).isValidAndTrue () ;
    if (enumerator_13570.hasCurrentObject () && bool_5) {
      while (enumerator_13570.hasCurrentObject () && bool_5) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "  - '").operator_concat (categoryReader_ebTypeName (enumerator_13570.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (344)) COMMA_SOURCE_FILE_AT_LINE (344)).operator_concat (GALGAS_string ("'") COMMA_SOURCE_FILE_AT_LINE (344)) COMMA_SOURCE_FILE_AT_LINE (344)) ;
        enumerator_13570.gotoNextObject () ;
        if (enumerator_13570.hasCurrentObject ()) {
          bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (343)).isValidAndTrue () ;
        }
      }
    }
    GALGAS_location location_6 (object->mAttribute_mObservableAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_6, var_s COMMA_SOURCE_FILE_AT_LINE (346)) ;
  }
  GALGAS__32_stringlist var_bindingOptionList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (349)) ;
  cEnumerator_outletBindingOptionList enumerator_13843 (object->mAttribute_mOutletBindingOptionList, kEnumeration_up) ;
  while (enumerator_13843.hasCurrentObject ()) {
    GALGAS_ebTypeList var_acceptableTypeList ;
    var_outletClassBindingOptionMap.method_searchKey (enumerator_13843.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (352)) ;
    GALGAS_string var_objectiveCDefaultValueAsString ;
    GALGAS_string joker_14068_0 ; // Joker input parameter
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_13843.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_14068_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (353)) ;
    var_bindingOptionList.addAssign_operation (enumerator_13843.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (360)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (360)) ;
    enumerator_13843.gotoNextObject () ;
  }
  ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (object->mAttribute_mBindingName.reader_string (SOURCE_FILE_AT_LINE (364)), var_requiredFormatter, GALGAS_string ("mRootObject"), var_observableKeyPath, var_bindingOptionList COMMA_SOURCE_FILE_AT_LINE (363)) COMMA_SOURCE_FILE_AT_LINE (363)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_regularRootBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_regularRootBinding.mSlotID,
                                            categoryMethod_regularRootBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_regularRootBinding_analyzeOutletBinding (defineCategoryMethod_regularRootBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//   Overriding category method '@regularSelfBinding analyzeOutletBinding'   *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_regularSelfBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                    const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                    const GALGAS_observablePropertyMap constinArgument_inSelfObservableAttributeMap,
                                                                    const GALGAS_outletClassBindingMap constinArgument_inBoundObjectBindingMap,
                                                                    const GALGAS_controllerMap /* constinArgument_inControllerMap */,
                                                                    const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                    const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                                    const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                    GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                    GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                    C_Compiler * inCompiler
                                                                    COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_regularSelfBinding * object = (const cPtr_regularSelfBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_regularSelfBinding) ;
  GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList ;
  GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap ;
  constinArgument_inBoundObjectBindingMap.method_searchKey (object->mAttribute_mBindingName, var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (386)) ;
  GALGAS_ebType var_observablePropertyType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_15585_0 ; // Joker input parameter
  GALGAS_lstring joker_15592_0 ; // Joker input parameter
  constinArgument_inSelfObservableAttributeMap.method_searchKey (object->mAttribute_mObservableAttributeName, var_observablePropertyType, joker_15585_0, joker_15592_0, var_isCollection, inCompiler COMMA_SOURCE_FILE_AT_LINE (392)) ;
  GALGAS_string var_observableKeyPath = object->mAttribute_mObservableAttributeName.mAttribute_string ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.boolEnum () ;
  if (kBoolTrue == test_0) {
    const enumGalgasBool test_1 = var_isCollection.boolEnum () ;
    if (kBoolTrue == test_1) {
      var_observableKeyPath.dotAssign_operation (GALGAS_string (".@count") COMMA_SOURCE_FILE_AT_LINE (403)) ;
      var_observablePropertyType = GALGAS_ebType::constructor_new (GALGAS_string ("UInteger").reader_nowhere (SOURCE_FILE_AT_LINE (404)), GALGAS_typeKind::constructor_uintegerType (SOURCE_FILE_AT_LINE (404)) COMMA_SOURCE_FILE_AT_LINE (404)) ;
    }else if (kBoolFalse == test_1) {
      GALGAS_location location_2 (object->mAttribute_mObservableAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("the 'count' path is only allowed for to-many relationships") COMMA_SOURCE_FILE_AT_LINE (406)) ;
    }
  }
  GALGAS_bool var_found = GALGAS_bool (false) ;
  GALGAS_formatterEnum var_requiredFormatter = GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE_AT_LINE (411)) ;
  cEnumerator_ebTypeAndFormatterList enumerator_16271 (var_acceptableTypeFormatterList, kEnumeration_up) ;
  bool bool_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (412)).isValidAndTrue () ;
  if (enumerator_16271.hasCurrentObject () && bool_3) {
    while (enumerator_16271.hasCurrentObject () && bool_3) {
      var_requiredFormatter = enumerator_16271.current_mRequiredFormatter (HERE) ;
      var_found = GALGAS_bool (kIsEqual, enumerator_16271.current_mType (HERE).mAttribute_mKind.objectCompare (var_observablePropertyType.mAttribute_mKind)) ;
      enumerator_16271.gotoNextObject () ;
      if (enumerator_16271.hasCurrentObject ()) {
        bool_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (412)).isValidAndTrue () ;
      }
    }
  }
  const enumGalgasBool test_4 = var_found.operator_not (SOURCE_FILE_AT_LINE (416)).boolEnum () ;
  if (kBoolTrue == test_4) {
    GALGAS_string var_s = GALGAS_string ("the bound property has '").operator_concat (categoryReader_ebTypeName (var_observablePropertyType, inCompiler COMMA_SOURCE_FILE_AT_LINE (417)) COMMA_SOURCE_FILE_AT_LINE (417)).operator_concat (GALGAS_string ("' type, acceptable type(s):") COMMA_SOURCE_FILE_AT_LINE (417)) ;
    cEnumerator_ebTypeAndFormatterList enumerator_16589 (var_acceptableTypeFormatterList, kEnumeration_up) ;
    bool bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (418)).isValidAndTrue () ;
    if (enumerator_16589.hasCurrentObject () && bool_5) {
      while (enumerator_16589.hasCurrentObject () && bool_5) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "  - '").operator_concat (categoryReader_ebTypeName (enumerator_16589.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (419)) COMMA_SOURCE_FILE_AT_LINE (419)).operator_concat (GALGAS_string ("'") COMMA_SOURCE_FILE_AT_LINE (419)) COMMA_SOURCE_FILE_AT_LINE (419)) ;
        enumerator_16589.gotoNextObject () ;
        if (enumerator_16589.hasCurrentObject ()) {
          bool_5 = var_found.operator_not (SOURCE_FILE_AT_LINE (418)).isValidAndTrue () ;
        }
      }
    }
    GALGAS_location location_6 (object->mAttribute_mObservableAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_6, var_s COMMA_SOURCE_FILE_AT_LINE (421)) ;
  }
  GALGAS__32_stringlist var_bindingOptionList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (424)) ;
  cEnumerator_outletBindingOptionList enumerator_16862 (object->mAttribute_mOutletBindingOptionList, kEnumeration_up) ;
  while (enumerator_16862.hasCurrentObject ()) {
    GALGAS_ebTypeList var_acceptableTypeList ;
    var_outletClassBindingOptionMap.method_searchKey (enumerator_16862.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (427)) ;
    GALGAS_string var_objectiveCDefaultValueAsString ;
    GALGAS_string joker_17087_0 ; // Joker input parameter
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_16862.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_17087_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (428)) ;
    var_bindingOptionList.addAssign_operation (enumerator_16862.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (435)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (435)) ;
    enumerator_16862.gotoNextObject () ;
  }
  ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (object->mAttribute_mBindingName.reader_string (SOURCE_FILE_AT_LINE (439)), var_requiredFormatter, GALGAS_string ("self"), var_observableKeyPath, var_bindingOptionList COMMA_SOURCE_FILE_AT_LINE (438)) COMMA_SOURCE_FILE_AT_LINE (438)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_regularSelfBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_regularSelfBinding.mSlotID,
                                            categoryMethod_regularSelfBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_regularSelfBinding_analyzeOutletBinding (defineCategoryMethod_regularSelfBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//Overriding category method '@regularPreferenceBinding analyzeOutletBinding'*
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_regularPreferenceBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                          const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                          const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                          const GALGAS_outletClassBindingMap constinArgument_inBoundObjectBindingMap,
                                                                          const GALGAS_controllerMap /* constinArgument_inControllerMap */,
                                                                          const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                          const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                                          const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                          GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                          GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                          C_Compiler * inCompiler
                                                                          COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_regularPreferenceBinding * object = (const cPtr_regularPreferenceBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_regularPreferenceBinding) ;
  ioArgument_ioFileInclusionSet.mAttribute_mImplementationFileInclusionSet.addAssign_operation (object->mAttribute_mPreferenceName.mAttribute_string COMMA_SOURCE_FILE_AT_LINE (460)) ;
  GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList ;
  GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap ;
  constinArgument_inBoundObjectBindingMap.method_searchKey (object->mAttribute_mBindingName, var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (462)) ;
  GALGAS_typeKind var_kind ;
  GALGAS_observablePropertyMap var_observablePropertyMap ;
  constinArgument_inContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (object->mAttribute_mPreferenceName, var_kind, var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (468)) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_preferencesType (SOURCE_FILE_AT_LINE (473)))).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mPreferenceName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("'").operator_concat (object->mAttribute_mPreferenceName.reader_string (SOURCE_FILE_AT_LINE (474)) COMMA_SOURCE_FILE_AT_LINE (474)).operator_concat (GALGAS_string ("' is not a preference") COMMA_SOURCE_FILE_AT_LINE (474)) COMMA_SOURCE_FILE_AT_LINE (474)) ;
  }
  GALGAS_ebType var_observablePropertyType ;
  GALGAS_bool joker_19062_3 ; // Joker input parameter
  GALGAS_lstring joker_19062_2 ; // Joker input parameter
  GALGAS_bool joker_19062_1 ; // Joker input parameter
  var_observablePropertyMap.method_searchKey (object->mAttribute_mPreferenceAttributeName, var_observablePropertyType, joker_19062_3, joker_19062_2, joker_19062_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (477)) ;
  GALGAS_bool var_found = GALGAS_bool (false) ;
  GALGAS_formatterEnum var_requiredFormatter = GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE_AT_LINE (484)) ;
  cEnumerator_ebTypeAndFormatterList enumerator_19274 (var_acceptableTypeFormatterList, kEnumeration_up) ;
  bool bool_2 = var_found.operator_not (SOURCE_FILE_AT_LINE (485)).isValidAndTrue () ;
  if (enumerator_19274.hasCurrentObject () && bool_2) {
    while (enumerator_19274.hasCurrentObject () && bool_2) {
      var_requiredFormatter = enumerator_19274.current_mRequiredFormatter (HERE) ;
      var_found = GALGAS_bool (kIsEqual, enumerator_19274.current_mType (HERE).objectCompare (var_observablePropertyType)) ;
      enumerator_19274.gotoNextObject () ;
      if (enumerator_19274.hasCurrentObject ()) {
        bool_2 = var_found.operator_not (SOURCE_FILE_AT_LINE (485)).isValidAndTrue () ;
      }
    }
  }
  const enumGalgasBool test_3 = var_found.operator_not (SOURCE_FILE_AT_LINE (489)).boolEnum () ;
  if (kBoolTrue == test_3) {
    GALGAS_string var_s = GALGAS_string ("the bound property has '").operator_concat (categoryReader_ebTypeName (var_observablePropertyType, inCompiler COMMA_SOURCE_FILE_AT_LINE (490)) COMMA_SOURCE_FILE_AT_LINE (490)).operator_concat (GALGAS_string ("' type, acceptable type(s):") COMMA_SOURCE_FILE_AT_LINE (490)) ;
    cEnumerator_ebTypeAndFormatterList enumerator_19578 (var_acceptableTypeFormatterList, kEnumeration_up) ;
    bool bool_4 = var_found.operator_not (SOURCE_FILE_AT_LINE (491)).isValidAndTrue () ;
    if (enumerator_19578.hasCurrentObject () && bool_4) {
      while (enumerator_19578.hasCurrentObject () && bool_4) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "  - '").operator_concat (categoryReader_ebTypeName (enumerator_19578.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (492)) COMMA_SOURCE_FILE_AT_LINE (492)).operator_concat (GALGAS_string ("'") COMMA_SOURCE_FILE_AT_LINE (492)) COMMA_SOURCE_FILE_AT_LINE (492)) ;
        enumerator_19578.gotoNextObject () ;
        if (enumerator_19578.hasCurrentObject ()) {
          bool_4 = var_found.operator_not (SOURCE_FILE_AT_LINE (491)).isValidAndTrue () ;
        }
      }
    }
    GALGAS_location location_5 (object->mAttribute_mPreferenceAttributeName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_5, var_s COMMA_SOURCE_FILE_AT_LINE (494)) ;
  }
  GALGAS__32_stringlist var_bindingOptionList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (497)) ;
  cEnumerator_outletBindingOptionList enumerator_19851 (object->mAttribute_mOutletBindingOptionList, kEnumeration_up) ;
  while (enumerator_19851.hasCurrentObject ()) {
    GALGAS_ebTypeList var_acceptableTypeList ;
    var_outletClassBindingOptionMap.method_searchKey (enumerator_19851.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (500)) ;
    GALGAS_string var_objectiveCDefaultValueAsString ;
    GALGAS_string joker_20076_0 ; // Joker input parameter
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_19851.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_20076_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (501)) ;
    var_bindingOptionList.addAssign_operation (enumerator_19851.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (509)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (509)) ;
    enumerator_19851.gotoNextObject () ;
  }
  ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (object->mAttribute_mBindingName.reader_string (SOURCE_FILE_AT_LINE (513)), var_requiredFormatter, GALGAS_string ("g_").operator_concat (object->mAttribute_mPreferenceName.reader_string (SOURCE_FILE_AT_LINE (515)) COMMA_SOURCE_FILE_AT_LINE (515)), object->mAttribute_mPreferenceAttributeName.mAttribute_string, var_bindingOptionList COMMA_SOURCE_FILE_AT_LINE (512)) COMMA_SOURCE_FILE_AT_LINE (512)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_regularPreferenceBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_regularPreferenceBinding.mSlotID,
                                            categoryMethod_regularPreferenceBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_regularPreferenceBinding_analyzeOutletBinding (defineCategoryMethod_regularPreferenceBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//   Overriding category method '@multiValuedBinding analyzeOutletBinding'   *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_multiValuedBinding_analyzeOutletBinding (const cPtr_abstractBinding * inObject,
                                                                    const GALGAS_observablePropertyMap constinArgument_inRootEntityObservableAttributeMap,
                                                                    const GALGAS_observablePropertyMap constinArgument_inSelfObservableAttributeMap,
                                                                    const GALGAS_outletClassBindingMap constinArgument_inBoundObjectBindingMap,
                                                                    const GALGAS_controllerMap constinArgument_inControllerMap,
                                                                    const GALGAS_actionMap /* constinArgument_inActionMap */,
                                                                    const GALGAS_bool /* constinArgument_inHasTableValueBinding */,
                                                                    const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                    GALGAS_outletBindingListForGeneration & ioArgument_ioOutletBindingListForGeneration,
                                                                    GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                    C_Compiler * inCompiler
                                                                    COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_multiValuedBinding * object = (const cPtr_multiValuedBinding *) inObject ;
  macroValidSharedObject (object, const cPtr_multiValuedBinding) ;
  GALGAS_ebTypeAndFormatterList var_acceptableTypeFormatterList ;
  GALGAS_outletClassBindingOptionMap var_outletClassBindingOptionMap ;
  constinArgument_inBoundObjectBindingMap.method_searchKey (object->mAttribute_mBindingName, var_acceptableTypeFormatterList, var_outletClassBindingOptionMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (534)) ;
  GALGAS_string var_generatedBindingName = object->mAttribute_mBindingName.mAttribute_string ;
  GALGAS_uint var_idx = GALGAS_uint ((PMUInt32) 1U) ;
  cEnumerator_multiValuedBindingList enumerator_21448 (object->mAttribute_mMultiValuedBindingList, kEnumeration_up) ;
  while (enumerator_21448.hasCurrentObject ()) {
    GALGAS_string var_observedObjectName ;
    GALGAS_ebType var_observablePropertyType ;
    GALGAS_string var_keyPathPrefix ;
    callCategoryMethod_analyzeModel ((const cPtr_multiValuedBindingBoundModel *) enumerator_21448.current_mBoundModel (HERE).ptr (), constinArgument_inContextAnalysisStruct, constinArgument_inRootEntityObservableAttributeMap, constinArgument_inSelfObservableAttributeMap, constinArgument_inControllerMap, ioArgument_ioFileInclusionSet, var_observedObjectName, var_observablePropertyType, var_keyPathPrefix, inCompiler COMMA_SOURCE_FILE_AT_LINE (543)) ;
    GALGAS_bool var_found = GALGAS_bool (false) ;
    GALGAS_formatterEnum var_requiredFormatter = GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE_AT_LINE (555)) ;
    cEnumerator_ebTypeAndFormatterList enumerator_21959 (var_acceptableTypeFormatterList, kEnumeration_up) ;
    bool bool_0 = var_found.operator_not (SOURCE_FILE_AT_LINE (556)).isValidAndTrue () ;
    if (enumerator_21959.hasCurrentObject () && bool_0) {
      while (enumerator_21959.hasCurrentObject () && bool_0) {
        var_requiredFormatter = enumerator_21959.current_mRequiredFormatter (HERE) ;
        var_found = GALGAS_bool (kIsEqual, enumerator_21959.current_mType (HERE).objectCompare (var_observablePropertyType)) ;
        enumerator_21959.gotoNextObject () ;
        if (enumerator_21959.hasCurrentObject ()) {
          bool_0 = var_found.operator_not (SOURCE_FILE_AT_LINE (556)).isValidAndTrue () ;
        }
      }
    }
    const enumGalgasBool test_1 = var_found.operator_not (SOURCE_FILE_AT_LINE (560)).boolEnum () ;
    if (kBoolTrue == test_1) {
      GALGAS_string var_s = GALGAS_string ("the bound property has '").operator_concat (categoryReader_ebTypeName (var_observablePropertyType, inCompiler COMMA_SOURCE_FILE_AT_LINE (561)) COMMA_SOURCE_FILE_AT_LINE (561)).operator_concat (GALGAS_string ("' type, acceptable type(s):") COMMA_SOURCE_FILE_AT_LINE (561)) ;
      cEnumerator_ebTypeAndFormatterList enumerator_22275 (var_acceptableTypeFormatterList, kEnumeration_up) ;
      bool bool_2 = var_found.operator_not (SOURCE_FILE_AT_LINE (562)).isValidAndTrue () ;
      if (enumerator_22275.hasCurrentObject () && bool_2) {
        while (enumerator_22275.hasCurrentObject () && bool_2) {
          var_s.dotAssign_operation (GALGAS_string ("\n"
            "  - '").operator_concat (categoryReader_ebTypeName (enumerator_22275.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (563)) COMMA_SOURCE_FILE_AT_LINE (563)).operator_concat (GALGAS_string ("'") COMMA_SOURCE_FILE_AT_LINE (563)) COMMA_SOURCE_FILE_AT_LINE (563)) ;
          enumerator_22275.gotoNextObject () ;
          if (enumerator_22275.hasCurrentObject ()) {
            bool_2 = var_found.operator_not (SOURCE_FILE_AT_LINE (562)).isValidAndTrue () ;
          }
        }
      }
      GALGAS_location location_3 (enumerator_21448.current_mBoundModel (HERE).reader_mPropertyName (SOURCE_FILE_AT_LINE (565)).reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_3, var_s COMMA_SOURCE_FILE_AT_LINE (565)) ;
    }
    GALGAS__32_stringlist var_bindingOptionList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (568)) ;
    const enumGalgasBool test_4 = enumerator_21448.current_mNegate (HERE).boolEnum () ;
    if (kBoolTrue == test_4) {
      var_bindingOptionList.addAssign_operation (GALGAS_string ("NSValueTransformerName"), GALGAS_string ("NSNegateBooleanTransformerName") COMMA_SOURCE_FILE_AT_LINE (570)) ;
    }
    cEnumerator_outletBindingOptionList enumerator_22650 (enumerator_21448.current_mOutletBindingOptionList (HERE), kEnumeration_up) ;
    while (enumerator_22650.hasCurrentObject ()) {
      GALGAS_ebTypeList var_acceptableTypeList ;
      var_outletClassBindingOptionMap.method_searchKey (enumerator_22650.current_mOptionName (HERE), var_acceptableTypeList, inCompiler COMMA_SOURCE_FILE_AT_LINE (574)) ;
      GALGAS_string var_objectiveCDefaultValueAsString ;
      GALGAS_string joker_22879_0 ; // Joker input parameter
      callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_22650.current_mDefaultValue (HERE).ptr (), var_acceptableTypeList, constinArgument_inContextAnalysisStruct, joker_22879_0, var_objectiveCDefaultValueAsString, ioArgument_ioFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (575)) ;
      var_bindingOptionList.addAssign_operation (enumerator_22650.current_mOptionName (HERE).reader_string (SOURCE_FILE_AT_LINE (582)), var_objectiveCDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (582)) ;
      enumerator_22650.gotoNextObject () ;
    }
    ioArgument_ioOutletBindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (var_generatedBindingName, var_requiredFormatter, var_observedObjectName, var_keyPathPrefix.operator_concat (enumerator_21448.current_mBoundModel (HERE).reader_mPropertyName (SOURCE_FILE_AT_LINE (588)).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (588)), var_bindingOptionList COMMA_SOURCE_FILE_AT_LINE (584)) COMMA_SOURCE_FILE_AT_LINE (584)) ;
    var_idx.increment_operation (inCompiler COMMA_SOURCE_FILE_AT_LINE (592)) ;
    var_generatedBindingName = object->mAttribute_mBindingName.mAttribute_string.operator_concat (var_idx.reader_string (SOURCE_FILE_AT_LINE (593)) COMMA_SOURCE_FILE_AT_LINE (593)) ;
    enumerator_21448.gotoNextObject () ;
  }
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_multiValuedBinding_analyzeOutletBinding (void) {
  enterCategoryMethod_analyzeOutletBinding (kTypeDescriptor_GALGAS_multiValuedBinding.mSlotID,
                                            categoryMethod_multiValuedBinding_analyzeOutletBinding) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBinding_analyzeOutletBinding (defineCategoryMethod_multiValuedBinding_analyzeOutletBinding, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//   Abstract category method '@multiValuedBindingBoundModel analyzeModel'   *
//                                                                           *
//---------------------------------------------------------------------------*

static TC_UniqueArray <categoryMethodSignature_multiValuedBindingBoundModel_analyzeModel> gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel ;

//---------------------------------------------------------------------------*

void enterCategoryMethod_analyzeModel (const PMSInt32 inClassIndex,
                                       categoryMethodSignature_multiValuedBindingBoundModel_analyzeModel inMethod) {
  gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel.forceObjectAtIndex (inClassIndex, inMethod, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------*

static void freeCategoryMethod_multiValuedBindingBoundModel_analyzeModel (void) {
  gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel.free () ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBindingBoundModel_analyzeModel (NULL,
                                                                      freeCategoryMethod_multiValuedBindingBoundModel_analyzeModel) ;

//---------------------------------------------------------------------------*

void callCategoryMethod_analyzeModel (const cPtr_multiValuedBindingBoundModel * inObject,
                                      const GALGAS_contextAnalysisStruct constin_inContextAnalysisStruct,
                                      const GALGAS_observablePropertyMap constin_inRootEntityObservableAttributeMap,
                                      const GALGAS_observablePropertyMap constin_inSelfObservableAttributeMap,
                                      const GALGAS_controllerMap constin_inControllerMap,
                                      GALGAS_fileInclusionSet & io_ioFileInclusionSet,
                                      GALGAS_string & out_outObservedObjectName,
                                      GALGAS_ebType & out_outObservablePropertyType,
                                      GALGAS_string & out_outKeyPathPrefix,
                                      C_Compiler * inCompiler
                                      COMMA_LOCATION_ARGS) {
//--- Drop output arguments
  out_outObservedObjectName.drop () ;
  out_outObservablePropertyType.drop () ;
  out_outKeyPathPrefix.drop () ;
//--- Find method
  if (NULL != inObject) {
    macroValidSharedObject (inObject, const cPtr_multiValuedBindingBoundModel) ;
    const C_galgas_type_descriptor * info = inObject->classDescriptor () ;
    const PMSInt32 classIndex = info->mSlotID ;
    categoryMethodSignature_multiValuedBindingBoundModel_analyzeModel f = NULL ;
    if (classIndex < gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel.count ()) {
      f = gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel (classIndex COMMA_HERE) ;
    }
    if (NULL == f) {
       const C_galgas_type_descriptor * p = info->mSuperclassDescriptor ;
       while ((NULL == f) && (NULL != p)) {
         if (p->mSlotID < gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel.count ()) {
           f = gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel (p->mSlotID COMMA_HERE) ;
         }
         p = p->mSuperclassDescriptor ;
       }
       gCategoryMethodTable_multiValuedBindingBoundModel_analyzeModel.forceObjectAtIndex (classIndex, f, NULL COMMA_HERE) ;
    }
    if (NULL == f) {
      fatalError ("FATAL CATEGORY METHOD CALL ERROR", __FILE__, __LINE__) ;
    }else{
      f (inObject, constin_inContextAnalysisStruct, constin_inRootEntityObservableAttributeMap, constin_inSelfObservableAttributeMap, constin_inControllerMap, io_ioFileInclusionSet, out_outObservedObjectName, out_outObservablePropertyType, out_outKeyPathPrefix, inCompiler COMMA_THERE) ;
    }
  }
}

//---------------------------------------------------------------------------*
//                                                                           *
// Overriding category method '@multiValuedBindingBoundToRoot analyzeModel'  *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_multiValuedBindingBoundToRoot_analyzeModel (const cPtr_multiValuedBindingBoundModel * inObject,
                                                                       const GALGAS_contextAnalysisStruct /* constinArgument_inContextAnalysisStruct */,
                                                                       const GALGAS_observablePropertyMap constinArgument_inRootEntityObservableAttributeMap,
                                                                       const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                       const GALGAS_controllerMap /* constinArgument_inControllerMap */,
                                                                       GALGAS_fileInclusionSet & /* ioArgument_ioFileInclusionSet */,
                                                                       GALGAS_string & outArgument_outObservedObjectName,
                                                                       GALGAS_ebType & outArgument_outObservablePropertyType,
                                                                       GALGAS_string & outArgument_outKeyPathPrefix,
                                                                       C_Compiler * inCompiler
                                                                       COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_multiValuedBindingBoundToRoot * object = (const cPtr_multiValuedBindingBoundToRoot *) inObject ;
  macroValidSharedObject (object, const cPtr_multiValuedBindingBoundToRoot) ;
  GALGAS_bool joker_24517_3 ; // Joker input parameter
  GALGAS_lstring joker_24517_2 ; // Joker input parameter
  GALGAS_bool joker_24517_1 ; // Joker input parameter
  constinArgument_inRootEntityObservableAttributeMap.method_searchKey (object->mAttribute_mPropertyName, outArgument_outObservablePropertyType, joker_24517_3, joker_24517_2, joker_24517_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (622)) ;
  outArgument_outObservedObjectName = GALGAS_string ("mRootObject") ;
  outArgument_outKeyPathPrefix = GALGAS_string::makeEmptyString () ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_multiValuedBindingBoundToRoot_analyzeModel (void) {
  enterCategoryMethod_analyzeModel (kTypeDescriptor_GALGAS_multiValuedBindingBoundToRoot.mSlotID,
                                    categoryMethod_multiValuedBindingBoundToRoot_analyzeModel) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBindingBoundToRoot_analyzeModel (defineCategoryMethod_multiValuedBindingBoundToRoot_analyzeModel, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
// Overriding category method '@multiValuedBindingBoundToSelf analyzeModel'  *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_multiValuedBindingBoundToSelf_analyzeModel (const cPtr_multiValuedBindingBoundModel * inObject,
                                                                       const GALGAS_contextAnalysisStruct /* constinArgument_inContextAnalysisStruct */,
                                                                       const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                       const GALGAS_observablePropertyMap constinArgument_inSelfObservableAttributeMap,
                                                                       const GALGAS_controllerMap /* constinArgument_inControllerMap */,
                                                                       GALGAS_fileInclusionSet & /* ioArgument_ioFileInclusionSet */,
                                                                       GALGAS_string & outArgument_outObservedObjectName,
                                                                       GALGAS_ebType & outArgument_outObservablePropertyType,
                                                                       GALGAS_string & outArgument_outKeyPathPrefix,
                                                                       C_Compiler * inCompiler
                                                                       COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_multiValuedBindingBoundToSelf * object = (const cPtr_multiValuedBindingBoundToSelf *) inObject ;
  macroValidSharedObject (object, const cPtr_multiValuedBindingBoundToSelf) ;
  GALGAS_bool joker_25220_3 ; // Joker input parameter
  GALGAS_lstring joker_25220_2 ; // Joker input parameter
  GALGAS_bool joker_25220_1 ; // Joker input parameter
  constinArgument_inSelfObservableAttributeMap.method_searchKey (object->mAttribute_mPropertyName, outArgument_outObservablePropertyType, joker_25220_3, joker_25220_2, joker_25220_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (643)) ;
  outArgument_outObservedObjectName = GALGAS_string ("self") ;
  outArgument_outKeyPathPrefix = GALGAS_string::makeEmptyString () ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_multiValuedBindingBoundToSelf_analyzeModel (void) {
  enterCategoryMethod_analyzeModel (kTypeDescriptor_GALGAS_multiValuedBindingBoundToSelf.mSlotID,
                                    categoryMethod_multiValuedBindingBoundToSelf_analyzeModel) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBindingBoundToSelf_analyzeModel (defineCategoryMethod_multiValuedBindingBoundToSelf_analyzeModel, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
// Overriding category method '@multiValuedBindingBoundToPref analyzeModel'  *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_multiValuedBindingBoundToPref_analyzeModel (const cPtr_multiValuedBindingBoundModel * inObject,
                                                                       const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                       const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                       const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                       const GALGAS_controllerMap /* constinArgument_inControllerMap */,
                                                                       GALGAS_fileInclusionSet & ioArgument_ioFileInclusionSet,
                                                                       GALGAS_string & outArgument_outObservedObjectName,
                                                                       GALGAS_ebType & outArgument_outObservablePropertyType,
                                                                       GALGAS_string & outArgument_outKeyPathPrefix,
                                                                       C_Compiler * inCompiler
                                                                       COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_multiValuedBindingBoundToPref * object = (const cPtr_multiValuedBindingBoundToPref *) inObject ;
  macroValidSharedObject (object, const cPtr_multiValuedBindingBoundToPref) ;
  GALGAS_typeKind var_kind ;
  GALGAS_observablePropertyMap var_preferenceObservableAttributeMap ;
  constinArgument_inContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (object->mAttribute_mPreferenceName, var_kind, var_preferenceObservableAttributeMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (664)) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_preferencesType (SOURCE_FILE_AT_LINE (669)))).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mPreferenceName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("'").operator_concat (object->mAttribute_mPreferenceName.reader_string (SOURCE_FILE_AT_LINE (670)) COMMA_SOURCE_FILE_AT_LINE (670)).operator_concat (GALGAS_string ("' is not a preference") COMMA_SOURCE_FILE_AT_LINE (670)) COMMA_SOURCE_FILE_AT_LINE (670)) ;
  }
  GALGAS_bool joker_26220_3 ; // Joker input parameter
  GALGAS_lstring joker_26220_2 ; // Joker input parameter
  GALGAS_bool joker_26220_1 ; // Joker input parameter
  var_preferenceObservableAttributeMap.method_searchKey (object->mAttribute_mPropertyName, outArgument_outObservablePropertyType, joker_26220_3, joker_26220_2, joker_26220_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (672)) ;
  outArgument_outObservedObjectName = GALGAS_string ("g_").operator_concat (object->mAttribute_mPreferenceName.reader_string (SOURCE_FILE_AT_LINE (677)) COMMA_SOURCE_FILE_AT_LINE (677)) ;
  outArgument_outKeyPathPrefix = GALGAS_string::makeEmptyString () ;
  ioArgument_ioFileInclusionSet.mAttribute_mImplementationFileInclusionSet.addAssign_operation (object->mAttribute_mPreferenceName.mAttribute_string COMMA_SOURCE_FILE_AT_LINE (679)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_multiValuedBindingBoundToPref_analyzeModel (void) {
  enterCategoryMethod_analyzeModel (kTypeDescriptor_GALGAS_multiValuedBindingBoundToPref.mSlotID,
                                    categoryMethod_multiValuedBindingBoundToPref_analyzeModel) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBindingBoundToPref_analyzeModel (defineCategoryMethod_multiValuedBindingBoundToPref_analyzeModel, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//Overriding category method '@multiValuedBindingBoundToController analyzeModel'*
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_multiValuedBindingBoundToController_analyzeModel (const cPtr_multiValuedBindingBoundModel * inObject,
                                                                             const GALGAS_contextAnalysisStruct /* constinArgument_inContextAnalysisStruct */,
                                                                             const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                             const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                             const GALGAS_controllerMap constinArgument_inControllerMap,
                                                                             GALGAS_fileInclusionSet & /* ioArgument_ioFileInclusionSet */,
                                                                             GALGAS_string & outArgument_outObservedObjectName,
                                                                             GALGAS_ebType & outArgument_outObservablePropertyType,
                                                                             GALGAS_string & outArgument_outKeyPathPrefix,
                                                                             C_Compiler * inCompiler
                                                                             COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_multiValuedBindingBoundToController * object = (const cPtr_multiValuedBindingBoundToController *) inObject ;
  macroValidSharedObject (object, const cPtr_multiValuedBindingBoundToController) ;
  GALGAS_observablePropertyMap var_controllerObservableAttributeMap ;
  GALGAS_string joker_26980_5 ; // Joker input parameter
  GALGAS_lstring joker_26980_4 ; // Joker input parameter
  GALGAS_bool joker_26980_3 ; // Joker input parameter
  GALGAS_outletBindingListForGeneration joker_26980_2 ; // Joker input parameter
  GALGAS_actionMap joker_26980_1 ; // Joker input parameter
  constinArgument_inControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_26980_5, joker_26980_4, joker_26980_3, joker_26980_2, joker_26980_1, var_controllerObservableAttributeMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (694)) ;
  GALGAS_bool joker_27151_3 ; // Joker input parameter
  GALGAS_lstring joker_27151_2 ; // Joker input parameter
  GALGAS_bool joker_27151_1 ; // Joker input parameter
  var_controllerObservableAttributeMap.method_searchKey (object->mAttribute_mPropertyName, outArgument_outObservablePropertyType, joker_27151_3, joker_27151_2, joker_27151_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (699)) ;
  outArgument_outObservedObjectName = object->mAttribute_mControllerName.mAttribute_string ;
  outArgument_outKeyPathPrefix = GALGAS_string::makeEmptyString () ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_multiValuedBindingBoundToController_analyzeModel (void) {
  enterCategoryMethod_analyzeModel (kTypeDescriptor_GALGAS_multiValuedBindingBoundToController.mSlotID,
                                    categoryMethod_multiValuedBindingBoundToController_analyzeModel) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBindingBoundToController_analyzeModel (defineCategoryMethod_multiValuedBindingBoundToController_analyzeModel, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//Overriding category method '@multiValuedBindingBoundToControllerSelection analyzeModel'*
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_multiValuedBindingBoundToControllerSelection_analyzeModel (const cPtr_multiValuedBindingBoundModel * inObject,
                                                                                      const GALGAS_contextAnalysisStruct constinArgument_inContextAnalysisStruct,
                                                                                      const GALGAS_observablePropertyMap /* constinArgument_inRootEntityObservableAttributeMap */,
                                                                                      const GALGAS_observablePropertyMap /* constinArgument_inSelfObservableAttributeMap */,
                                                                                      const GALGAS_controllerMap constinArgument_inControllerMap,
                                                                                      GALGAS_fileInclusionSet & /* ioArgument_ioFileInclusionSet */,
                                                                                      GALGAS_string & outArgument_outObservedObjectName,
                                                                                      GALGAS_ebType & outArgument_outObservablePropertyType,
                                                                                      GALGAS_string & outArgument_outKeyPathPrefix,
                                                                                      C_Compiler * inCompiler
                                                                                      COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_multiValuedBindingBoundToControllerSelection * object = (const cPtr_multiValuedBindingBoundToControllerSelection *) inObject ;
  macroValidSharedObject (object, const cPtr_multiValuedBindingBoundToControllerSelection) ;
  GALGAS_lstring var_controlledClassOrEntityName ;
  GALGAS_bool var_isEntity ;
  GALGAS_string joker_27830_0 ; // Joker input parameter
  GALGAS_outletBindingListForGeneration joker_27899_3 ; // Joker input parameter
  GALGAS_actionMap joker_27899_2 ; // Joker input parameter
  GALGAS_observablePropertyMap joker_27899_1 ; // Joker input parameter
  constinArgument_inControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_27830_0, var_controlledClassOrEntityName, var_isEntity, joker_27899_3, joker_27899_2, joker_27899_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (720)) ;
  GALGAS_typeKind var_kind ;
  GALGAS_observablePropertyMap var_observablePropertyMap ;
  constinArgument_inContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (var_controlledClassOrEntityName, var_kind, var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (728)) ;
  const enumGalgasBool test_0 = var_isEntity.boolEnum () ;
  if (kBoolTrue == test_0) {
    const enumGalgasBool test_1 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_entityType (SOURCE_FILE_AT_LINE (734)))).boolEnum () ;
    if (kBoolTrue == test_1) {
      GALGAS_location location_2 (var_controlledClassOrEntityName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("'").operator_concat (var_controlledClassOrEntityName.reader_string (SOURCE_FILE_AT_LINE (735)) COMMA_SOURCE_FILE_AT_LINE (735)).operator_concat (GALGAS_string ("' is not an entity") COMMA_SOURCE_FILE_AT_LINE (735)) COMMA_SOURCE_FILE_AT_LINE (735)) ;
    }
  }else if (kBoolFalse == test_0) {
    const enumGalgasBool test_3 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (737)))).boolEnum () ;
    if (kBoolTrue == test_3) {
      GALGAS_location location_4 (var_controlledClassOrEntityName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_4, GALGAS_string ("'").operator_concat (var_controlledClassOrEntityName.reader_string (SOURCE_FILE_AT_LINE (738)) COMMA_SOURCE_FILE_AT_LINE (738)).operator_concat (GALGAS_string ("' is not a class") COMMA_SOURCE_FILE_AT_LINE (738)) COMMA_SOURCE_FILE_AT_LINE (738)) ;
    }
  }
  GALGAS_bool joker_28577_3 ; // Joker input parameter
  GALGAS_lstring joker_28577_2 ; // Joker input parameter
  GALGAS_bool joker_28577_1 ; // Joker input parameter
  var_observablePropertyMap.method_searchKey (object->mAttribute_mPropertyName, outArgument_outObservablePropertyType, joker_28577_3, joker_28577_2, joker_28577_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (741)) ;
  outArgument_outObservedObjectName = object->mAttribute_mControllerName.mAttribute_string ;
  outArgument_outKeyPathPrefix = GALGAS_string ("selection.") ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_multiValuedBindingBoundToControllerSelection_analyzeModel (void) {
  enterCategoryMethod_analyzeModel (kTypeDescriptor_GALGAS_multiValuedBindingBoundToControllerSelection.mSlotID,
                                    categoryMethod_multiValuedBindingBoundToControllerSelection_analyzeModel) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_multiValuedBindingBoundToControllerSelection_analyzeModel (defineCategoryMethod_multiValuedBindingBoundToControllerSelection_analyzeModel, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


