//---------------------------------------------------------------------------*
//                                                                           *
//                         File 'classAnalysis.cpp'                          *
//                        Generated by version 2.5.0                         *
//                      july 19th, 2013, at 15h26'36"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "classAnalysis.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "classAnalysis.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//       Overriding category method '@classDeclaration typeInventory'        *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_classDeclaration_typeInventory (const cPtr_astDeclaration * inObject,
                                                           GALGAS_unifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                                           C_Compiler * inCompiler
                                                           COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_classDeclaration * object = (const cPtr_classDeclaration *) inObject ;
  macroValidSharedObject (object, const cPtr_classDeclaration) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, object->mAttribute_mSuperClassName.mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_unifiedTypeProxy var_superClassProxy ;
    {
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, object->mAttribute_mSuperClassName, var_superClassProxy COMMA_SOURCE_FILE_AT_LINE (13)) ;
    }
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mClassName, object->mAttribute_mSuperClassName COMMA_SOURCE_FILE_AT_LINE (18)) ;
    }
  }
  cEnumerator_attributeList enumerator_729 (object->mAttribute_mAttributeList, kEnumeration_up) ;
  while (enumerator_729.hasCurrentObject ()) {
    {
    GALGAS_unifiedTypeProxy joker_822_0 ; // Joker input parameter
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_729.current_mAttributeTypeName (HERE), joker_822_0 COMMA_SOURCE_FILE_AT_LINE (25)) ;
    }
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mClassName, enumerator_729.current_mAttributeTypeName (HERE) COMMA_SOURCE_FILE_AT_LINE (30)) ;
    }
    enumerator_729.gotoNextObject () ;
  }
  cEnumerator_classArrayList enumerator_1008 (object->mAttribute_mArrayList, kEnumeration_up) ;
  while (enumerator_1008.hasCurrentObject ()) {
    {
    GALGAS_unifiedTypeProxy joker_1100_0 ; // Joker input parameter
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_1008.current_mElementClassName (HERE), joker_1100_0 COMMA_SOURCE_FILE_AT_LINE (37)) ;
    }
    enumerator_1008.gotoNextObject () ;
  }
  cEnumerator_transientList enumerator_1217 (object->mAttribute_mTransientList, kEnumeration_up) ;
  while (enumerator_1217.hasCurrentObject ()) {
    {
    GALGAS_unifiedTypeProxy joker_1310_0 ; // Joker input parameter
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_1217.current_mTransientTypeName (HERE), joker_1310_0 COMMA_SOURCE_FILE_AT_LINE (45)) ;
    }
    enumerator_1217.gotoNextObject () ;
  }
  {
  //--- @selfCopyInExpressionForGeneration
  const GALGAS_classDeclaration temp_1 = object ;
  ioArgument_ioUnifiedTypeMap.modifier_insertKey (object->mAttribute_mClassName, GALGAS_ebType::constructor_new (object->mAttribute_mClassName, GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (54)) COMMA_SOURCE_FILE_AT_LINE (54)), temp_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (52)) ;
  }
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_classDeclaration_typeInventory (void) {
  enterCategoryMethod_typeInventory (kTypeDescriptor_GALGAS_classDeclaration.mSlotID,
                                     categoryMethod_classDeclaration_typeInventory) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_classDeclaration_typeInventory (defineCategoryMethod_classDeclaration_typeInventory, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
// Overriding category method '@classDeclaration buildObservablePropertyMap' *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_classDeclaration_buildObservablePropertyMap (const cPtr_astDeclaration * inObject,
                                                                        const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                        GALGAS_observablePropertyMapMap & ioArgument_ioObservablePropertyMapMap,
                                                                        GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                        C_Compiler * inCompiler
                                                                        COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_classDeclaration * object = (const cPtr_classDeclaration *) inObject ;
  macroValidSharedObject (object, const cPtr_classDeclaration) ;
  GALGAS_observablePropertyMap var_observablePropertyMap ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, object->mAttribute_mSuperClassName.reader_string (SOURCE_FILE_AT_LINE (68)).objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_typeKind var_kind ;
    ioArgument_ioObservablePropertyMapMap.method_searchKey (object->mAttribute_mSuperClassName, var_kind, var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (69)) ;
    const enumGalgasBool test_1 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (74)))).boolEnum () ;
    if (kBoolTrue == test_1) {
      GALGAS_location location_2 (object->mAttribute_mSuperClassName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("'").operator_concat (object->mAttribute_mSuperClassName.reader_string (SOURCE_FILE_AT_LINE (75)) COMMA_SOURCE_FILE_AT_LINE (75)).operator_concat (GALGAS_string ("' is not a class") COMMA_SOURCE_FILE_AT_LINE (75)) COMMA_SOURCE_FILE_AT_LINE (75)) ;
    }
  }else if (kBoolFalse == test_0) {
    var_observablePropertyMap = GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (78)) ;
  }
  {
  routine_buildObservablePropertyMap (object->mAttribute_mAttributeList, object->mAttribute_mArrayList, object->mAttribute_mTransientList, GALGAS_controllerList::constructor_emptyList (SOURCE_FILE_AT_LINE (85)), GALGAS_controllerObservablePropertyList::constructor_emptyList (SOURCE_FILE_AT_LINE (86)), ioArgument_ioObservablePropertyMapMap, ioArgument_ioTransientDependencyGraph, constinArgument_inUnifiedTypeMap, GALGAS_string ("class.").operator_concat (object->mAttribute_mClassName.reader_string (SOURCE_FILE_AT_LINE (90)) COMMA_SOURCE_FILE_AT_LINE (90)), var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (81)) ;
  }
  {
  ioArgument_ioObservablePropertyMapMap.modifier_insertKey (object->mAttribute_mClassName, GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (96)), var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (94)) ;
  }
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_classDeclaration_buildObservablePropertyMap (void) {
  enterCategoryMethod_buildObservablePropertyMap (kTypeDescriptor_GALGAS_classDeclaration.mSlotID,
                                                  categoryMethod_classDeclaration_buildObservablePropertyMap) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_classDeclaration_buildObservablePropertyMap (defineCategoryMethod_classDeclaration_buildObservablePropertyMap, NULL) ;

//---------------------------------------------------------------------------*
//                                                                           *
//      Overriding category method '@classDeclaration semanticAnalysis'      *
//                                                                           *
//---------------------------------------------------------------------------*

static void categoryMethod_classDeclaration_semanticAnalysis (const cPtr_astDeclaration * inObject,
                                                              const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                              GALGAS_contextAnalysisStruct & ioArgument_ioContextAnalysisStruct,
                                                              GALGAS_generationList & ioArgument_ioGenerationList,
                                                              C_Compiler * inCompiler
                                                              COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_classDeclaration * object = (const cPtr_classDeclaration *) inObject ;
  macroValidSharedObject (object, const cPtr_classDeclaration) ;
  GALGAS_observablePropertyMap var_observablePropertyMap ;
  GALGAS_typeKind joker_3683_0 ; // Joker input parameter
  ioArgument_ioContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (object->mAttribute_mClassName, joker_3683_0, var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (116)) ;
  GALGAS_attributeListForImplementation var_inheritedAttributeListForInitHeader ;
  GALGAS_propertyArrayMap var_allArrayPropertyForImplementation ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsEqual, object->mAttribute_mSuperClassName.mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
  if (kBoolTrue == test_0) {
    var_inheritedAttributeListForInitHeader = GALGAS_attributeListForImplementation::constructor_emptyList (SOURCE_FILE_AT_LINE (125)) ;
    var_allArrayPropertyForImplementation = GALGAS_propertyArrayMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (126)) ;
  }else if (kBoolFalse == test_0) {
    ioArgument_ioContextAnalysisStruct.mAttribute_mClassMap.method_searchKey (object->mAttribute_mSuperClassName, var_inheritedAttributeListForInitHeader, var_allArrayPropertyForImplementation, inCompiler COMMA_SOURCE_FILE_AT_LINE (128)) ;
  }
  GALGAS_attributeListForImplementation var_attributeListForInitHeader = var_inheritedAttributeListForInitHeader ;
  GALGAS_propertyArrayMap var_currentArrayPropertyForImplementation = GALGAS_propertyArrayMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (135)) ;
  GALGAS_transientListForImplementation var_transientListForImplementation ;
  GALGAS_fileInclusionSet var_fileInclusionSet = GALGAS_fileInclusionSet::constructor_default (SOURCE_FILE_AT_LINE (143)) ;
  {
  routine_analyzeTransientProperties (object->mAttribute_mTransientList, GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (146)), ioArgument_ioContextAnalysisStruct, GALGAS_string::makeEmptyString (), var_observablePropertyMap, var_fileInclusionSet, var_transientListForImplementation, inCompiler COMMA_SOURCE_FILE_AT_LINE (144)) ;
  }
  GALGAS_attributeListForImplementation var_attributeListForImplementation ;
  {
  routine_analyzeAttributeDeclaration (object->mAttribute_mAttributeList, ioArgument_ioContextAnalysisStruct, constinArgument_inUnifiedTypeMap, var_fileInclusionSet, var_attributeListForImplementation, var_attributeListForInitHeader, inCompiler COMMA_SOURCE_FILE_AT_LINE (154)) ;
  }
  cEnumerator_classArrayList enumerator_5566 (object->mAttribute_mArrayList, kEnumeration_up) ;
  while (enumerator_5566.hasCurrentObject ()) {
    GALGAS_ebType var_type ;
    GALGAS_astDeclaration joker_5645_0 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (object->mAttribute_mClassName, var_type, joker_5645_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (164)) ;
    const enumGalgasBool test_1 = GALGAS_bool (kIsNotEqual, var_type.mAttribute_mKind.objectCompare (GALGAS_typeKind::constructor_classType (SOURCE_FILE_AT_LINE (169)))).boolEnum () ;
    if (kBoolTrue == test_1) {
      GALGAS_location location_2 (object->mAttribute_mClassName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_2, GALGAS_string ("'").operator_concat (object->mAttribute_mClassName.reader_string (SOURCE_FILE_AT_LINE (170)) COMMA_SOURCE_FILE_AT_LINE (170)).operator_concat (GALGAS_string ("' is not a class") COMMA_SOURCE_FILE_AT_LINE (170)) COMMA_SOURCE_FILE_AT_LINE (170)) ;
    }
    {
    var_allArrayPropertyForImplementation.modifier_insertKey (enumerator_5566.current_mArrayName (HERE), var_type, inCompiler COMMA_SOURCE_FILE_AT_LINE (172)) ;
    }
    {
    var_currentArrayPropertyForImplementation.modifier_insertKey (enumerator_5566.current_mArrayName (HERE), var_type, inCompiler COMMA_SOURCE_FILE_AT_LINE (176)) ;
    }
    enumerator_5566.gotoNextObject () ;
  }
  {
  ioArgument_ioContextAnalysisStruct.mAttribute_mClassMap.modifier_insertKey (object->mAttribute_mClassName, var_attributeListForInitHeader, var_allArrayPropertyForImplementation, inCompiler COMMA_SOURCE_FILE_AT_LINE (182)) ;
  }
  ioArgument_ioGenerationList.addAssign_operation (GALGAS_classTypeGeneration::constructor_new (object->mAttribute_mClassName.mAttribute_string, object->mAttribute_mSuperClassName.mAttribute_string, var_attributeListForInitHeader, var_inheritedAttributeListForInitHeader, var_attributeListForImplementation, var_transientListForImplementation, var_allArrayPropertyForImplementation, var_currentArrayPropertyForImplementation, var_fileInclusionSet COMMA_SOURCE_FILE_AT_LINE (188)) COMMA_SOURCE_FILE_AT_LINE (188)) ;
}
//---------------------------------------------------------------------------*

static void defineCategoryMethod_classDeclaration_semanticAnalysis (void) {
  enterCategoryMethod_semanticAnalysis (kTypeDescriptor_GALGAS_classDeclaration.mSlotID,
                                        categoryMethod_classDeclaration_semanticAnalysis) ;
}

//---------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_classDeclaration_semanticAnalysis (defineCategoryMethod_classDeclaration_semanticAnalysis, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


