//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                           File 'documentGeneration.cpp'                                             *
//                                             Generated by version 2.7.0                                              *
//                                           august 8th, 2014, at 20h3'38"                                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "documentGeneration.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                      Filewrapper 'documentGenerationTemplate'                                       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- All files of '' directory

static const cRegularFileWrapper * gWrapperAllFiles_documentGenerationTemplate_0 [1] = {
  NULL
} ;

//--- All sub-directories of '' directory

static const cDirectoryWrapper * gWrapperAllDirectories_documentGenerationTemplate_0 [1] = {
  NULL
} ;

//--- Directory ''

const cDirectoryWrapper gWrapperDirectory_0_documentGenerationTemplate (
  "",
  0,
  gWrapperAllFiles_documentGenerationTemplate_0,
  0,
  gWrapperAllDirectories_documentGenerationTemplate_0
) ;


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                   Filewrapper template 'documentGenerationTemplate documentImplementationInSwift'                   *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentImplementationInSwift (C_Compiler * inCompiler,
                                                                                            const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                            const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                            const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                            const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                            const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION,
                                                                                            const GALGAS_stringset & /* in_INCLUSION_5F_SET */,
                                                                                            const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                            const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                            COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "\n"
    "import Cocoa\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "@objc(" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << ") class " ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << " : PMManagedDocument {\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    Outlets                                                                                                        *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_605_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_605 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_605.hasCurrentObject ()) {
      result << "  @IBOutlet var " ;
      result << enumerator_605.current_mOutletName (HERE).stringValue () ;
      result << " : " ;
      result << enumerator_605.current_mOutletType (HERE).stringValue () ;
      result << "\?\n" ;
      index_605_.increment () ;
      enumerator_605.gotoNextObject () ;
    }
  }
  result << "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    Controllers                                                                                                    *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_1056_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_1056 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_1056.hasCurrentObject ()) {
      result << "  var " ;
      result << enumerator_1056.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " : " ;
      result << enumerator_1056.current_mControllerClassName (HERE).stringValue () ;
      result << " \n" ;
      index_1056_.increment () ;
      enumerator_1056.gotoNextObject () ;
    }
  }
  result << "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    Document attributes                                                                                            *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_1508_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_1508 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_1508.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_1508.current_mAttributeName (HERE).stringValue () ;
      result << "' attribute\n"
        "  @property" ;
      result << categoryReader_propertyAttributeString (enumerator_1508.current_mType (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 34)).stringValue () ;
      result << " " ;
      result << categoryReader_ocTypeName (enumerator_1508.current_mType (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 34)).stringValue () ;
      result << " " ;
      result << enumerator_1508.current_mAttributeName (HERE).stringValue () ;
      result << " ;\n"
        "  - (void) addObserverOf_" ;
      result << enumerator_1508.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver ;\n"
        "  - (void) removeObserverOf_" ;
      result << enumerator_1508.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver ;\n"
        "\n" ;
      index_1508_.increment () ;
      enumerator_1508.gotoNextObject () ;
    }
  }
  GALGAS_uint index_1807_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_1807 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_1807.hasCurrentObject ()) {
      result << "  @private NSMutableSet * " ;
      result << enumerator_1807.current_mAttributeName (HERE).stringValue () ;
      result << "_observers ;\n" ;
      index_1807_.increment () ;
      enumerator_1807.gotoNextObject () ;
    }
  }
  result << "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    init                                                                                                           *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  init () {\n"
    "    let em = PMObjectManager ()\n" ;
  GALGAS_uint index_2309_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_2309 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_2309.hasCurrentObject ()) {
      result << "    " ;
      result << enumerator_2309.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " = " ;
      result << enumerator_2309.current_mControllerClassName (HERE).stringValue () ;
      result << " (" ;
      const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, enumerator_2309.current_mControlledClassOrEntityName (HERE).mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
      if (kBoolTrue == test_0) {
        result << "entityManager:em, inClassName:\"" ;
        result << enumerator_2309.current_mControlledClassOrEntityName (HERE).mAttribute_string.stringValue () ;
        result << "\"" ;
      }else if (kBoolFalse == test_0) {
      }
      result << ")\n" ;
      index_2309_.increment () ;
      enumerator_2309.gotoNextObject () ;
    }
  }
  result << "    super.init (inEntityManager:em)\n"
    "  }\n"
    "  \n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    windowNibName                                                                                                  *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  override var windowNibName: String {\n"
    "    return \"" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << "\"\n"
    "  }\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    rootEntityClassName                                                                                            *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  override func rootEntityClassName () -> String {\n"
    "    return \"" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << "\"\n"
    "  }\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    rootObject                                                                                                     *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  var rootObject : MyRootEntity {\n"
    "    get {\n"
    "      return mRootObject as " ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << "\n"
    "    }\n"
    "  }\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //    windowControllerDidLoadNib                                                                                     *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  override func windowControllerDidLoadNib (aController: NSWindowController) {\n"
    "    super.windowControllerDidLoadNib (aController)\n"
    "  //--------------------------- Controller bindings\n" ;
  GALGAS_uint index_4486_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_4486 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_4486.hasCurrentObject ()) {
      GALGAS_uint index_4586_ (0) ;
      if (enumerator_4486.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_4586 (enumerator_4486.current_mControllerBindingList (HERE), kEnumeration_up) ;
        const bool nonEmpty_enumerator_4586 = enumerator_4586.hasCurrentObject () ;
        if (nonEmpty_enumerator_4586) {
          result << "//--- '" ;
          result << enumerator_4486.current_lkey (HERE).mAttribute_string.stringValue () ;
          result << "' controller bindings\n" ;
        }
        while (enumerator_4586.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftBinding ((const cPtr_abstractBindingForGeneration *) enumerator_4586.current_mBinding (HERE).ptr (), enumerator_4486.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 98)).stringValue () ;
          index_4586_.increment () ;
          enumerator_4586.gotoNextObject () ;
        }
      }
      index_4486_.increment () ;
      enumerator_4486.gotoNextObject () ;
    }
  }
  result << "  //--------------------------- Outlet bindings\n" ;
  GALGAS_uint index_4732_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_4732 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_4732.hasCurrentObject ()) {
      result << "  //--- Outlet " ;
      result << enumerator_4732.current_mOutletName (HERE).stringValue () ;
      result << "\n"
        "    if nil == " ;
      result << enumerator_4732.current_mOutletName (HERE).stringValue () ;
      result << " {\n"
        "      presentErrorWindow (__FILE__, __LINE__, \"the '" ;
      result << enumerator_4732.current_mOutletName (HERE).stringValue () ;
      result << "' outlet is nil\") ;\n"
        "    }\n" ;
      GALGAS_uint index_4945_ (0) ;
      if (enumerator_4732.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_4945 (enumerator_4732.current_mOutletBindingList (HERE), kEnumeration_up) ;
        while (enumerator_4945.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftBinding ((const cPtr_abstractBindingForGeneration *) enumerator_4945.current_mBinding (HERE).ptr (), enumerator_4732.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 110)).stringValue () ;
          index_4945_.increment () ;
          enumerator_4945.gotoNextObject () ;
        }
      }
      index_4732_.increment () ;
      enumerator_4732.gotoNextObject () ;
    }
  }
  result << "  //--------------------------- Add Transient observers\n" ;
  result << function_generateAddSwiftObserverForTransients (GALGAS_string ("document"), in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, GALGAS_string ("    "), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 114)).stringValue () ;
  result << "  //--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_1 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_1) {
    result << "  [mRootObject addSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_1) {
  }
  result << "}\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  //   removeWindowController                                                                                          *\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  override func removeWindowController (inWindowController : NSWindowController) {\n"
    "  //--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_2 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_2) {
    result << "  [mRootObject removeSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_2) {
  }
  result << "  //--- Unbind Outlets\n" ;
  GALGAS_uint index_5972_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_5972 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_5972.hasCurrentObject ()) {
      GALGAS_uint index_6006_ (0) ;
      if (enumerator_5972.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_6006 (enumerator_5972.current_mOutletBindingList (HERE), kEnumeration_down) ;
        while (enumerator_6006.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_6006.current_mBinding (HERE).ptr (), enumerator_5972.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 135)).stringValue () ;
          index_6006_.increment () ;
          enumerator_6006.gotoNextObject () ;
        }
      }
      index_5972_.increment () ;
      enumerator_5972.gotoNextObject () ;
    }
  }
  result << "  //--- Unbind Controllers\n" ;
  GALGAS_uint index_6127_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_6127 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_6127.hasCurrentObject ()) {
      GALGAS_uint index_6163_ (0) ;
      if (enumerator_6127.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_6163 (enumerator_6127.current_mControllerBindingList (HERE), kEnumeration_up) ;
        while (enumerator_6163.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_6163.current_mBinding (HERE).ptr (), enumerator_6127.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 141)).stringValue () ;
          index_6163_.increment () ;
          enumerator_6163.gotoNextObject () ;
        }
      }
      index_6127_.increment () ;
      enumerator_6127.gotoNextObject () ;
    }
  }
  result << "  //--- Remove Transient observers\n" ;
  result << function_generateRemoveSwiftObserverForTransients (GALGAS_string ("document"), in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, GALGAS_string ("   "), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 145)).stringValue () ;
  result << "  //--- Release controllers\n" ;
  GALGAS_uint index_6435_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_6435 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_6435.hasCurrentObject ()) {
      result << "    // " ;
      result << enumerator_6435.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " = nil\n" ;
      index_6435_.increment () ;
      enumerator_6435.gotoNextObject () ;
    }
  }
  result << "  //--- Remove circularities in outlets\n" ;
  GALGAS_uint index_6550_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_6550 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_6550.hasCurrentObject ()) {
      const enumGalgasBool test_3 = enumerator_6550.current_mImplementsDeallocProtocol (HERE).boolEnum () ;
      if (kBoolTrue == test_3) {
        result << "  [" ;
        result << enumerator_6550.current_mOutletName (HERE).stringValue () ;
        result << " objectWillBeDeallocated] ;\n" ;
      }else if (kBoolFalse == test_3) {
      }
      index_6550_.increment () ;
      enumerator_6550.gotoNextObject () ;
    }
  }
  result << "  //---\n"
    "    super.removeWindowController (inWindowController)\n"
    "  }\n"
    "\n" ;
  GALGAS_uint index_6876_ (0) ;
  if (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION.isValid ()) {
    cEnumerator_transientListForImplementation enumerator_6876 (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, kEnumeration_up) ;
    while (enumerator_6876.hasCurrentObject ()) {
      result << "  //-------------------------------------------------------------------------------------------------------------------*\n"
        "  //    " ;
      result << GALGAS_string ("Transient: ").add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 166)).reader_stringByRightPadding (GALGAS_uint ((uint32_t) 111U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE ("document.swift.gTemplate", 166)).stringValue () ;
      result << "*\n"
        "  //-------------------------------------------------------------------------------------------------------------------*\n"
        " \n"
        "  var " ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << "_observers = NSMutableSet ()\n"
        "  var " ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << "__cache : " ;
      result << categoryReader_swiftTypeName (enumerator_6876.current_mTransientType (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 170)).stringValue () ;
      result << "\?\n"
        "  var " ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << " : " ;
      result << categoryReader_swiftTypeName (enumerator_6876.current_mTransientType (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 171)).stringValue () ;
      result << " {\n" ;
      result << function_generateSwiftTransientCacheRoutine (in_DOCUMENT_5F_NAME, enumerator_6876.current_mTransientType (HERE), enumerator_6876.current_mTransientName (HERE), enumerator_6876.current_mDependencyList (HERE), enumerator_6876.current_mRootSignDependencyList (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 172)).stringValue () ;
      result << "  }\n"
        "\n"
        "  func " ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 175)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 175)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 175)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 175)).stringValue () ;
      result << "_didChange () {\n"
        "    self.willChangeValueForKey (\"" ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << "\")\n"
        "    self.didChangeValueForKey  (\"" ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << "\")\n"
        "  }\n"
        "\n"
        "  func addObserverOf_" ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << " (inObserver : PMTriggerProtocol) {\n"
        "    " ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << "_observers.addObject (inObserver)\n"
        "    enterTriggerWithObject (inObserver)\n"
        "  }\n"
        " \n"
        "  func removeObserverOf_" ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << " (inObserver : PMTriggerProtocol) {\n"
        "    " ;
      result << enumerator_6876.current_mTransientName (HERE).stringValue () ;
      result << "_observers.removeObject (inObserver)\n"
        "    enterTriggerWithObject (inObserver)\n"
        "  }\n"
        "\n"
        "  var triggerObjectFor_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 190)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 190)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 190)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 190)).stringValue () ;
      result << "__cache : PMTrigger_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 190)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 190)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 190)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 190)).stringValue () ;
      result << "\? = nil\n"
        "  var triggerObjectFor_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 191)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 191)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 191)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 191)).stringValue () ;
      result << " : PMTrigger_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 191)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 191)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 191)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 191)).stringValue () ;
      result << " {\n"
        "    if !triggerObjectFor_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 192)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 192)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 192)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 192)).stringValue () ;
      result << "__cache {\n"
        "      triggerObjectFor_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 193)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 193)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 193)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 193)).stringValue () ;
      result << "__cache = PMTrigger_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 193)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 193)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 193)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 193)).stringValue () ;
      result << " (object:self)\n"
        "    }\n"
        "    return triggerObjectFor_" ;
      result << GALGAS_string ("document.").add_operation (in_DOCUMENT_5F_NAME, inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 195)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 195)).add_operation (enumerator_6876.current_mTransientName (HERE), inCompiler COMMA_SOURCE_FILE ("document.swift.gTemplate", 195)).reader_identifierRepresentation (SOURCE_FILE ("document.swift.gTemplate", 195)).stringValue () ;
      result << "__cache!\n"
        "  }\n"
        "\n"
        " \n" ;
      index_6876_.increment () ;
      enumerator_6876.gotoNextObject () ;
    }
  }
  result << "}\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n" ;
  return GALGAS_string (result) ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                              Overriding category method '@documentGeneration generate'                              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_documentGeneration_generate (const cPtr_generation * inObject,
                                                        const GALGAS_string constinArgument_inOutputDirectory,
                                                        C_Compiler * inCompiler
                                                        COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_documentGeneration * object = (const cPtr_documentGeneration *) inObject ;
  macroValidSharedObject (object, cPtr_documentGeneration) ;
  GALGAS_bool var_hasSignatureObserver = GALGAS_bool (false) ;
  cEnumerator_transientListForImplementation enumerator_2643 (object->mAttribute_mTransientListForImplementation, kEnumeration_up) ;
  bool bool_0 = var_hasSignatureObserver.operator_not (SOURCE_FILE ("documentGeneration.gSemantics", 77)).isValidAndTrue () ;
  if (enumerator_2643.hasCurrentObject () && bool_0) {
    while (enumerator_2643.hasCurrentObject () && bool_0) {
      var_hasSignatureObserver = GALGAS_bool (kIsStrictSup, enumerator_2643.current_mRootSignDependencyList (HERE).reader_length (SOURCE_FILE ("documentGeneration.gSemantics", 78)).objectCompare (GALGAS_uint ((uint32_t) 0U))) ;
      enumerator_2643.gotoNextObject () ;
      if (enumerator_2643.hasCurrentObject ()) {
        bool_0 = var_hasSignatureObserver.operator_not (SOURCE_FILE ("documentGeneration.gSemantics", 77)).isValidAndTrue () ;
      }
    }
  }
  GALGAS_string var_s = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentImplementationInSwift (inCompiler, object->mAttribute_mGenerationName, object->mAttribute_mRootEntityName, object->mAttribute_mOutletDeclarationList, object->mAttribute_mControllerMap, object->mAttribute_mTransientListForImplementation, object->mAttribute_mFileInclusionSet.mAttribute_mImplementationFileInclusionSet, var_hasSignatureObserver, object->mAttribute_mAttributeListForImplementation COMMA_SOURCE_FILE ("documentGeneration.gSemantics", 81))) ;
  {
  GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, object->mAttribute_mGenerationName.operator_concat (GALGAS_string (".swift")  COMMA_SOURCE_FILE ("documentGeneration.gSemantics", 93)), GALGAS_string ("//"), GALGAS_string ("\n"
    "\n"), var_s, GALGAS_string ("\n"
    "\n"), GALGAS_string ("\n"), inCompiler COMMA_SOURCE_FILE ("documentGeneration.gSemantics", 91)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_documentGeneration_generate (void) {
  enterCategoryMethod_generate (kTypeDescriptor_GALGAS_documentGeneration.mSlotID,
                                categoryMethod_documentGeneration_generate) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_documentGeneration_generate (defineCategoryMethod_documentGeneration_generate, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


