//-----------------------------------------------------------------------------*
//                                                                             *
//                       File 'documentGeneration.cpp'                         *
//                         Generated by version 2.6.0                          *
//                       june 23th, 2014, at 21h36'41"                         *
//                                                                             *
//-----------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "documentGeneration.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//-----------------------------------------------------------------------------*

#include "easyBindings_options.h"

//-----------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "documentGeneration.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//-----------------------------------------------------------------------------*
//                                                                             *
//                  Filewrapper 'documentGenerationTemplate'                   *
//                                                                             *
//-----------------------------------------------------------------------------*

extern const cDirectoryWrapper gWrapperDirectory_0_documentGenerationTemplate ;

//-----------------------------------------------------------------------------*
//                                                                             *
//   Filewrapper template 'documentGenerationTemplate documentDeclaration1'    *
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentDeclaration_31_ (C_Compiler * inCompiler,
                                                                                      const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                      const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                      const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                      const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                      const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST,
                                                                                      const GALGAS_stringset & in_HEADER_5F_FILE_5F_PREDECLARATION_5F_SET,
                                                                                      const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                      const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                      COMMA_LOCATION_ARGS) ;

//-----------------------------------------------------------------------------*
//                                                                             *
//   Filewrapper template 'documentGenerationTemplate documentDeclaration2'    *
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentDeclaration_32_ (C_Compiler * inCompiler,
                                                                                      const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST,
                                                                                      const GALGAS_lstringlist & in_ACTION_5F_LIST
                                                                                      COMMA_LOCATION_ARGS) ;

//-----------------------------------------------------------------------------*
//                                                                             *
//  Filewrapper template 'documentGenerationTemplate documentImplementation'   *
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentImplementation (C_Compiler * inCompiler,
                                                                                     const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                     const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                     const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                     const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                     const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST,
                                                                                     const GALGAS_stringset & in_INCLUSION_5F_SET,
                                                                                     const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                     const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                     COMMA_LOCATION_ARGS) ;

//-----------------------------------------------------------------------------*
//                                                                             *
//Filewrapper template 'documentGenerationTemplate documentImplementationInSwift'*
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentImplementationInSwift (C_Compiler * inCompiler,
                                                                                            const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                            const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                            const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                            const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                            const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION,
                                                                                            const GALGAS_stringset & in_INCLUSION_5F_SET,
                                                                                            const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                            const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                            COMMA_LOCATION_ARGS) ;

//-----------------------------------------------------------------------------*
//                                                                             *
//Filewrapper template 'documentGenerationTemplate documentComputationsHeaderFile'*
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentComputationsHeaderFile (C_Compiler * inCompiler,
                                                                                             const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                             const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION
                                                                                             COMMA_LOCATION_ARGS) ;

//-----------------------------------------------------------------------------*
//                                                                             *
//Filewrapper template 'documentGenerationTemplate documentTransientComputationImplementationFile'*
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentTransientComputationImplementationFile (C_Compiler * inCompiler,
                                                                                                             const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                                             const GALGAS_ebType & in_RESULT_5F_TYPE,
                                                                                                             const GALGAS_string & in_TRANSIENT_5F_NAME,
                                                                                                             const GALGAS_directDependancyList & in_DIRECT_5F_DEPENDANCY_5F_LIST,
                                                                                                             const GALGAS_stringlist & in_ROOT_5F_SIGN_5F_LIST
                                                                                                             COMMA_LOCATION_ARGS) ;

//-----------------------------------------------------------------------------*
//                                                                             *
//                  Filewrapper 'documentGenerationTemplate'                   *
//                                                                             *
//-----------------------------------------------------------------------------*

//--- All files of '' directory

static const cRegularFileWrapper * gWrapperAllFiles_documentGenerationTemplate_0 [1] = {
  NULL
} ;

//--- All sub-directories of '' directory

static const cDirectoryWrapper * gWrapperAllDirectories_documentGenerationTemplate_0 [1] = {
  NULL
} ;

//--- Directory ''

const cDirectoryWrapper gWrapperDirectory_0_documentGenerationTemplate (
  "",
  0,
  gWrapperAllFiles_documentGenerationTemplate_0,
  0,
  gWrapperAllDirectories_documentGenerationTemplate_0
) ;


//-----------------------------------------------------------------------------*
//                                                                             *
//   Filewrapper template 'documentGenerationTemplate documentDeclaration1'    *
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentDeclaration_31_ (C_Compiler * inCompiler,
                                                                                      const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                      const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                      const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                      const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                      const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST,
                                                                                      const GALGAS_stringset & in_HEADER_5F_FILE_5F_PREDECLARATION_5F_SET,
                                                                                      const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                      const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                      COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#import \"PMManagedDocument.h\"\n"
    "#import \"PMManagedEntity.h\"\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "@class PMEntityArrayController ;\n"
    "// @class " ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " ;\n" ;
  GALGAS_uint index_246_ (0) ;
  if (in_HEADER_5F_FILE_5F_PREDECLARATION_5F_SET.isValid ()) {
    cEnumerator_stringset enumerator_246 (in_HEADER_5F_FILE_5F_PREDECLARATION_5F_SET, kEnumeration_up) ;
    while (enumerator_246.hasCurrentObject ()) {
      result << "@class " ;
      result << enumerator_246.current_key (HERE).stringValue () ;
      result << " ;\n" ;
      index_246_.increment () ;
      enumerator_246.gotoNextObject () ;
    }
  }
  result << "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "@interface " ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << " : PMManagedDocument " ;
  const enumGalgasBool test_0 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_0) {
    result << "<PMSignatureObserverProtocol> " ;
  }else if (kBoolFalse == test_0) {
  }
  result << "{\n" ;
  GALGAS_uint index_513_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_513 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_513.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_513.current_mOutletName (HERE).stringValue () ;
      result << "' outlet\n"
        "  @private IBOutlet " ;
      result << enumerator_513.current_mOutletType (HERE).stringValue () ;
      result << " * " ;
      result << enumerator_513.current_mOutletName (HERE).stringValue () ;
      result << " ;\n" ;
      index_513_.increment () ;
      enumerator_513.gotoNextObject () ;
    }
  }
  GALGAS_uint index_631_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_631 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_631.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_631.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << "' controller\n"
        "  @private " ;
      result << enumerator_631.current_mControllerClassName (HERE).stringValue () ;
      result << " * " ;
      result << enumerator_631.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " ;\n" ;
      index_631_.increment () ;
      enumerator_631.gotoNextObject () ;
    }
  }
  result << "//--- Attribute observers\n" ;
  GALGAS_uint index_784_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_784 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_784.hasCurrentObject ()) {
      result << "  @private NSMutableSet * " ;
      result << enumerator_784.current_mAttributeName (HERE).stringValue () ;
      result << "_observers ;\n" ;
      index_784_.increment () ;
      enumerator_784.gotoNextObject () ;
    }
  }
  GALGAS_uint index_875_ (0) ;
  if (in_TRANSIENT_5F_LIST.isValid ()) {
    cEnumerator_transientListForImplementation enumerator_875 (in_TRANSIENT_5F_LIST, kEnumeration_up) ;
    while (enumerator_875.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_875.current_mTransientName (HERE).stringValue () ;
      result << "' transient cache\n"
        "  @private " ;
      result << categoryReader_ocTypeName (enumerator_875.current_mTransientType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (37)).stringValue () ;
      result << " " ;
      result << enumerator_875.current_mTransientName (HERE).stringValue () ;
      result << "__cache ;\n"
        "  @private BOOL " ;
      result << enumerator_875.current_mTransientName (HERE).stringValue () ;
      result << "__computed ;\n" ;
      index_875_.increment () ;
      enumerator_875.gotoNextObject () ;
    }
  }
  result << "\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//-----------------------------------------------------------------------------*
//                                                                             *
//   Filewrapper template 'documentGenerationTemplate documentDeclaration2'    *
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentDeclaration_32_ (C_Compiler * inCompiler,
                                                                                      const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST,
                                                                                      const GALGAS_lstringlist & in_ACTION_5F_LIST
                                                                                      COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  GALGAS_uint index_26_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_26 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_26.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_26.current_mAttributeName (HERE).stringValue () ;
      result << "' attribute\n"
        "  @property" ;
      result << categoryReader_propertyAttributeString (enumerator_26.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (4)).stringValue () ;
      result << " " ;
      result << categoryReader_ocTypeName (enumerator_26.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (4)).stringValue () ;
      result << " " ;
      result << enumerator_26.current_mAttributeName (HERE).stringValue () ;
      result << " ;\n"
        "  - (void) addObserverOf_" ;
      result << enumerator_26.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver ;\n"
        "  - (void) removeObserverOf_" ;
      result << enumerator_26.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver ;\n"
        "\n" ;
      index_26_.increment () ;
      enumerator_26.gotoNextObject () ;
    }
  }
  result << "//--- Actions\n" ;
  GALGAS_uint index_339_ (0) ;
  if (in_ACTION_5F_LIST.isValid ()) {
    cEnumerator_lstringlist enumerator_339 (in_ACTION_5F_LIST, kEnumeration_up) ;
    while (enumerator_339.hasCurrentObject ()) {
      result << "- (IBAction) " ;
      result << enumerator_339.current_mValue (HERE).mAttribute_string.stringValue () ;
      result << ": (id) inSender ;\n" ;
      index_339_.increment () ;
      enumerator_339.gotoNextObject () ;
    }
  }
  result << "\n"
    "@end\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//-----------------------------------------------------------------------------*
//                                                                             *
//  Filewrapper template 'documentGenerationTemplate documentImplementation'   *
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentImplementation (C_Compiler * inCompiler,
                                                                                     const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                     const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                     const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                     const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                     const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST,
                                                                                     const GALGAS_stringset & in_INCLUSION_5F_SET,
                                                                                     const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                     const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                     COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#import \"PMAllocationDebug.h\"\n"
    "#import \"easy-bindings-utilities.h\"\n"
    "#import \"PMApplication.h\"\n"
    "#import \"PMEntityArrayController.h\"\n"
    "#import \"PMEntityController.h\"\n"
    "#import \"" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << ".h\"\n"
    "#import \"" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << ".h\"\n" ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsStrictSup, in_TRANSIENT_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (8)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_0) {
    result << "#import \"" ;
    result << in_DOCUMENT_5F_NAME.stringValue () ;
    result << "-computations.h\"\n" ;
  }else if (kBoolFalse == test_0) {
  }
  GALGAS_uint index_330_ (0) ;
  if (in_INCLUSION_5F_SET.isValid ()) {
    cEnumerator_stringset enumerator_330 (in_INCLUSION_5F_SET, kEnumeration_up) ;
    while (enumerator_330.hasCurrentObject ()) {
      result << "#import \"" ;
      result << enumerator_330.current_key (HERE).stringValue () ;
      result << ".h\"\n" ;
      index_330_.increment () ;
      enumerator_330.gotoNextObject () ;
    }
  }
  result << "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "@implementation " ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << "\n"
    "\n" ;
  const enumGalgasBool test_1 = GALGAS_bool (kIsStrictSup, in_ATTRIBUTE_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (21)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_1) {
    result << "//----------------------------------------------------------------------------*\n"
      "//    @synthesize                                                             *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n" ;
    GALGAS_uint index_787_ (0) ;
    if (in_ATTRIBUTE_5F_LIST.isValid ()) {
      cEnumerator_attributeListForImplementation enumerator_787 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
      while (enumerator_787.hasCurrentObject ()) {
        result << "@synthesize " ;
        result << enumerator_787.current_mAttributeName (HERE).stringValue () ;
        result << " ;\n" ;
        index_787_.increment () ;
        enumerator_787.gotoNextObject () ;
      }
    }
    result << "\n" ;
  }else if (kBoolFalse == test_1) {
  }
  const enumGalgasBool test_2 = GALGAS_bool (kIsStrictSup, in_ATTRIBUTE_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (34)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_2) {
    result << "//----------------------------------------------------------------------------*\n"
      "//    Swizzle                                                                 *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n"
      "+ (void) load {\n"
      "  Method original, swizzled ;\n" ;
    GALGAS_uint index_1194_ (0) ;
    if (in_ATTRIBUTE_5F_LIST.isValid ()) {
      cEnumerator_attributeListForImplementation enumerator_1194 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
      while (enumerator_1194.hasCurrentObject ()) {
        result << "  original = class_getInstanceMethod (self, @selector (set" ;
        result << enumerator_1194.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (43)).stringValue () ;
        result << ":));\n"
          "  swizzled = class_getInstanceMethod (self, @selector (set" ;
        result << enumerator_1194.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (44)).stringValue () ;
        result << "_swizzled:));\n"
          "  macroCheckMethodSwizzling (original, swizzled) ;\n"
          "  method_exchangeImplementations (original, swizzled) ;\n" ;
        index_1194_.increment () ;
        enumerator_1194.gotoNextObject () ;
      }
    }
    result << "}\n"
      "\n" ;
  }else if (kBoolFalse == test_2) {
  }
  const enumGalgasBool test_3 = GALGAS_bool (kIsStrictSup, in_ATTRIBUTE_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (53)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_3) {
    result << "//----------------------------------------------------------------------------*\n"
      "//    init                                                                    *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n"
      "- (instancetype) init {\n"
      "  self = [super init] ;\n"
      "  if (self) {\n" ;
    GALGAS_uint index_1931_ (0) ;
    if (in_ATTRIBUTE_5F_LIST.isValid ()) {
      cEnumerator_attributeListForImplementation enumerator_1931 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
      while (enumerator_1931.hasCurrentObject ()) {
        result << "    self." ;
        result << enumerator_1931.current_mAttributeName (HERE).stringValue () ;
        result << " = " ;
        result << enumerator_1931.current_mDirectOCDefaultValue (HERE).stringValue () ;
        result << " ;\n" ;
        index_1931_.increment () ;
        enumerator_1931.gotoNextObject () ;
      }
    }
    result << function_generateAddObserverForTransients (in_TRANSIENT_5F_LIST, GALGAS_string ("  "), inCompiler COMMA_SOURCE_FILE_AT_LINE (65)).stringValue () ;
    result << "  }\n"
      "  return self ;\n"
      "}\n"
      "\n" ;
  }else if (kBoolFalse == test_3) {
  }
  result << "//----------------------------------------------------------------------------*\n"
    "//    windowNibName                                                           *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (NSString *) windowNibName {\n"
    "  return @\"" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << "\" ;\n"
    "}\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "//    rootEntityClass                                                         *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (Class) rootEntityClass {\n"
    "  return [" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " class] ;\n"
    "}\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "//    rootObject                                                              *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " *) rootObject {\n"
    "  return (" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " *) mRootObject ;\n"
    "}\n"
    "\n" ;
  GALGAS_uint index_3067_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_3067 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_3067.hasCurrentObject ()) {
      result << "//----------------------------------------------------------------------------*\n"
        "//    '" ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << "' attribute                                            *\n"
        "//----------------------------------------------------------------------------*\n"
        "\n"
        "- (void) set" ;
      result << enumerator_3067.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (104)).stringValue () ;
      result << "_swizzled: (" ;
      result << categoryReader_ocTypeName (enumerator_3067.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (104)).stringValue () ;
      result << ") inNewValue {\n"
        "  if (! (" ;
      result << categoryReader_equalExpression (enumerator_3067.current_mType (HERE), GALGAS_string ("self.").operator_concat (enumerator_3067.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (105)), GALGAS_string ("inNewValue"), inCompiler COMMA_SOURCE_FILE_AT_LINE (105)).stringValue () ;
      result << ")) {\n"
        "    [self set" ;
      result << enumerator_3067.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (106)).stringValue () ;
      result << "_swizzled:inNewValue] ;\n"
        "    [" ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << "_observers makeObjectsPerformSelector:@selector (" ;
      result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (107)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (107)).operator_concat (enumerator_3067.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (107)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (107)).stringValue () ;
      result << "_didChange)] ;\n" ;
      result << function_generateObjectiveCTransientTriggering (enumerator_3067.current_mAttributeName (HERE), in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST, GALGAS_string ("document"), inCompiler COMMA_SOURCE_FILE_AT_LINE (108)).stringValue () ;
      result << "  }\n"
        "}\n"
        "\n"
        "//----------------------------------------------------------------------------*\n"
        "\n"
        "- (void) addObserverOf_" ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver {\n"
        "  if (nil == " ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << "_observers) {\n"
        "    " ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << "_observers = [NSMutableSet new] ;\n"
        "  }\n"
        "  [" ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << "_observers addObject:inObserver] ;\n"
        "  [inObserver performSelector:@selector (" ;
      result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (119)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (119)).operator_concat (enumerator_3067.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (119)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (119)).stringValue () ;
      result << "_didChange)] ;\n"
        "}\n"
        "\n"
        "//----------------------------------------------------------------------------*\n"
        "\n"
        "- (void) removeObserverOf_" ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver {\n"
        "  [" ;
      result << enumerator_3067.current_mAttributeName (HERE).stringValue () ;
      result << "_observers removeObject:inObserver] ;\n"
        "  [inObserver performSelector:@selector (" ;
      result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (126)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (126)).operator_concat (enumerator_3067.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (126)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (126)).stringValue () ;
      result << "_didChange)] ;\n"
        "}\n"
        "\n" ;
      index_3067_.increment () ;
      enumerator_3067.gotoNextObject () ;
    }
  }
  result << "\n"
    "//----------------------------------------------------------------------------*\n"
    "//    windowControllerDidLoadNib                                              *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (void) windowControllerDidLoadNib: (NSWindowController *) inWindowController { \n"
    "  #ifdef EASY_BINDINGS_DEBUG\n"
    "    NSLog (@\"%s\", __PRETTY_FUNCTION__) ;\n"
    "  #endif\n"
    "  [super windowControllerDidLoadNib:inWindowController] ;\n"
    "//--------------------------- Controller instanciation\n" ;
  GALGAS_uint index_5200_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_5200 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_5200.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_5200.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << "' controller instanciation\n"
        "  " ;
      result << enumerator_5200.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " = [" ;
      result << enumerator_5200.current_mControllerClassName (HERE).stringValue () ;
      result << " new] ;\n" ;
      const enumGalgasBool test_4 = GALGAS_bool (kIsNotEqual, enumerator_5200.current_mControlledClassOrEntityName (HERE).mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
      if (kBoolTrue == test_4) {
        result << "  " ;
        result << enumerator_5200.current_lkey (HERE).mAttribute_string.stringValue () ;
        result << ".objectClass = [" ;
        result << enumerator_5200.current_mControlledClassOrEntityName (HERE).mAttribute_string.stringValue () ;
        result << " class] ;\n"
          "  " ;
        result << enumerator_5200.current_lkey (HERE).mAttribute_string.stringValue () ;
        result << ".entityManager = self.entityManager ;\n" ;
      }else if (kBoolFalse == test_4) {
      }
      index_5200_.increment () ;
      enumerator_5200.gotoNextObject () ;
    }
  }
  result << "//--------------------------- Controller bindings\n" ;
  GALGAS_uint index_5608_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_5608 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_5608.hasCurrentObject ()) {
      GALGAS_uint index_5708_ (0) ;
      if (enumerator_5608.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_5708 (enumerator_5608.current_mControllerBindingList (HERE), kEnumeration_up) ;
        const bool nonEmpty_enumerator_5708 = enumerator_5708.hasCurrentObject () ;
        if (nonEmpty_enumerator_5708) {
          result << "//--- '" ;
          result << enumerator_5608.current_lkey (HERE).mAttribute_string.stringValue () ;
          result << "' controller bindings\n" ;
        }
        while (enumerator_5708.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCBinding ((const cPtr_abstractBindingForGeneration *) enumerator_5708.current_mBinding (HERE).ptr (), enumerator_5608.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (158)).stringValue () ;
          index_5708_.increment () ;
          enumerator_5708.gotoNextObject () ;
        }
      }
      index_5608_.increment () ;
      enumerator_5608.gotoNextObject () ;
    }
  }
  result << "//--------------------------- Outlet bindings\n" ;
  GALGAS_uint index_5857_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_5857 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_5857.hasCurrentObject ()) {
      result << "//--- Outlet " ;
      result << enumerator_5857.current_mOutletName (HERE).stringValue () ;
      result << "\n"
        "  if (nil == " ;
      result << enumerator_5857.current_mOutletName (HERE).stringValue () ;
      result << ") {\n"
        "    presentErrorWindow (__FILE__, __LINE__, @\"the '" ;
      result << enumerator_5857.current_mOutletName (HERE).stringValue () ;
      result << "' outlet is nil\") ;\n"
        "  }\n" ;
      GALGAS_uint index_6065_ (0) ;
      if (enumerator_5857.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_6065 (enumerator_5857.current_mOutletBindingList (HERE), kEnumeration_up) ;
        while (enumerator_6065.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCBinding ((const cPtr_abstractBindingForGeneration *) enumerator_6065.current_mBinding (HERE).ptr (), enumerator_5857.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (170)).stringValue () ;
          index_6065_.increment () ;
          enumerator_6065.gotoNextObject () ;
        }
      }
      index_5857_.increment () ;
      enumerator_5857.gotoNextObject () ;
    }
  }
  result << "//--------------------------- Add Transient observers\n" ;
  result << function_generateAddObserverForTransients (in_TRANSIENT_5F_LIST, GALGAS_string::makeEmptyString (), inCompiler COMMA_SOURCE_FILE_AT_LINE (174)).stringValue () ;
  result << "//--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_5 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_5) {
    result << "  [mRootObject addSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_5) {
  }
  result << "}\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "//   R E M O V E    W I N D O W    C O N T R O L L E R                        *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (void) removeWindowController:(NSWindowController *) inWindowController {\n"
    "  //NSLog (@\"%s\", __PRETTY_FUNCTION__) ;\n"
    "//--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_6 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_6) {
    result << "  [mRootObject removeSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_6) {
  }
  result << "//--- Unbind Outlets\n" ;
  GALGAS_uint index_6946_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_6946 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_6946.hasCurrentObject ()) {
      GALGAS_uint index_6980_ (0) ;
      if (enumerator_6946.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_6980 (enumerator_6946.current_mOutletBindingList (HERE), kEnumeration_down) ;
        while (enumerator_6980.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_6980.current_mBinding (HERE).ptr (), enumerator_6946.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (196)).stringValue () ;
          index_6980_.increment () ;
          enumerator_6980.gotoNextObject () ;
        }
      }
      index_6946_.increment () ;
      enumerator_6946.gotoNextObject () ;
    }
  }
  result << "//--- Unbind Controllers\n" ;
  GALGAS_uint index_7104_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_7104 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_7104.hasCurrentObject ()) {
      GALGAS_uint index_7140_ (0) ;
      if (enumerator_7104.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_7140 (enumerator_7104.current_mControllerBindingList (HERE), kEnumeration_up) ;
        while (enumerator_7140.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_7140.current_mBinding (HERE).ptr (), enumerator_7104.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (202)).stringValue () ;
          index_7140_.increment () ;
          enumerator_7140.gotoNextObject () ;
        }
      }
      index_7104_.increment () ;
      enumerator_7104.gotoNextObject () ;
    }
  }
  result << "//--- Remove Transient observers\n" ;
  result << function_generateRemoveObserverForTransients (in_TRANSIENT_5F_LIST, inCompiler COMMA_SOURCE_FILE_AT_LINE (206)).stringValue () ;
  result << "//--- Release controllers\n" ;
  GALGAS_uint index_7355_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_7355 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_7355.hasCurrentObject ()) {
      result << "  macroReleaseSetToNil (" ;
      result << enumerator_7355.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << ") ;\n" ;
      index_7355_.increment () ;
      enumerator_7355.gotoNextObject () ;
    }
  }
  result << "//--- Remove circularities in outlets\n" ;
  GALGAS_uint index_7482_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_7482 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_7482.hasCurrentObject ()) {
      const enumGalgasBool test_7 = enumerator_7482.current_mImplementsDeallocProtocol (HERE).boolEnum () ;
      if (kBoolTrue == test_7) {
        result << "  [" ;
        result << enumerator_7482.current_mOutletName (HERE).stringValue () ;
        result << " objectWillBeDeallocated] ;\n" ;
      }else if (kBoolFalse == test_7) {
      }
      index_7482_.increment () ;
      enumerator_7482.gotoNextObject () ;
    }
  }
  result << "//---\n"
    "  [super removeWindowController:inWindowController] ;\n"
    "}\n"
    "\n" ;
  result << function_generateObserverRoutinesForTransient (in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST, GALGAS_string ("document"), inCompiler COMMA_SOURCE_FILE_AT_LINE (221)).stringValue () ;
  result << function_generateObjectiveCTransientCacheRoutine (in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST, inCompiler COMMA_SOURCE_FILE_AT_LINE (223)).stringValue () ;
  const enumGalgasBool test_8 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_8) {
    result << "//----------------------------------------------------------------------------*\n"
      "//   T R I G G E R    S I G N A T U R E    C O M P U T I N G                  *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n"
      "- (void) triggerSignatureComputing {\n"
      "  #ifdef EASY_BINDINGS_DEBUG\n"
      "    NSLog (@\"%s\", __PRETTY_FUNCTION__) ;\n"
      "  #endif\n" ;
    GALGAS_uint index_8226_ (0) ;
    if (in_TRANSIENT_5F_LIST.isValid ()) {
      cEnumerator_transientListForImplementation enumerator_8226 (in_TRANSIENT_5F_LIST, kEnumeration_up) ;
      while (enumerator_8226.hasCurrentObject ()) {
        const enumGalgasBool test_9 = GALGAS_bool (kIsStrictSup, enumerator_8226.current_mRootSignDependencyList (HERE).reader_length (SOURCE_FILE_AT_LINE (236)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
        if (kBoolTrue == test_9) {
          result << "  if (" ;
          result << enumerator_8226.current_mTransientName (HERE).stringValue () ;
          result << "__computed) {\n"
            "    " ;
          result << enumerator_8226.current_mTransientName (HERE).stringValue () ;
          result << "__computed = NO ;\n"
            "    [PMApplication\n"
            "      enterTriggerForObject:self\n"
            "      transientIndex:" ;
          result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (241)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (241)).operator_concat (enumerator_8226.current_mTransientName (HERE) COMMA_SOURCE_FILE_AT_LINE (241)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (241)).stringValue () ;
          result << "\n"
            "    ] ;\n"
            "  }\n" ;
        }else if (kBoolFalse == test_9) {
        }
        index_8226_.increment () ;
        enumerator_8226.gotoNextObject () ;
      }
    }
    result << "}\n"
      "\n"
      "//----------------------------------------------------------------------------*\n"
      "\n" ;
  }else if (kBoolFalse == test_8) {
  }
  result << "\n" ;
  return GALGAS_string (result) ;
}

//-----------------------------------------------------------------------------*
//                                                                             *
//Filewrapper template 'documentGenerationTemplate documentImplementationInSwift'*
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentImplementationInSwift (C_Compiler * inCompiler,
                                                                                            const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                            const GALGAS_string & in_ROOT_5F_ENTITY_5F_NAME,
                                                                                            const GALGAS_outletGenerationList & in_OUTLET_5F_GENERATION_5F_LIST,
                                                                                            const GALGAS_controllerMap & in_CONTROLLER_5F_MAP,
                                                                                            const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION,
                                                                                            const GALGAS_stringset & /* in_INCLUSION_5F_SET */,
                                                                                            const GALGAS_bool & in_HAS_5F_SIGNATURE_5F_OBSERVER,
                                                                                            const GALGAS_attributeListForImplementation & in_ATTRIBUTE_5F_LIST
                                                                                            COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "\n"
    "import Cocoa\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "@objc(" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << ") class " ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << " : PMManagedDocument {\n"
    "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //    Outlets                                                                 *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_446_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_446 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_446.hasCurrentObject ()) {
      result << "  @IBOutlet var " ;
      result << enumerator_446.current_mOutletName (HERE).stringValue () ;
      result << " : " ;
      result << enumerator_446.current_mOutletType (HERE).stringValue () ;
      result << "\n" ;
      index_446_.increment () ;
      enumerator_446.gotoNextObject () ;
    }
  }
  result << "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //    Controllers                                                             *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_779_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_779 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_779.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_779.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << "' controller\n"
        "  @private " ;
      result << enumerator_779.current_mControllerClassName (HERE).stringValue () ;
      result << " * " ;
      result << enumerator_779.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " ;\n" ;
      index_779_.increment () ;
      enumerator_779.gotoNextObject () ;
    }
  }
  result << "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //    Documents attributes                                                    *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_1155_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_1155 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_1155.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_1155.current_mAttributeName (HERE).stringValue () ;
      result << "' attribute\n"
        "  @property" ;
      result << categoryReader_propertyAttributeString (enumerator_1155.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (34)).stringValue () ;
      result << " " ;
      result << categoryReader_ocTypeName (enumerator_1155.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (34)).stringValue () ;
      result << " " ;
      result << enumerator_1155.current_mAttributeName (HERE).stringValue () ;
      result << " ;\n"
        "  - (void) addObserverOf_" ;
      result << enumerator_1155.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver ;\n"
        "  - (void) removeObserverOf_" ;
      result << enumerator_1155.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver ;\n"
        "\n" ;
      index_1155_.increment () ;
      enumerator_1155.gotoNextObject () ;
    }
  }
  result << "//--- Attribute observers\n" ;
  GALGAS_uint index_1483_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_1483 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_1483.hasCurrentObject ()) {
      result << "  @private NSMutableSet * " ;
      result << enumerator_1483.current_mAttributeName (HERE).stringValue () ;
      result << "_observers ;\n" ;
      index_1483_.increment () ;
      enumerator_1483.gotoNextObject () ;
    }
  }
  result << "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //    windowNibName                                                           *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n"
    "  var windowNibName: String {\n"
    "    return \"" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << "\"\n"
    "  }\n"
    "\n"
    "  //-----------------------------------------------------------------------------*\n"
    "  //    rootEntityClassName                                                      *\n"
    "  //-----------------------------------------------------------------------------*\n"
    "\n"
    "  override func rootEntityClassName () -> String {\n"
    "    return \"" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << "\"\n"
    "  }\n"
    "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //    rootObject                                                              *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n"
    "  func rootObject () -> MyRootEntity {\n"
    "    return mRootObject as " ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << "\n"
    "  }\n"
    "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //    windowControllerDidLoadNib                                              *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n"
    "  override func windowControllerDidLoadNib (aController: NSWindowController) {\n"
    "    super.windowControllerDidLoadNib (aController)\n"
    "  //--------------------------- Controller instanciation\n" ;
  GALGAS_uint index_2999_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_2999 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_2999.hasCurrentObject ()) {
      result << "//--- '" ;
      result << enumerator_2999.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << "' controller instanciation\n"
        "  " ;
      result << enumerator_2999.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << " = [" ;
      result << enumerator_2999.current_mControllerClassName (HERE).stringValue () ;
      result << " new] ;\n" ;
      const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, enumerator_2999.current_mControlledClassOrEntityName (HERE).mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
      if (kBoolTrue == test_0) {
        result << "  " ;
        result << enumerator_2999.current_lkey (HERE).mAttribute_string.stringValue () ;
        result << ".objectClass = [" ;
        result << enumerator_2999.current_mControlledClassOrEntityName (HERE).mAttribute_string.stringValue () ;
        result << " class] ;\n"
          "  " ;
        result << enumerator_2999.current_lkey (HERE).mAttribute_string.stringValue () ;
        result << ".entityManager = self.entityManager ;\n" ;
      }else if (kBoolFalse == test_0) {
      }
      index_2999_.increment () ;
      enumerator_2999.gotoNextObject () ;
    }
  }
  result << "  //--------------------------- Controller bindings\n" ;
  GALGAS_uint index_3409_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_3409 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_3409.hasCurrentObject ()) {
      GALGAS_uint index_3509_ (0) ;
      if (enumerator_3409.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_3509 (enumerator_3409.current_mControllerBindingList (HERE), kEnumeration_up) ;
        const bool nonEmpty_enumerator_3509 = enumerator_3509.hasCurrentObject () ;
        if (nonEmpty_enumerator_3509) {
          result << "//--- '" ;
          result << enumerator_3409.current_lkey (HERE).mAttribute_string.stringValue () ;
          result << "' controller bindings\n" ;
        }
        while (enumerator_3509.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCBinding ((const cPtr_abstractBindingForGeneration *) enumerator_3509.current_mBinding (HERE).ptr (), enumerator_3409.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (91)).stringValue () ;
          index_3509_.increment () ;
          enumerator_3509.gotoNextObject () ;
        }
      }
      index_3409_.increment () ;
      enumerator_3409.gotoNextObject () ;
    }
  }
  result << "  //--------------------------- Outlet bindings\n" ;
  GALGAS_uint index_3660_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_3660 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_3660.hasCurrentObject ()) {
      result << "  //--- Outlet " ;
      result << enumerator_3660.current_mOutletName (HERE).stringValue () ;
      result << "\n"
        "    if nil == " ;
      result << enumerator_3660.current_mOutletName (HERE).stringValue () ;
      result << " {\n"
        "      presentErrorWindow (__FILE__, __LINE__, \"the '" ;
      result << enumerator_3660.current_mOutletName (HERE).stringValue () ;
      result << "' outlet is nil\") ;\n"
        "    }\n" ;
      GALGAS_uint index_3873_ (0) ;
      if (enumerator_3660.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_3873 (enumerator_3660.current_mOutletBindingList (HERE), kEnumeration_up) ;
        while (enumerator_3873.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftBinding ((const cPtr_abstractBindingForGeneration *) enumerator_3873.current_mBinding (HERE).ptr (), enumerator_3660.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (103)).stringValue () ;
          index_3873_.increment () ;
          enumerator_3873.gotoNextObject () ;
        }
      }
      index_3660_.increment () ;
      enumerator_3660.gotoNextObject () ;
    }
  }
  result << "  //--------------------------- Add Transient observers\n" ;
  result << function_generateAddObserverForTransients (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, GALGAS_string::makeEmptyString (), inCompiler COMMA_SOURCE_FILE_AT_LINE (107)).stringValue () ;
  result << "  //--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_1 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_1) {
    result << "  [mRootObject addSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_1) {
  }
  result << "}\n"
    "\n"
    "  //----------------------------------------------------------------------------*\n"
    "  //   R E M O V E    W I N D O W    C O N T R O L L E R                        *\n"
    "  //----------------------------------------------------------------------------*\n"
    "\n"
    "  override func removeWindowController (inWindowController : NSWindowController) {\n"
    "  //--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_2 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_2) {
    result << "  [mRootObject removeSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_2) {
  }
  result << "  //--- Unbind Outlets\n" ;
  GALGAS_uint index_4747_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_4747 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_4747.hasCurrentObject ()) {
      GALGAS_uint index_4781_ (0) ;
      if (enumerator_4747.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_4781 (enumerator_4747.current_mOutletBindingList (HERE), kEnumeration_down) ;
        while (enumerator_4781.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_4781.current_mBinding (HERE).ptr (), enumerator_4747.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (128)).stringValue () ;
          index_4781_.increment () ;
          enumerator_4781.gotoNextObject () ;
        }
      }
      index_4747_.increment () ;
      enumerator_4747.gotoNextObject () ;
    }
  }
  result << "  //--- Unbind Controllers\n" ;
  GALGAS_uint index_4902_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_4902 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_4902.hasCurrentObject ()) {
      GALGAS_uint index_4938_ (0) ;
      if (enumerator_4902.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_4938 (enumerator_4902.current_mControllerBindingList (HERE), kEnumeration_up) ;
        while (enumerator_4938.hasCurrentObject ()) {
          result << callCategoryReader_generateSwiftRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_4938.current_mBinding (HERE).ptr (), enumerator_4902.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (134)).stringValue () ;
          index_4938_.increment () ;
          enumerator_4938.gotoNextObject () ;
        }
      }
      index_4902_.increment () ;
      enumerator_4902.gotoNextObject () ;
    }
  }
  result << "  //--- Remove Transient observers\n" ;
  result << function_generateRemoveObserverForTransients (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, inCompiler COMMA_SOURCE_FILE_AT_LINE (138)).stringValue () ;
  result << "  //--- Release controllers\n" ;
  GALGAS_uint index_5171_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_5171 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_5171.hasCurrentObject ()) {
      result << "  macroReleaseSetToNil (" ;
      result << enumerator_5171.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << ") ;\n" ;
      index_5171_.increment () ;
      enumerator_5171.gotoNextObject () ;
    }
  }
  result << "  //--- Remove circularities in outlets\n" ;
  GALGAS_uint index_5300_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_5300 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_5300.hasCurrentObject ()) {
      const enumGalgasBool test_3 = enumerator_5300.current_mImplementsDeallocProtocol (HERE).boolEnum () ;
      if (kBoolTrue == test_3) {
        result << "  [" ;
        result << enumerator_5300.current_mOutletName (HERE).stringValue () ;
        result << " objectWillBeDeallocated] ;\n" ;
      }else if (kBoolFalse == test_3) {
      }
      index_5300_.increment () ;
      enumerator_5300.gotoNextObject () ;
    }
  }
  result << "  //---\n"
    "    super.removeWindowController (inWindowController)\n"
    "  }\n" ;
  GALGAS_uint index_5515_ (0) ;
  if (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION.isValid ()) {
    cEnumerator_transientListForImplementation enumerator_5515 (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, kEnumeration_up) ;
    while (enumerator_5515.hasCurrentObject ()) {
      result << "  //-----------------------------------------------------------------------------*\n"
        "  //    " ;
      result << GALGAS_string ("Transient: ").operator_concat (enumerator_5515.current_mTransientName (HERE) COMMA_SOURCE_FILE_AT_LINE (155)).reader_stringByRightPadding (GALGAS_uint ((uint32_t) 73U), GALGAS_char (TO_UNICODE (32)) COMMA_SOURCE_FILE_AT_LINE (155)).stringValue () ;
      result << "*\n"
        "  //-----------------------------------------------------------------------------*\n"
        "\n"
        "  var " ;
      result << enumerator_5515.current_mTransientName (HERE).stringValue () ;
      result << "__cache : " ;
      result << categoryReader_swiftTypeName (enumerator_5515.current_mTransientType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (157)).stringValue () ;
      result << "\?\n"
        "  var " ;
      result << enumerator_5515.current_mTransientName (HERE).stringValue () ;
      result << " : " ;
      result << categoryReader_swiftTypeName (enumerator_5515.current_mTransientType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (158)).stringValue () ;
      result << " {\n" ;
      result << function_generateSwiftTransientCacheRoutine (in_DOCUMENT_5F_NAME, enumerator_5515.current_mTransientType (HERE), enumerator_5515.current_mTransientName (HERE), enumerator_5515.current_mDependencyList (HERE), enumerator_5515.current_mRootSignDependencyList (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (159)).stringValue () ;
      result << "  }\n"
        "\n" ;
      index_5515_.increment () ;
      enumerator_5515.gotoNextObject () ;
    }
  }
  result << "\n"
    "}\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "/*\n" ;
  const enumGalgasBool test_4 = GALGAS_bool (kIsStrictSup, in_ATTRIBUTE_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (191)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_4) {
    result << "//----------------------------------------------------------------------------*\n"
      "//    @synthesize                                                             *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n" ;
    GALGAS_uint index_6383_ (0) ;
    if (in_ATTRIBUTE_5F_LIST.isValid ()) {
      cEnumerator_attributeListForImplementation enumerator_6383 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
      while (enumerator_6383.hasCurrentObject ()) {
        result << "@synthesize " ;
        result << enumerator_6383.current_mAttributeName (HERE).stringValue () ;
        result << " ;\n" ;
        index_6383_.increment () ;
        enumerator_6383.gotoNextObject () ;
      }
    }
    result << "\n" ;
  }else if (kBoolFalse == test_4) {
  }
  const enumGalgasBool test_5 = GALGAS_bool (kIsStrictSup, in_ATTRIBUTE_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (204)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_5) {
    result << "//----------------------------------------------------------------------------*\n"
      "//    Swizzle                                                                 *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n"
      "+ (void) load {\n"
      "  Method original, swizzled ;\n" ;
    GALGAS_uint index_6790_ (0) ;
    if (in_ATTRIBUTE_5F_LIST.isValid ()) {
      cEnumerator_attributeListForImplementation enumerator_6790 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
      while (enumerator_6790.hasCurrentObject ()) {
        result << "  original = class_getInstanceMethod (self, @selector (set" ;
        result << enumerator_6790.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (213)).stringValue () ;
        result << ":));\n"
          "  swizzled = class_getInstanceMethod (self, @selector (set" ;
        result << enumerator_6790.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (214)).stringValue () ;
        result << "_swizzled:));\n"
          "  macroCheckMethodSwizzling (original, swizzled) ;\n"
          "  method_exchangeImplementations (original, swizzled) ;\n" ;
        index_6790_.increment () ;
        enumerator_6790.gotoNextObject () ;
      }
    }
    result << "}\n"
      "\n" ;
  }else if (kBoolFalse == test_5) {
  }
  const enumGalgasBool test_6 = GALGAS_bool (kIsStrictSup, in_ATTRIBUTE_5F_LIST.reader_length (SOURCE_FILE_AT_LINE (223)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_6) {
    result << "//----------------------------------------------------------------------------*\n"
      "//    init                                                                    *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n"
      "- (instancetype) init {\n"
      "  self = [super init] ;\n"
      "  if (self) {\n" ;
    GALGAS_uint index_7527_ (0) ;
    if (in_ATTRIBUTE_5F_LIST.isValid ()) {
      cEnumerator_attributeListForImplementation enumerator_7527 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
      while (enumerator_7527.hasCurrentObject ()) {
        result << "    self." ;
        result << enumerator_7527.current_mAttributeName (HERE).stringValue () ;
        result << " = " ;
        result << enumerator_7527.current_mDirectOCDefaultValue (HERE).stringValue () ;
        result << " ;\n" ;
        index_7527_.increment () ;
        enumerator_7527.gotoNextObject () ;
      }
    }
    result << function_generateAddObserverForTransients (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, GALGAS_string ("  "), inCompiler COMMA_SOURCE_FILE_AT_LINE (235)).stringValue () ;
    result << "  }\n"
      "  return self ;\n"
      "}\n"
      "\n" ;
  }else if (kBoolFalse == test_6) {
  }
  result << "//----------------------------------------------------------------------------*\n"
    "//    windowNibName                                                           *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (NSString *) windowNibName {\n"
    "  return @\"" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << "\" ;\n"
    "}\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "//    rootEntityClass                                                         *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (Class) rootEntityClass {\n"
    "  return [" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " class] ;\n"
    "}\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "//    rootObject                                                              *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " *) rootObject {\n"
    "  return (" ;
  result << in_ROOT_5F_ENTITY_5F_NAME.stringValue () ;
  result << " *) mRootObject ;\n"
    "}\n"
    "\n" ;
  GALGAS_uint index_8682_ (0) ;
  if (in_ATTRIBUTE_5F_LIST.isValid ()) {
    cEnumerator_attributeListForImplementation enumerator_8682 (in_ATTRIBUTE_5F_LIST, kEnumeration_up) ;
    while (enumerator_8682.hasCurrentObject ()) {
      result << "//----------------------------------------------------------------------------*\n"
        "//    '" ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << "' attribute                                            *\n"
        "//----------------------------------------------------------------------------*\n"
        "\n"
        "- (void) set" ;
      result << enumerator_8682.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (274)).stringValue () ;
      result << "_swizzled: (" ;
      result << categoryReader_ocTypeName (enumerator_8682.current_mType (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (274)).stringValue () ;
      result << ") inNewValue {\n"
        "  if (! (" ;
      result << categoryReader_equalExpression (enumerator_8682.current_mType (HERE), GALGAS_string ("self.").operator_concat (enumerator_8682.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (275)), GALGAS_string ("inNewValue"), inCompiler COMMA_SOURCE_FILE_AT_LINE (275)).stringValue () ;
      result << ")) {\n"
        "    [self set" ;
      result << enumerator_8682.current_mAttributeName (HERE).reader_stringByCapitalizingFirstCharacter (SOURCE_FILE_AT_LINE (276)).stringValue () ;
      result << "_swizzled:inNewValue] ;\n"
        "    [" ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << "_observers makeObjectsPerformSelector:@selector (" ;
      result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (277)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (277)).operator_concat (enumerator_8682.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (277)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (277)).stringValue () ;
      result << "_didChange)] ;\n" ;
      result << function_generateObjectiveCTransientTriggering (enumerator_8682.current_mAttributeName (HERE), in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, GALGAS_string ("document"), inCompiler COMMA_SOURCE_FILE_AT_LINE (278)).stringValue () ;
      result << "  }\n"
        "}\n"
        "\n"
        "//----------------------------------------------------------------------------*\n"
        "\n"
        "- (void) addObserverOf_" ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver {\n"
        "  if (nil == " ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << "_observers) {\n"
        "    " ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << "_observers = [NSMutableSet new] ;\n"
        "  }\n"
        "  [" ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << "_observers addObject:inObserver] ;\n"
        "  [inObserver performSelector:@selector (" ;
      result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (289)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (289)).operator_concat (enumerator_8682.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (289)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (289)).stringValue () ;
      result << "_didChange)] ;\n"
        "}\n"
        "\n"
        "//----------------------------------------------------------------------------*\n"
        "\n"
        "- (void) removeObserverOf_" ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << ": (id) inObserver {\n"
        "  [" ;
      result << enumerator_8682.current_mAttributeName (HERE).stringValue () ;
      result << "_observers removeObject:inObserver] ;\n"
        "  [inObserver performSelector:@selector (" ;
      result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (296)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (296)).operator_concat (enumerator_8682.current_mAttributeName (HERE) COMMA_SOURCE_FILE_AT_LINE (296)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (296)).stringValue () ;
      result << "_didChange)] ;\n"
        "}\n"
        "\n" ;
      index_8682_.increment () ;
      enumerator_8682.gotoNextObject () ;
    }
  }
  result << "\n"
    "//----------------------------------------------------------------------------*\n"
    "//   R E M O V E    W I N D O W    C O N T R O L L E R                        *\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "- (void) removeWindowController:(NSWindowController *) inWindowController {\n"
    "  //NSLog (@\"%s\", __PRETTY_FUNCTION__) ;\n"
    "//--------------------------- Add Signature observer\n" ;
  const enumGalgasBool test_7 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_7) {
    result << "  [mRootObject removeSignatureObserver:self] ;\n" ;
  }else if (kBoolFalse == test_7) {
  }
  result << "//--- Unbind Outlets\n" ;
  GALGAS_uint index_10849_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_10849 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_10849.hasCurrentObject ()) {
      GALGAS_uint index_10883_ (0) ;
      if (enumerator_10849.current_mOutletBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_10883 (enumerator_10849.current_mOutletBindingList (HERE), kEnumeration_down) ;
        while (enumerator_10883.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_10883.current_mBinding (HERE).ptr (), enumerator_10849.current_mOutletName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (316)).stringValue () ;
          index_10883_.increment () ;
          enumerator_10883.gotoNextObject () ;
        }
      }
      index_10849_.increment () ;
      enumerator_10849.gotoNextObject () ;
    }
  }
  result << "//--- Unbind Controllers\n" ;
  GALGAS_uint index_11007_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_11007 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_11007.hasCurrentObject ()) {
      GALGAS_uint index_11043_ (0) ;
      if (enumerator_11007.current_mControllerBindingList (HERE).isValid ()) {
        cEnumerator_outletBindingListForGeneration enumerator_11043 (enumerator_11007.current_mControllerBindingList (HERE), kEnumeration_up) ;
        while (enumerator_11043.hasCurrentObject ()) {
          result << callCategoryReader_generateObjectiveCRemoveBinding ((const cPtr_abstractBindingForGeneration *) enumerator_11043.current_mBinding (HERE).ptr (), enumerator_11007.current_lkey (HERE).mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (322)).stringValue () ;
          index_11043_.increment () ;
          enumerator_11043.gotoNextObject () ;
        }
      }
      index_11007_.increment () ;
      enumerator_11007.gotoNextObject () ;
    }
  }
  result << "//--- Remove Transient observers\n" ;
  result << function_generateRemoveObserverForTransients (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, inCompiler COMMA_SOURCE_FILE_AT_LINE (326)).stringValue () ;
  result << "//--- Release controllers\n" ;
  GALGAS_uint index_11277_ (0) ;
  if (in_CONTROLLER_5F_MAP.isValid ()) {
    cEnumerator_controllerMap enumerator_11277 (in_CONTROLLER_5F_MAP, kEnumeration_up) ;
    while (enumerator_11277.hasCurrentObject ()) {
      result << "  macroReleaseSetToNil (" ;
      result << enumerator_11277.current_lkey (HERE).mAttribute_string.stringValue () ;
      result << ") ;\n" ;
      index_11277_.increment () ;
      enumerator_11277.gotoNextObject () ;
    }
  }
  result << "//--- Remove circularities in outlets\n" ;
  GALGAS_uint index_11404_ (0) ;
  if (in_OUTLET_5F_GENERATION_5F_LIST.isValid ()) {
    cEnumerator_outletGenerationList enumerator_11404 (in_OUTLET_5F_GENERATION_5F_LIST, kEnumeration_up) ;
    while (enumerator_11404.hasCurrentObject ()) {
      const enumGalgasBool test_8 = enumerator_11404.current_mImplementsDeallocProtocol (HERE).boolEnum () ;
      if (kBoolTrue == test_8) {
        result << "  [" ;
        result << enumerator_11404.current_mOutletName (HERE).stringValue () ;
        result << " objectWillBeDeallocated] ;\n" ;
      }else if (kBoolFalse == test_8) {
      }
      index_11404_.increment () ;
      enumerator_11404.gotoNextObject () ;
    }
  }
  result << "//---\n"
    "  [super removeWindowController:inWindowController] ;\n"
    "}\n"
    "\n" ;
  result << function_generateObserverRoutinesForTransient (in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, GALGAS_string ("document"), inCompiler COMMA_SOURCE_FILE_AT_LINE (341)).stringValue () ;
  result << function_generateObjectiveCTransientCacheRoutine (in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, inCompiler COMMA_SOURCE_FILE_AT_LINE (343)).stringValue () ;
  const enumGalgasBool test_9 = in_HAS_5F_SIGNATURE_5F_OBSERVER.boolEnum () ;
  if (kBoolTrue == test_9) {
    result << "//----------------------------------------------------------------------------*\n"
      "//   T R I G G E R    S I G N A T U R E    C O M P U T I N G                  *\n"
      "//----------------------------------------------------------------------------*\n"
      "\n"
      "- (void) triggerSignatureComputing {\n"
      "  #ifdef EASY_BINDINGS_DEBUG\n"
      "    NSLog (@\"%s\", __PRETTY_FUNCTION__) ;\n"
      "  #endif\n" ;
    GALGAS_uint index_12205_ (0) ;
    if (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION.isValid ()) {
      cEnumerator_transientListForImplementation enumerator_12205 (in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, kEnumeration_up) ;
      while (enumerator_12205.hasCurrentObject ()) {
        const enumGalgasBool test_10 = GALGAS_bool (kIsStrictSup, enumerator_12205.current_mRootSignDependencyList (HERE).reader_length (SOURCE_FILE_AT_LINE (356)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
        if (kBoolTrue == test_10) {
          result << "  if (" ;
          result << enumerator_12205.current_mTransientName (HERE).stringValue () ;
          result << "__computed) {\n"
            "    " ;
          result << enumerator_12205.current_mTransientName (HERE).stringValue () ;
          result << "__computed = NO ;\n"
            "    [PMApplication\n"
            "      enterTriggerForObject:self\n"
            "      transientIndex:" ;
          result << GALGAS_string ("document.").operator_concat (in_DOCUMENT_5F_NAME COMMA_SOURCE_FILE_AT_LINE (361)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (361)).operator_concat (enumerator_12205.current_mTransientName (HERE) COMMA_SOURCE_FILE_AT_LINE (361)).reader_identifierRepresentation (SOURCE_FILE_AT_LINE (361)).stringValue () ;
          result << "\n"
            "    ] ;\n"
            "  }\n" ;
        }else if (kBoolFalse == test_10) {
        }
        index_12205_.increment () ;
        enumerator_12205.gotoNextObject () ;
      }
    }
    result << "}\n"
      "\n"
      "//----------------------------------------------------------------------------*\n"
      "\n" ;
  }else if (kBoolFalse == test_9) {
  }
  result << "\n"
    "\n"
    "*/\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//-----------------------------------------------------------------------------*
//                                                                             *
//Filewrapper template 'documentGenerationTemplate documentComputationsHeaderFile'*
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentComputationsHeaderFile (C_Compiler * inCompiler,
                                                                                             const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                             const GALGAS_transientListForImplementation & in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION
                                                                                             COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#import <Cocoa/Cocoa.h>\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "@class " ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << " ;\n"
    "\n" ;
  result << function_generateTransientFunctionDeclarations (in_DOCUMENT_5F_NAME, in_TRANSIENT_5F_LIST_5F_FOR_5F_IMPLEMENTATION, inCompiler COMMA_SOURCE_FILE_AT_LINE (7)).stringValue () ;
  result << "\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//-----------------------------------------------------------------------------*
//                                                                             *
//Filewrapper template 'documentGenerationTemplate documentTransientComputationImplementationFile'*
//                                                                             *
//-----------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_documentGenerationTemplate_documentTransientComputationImplementationFile (C_Compiler * inCompiler,
                                                                                                             const GALGAS_string & in_DOCUMENT_5F_NAME,
                                                                                                             const GALGAS_ebType & in_RESULT_5F_TYPE,
                                                                                                             const GALGAS_string & in_TRANSIENT_5F_NAME,
                                                                                                             const GALGAS_directDependancyList & in_DIRECT_5F_DEPENDANCY_5F_LIST,
                                                                                                             const GALGAS_stringlist & in_ROOT_5F_SIGN_5F_LIST
                                                                                                             COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#import \"" ;
  result << in_DOCUMENT_5F_NAME.stringValue () ;
  result << "-computations.h\"\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n" ;
  result << function_generateTransientFunctionImplementation (in_DOCUMENT_5F_NAME, in_RESULT_5F_TYPE, in_TRANSIENT_5F_NAME, in_DIRECT_5F_DEPENDANCY_5F_LIST, in_ROOT_5F_SIGN_5F_LIST, inCompiler COMMA_SOURCE_FILE_AT_LINE (5)).stringValue () ;
  result << "\n" ;
  return GALGAS_string (result) ;
}

//-----------------------------------------------------------------------------*
//                                                                             *
//          Overriding category method '@documentGeneration generate'          *
//                                                                             *
//-----------------------------------------------------------------------------*

static void categoryMethod_documentGeneration_generate (const cPtr_generation * inObject,
                                                        const GALGAS_string constinArgument_inOutputDirectory,
                                                        C_Compiler * inCompiler
                                                        COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_documentGeneration * object = (const cPtr_documentGeneration *) inObject ;
  macroValidSharedObject (object, cPtr_documentGeneration) ;
  GALGAS_bool var_hasSignatureObserver = GALGAS_bool (false) ;
  cEnumerator_transientListForImplementation enumerator_2310 (object->mAttribute_mTransientListForImplementation, kEnumeration_up) ;
  bool bool_0 = var_hasSignatureObserver.operator_not (SOURCE_FILE_AT_LINE (69)).isValidAndTrue () ;
  if (enumerator_2310.hasCurrentObject () && bool_0) {
    while (enumerator_2310.hasCurrentObject () && bool_0) {
      var_hasSignatureObserver = GALGAS_bool (kIsStrictSup, enumerator_2310.current_mRootSignDependencyList (HERE).reader_length (SOURCE_FILE_AT_LINE (70)).objectCompare (GALGAS_uint ((uint32_t) 0U))) ;
      enumerator_2310.gotoNextObject () ;
      if (enumerator_2310.hasCurrentObject ()) {
        bool_0 = var_hasSignatureObserver.operator_not (SOURCE_FILE_AT_LINE (69)).isValidAndTrue () ;
      }
    }
  }
  const enumGalgasBool test_1 = GALGAS_bool (gOption_easyBindings_5F_options_outputSwift.reader_value ()).boolEnum () ;
  if (kBoolTrue == test_1) {
    GALGAS_string var_s = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentImplementationInSwift (inCompiler, object->mAttribute_mGenerationName, object->mAttribute_mRootEntityName, object->mAttribute_mOutletDeclarationList, object->mAttribute_mControllerMap, object->mAttribute_mTransientListForImplementation, object->mAttribute_mFileInclusionSet.mAttribute_mImplementationFileInclusionSet, var_hasSignatureObserver, object->mAttribute_mAttributeListForImplementation COMMA_SOURCE_FILE_AT_LINE (74))) ;
    {
    GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, object->mAttribute_mGenerationName.operator_concat (GALGAS_string (".swift") COMMA_SOURCE_FILE_AT_LINE (86)), GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_s, GALGAS_string ("\n"
      "\n"), GALGAS_string ("\n"), inCompiler COMMA_SOURCE_FILE_AT_LINE (84)) ;
    }
  }else if (kBoolFalse == test_1) {
    GALGAS_string var_s = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentDeclaration_31_ (inCompiler, object->mAttribute_mGenerationName, object->mAttribute_mRootEntityName, object->mAttribute_mOutletDeclarationList, object->mAttribute_mControllerMap, object->mAttribute_mTransientListForImplementation, object->mAttribute_mFileInclusionSet.mAttribute_mHeaderPredeclarationSet, var_hasSignatureObserver, object->mAttribute_mAttributeListForImplementation COMMA_SOURCE_FILE_AT_LINE (95))) ;
    GALGAS_string var_s_32_ = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentDeclaration_32_ (inCompiler, object->mAttribute_mAttributeListForImplementation, object->mAttribute_mActionList COMMA_SOURCE_FILE_AT_LINE (105))) ;
    {
    GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, object->mAttribute_mGenerationName.operator_concat (GALGAS_string (".h") COMMA_SOURCE_FILE_AT_LINE (111)), GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_s, GALGAS_string ("\n"
      "\n"
      "}\n"
      "\n"), var_s_32_, inCompiler COMMA_SOURCE_FILE_AT_LINE (109)) ;
    }
    var_s = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentImplementation (inCompiler, object->mAttribute_mGenerationName, object->mAttribute_mRootEntityName, object->mAttribute_mOutletDeclarationList, object->mAttribute_mControllerMap, object->mAttribute_mTransientListForImplementation, object->mAttribute_mFileInclusionSet.mAttribute_mImplementationFileInclusionSet, var_hasSignatureObserver, object->mAttribute_mAttributeListForImplementation COMMA_SOURCE_FILE_AT_LINE (119))) ;
    {
    GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, object->mAttribute_mGenerationName.operator_concat (GALGAS_string (".m") COMMA_SOURCE_FILE_AT_LINE (131)), GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_s, GALGAS_string ("\n"
      "\n"), GALGAS_string ("@end\n"), inCompiler COMMA_SOURCE_FILE_AT_LINE (129)) ;
    }
    const enumGalgasBool test_2 = GALGAS_bool (kIsStrictSup, object->mAttribute_mTransientListForImplementation.reader_length (SOURCE_FILE_AT_LINE (139)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
    if (kBoolTrue == test_2) {
      var_s = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentComputationsHeaderFile (inCompiler, object->mAttribute_mGenerationName, object->mAttribute_mTransientListForImplementation COMMA_SOURCE_FILE_AT_LINE (140))) ;
      {
      GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, object->mAttribute_mGenerationName.operator_concat (GALGAS_string ("-computations.h") COMMA_SOURCE_FILE_AT_LINE (146)), GALGAS_string ("//"), GALGAS_string ("\n"
        "\n"), var_s, GALGAS_string ("\n"
        "\n"), GALGAS_string ("\n"), inCompiler COMMA_SOURCE_FILE_AT_LINE (144)) ;
      }
    }
    cEnumerator_transientListForImplementation enumerator_4934 (object->mAttribute_mTransientListForImplementation, kEnumeration_up) ;
    while (enumerator_4934.hasCurrentObject ()) {
      var_s = GALGAS_string (filewrapperTemplate_documentGenerationTemplate_documentTransientComputationImplementationFile (inCompiler, object->mAttribute_mGenerationName, enumerator_4934.current_mTransientType (HERE), enumerator_4934.current_mTransientName (HERE), enumerator_4934.current_mDependencyList (HERE), enumerator_4934.current_mRootSignDependencyList (HERE) COMMA_SOURCE_FILE_AT_LINE (156))) ;
      {
      GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, object->mAttribute_mGenerationName.operator_concat (GALGAS_string ("_") COMMA_SOURCE_FILE_AT_LINE (165)).operator_concat (enumerator_4934.current_mTransientName (HERE) COMMA_SOURCE_FILE_AT_LINE (165)).operator_concat (GALGAS_string (".m") COMMA_SOURCE_FILE_AT_LINE (165)), GALGAS_string ("//"), GALGAS_string ("\n"
        "\n"), var_s, GALGAS_string ("  return what \? ; // ADD YOUR CODE HERE\n"), GALGAS_string ("}\n"
        "\n").operator_concat (GALGAS_string ("//----------------------------------------------------------------------------*\n") COMMA_SOURCE_FILE_AT_LINE (170)), inCompiler COMMA_SOURCE_FILE_AT_LINE (163)) ;
      }
      enumerator_4934.gotoNextObject () ;
    }
  }
}
//-----------------------------------------------------------------------------*

static void defineCategoryMethod_documentGeneration_generate (void) {
  enterCategoryMethod_generate (kTypeDescriptor_GALGAS_documentGeneration.mSlotID,
                                categoryMethod_documentGeneration_generate) ;
}

//-----------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_documentGeneration_generate (defineCategoryMethod_documentGeneration_generate, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


