//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                           File 'easyBindings_syntax.cpp'                                            *
//                                             Generated by version 2.7.0                                              *
//                                          august 16th, 2014, at 17h59'31"                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "easyBindings_syntax.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "easyBindings_grammar.h"

//---------------------------------------------------------------------------------------------------------------------*

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_start_5F_symbol_i0_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                      GALGAS_astDeclarationStruct & ioArgument_ioDeclarationAST,
                                                                                      GALGAS_location & outArgument_outEndOfFile,
                                                                                      C_Lexique_easyBindings_5F_lexique * inCompiler) {
  outArgument_outEndOfFile.drop () ; // Release 'out' argument
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_0 (inCompiler)) {
    case 2: {
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_include) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 15)) ;
      GALGAS_lstring var_filePath = inCompiler->synthetizedAttribute_tokenString () ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_string) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 16)) ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 17)) ;
      GALGAS_lstring var_sourceFile = GALGAS_lstring::constructor_new (var_filePath.mAttribute_string.reader_absolutePathFromPath (GALGAS_string::constructor_stringWithSourceFilePath (inCompiler  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 19)).reader_stringByDeletingLastPathComponent (SOURCE_FILE ("easyBindings_syntax.gSyntax", 19)) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 19)), var_filePath.mAttribute_location  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 18)) ;
      GALGAS_location joker_773_0 ; // Joker input parameter
      cGrammar_easyBindings_5F_grammar::_performSourceFileParsing_ (inCompiler, var_sourceFile, constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST, joker_773_0  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 22)) ;
    } break ;
    case 3: {
      nt_class_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST, inCompiler) ;
    } break ;
    case 4: {
      nt_entity_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST, inCompiler) ;
    } break ;
    case 5: {
      nt_nib_5F_class_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST, inCompiler) ;
    } break ;
    case 6: {
      nt_preferences_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST, inCompiler) ;
    } break ;
    case 7: {
      nt_document_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST, inCompiler) ;
    } break ;
    case 8: {
      nt_outlet_5F_class_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST.mAttribute_mOutletClassDeclarationList, inCompiler) ;
    } break ;
    case 9: {
      nt_controller_5F_template_5F_declaration_ (constinArgument_inIsUserDefined, ioArgument_ioDeclarationAST.mAttribute_mControllerTemplateList, inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  outArgument_outEndOfFile = inCompiler->here () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_end) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 51)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_start_5F_symbol_i0_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_0 (inCompiler)) {
    case 2: {
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_include) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 15)) ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_string) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 16)) ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 17)) ;
    } break ;
    case 3: {
      nt_class_5F_declaration_parse (inCompiler) ;
    } break ;
    case 4: {
      nt_entity_5F_declaration_parse (inCompiler) ;
    } break ;
    case 5: {
      nt_nib_5F_class_5F_declaration_parse (inCompiler) ;
    } break ;
    case 6: {
      nt_preferences_5F_declaration_parse (inCompiler) ;
    } break ;
    case 7: {
      nt_document_5F_declaration_parse (inCompiler) ;
    } break ;
    case 8: {
      nt_outlet_5F_class_5F_declaration_parse (inCompiler) ;
    } break ;
    case 9: {
      nt_controller_5F_template_5F_declaration_parse (inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_end) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 51)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_controller_5F_template_5F_declaration_i1_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                                            GALGAS_controllerTemplateList & ioArgument_ioControllerTemplateList,
                                                                                                            C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_controllerTemplate) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 60)) ;
  GALGAS_lstring var_outletClassName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 61)) ;
  GALGAS_lstring var_bindingName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_binding) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 62)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3A_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 63)) ;
  GALGAS_lstring var_modelTypeName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 64)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 65)) ;
  ioArgument_ioControllerTemplateList.addAssign_operation (constinArgument_inIsUserDefined, var_outletClassName, var_bindingName, var_modelTypeName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 66)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_controller_5F_template_5F_declaration_i1_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_controllerTemplate) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 60)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 61)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_binding) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 62)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3A_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 63)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 64)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 65)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_outlet_5F_declaration_i2_ (GALGAS_outletDeclarationList & ioArgument_ioOutletDeclarationList,
                                                                                            C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_outlet) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 332)) ;
  GALGAS_lstring var_outletTypeName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 333)) ;
  GALGAS_lstring var_outletName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 334)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 335)) ;
  ioArgument_ioOutletDeclarationList.addAssign_operation (var_outletTypeName, var_outletName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 336)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_outlet_5F_declaration_i2_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_outlet) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 332)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 333)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 334)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 335)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_action_5F_declaration_i3_ (GALGAS_lstringlist & ioArgument_ioActionDeclarationList,
                                                                                            C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_action) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 344)) ;
  GALGAS_lstring var_actionName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 345)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 346)) ;
  ioArgument_ioActionDeclarationList.addAssign_operation (var_actionName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 347)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_action_5F_declaration_i3_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_action) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 344)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 345)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 346)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_preferences_5F_declaration_i4_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                                 GALGAS_astDeclarationStruct & ioArgument_ioDeclarationAST,
                                                                                                 C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_preferences) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 356)) ;
  GALGAS_lstring var_preferencesName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 357)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 358)) ;
  GALGAS_outletDeclarationList var_outletDeclarationList = GALGAS_outletDeclarationList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 359)) ;
  GALGAS_attributeList var_attributeList = GALGAS_attributeList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 360)) ;
  GALGAS_transientList var_transientList = GALGAS_transientList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 361)) ;
  GALGAS_lstringlist var_actionDeclarationList = GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 362)) ;
  GALGAS_bindingList var_bindingList = GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 363)) ;
  GALGAS_classArrayList var_classArrayList = GALGAS_classArrayList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 364)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_1 (inCompiler)) {
    case 2: {
      nt_action_5F_declaration_ (var_actionDeclarationList, inCompiler) ;
    } break ;
    case 3: {
      nt_attribute_5F_declaration_ (var_attributeList, inCompiler) ;
    } break ;
    case 4: {
      nt_outlet_5F_declaration_ (var_outletDeclarationList, inCompiler) ;
    } break ;
    case 5: {
      nt_binding_5F_declaration_ (var_bindingList, inCompiler) ;
    } break ;
    case 6: {
      nt_array_5F_declaration_ (var_classArrayList, inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 379)) ;
  ioArgument_ioDeclarationAST.mAttribute_mDeclarationList.addAssign_operation (GALGAS_unifiedTypeDeclaration::constructor_new (constinArgument_inIsUserDefined, var_preferencesName, GALGAS_typeKind::constructor_preferencesType (SOURCE_FILE ("easyBindings_syntax.gSyntax", 383)), GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 384)), var_outletDeclarationList, GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 386)), var_attributeList, GALGAS_relationshipList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 388)), var_classArrayList, var_transientList, var_bindingList, var_actionDeclarationList  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 380))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 380)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_preferences_5F_declaration_i4_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_preferences) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 356)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 357)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 358)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_1 (inCompiler)) {
    case 2: {
      nt_action_5F_declaration_parse (inCompiler) ;
    } break ;
    case 3: {
      nt_attribute_5F_declaration_parse (inCompiler) ;
    } break ;
    case 4: {
      nt_outlet_5F_declaration_parse (inCompiler) ;
    } break ;
    case 5: {
      nt_binding_5F_declaration_parse (inCompiler) ;
    } break ;
    case 6: {
      nt_array_5F_declaration_parse (inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 379)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_nib_5F_class_5F_declaration_i5_ (const GALGAS_bool /* constinArgument_inIsUserDefined */,
                                                                                                  GALGAS_astDeclarationStruct & /* ioArgument_ioDeclarationAST */,
                                                                                                  C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_nibClass) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 402)) ;
  GALGAS_lstring var_preferencesName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 403)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 404)) ;
  GALGAS_outletDeclarationList var_outletDeclarationList = GALGAS_outletDeclarationList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 405)) ;
  GALGAS_attributeList var_attributeList = GALGAS_attributeList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 406)) ;
  GALGAS_transientList var_transientList = GALGAS_transientList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 407)) ;
  GALGAS_lstringlist var_actionDeclarationList = GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 408)) ;
  GALGAS_bindingList var_bindingList = GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 409)) ;
  GALGAS_classArrayList var_classArrayList = GALGAS_classArrayList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 410)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_2 (inCompiler)) {
    case 2: {
      nt_action_5F_declaration_ (var_actionDeclarationList, inCompiler) ;
    } break ;
    case 3: {
      nt_attribute_5F_declaration_ (var_attributeList, inCompiler) ;
    } break ;
    case 4: {
      nt_outlet_5F_declaration_ (var_outletDeclarationList, inCompiler) ;
    } break ;
    case 5: {
      nt_binding_5F_declaration_ (var_bindingList, inCompiler) ;
    } break ;
    case 6: {
      nt_array_5F_declaration_ (var_classArrayList, inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 425)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_nib_5F_class_5F_declaration_i5_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_nibClass) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 402)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 403)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 404)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_2 (inCompiler)) {
    case 2: {
      nt_action_5F_declaration_parse (inCompiler) ;
    } break ;
    case 3: {
      nt_attribute_5F_declaration_parse (inCompiler) ;
    } break ;
    case 4: {
      nt_outlet_5F_declaration_parse (inCompiler) ;
    } break ;
    case 5: {
      nt_binding_5F_declaration_parse (inCompiler) ;
    } break ;
    case 6: {
      nt_array_5F_declaration_parse (inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 425)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_array_5F_declaration_i6_ (GALGAS_classArrayList & ioArgument_ioClassArrayList,
                                                                                           C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_array) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 433)) ;
  GALGAS_lstring var_className = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 434)) ;
  GALGAS_lstring var_arrayName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 435)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 436)) ;
  ioArgument_ioClassArrayList.addAssign_operation (var_className, var_arrayName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 437)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_array_5F_declaration_i6_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_array) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 433)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 434)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 435)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 436)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_document_5F_declaration_i7_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                              GALGAS_astDeclarationStruct & ioArgument_ioDeclarationAST,
                                                                                              C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_document) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 446)) ;
  GALGAS_lstring var_documentName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 447)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_root) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 448)) ;
  GALGAS_lstring var_rootEntityName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 449)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 450)) ;
  GALGAS_outletDeclarationList var_outletDeclarationList = GALGAS_outletDeclarationList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 451)) ;
  GALGAS_bindingList var_bindingList = GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 452)) ;
  GALGAS_lstringlist var_actionDeclarationList = GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 453)) ;
  GALGAS_transientList var_transientList = GALGAS_transientList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 454)) ;
  GALGAS_attributeList var_attributeList = GALGAS_attributeList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 455)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_3 (inCompiler)) {
    case 2: {
      nt_attribute_5F_declaration_ (var_attributeList, inCompiler) ;
    } break ;
    case 3: {
      nt_action_5F_declaration_ (var_actionDeclarationList, inCompiler) ;
    } break ;
    case 4: {
      nt_outlet_5F_declaration_ (var_outletDeclarationList, inCompiler) ;
    } break ;
    case 5: {
      nt_binding_5F_declaration_ (var_bindingList, inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 468)) ;
  ioArgument_ioDeclarationAST.mAttribute_mDeclarationList.addAssign_operation (GALGAS_unifiedTypeDeclaration::constructor_new (constinArgument_inIsUserDefined, var_documentName, GALGAS_typeKind::constructor_documentType (SOURCE_FILE ("easyBindings_syntax.gSyntax", 472)), GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 473)), GALGAS_outletDeclarationList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 474)), var_rootEntityName, var_attributeList, GALGAS_relationshipList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 477)), GALGAS_classArrayList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 478)), var_transientList, var_bindingList, var_actionDeclarationList  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 469))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 469)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_document_5F_declaration_i7_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_document) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 446)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 447)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_root) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 448)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 449)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 450)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_3 (inCompiler)) {
    case 2: {
      nt_attribute_5F_declaration_parse (inCompiler) ;
    } break ;
    case 3: {
      nt_action_5F_declaration_parse (inCompiler) ;
    } break ;
    case 4: {
      nt_outlet_5F_declaration_parse (inCompiler) ;
    } break ;
    case 5: {
      nt_binding_5F_declaration_parse (inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 468)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_explicit_5F_value_i8_ (GALGAS_abstractDefaultValue & outArgument_outDefaultValue,
                                                                                        C_Lexique_easyBindings_5F_lexique * inCompiler) {
  outArgument_outDefaultValue.drop () ; // Release 'out' argument
  switch (select_easyBindings_5F_syntax_4 (inCompiler)) {
  case 1: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_YES) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 491)) ;
    outArgument_outDefaultValue = GALGAS_boolAsDefaultValue::constructor_new (GALGAS_lbool::constructor_new (GALGAS_bool (true), inCompiler->here ()  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 492))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 492)) ;
  } break ;
  case 2: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_NO) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 494)) ;
    outArgument_outDefaultValue = GALGAS_boolAsDefaultValue::constructor_new (GALGAS_lbool::constructor_new (GALGAS_bool (false), inCompiler->here ()  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 495))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 495)) ;
  } break ;
  case 3: {
    GALGAS_luint var_integerValue = inCompiler->synthetizedAttribute_uint_33__32_value () ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_integer) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 497)) ;
    outArgument_outDefaultValue = GALGAS_integerAsDefaultValue::constructor_new (var_integerValue  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 498)) ;
  } break ;
  case 4: {
    GALGAS_ldouble var_doubleValue = inCompiler->synthetizedAttribute_floatValue () ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_double) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 500)) ;
    outArgument_outDefaultValue = GALGAS_doubleAsDefaultValue::constructor_new (var_doubleValue  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 501)) ;
  } break ;
  case 5: {
    GALGAS_lstring var_stringValue = inCompiler->synthetizedAttribute_tokenString () ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_string) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 503)) ;
    outArgument_outDefaultValue = GALGAS_stringAsDefaultValue::constructor_new (var_stringValue  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 504)) ;
  } break ;
  case 6: {
    GALGAS_lstring var_stringValue = inCompiler->synthetizedAttribute_tokenString () ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 506)) ;
    outArgument_outDefaultValue = GALGAS_identifierAsDefaultValue::constructor_new (var_stringValue  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 507)) ;
  } break ;
  case 7: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__28_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 509)) ;
    GALGAS_location var_startLocation = inCompiler->here () ;
    GALGAS_defaultValueList var_defaultValueList = GALGAS_defaultValueList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 511)) ;
    bool repeatFlag_0 = true ;
    while (repeatFlag_0) {
      GALGAS_abstractDefaultValue var_defaultValue ;
      nt_explicit_5F_value_ (var_defaultValue, inCompiler) ;
      var_defaultValueList.addAssign_operation (var_defaultValue  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 514)) ;
      switch (select_easyBindings_5F_syntax_5 (inCompiler)) {
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__2C_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 516)) ;
      } break ;
      default:
        repeatFlag_0 = false ;
        break ;
      }
    }
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__29_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 518)) ;
    outArgument_outDefaultValue = GALGAS_listAsDefaultValue::constructor_new (var_startLocation, var_defaultValueList  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 519)) ;
  } break ;
  default:
    break ;
  }
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_explicit_5F_value_i8_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  switch (select_easyBindings_5F_syntax_4 (inCompiler)) {
  case 1: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_YES) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 491)) ;
  } break ;
  case 2: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_NO) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 494)) ;
  } break ;
  case 3: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_integer) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 497)) ;
  } break ;
  case 4: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_double) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 500)) ;
  } break ;
  case 5: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_literal_5F_string) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 503)) ;
  } break ;
  case 6: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 506)) ;
  } break ;
  case 7: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__28_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 509)) ;
    bool repeatFlag_0 = true ;
    while (repeatFlag_0) {
      nt_explicit_5F_value_parse (inCompiler) ;
      switch (select_easyBindings_5F_syntax_5 (inCompiler)) {
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__2C_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 516)) ;
      } break ;
      default:
        repeatFlag_0 = false ;
        break ;
      }
    }
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__29_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 518)) ;
  } break ;
  default:
    break ;
  }
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_class_5F_declaration_i9_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                           GALGAS_astDeclarationStruct & ioArgument_ioDeclarationAST,
                                                                                           C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_class) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 529)) ;
  GALGAS_lstring var_className = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 530)) ;
  GALGAS_lstring var_superClassName ;
  switch (select_easyBindings_5F_syntax_6 (inCompiler)) {
  case 1: {
    var_superClassName = GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 533)) ;
  } break ;
  case 2: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3A_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 535)) ;
    var_superClassName = inCompiler->synthetizedAttribute_tokenString () ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 536)) ;
  } break ;
  default:
    break ;
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 538)) ;
  GALGAS_attributeList var_attributeList = GALGAS_attributeList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 539)) ;
  GALGAS_transientList var_classTransientList = GALGAS_transientList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 540)) ;
  GALGAS_classArrayList var_classArrayList = GALGAS_classArrayList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 541)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_7 (inCompiler)) {
    case 2: {
      nt_attribute_5F_declaration_ (var_attributeList, inCompiler) ;
    } break ;
    case 3: {
      nt_array_5F_declaration_ (var_classArrayList, inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 550)) ;
  ioArgument_ioDeclarationAST.mAttribute_mDeclarationList.addAssign_operation (GALGAS_unifiedTypeDeclaration::constructor_new (constinArgument_inIsUserDefined, var_className, GALGAS_typeKind::constructor_classType (SOURCE_FILE ("easyBindings_syntax.gSyntax", 554)), var_superClassName, GALGAS_outletDeclarationList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 556)), GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 557)), var_attributeList, GALGAS_relationshipList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 559)), var_classArrayList, var_classTransientList, GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 562)), GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 563))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 551))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 551)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_class_5F_declaration_i9_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_class) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 529)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 530)) ;
  switch (select_easyBindings_5F_syntax_6 (inCompiler)) {
  case 1: {
  } break ;
  case 2: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3A_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 535)) ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 536)) ;
  } break ;
  default:
    break ;
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 538)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_7 (inCompiler)) {
    case 2: {
      nt_attribute_5F_declaration_parse (inCompiler) ;
    } break ;
    case 3: {
      nt_array_5F_declaration_parse (inCompiler) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 550)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_attribute_5F_declaration_i10_ (GALGAS_attributeList & ioArgument_ioAttributeList,
                                                                                                C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_attribute) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 572)) ;
  GALGAS_lstring var_attributeTypeName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 573)) ;
  GALGAS_lstring var_attributeName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 574)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_default) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 575)) ;
  GALGAS_abstractDefaultValue var_defaultValue ;
  nt_explicit_5F_value_ (var_defaultValue, inCompiler) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 577)) ;
  ioArgument_ioAttributeList.addAssign_operation (var_attributeTypeName, var_attributeName, var_defaultValue  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 578)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_attribute_5F_declaration_i10_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_attribute) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 572)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 573)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 574)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_default) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 575)) ;
  nt_explicit_5F_value_parse (inCompiler) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 577)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_binding_5F_declaration_i11_ (GALGAS_bindingList & ioArgument_ioBindingList,
                                                                                              C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_bind) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 639)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_self) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 640)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__2E_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 641)) ;
  GALGAS_lstring var_observableProperty = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 642)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_to) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 643)) ;
  GALGAS_lstring var_outletName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 644)) ;
  GALGAS_lstring var_bindingName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_binding) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 645)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 646)) ;
  ioArgument_ioBindingList.addAssign_operation (var_observableProperty, var_outletName, var_bindingName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 647)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_binding_5F_declaration_i11_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_bind) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 639)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_self) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 640)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__2E_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 641)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 642)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_to) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 643)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 644)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_binding) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 645)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 646)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_entity_5F_declaration_i12_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                             GALGAS_astDeclarationStruct & ioArgument_ioDeclarationAST,
                                                                                             C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_entity) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 818)) ;
  GALGAS_lstring var_entityName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 819)) ;
  GALGAS_lstring var_superEntityName ;
  switch (select_easyBindings_5F_syntax_8 (inCompiler)) {
  case 1: {
    var_superEntityName = GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 822)) ;
  } break ;
  case 2: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3A_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 824)) ;
    var_superEntityName = inCompiler->synthetizedAttribute_tokenString () ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 825)) ;
  } break ;
  default:
    break ;
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 827)) ;
  GALGAS_attributeList var_attributeList = GALGAS_attributeList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 828)) ;
  GALGAS_transientList var_classTransientList = GALGAS_transientList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 829)) ;
  GALGAS_relationshipList var_relationshipList = GALGAS_relationshipList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 830)) ;
  GALGAS_lstringlist var_signList = GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 831)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_9 (inCompiler)) {
    case 2: {
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_signature) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 834)) ;
      bool repeatFlag_1 = true ;
      while (repeatFlag_1) {
        GALGAS_lstring var_propertyName = inCompiler->synthetizedAttribute_tokenString () ;
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 836)) ;
        var_signList.addAssign_operation (var_propertyName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 837)) ;
        switch (select_easyBindings_5F_syntax_10 (inCompiler)) {
        case 2: {
          inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__2C_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 839)) ;
        } break ;
        default:
          repeatFlag_1 = false ;
          break ;
        }
      }
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 841)) ;
    } break ;
    case 3: {
      nt_attribute_5F_declaration_ (var_attributeList, inCompiler) ;
    } break ;
    case 4: {
      GALGAS_bool var_isToMany ;
      switch (select_easyBindings_5F_syntax_11 (inCompiler)) {
      case 1: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toOne) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 849)) ;
        var_isToMany = GALGAS_bool (false) ;
      } break ;
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toMany) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 852)) ;
        var_isToMany = GALGAS_bool (true) ;
      } break ;
      default:
        break ;
      }
      GALGAS_lstring var_destinationEntityName = inCompiler->synthetizedAttribute_tokenString () ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 855)) ;
      GALGAS_lstring var_relationshipName = inCompiler->synthetizedAttribute_tokenString () ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 856)) ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_inverse) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 857)) ;
      GALGAS_bool var_inverseIsToMany ;
      switch (select_easyBindings_5F_syntax_12 (inCompiler)) {
      case 1: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toOne) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 860)) ;
        var_inverseIsToMany = GALGAS_bool (false) ;
      } break ;
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toMany) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 863)) ;
        var_inverseIsToMany = GALGAS_bool (true) ;
      } break ;
      default:
        break ;
      }
      GALGAS_lstring var_inverseRelationshipName = inCompiler->synthetizedAttribute_tokenString () ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 866)) ;
      GALGAS_deleteRuleEnum var_deleteRule ;
      switch (select_easyBindings_5F_syntax_13 (inCompiler)) {
      case 1: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_nullify) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 869)) ;
        var_deleteRule = GALGAS_deleteRuleEnum::constructor_nullifyDeleteRule (SOURCE_FILE ("easyBindings_syntax.gSyntax", 870)) ;
      } break ;
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_cascade) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 872)) ;
        var_deleteRule = GALGAS_deleteRuleEnum::constructor_cascadeDeleteRule (SOURCE_FILE ("easyBindings_syntax.gSyntax", 873)) ;
      } break ;
      case 3: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_deny) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 875)) ;
        var_deleteRule = GALGAS_deleteRuleEnum::constructor_denyDeleteRule (SOURCE_FILE ("easyBindings_syntax.gSyntax", 876)) ;
      } break ;
      default:
        break ;
      }
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 878)) ;
      var_relationshipList.addAssign_operation (var_isToMany, var_destinationEntityName, var_relationshipName, var_inverseRelationshipName, var_inverseIsToMany, var_deleteRule  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 879)) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 888)) ;
  ioArgument_ioDeclarationAST.mAttribute_mDeclarationList.addAssign_operation (GALGAS_unifiedTypeDeclaration::constructor_new (constinArgument_inIsUserDefined, var_entityName, GALGAS_typeKind::constructor_entityType (SOURCE_FILE ("easyBindings_syntax.gSyntax", 892)), var_superEntityName, GALGAS_outletDeclarationList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 894)), GALGAS_string::makeEmptyString ().reader_nowhere (SOURCE_FILE ("easyBindings_syntax.gSyntax", 895)), var_attributeList, var_relationshipList, GALGAS_classArrayList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 898)), var_classTransientList, GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 900)), GALGAS_lstringlist::constructor_emptyList (SOURCE_FILE ("easyBindings_syntax.gSyntax", 901))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 889))  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 889)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_entity_5F_declaration_i12_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_entity) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 818)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 819)) ;
  switch (select_easyBindings_5F_syntax_8 (inCompiler)) {
  case 1: {
  } break ;
  case 2: {
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3A_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 824)) ;
    inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 825)) ;
  } break ;
  default:
    break ;
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 827)) ;
  bool repeatFlag_0 = true ;
  while (repeatFlag_0) {
    switch (select_easyBindings_5F_syntax_9 (inCompiler)) {
    case 2: {
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_signature) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 834)) ;
      bool repeatFlag_1 = true ;
      while (repeatFlag_1) {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 836)) ;
        switch (select_easyBindings_5F_syntax_10 (inCompiler)) {
        case 2: {
          inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__2C_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 839)) ;
        } break ;
        default:
          repeatFlag_1 = false ;
          break ;
        }
      }
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 841)) ;
    } break ;
    case 3: {
      nt_attribute_5F_declaration_parse (inCompiler) ;
    } break ;
    case 4: {
      switch (select_easyBindings_5F_syntax_11 (inCompiler)) {
      case 1: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toOne) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 849)) ;
      } break ;
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toMany) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 852)) ;
      } break ;
      default:
        break ;
      }
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 855)) ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 856)) ;
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_inverse) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 857)) ;
      switch (select_easyBindings_5F_syntax_12 (inCompiler)) {
      case 1: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toOne) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 860)) ;
      } break ;
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_toMany) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 863)) ;
      } break ;
      default:
        break ;
      }
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 866)) ;
      switch (select_easyBindings_5F_syntax_13 (inCompiler)) {
      case 1: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_nullify) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 869)) ;
      } break ;
      case 2: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_cascade) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 872)) ;
      } break ;
      case 3: {
        inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_deny) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 875)) ;
      } break ;
      default:
        break ;
      }
      inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 878)) ;
    } break ;
    default:
      repeatFlag_0 = false ;
      break ;
    }
  }
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__7D_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 888)) ;
  inCompiler->resetTemplateString () ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_outlet_5F_class_5F_declaration_i13_ (const GALGAS_bool constinArgument_inIsUserDefined,
                                                                                                      GALGAS_outletClassDeclarationList & ioArgument_ioOutletClassDeclarationList,
                                                                                                      C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_outletClass) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 988)) ;
  GALGAS_lstring var_outletClassName = inCompiler->synthetizedAttribute_tokenString () ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 989)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 990)) ;
  ioArgument_ioOutletClassDeclarationList.addAssign_operation (constinArgument_inIsUserDefined, var_outletClassName  COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 991)) ;
}

//---------------------------------------------------------------------------------------------------------------------*

void cParser_easyBindings_5F_syntax::rule_easyBindings_5F_syntax_outlet_5F_class_5F_declaration_i13_parse (C_Lexique_easyBindings_5F_lexique * inCompiler) {
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_outletClass) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 988)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken_Identifier) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 989)) ;
  inCompiler->acceptTerminal (ACCEPT_TERMINAL (C_Lexique_easyBindings_5F_lexique::kToken__3B_) COMMA_SOURCE_FILE ("easyBindings_syntax.gSyntax", 990)) ;
  inCompiler->resetTemplateString () ;
}

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


