//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'entityAnalysis.cpp'                          *
//                        Generated by version 2.4.5                         *
//                       july 2nd, 2013, at 19h1'23"                         *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "entityAnalysis.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "entityAnalysis.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//                          Routine 'analyzeEntity'                          *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_analyzeEntity (const GALGAS_entityList_2E_element constinArgument0,
                            const GALGAS_globalEnumConstantMap constinArgument1,
                            GALGAS_entityMap & ioArgument2,
                            const GALGAS_preferencesMap constinArgument3,
                            GALGAS_transientDependencyGraph & ioArgument4,
                            C_Compiler * inCompiler
                            COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                          Routine 'analyzeEntity'                          *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_analyzeEntity (const GALGAS_entityList_2E_element constinArgument_inEntity,
                            const GALGAS_globalEnumConstantMap constinArgument_inGlobalEnumConstantMap,
                            GALGAS_entityMap & ioArgument_ioEntityMap,
                            const GALGAS_preferencesMap constinArgument_inPreferencesMap,
                            GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                            C_Compiler * inCompiler
                            COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @localVariableDeclarationForGeneration
  GALGAS_observablePropertyMap var_observablePropertyMap ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_attributeListForImplementation var_propertyListForInitMethodHeader = GALGAS_attributeListForImplementation::constructor_emptyList (SOURCE_FILE_AT_LINE (17)) ;
  //-------- @localVariableDeclarationForGeneration
  GALGAS_relationshipList var_allRelationshipList ;
  //-------- @localVariableDeclarationForGeneration
  GALGAS_propertyMap var_allPropertyMap ;
  //-------- @localVariableDeclarationForGeneration
  GALGAS_relationshipMap var_allRelationshipMap ;
  //-------- @ifInstructionForGeneration
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, constinArgument_inEntity.mAttribute_mSuperEntityName.reader_string (SOURCE_FILE_AT_LINE (21)).objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
  if (kBoolTrue == test_0) {
    //-------- @methodCallInstructionForGeneration
    GALGAS_string joker_979_0 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_1056_4 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_1056_3 ; // Joker input parameter
    GALGAS_transientListForImplementation joker_1056_2 ; // Joker input parameter
    GALGAS_relationshipList joker_1056_1 ; // Joker input parameter
    GALGAS_relationshipMap joker_1115_2 ; // Joker input parameter
    GALGAS_stringset joker_1115_1 ; // Joker input parameter
    GALGAS_stringset joker_1151_2 ; // Joker input parameter
    GALGAS_signListForGeneration joker_1151_1 ; // Joker input parameter
    ioArgument_ioEntityMap.method_searchKey (constinArgument_inEntity.mAttribute_mSuperEntityName, joker_979_0, var_observablePropertyMap, var_propertyListForInitMethodHeader, joker_1056_4, joker_1056_3, joker_1056_2, joker_1056_1, var_allRelationshipList, var_allPropertyMap, joker_1115_2, joker_1115_1, var_allRelationshipMap, joker_1151_2, joker_1151_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (22)) ;
    //-------- END @methodCallInstructionForGeneration
  }else if (kBoolFalse == test_0) {
    //-------- @assignmentInstructionForGeneration
    var_observablePropertyMap = GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (35)) ;
    //-------- @assignmentInstructionForGeneration
    var_propertyListForInitMethodHeader = GALGAS_attributeListForImplementation::constructor_emptyList (SOURCE_FILE_AT_LINE (36)) ;
    //-------- @assignmentInstructionForGeneration
    var_allRelationshipList = GALGAS_relationshipList::constructor_emptyList (SOURCE_FILE_AT_LINE (37)) ;
    //-------- @assignmentInstructionForGeneration
    var_allPropertyMap = GALGAS_propertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (38)) ;
    //-------- @assignmentInstructionForGeneration
    var_allRelationshipMap = GALGAS_relationshipMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (39)) ;
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_attributeListForImplementation var_attributeListForImplementation = GALGAS_attributeListForImplementation::constructor_emptyList (SOURCE_FILE_AT_LINE (41)) ;
  //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
  GALGAS_attributeListForImplementation var_inheritedAttributeListForImplementation = var_propertyListForInitMethodHeader ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringset var_headerFileInclusionSet = GALGAS_stringset::constructor_emptySet (SOURCE_FILE_AT_LINE (44)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_attributeList enumerator_1834 (constinArgument_inEntity.mAttribute_mAttributeList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_1834.hasCurrentObject ()) {
    //-------- @localVariableDeclarationForGeneration
    GALGAS_string var_directDefaultValueAsString ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_string var_objectiveCDefaultValueAsString ;
    //-------- @methodCallInstructionForGeneration
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_1834.current_mDefaultValue (HERE).ptr (), GALGAS_easyBindingTypeList::constructor_listWithValue (enumerator_1834.current_mType (HERE) COMMA_SOURCE_FILE_AT_LINE (47)), constinArgument_inGlobalEnumConstantMap, var_directDefaultValueAsString, var_objectiveCDefaultValueAsString, inCompiler COMMA_SOURCE_FILE_AT_LINE (46)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @methodCallInstructionForGeneration
    callCategoryMethod_addFileInclusion ((const cPtr_easyBindingType *) enumerator_1834.current_mType (HERE).ptr (), var_headerFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (52)) ;
    //-------- END @methodCallInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    var_allPropertyMap.modifier_insertKey (enumerator_1834.current_mAttributeName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (53)) ;
    } //-------- END @typeMethodInstructionForGeneration
    //-------- @plusEqualnstructionForGeneration
    var_attributeListForImplementation.addAssign_operation (enumerator_1834.current_mType (HERE), enumerator_1834.current_mAttributeName (HERE).reader_string (SOURCE_FILE_AT_LINE (54)), var_objectiveCDefaultValueAsString, var_directDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (54)) ;
    //-------- @plusEqualnstructionForGeneration
    var_propertyListForInitMethodHeader.addAssign_operation (enumerator_1834.current_mType (HERE), enumerator_1834.current_mAttributeName (HERE).reader_string (SOURCE_FILE_AT_LINE (55)), var_objectiveCDefaultValueAsString, var_directDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (55)) ;
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (GALGAS_string ("entity.").operator_concat (constinArgument_inEntity.mAttribute_mEntityName.reader_string (SOURCE_FILE_AT_LINE (57)) COMMA_SOURCE_FILE_AT_LINE (57)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (57)).operator_concat (enumerator_1834.current_mAttributeName (HERE).reader_string (SOURCE_FILE_AT_LINE (57)) COMMA_SOURCE_FILE_AT_LINE (57)), enumerator_1834.current_mAttributeName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (56)) ;
    { //-------- @modifierCallInstructionForGeneration
    var_observablePropertyMap.modifier_insertKey (enumerator_1834.current_mAttributeName (HERE), enumerator_1834.current_mType (HERE), GALGAS_bool (false), var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (60)) ;
    } //-------- END @typeMethodInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (66)) ;
    } //-------- END @typeMethodInstructionForGeneration
    enumerator_1834.gotoNextObject () ;
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_relationshipMap var_currentRelationshipMap = GALGAS_relationshipMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (72)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_relationshipList enumerator_3059 (constinArgument_inEntity.mAttribute_mRelationshipList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_3059.hasCurrentObject ()) {
    { //-------- @modifierCallInstructionForGeneration
    var_allRelationshipMap.modifier_insertKey (enumerator_3059.current_mRelationshipName (HERE), enumerator_3059.current_mIsToMany (HERE), enumerator_3059.current_mDestinationEntityName (HERE), enumerator_3059.current_mInverseRelationshipName (HERE), enumerator_3059.current_mInverseRelationIsToMany (HERE), enumerator_3059.current_mDeleteRule (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (74)) ;
    } //-------- END @typeMethodInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    var_currentRelationshipMap.modifier_insertKey (enumerator_3059.current_mRelationshipName (HERE), enumerator_3059.current_mIsToMany (HERE), enumerator_3059.current_mDestinationEntityName (HERE), enumerator_3059.current_mInverseRelationshipName (HERE), enumerator_3059.current_mInverseRelationIsToMany (HERE), enumerator_3059.current_mDeleteRule (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (82)) ;
    } //-------- END @typeMethodInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    var_allPropertyMap.modifier_insertKey (enumerator_3059.current_mRelationshipName (HERE), inCompiler COMMA_SOURCE_FILE_AT_LINE (90)) ;
    } //-------- END @typeMethodInstructionForGeneration
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (GALGAS_string ("entity.").operator_concat (constinArgument_inEntity.mAttribute_mEntityName.reader_string (SOURCE_FILE_AT_LINE (92)) COMMA_SOURCE_FILE_AT_LINE (92)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (92)).operator_concat (enumerator_3059.current_mRelationshipName (HERE).reader_string (SOURCE_FILE_AT_LINE (92)) COMMA_SOURCE_FILE_AT_LINE (92)), enumerator_3059.current_mRelationshipName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (91)) ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_easyBindingType var_type ;
    //-------- @ifInstructionForGeneration
    const enumGalgasBool test_1 = enumerator_3059.current_mIsToMany (HERE).boolEnum () ;
    if (kBoolTrue == test_1) {
      //-------- @assignmentInstructionForGeneration
      var_type = GALGAS_toManyEntitiesType::constructor_new (enumerator_3059.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (97)) ;
    }else if (kBoolFalse == test_1) {
      //-------- @assignmentInstructionForGeneration
      var_type = GALGAS_toOneEntityType::constructor_new (enumerator_3059.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (99)) ;
    }
    { //-------- @modifierCallInstructionForGeneration
    var_observablePropertyMap.modifier_insertKey (enumerator_3059.current_mRelationshipName (HERE), var_type, GALGAS_bool (false), var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (101)) ;
    } //-------- END @typeMethodInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (107)) ;
    } //-------- END @typeMethodInstructionForGeneration
    enumerator_3059.gotoNextObject () ;
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_signListForGeneration var_signList = GALGAS_signListForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (113)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_lstringlist enumerator_4331 (constinArgument_inEntity.mAttribute_mSignList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_4331.hasCurrentObject ()) {
    //-------- @localVariableDeclarationForGeneration
    GALGAS_easyBindingType var_type ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_string var_dependancyKey ;
    //-------- @methodCallInstructionForGeneration
    GALGAS_bool joker_4420_0 ; // Joker input parameter
    var_observablePropertyMap.method_searchKey (enumerator_4331.current_mValue (HERE), var_type, joker_4420_0, var_dependancyKey, inCompiler COMMA_SOURCE_FILE_AT_LINE (115)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @plusEqualnstructionForGeneration
    var_signList.addAssign_operation (enumerator_4331.current_mValue (HERE).mAttribute_string, var_type COMMA_SOURCE_FILE_AT_LINE (121)) ;
    enumerator_4331.gotoNextObject () ;
  }
  //-------- @ifInstructionForGeneration
  const enumGalgasBool test_2 = GALGAS_bool (kIsStrictSup, constinArgument_inEntity.mAttribute_mSignList.reader_length (SOURCE_FILE_AT_LINE (123)).objectCompare (GALGAS_uint ((PMUInt32) 0U))).boolEnum () ;
  if (kBoolTrue == test_2) {
    //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
    GALGAS_string var_key = GALGAS_string ("entity.").operator_concat (constinArgument_inEntity.mAttribute_mEntityName.reader_string (SOURCE_FILE_AT_LINE (124)) COMMA_SOURCE_FILE_AT_LINE (124)).operator_concat (GALGAS_string (".sign") COMMA_SOURCE_FILE_AT_LINE (124)) ;
    { //-------- @modifierCallInstructionForGeneration
    ioArgument_ioTransientDependencyGraph.modifier_addNode (GALGAS_lstring::constructor_new (var_key, constinArgument_inEntity.mAttribute_mEntityName.mAttribute_location COMMA_SOURCE_FILE_AT_LINE (126)), var_key, inCompiler COMMA_SOURCE_FILE_AT_LINE (125)) ;
    } //-------- END @typeMethodInstructionForGeneration
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringset var_implementationFileInclusionSet = GALGAS_stringset::constructor_emptySet (SOURCE_FILE_AT_LINE (131)) ;
  //-------- @localVariableDeclarationForGeneration
  GALGAS_transientListForImplementation var_transientListForImplementation ;
  { //-------- @routineCallInstructionForGeneration
  routine_analyzeTransientProperties (constinArgument_inPreferencesMap, GALGAS_string ("entity.").operator_concat (constinArgument_inEntity.mAttribute_mEntityName.reader_string (SOURCE_FILE_AT_LINE (135)) COMMA_SOURCE_FILE_AT_LINE (135)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (135)), constinArgument_inEntity.mAttribute_mTransientList, GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (137)), GALGAS_string::makeEmptyString (), GALGAS_controllerMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (139)), var_observablePropertyMap, var_implementationFileInclusionSet, var_transientListForImplementation, ioArgument_ioTransientDependencyGraph, inCompiler COMMA_SOURCE_FILE_AT_LINE (133)) ;
  } //-------- @routineCallInstructionForGeneration
  { //-------- @modifierCallInstructionForGeneration
  var_implementationFileInclusionSet.modifier_removeKey (GALGAS_string::makeEmptyString () COMMA_SOURCE_FILE_AT_LINE (146)) ;
  } //-------- END @typeMethodInstructionForGeneration
  { //-------- @modifierCallInstructionForGeneration
  ioArgument_ioEntityMap.modifier_insertKey (constinArgument_inEntity.mAttribute_mEntityName, constinArgument_inEntity.mAttribute_mSuperEntityName.mAttribute_string, var_observablePropertyMap, var_propertyListForInitMethodHeader, var_inheritedAttributeListForImplementation, var_attributeListForImplementation, var_transientListForImplementation, constinArgument_inEntity.mAttribute_mRelationshipList, var_allRelationshipList.operator_concat (constinArgument_inEntity.mAttribute_mRelationshipList COMMA_SOURCE_FILE_AT_LINE (156)), var_allPropertyMap, var_currentRelationshipMap, var_headerFileInclusionSet, var_allRelationshipMap, var_implementationFileInclusionSet, var_signList, inCompiler COMMA_SOURCE_FILE_AT_LINE (147)) ;
  } //-------- END @typeMethodInstructionForGeneration
}


//---------------------------------------------------------------------------*
//                                                                           *
//                         Routine 'analyzeEntities'                         *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_analyzeEntities (const GALGAS_entityList constinArgument_inEntityList,
                              const GALGAS_globalEnumConstantMap constinArgument_inGlobalEnumConstantMap,
                              GALGAS_entityMap & outArgument_outEntityMap,
                              GALGAS_entityListForGeneration & outArgument_outEntityListForGeneration,
                              const GALGAS_preferencesMap constinArgument_inPreferencesMap,
                              GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                              C_Compiler * inCompiler
                              COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outEntityMap.drop () ; // Release 'out' argument
  outArgument_outEntityListForGeneration.drop () ; // Release 'out' argument
  //-------- @assignmentInstructionForGeneration
  outArgument_outEntityMap = GALGAS_entityMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (177)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_entityList enumerator_6490 (constinArgument_inEntityList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_6490.hasCurrentObject ()) {
    { //-------- @routineCallInstructionForGeneration
    routine_analyzeEntity (enumerator_6490.current (HERE), constinArgument_inGlobalEnumConstantMap, outArgument_outEntityMap, constinArgument_inPreferencesMap, ioArgument_ioTransientDependencyGraph, inCompiler COMMA_SOURCE_FILE_AT_LINE (179)) ;
    } //-------- @routineCallInstructionForGeneration
    enumerator_6490.gotoNextObject () ;
  }
  //-------- @foreachInstructionForGeneration
  cEnumerator_entityMap enumerator_6730 (outArgument_outEntityMap, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_6730.hasCurrentObject ()) {
    //-------- @foreachInstructionForGeneration
    cEnumerator_relationshipMap enumerator_6769 (enumerator_6730.current_mCurrentRelationshipMap (HERE), kEnumeration_up) ;
    //--- simple foreach instruction
    while (enumerator_6769.hasCurrentObject ()) {
      //-------- @localVariableDeclarationForGeneration
      GALGAS_relationshipMap var_destinationEntityRelationshipMap ;
      //-------- @methodCallInstructionForGeneration
      GALGAS_string joker_6827_11 ; // Joker input parameter
      GALGAS_observablePropertyMap joker_6827_10 ; // Joker input parameter
      GALGAS_attributeListForImplementation joker_6827_9 ; // Joker input parameter
      GALGAS_attributeListForImplementation joker_6827_8 ; // Joker input parameter
      GALGAS_attributeListForImplementation joker_6827_7 ; // Joker input parameter
      GALGAS_transientListForImplementation joker_6827_6 ; // Joker input parameter
      GALGAS_relationshipList joker_6827_5 ; // Joker input parameter
      GALGAS_relationshipList joker_6827_4 ; // Joker input parameter
      GALGAS_propertyMap joker_6827_3 ; // Joker input parameter
      GALGAS_relationshipMap joker_6827_2 ; // Joker input parameter
      GALGAS_stringset joker_6827_1 ; // Joker input parameter
      GALGAS_stringset joker_6882_2 ; // Joker input parameter
      GALGAS_signListForGeneration joker_6882_1 ; // Joker input parameter
      outArgument_outEntityMap.method_searchKey (enumerator_6769.current_mDestinationEntityName (HERE), joker_6827_11, joker_6827_10, joker_6827_9, joker_6827_8, joker_6827_7, joker_6827_6, joker_6827_5, joker_6827_4, joker_6827_3, joker_6827_2, joker_6827_1, var_destinationEntityRelationshipMap, joker_6882_2, joker_6882_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (190)) ;
      //-------- END @methodCallInstructionForGeneration
      //-------- @localVariableDeclarationForGeneration
      GALGAS_lstring var_inverseOfInverseRelationshipName ;
      //-------- @localVariableDeclarationForGeneration
      GALGAS_bool var_inverseIsToMany ;
      //-------- @methodCallInstructionForGeneration
      GALGAS_bool joker_6965_2 ; // Joker input parameter
      GALGAS_lstring joker_6965_1 ; // Joker input parameter
      GALGAS_deleteRuleEnum joker_7035_0 ; // Joker input parameter
      var_destinationEntityRelationshipMap.method_searchKey (enumerator_6769.current_mInverseRelationshipName (HERE), joker_6965_2, joker_6965_1, var_inverseOfInverseRelationshipName, var_inverseIsToMany, joker_7035_0, inCompiler COMMA_SOURCE_FILE_AT_LINE (191)) ;
      //-------- END @methodCallInstructionForGeneration
      //-------- @ifInstructionForGeneration
      const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, enumerator_6769.current_lkey (HERE).mAttribute_string.objectCompare (var_inverseOfInverseRelationshipName.mAttribute_string)).boolEnum () ;
      if (kBoolTrue == test_0) {
        //-------- @errorInstructionForGeneration
        GALGAS_location location_1 (enumerator_6769.current_mInverseRelationshipName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_1, GALGAS_string ("the inverse relationship does not name '").operator_concat (enumerator_6769.current_lkey (HERE).reader_string (SOURCE_FILE_AT_LINE (193)) COMMA_SOURCE_FILE_AT_LINE (193)).operator_concat (GALGAS_string ("' relationship as inverse") COMMA_SOURCE_FILE_AT_LINE (193)) COMMA_SOURCE_FILE_AT_LINE (193)) ;
      }
      //-------- @ifInstructionForGeneration
      const enumGalgasBool test_2 = GALGAS_bool (kIsNotEqual, enumerator_6769.current_mIsToMany (HERE).objectCompare (var_inverseIsToMany)).boolEnum () ;
      if (kBoolTrue == test_2) {
        //-------- @errorInstructionForGeneration
        //--- @ifExpressionForGeneration
        GALGAS_string temp_3 ;
        const enumGalgasBool test_4 = var_inverseIsToMany.boolEnum () ;
        if (kBoolTrue == test_4) {
          temp_3 = GALGAS_string ("to many") ;
        }else if (kBoolFalse == test_4) {
          temp_3 = GALGAS_string ("to one") ;
        }
        GALGAS_location location_5 (enumerator_6769.current_mInverseRelationshipName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_5, GALGAS_string ("the inverse relationship is ").operator_concat (temp_3 COMMA_SOURCE_FILE_AT_LINE (196)) COMMA_SOURCE_FILE_AT_LINE (196)) ;
      }
      enumerator_6769.gotoNextObject () ;
    }
    enumerator_6730.gotoNextObject () ;
  }
  //-------- @assignmentInstructionForGeneration
  outArgument_outEntityListForGeneration = GALGAS_entityListForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (201)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_entityMap enumerator_7613 (outArgument_outEntityMap, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_7613.hasCurrentObject ()) {
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS__32_stringlist var_toManyRelationshipList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (203)) ;
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS__32_stringlist var_toOneRelationshipList = GALGAS__32_stringlist::constructor_emptyList (SOURCE_FILE_AT_LINE (204)) ;
    //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
    GALGAS_stringset var_headerFileInclusionSet = enumerator_7613.current_mHeaderFileInclusionSet (HERE) ;
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_stringset var_headerFilePredeclarationSet = GALGAS_stringset::constructor_emptySet (SOURCE_FILE_AT_LINE (206)) ;
    //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
    GALGAS_stringset var_implementationFileInclusionSet = enumerator_7613.current_mImplementationFileInclusionSet (HERE) ;
    //-------- @foreachInstructionForGeneration
    cEnumerator_relationshipMap enumerator_7965 (enumerator_7613.current_mCurrentRelationshipMap (HERE), kEnumeration_up) ;
    //--- simple foreach instruction
    while (enumerator_7965.hasCurrentObject ()) {
      //-------- @ifInstructionForGeneration
      const enumGalgasBool test_6 = enumerator_7965.current_mIsToMany (HERE).boolEnum () ;
      if (kBoolTrue == test_6) {
        //-------- @plusEqualnstructionForGeneration
        var_toManyRelationshipList.addAssign_operation (enumerator_7965.current_lkey (HERE).mAttribute_string, enumerator_7965.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (210)) ;
        //-------- @plusEqualnstructionForGeneration
        var_headerFilePredeclarationSet.addAssign_operation (enumerator_7965.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (211)) ;
        //-------- @plusEqualnstructionForGeneration
        var_implementationFileInclusionSet.addAssign_operation (enumerator_7965.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (212)) ;
      }else if (kBoolFalse == test_6) {
        //-------- @plusEqualnstructionForGeneration
        var_toOneRelationshipList.addAssign_operation (enumerator_7965.current_lkey (HERE).mAttribute_string, enumerator_7965.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (214)) ;
        //-------- @plusEqualnstructionForGeneration
        var_headerFilePredeclarationSet.addAssign_operation (enumerator_7965.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (215)) ;
        //-------- @plusEqualnstructionForGeneration
        var_implementationFileInclusionSet.addAssign_operation (enumerator_7965.current_mDestinationEntityName (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (216)) ;
      }
      enumerator_7965.gotoNextObject () ;
    }
    //-------- @plusEqualnstructionForGeneration
    outArgument_outEntityListForGeneration.addAssign_operation (enumerator_7613.current_lkey (HERE).mAttribute_string, enumerator_7613.current_mSuperEntityName (HERE), enumerator_7613.current_mObservablePropertyMap (HERE), enumerator_7613.current_mAttributeListForInitMethodHeader (HERE), enumerator_7613.current_mInheritedAttributeListForImplementation (HERE), enumerator_7613.current_mAttributeListForImplementation (HERE), enumerator_7613.current_mTransientListForImplementation (HERE), enumerator_7613.current_mCurrentRelationshipList (HERE), enumerator_7613.current_mAllRelationshipList (HERE), enumerator_7613.current_mAllPropertyMap (HERE), enumerator_7613.current_mCurrentRelationshipMap (HERE), enumerator_7613.current_mAllRelationshipMap (HERE), var_headerFilePredeclarationSet, var_toManyRelationshipList, var_headerFileInclusionSet, var_implementationFileInclusionSet, var_toOneRelationshipList, enumerator_7613.current_mSignList (HERE) COMMA_SOURCE_FILE_AT_LINE (219)) ;
    enumerator_7613.gotoNextObject () ;
  }
}


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


