//---------------------------------------------------------------------------*
//                                                                           *
//                        File 'enumGeneration.cpp'                          *
//                        Generated by version 2.4.3                         *
//                    december 16th, 2012, at 10h59'27"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "enumGeneration.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------*

#include "easyBindings_options.h"

//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "enumGeneration.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//                   Filewrapper 'enumGenerationTemplate'                    *
//                                                                           *
//---------------------------------------------------------------------------*

extern const cDirectoryWrapper gWrapperDirectory_0_enumGenerationTemplate ;

//---------------------------------------------------------------------------*
//                                                                           *
//       Filewrapper template 'enumGenerationTemplate enumDeclaration'       *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_enumGenerationTemplate_enumDeclaration (C_Compiler * inCompiler,
                                                                          const GALGAS_string & in_ENUM_5F_TYPE_5F_NAME,
                                                                          const GALGAS_lstringlist & in_CONSTANT_5F_ORDERED_5F_LIST
                                                                          COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                   Filewrapper 'enumGenerationTemplate'                    *
//                                                                           *
//---------------------------------------------------------------------------*

//--- All files of '' directory

static const cRegularFileWrapper * gWrapperAllFiles_enumGenerationTemplate_0 [1] = {
  NULL
} ;

//--- All sub-directories of '' directory

static const cDirectoryWrapper * gWrapperAllDirectories_enumGenerationTemplate_0 [1] = {
  NULL
} ;

//--- Directory ''

const cDirectoryWrapper gWrapperDirectory_0_enumGenerationTemplate (
  "",
  0,
  gWrapperAllFiles_enumGenerationTemplate_0,
  0,
  gWrapperAllDirectories_enumGenerationTemplate_0
) ;


//---------------------------------------------------------------------------*
//                                                                           *
//       Filewrapper template 'enumGenerationTemplate enumDeclaration'       *
//                                                                           *
//---------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_enumGenerationTemplate_enumDeclaration (C_Compiler * /* inCompiler */,
                                                                          const GALGAS_string & in_ENUM_5F_TYPE_5F_NAME,
                                                                          const GALGAS_lstringlist & in_CONSTANT_5F_ORDERED_5F_LIST
                                                                          COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "#import <Cocoa/Cocoa.h>\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "typedef enum " ;
  result << in_ENUM_5F_TYPE_5F_NAME.stringValue () ;
  result << " : NSInteger {\n" ;
  GALGAS_uint index_189_ (0) ;
  if (in_CONSTANT_5F_ORDERED_5F_LIST.isValid ()) {
    cEnumerator_lstringlist enumerator_189 (in_CONSTANT_5F_ORDERED_5F_LIST, kEnumeration_up) ;
    while (enumerator_189.hasCurrentObject ()) {
      result << "  " ;
      result << enumerator_189.current_mValue (HERE).mAttribute_string.stringValue () ;
      if (enumerator_189.hasNextObject ()) {
        result << ", \n" ;
      }
      index_189_.increment () ;
      enumerator_189.gotoNextObject () ;
    }
  }
  result << "\n"
    "} " ;
  result << in_ENUM_5F_TYPE_5F_NAME.stringValue () ;
  result << " ;\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//---------------------------------------------------------------------------*
//                                                                           *
//                      Routine 'generateEnumerations'                       *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_generateEnumerations (const GALGAS_enumMap constinArgument_inEnumMap,
                                   const GALGAS_string constinArgument_inOutputDirectory,
                                   C_Compiler * inCompiler
                                   COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @ifInstructionForGeneration
  const enumGalgasBool test_0 = GALGAS_bool (kIsEqual, GALGAS_uint::constructor_errorCount (SOURCE_FILE_AT_LINE (22)).objectCompare (GALGAS_uint ((PMUInt32) 0U))).boolEnum () ;
  if (kBoolTrue == test_0) {
    //-------- @foreachInstructionForGeneration
    cEnumerator_enumMap enumerator_625 (constinArgument_inEnumMap, kEnumeration_up) ;
    //--- simple foreach instruction
    while (enumerator_625.hasCurrentObject ()) {
      //-------- @localVariableOrConstantDeclarationWithSourceExpressionForGeneration
      GALGAS_string var_s = GALGAS_string (filewrapperTemplate_enumGenerationTemplate_enumDeclaration (inCompiler, enumerator_625.current_lkey (HERE).reader_string (SOURCE_FILE_AT_LINE (25)), enumerator_625.current_mConstantOrderedList (HERE) COMMA_SOURCE_FILE_AT_LINE (24))) ;
      { //-------- @typeMethodInstructionForGeneration
      GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, enumerator_625.current_lkey (HERE).reader_string (SOURCE_FILE_AT_LINE (30)).operator_concat (GALGAS_string (".h") COMMA_SOURCE_FILE_AT_LINE (30)), GALGAS_string ("//"), GALGAS_string ("\n"
        "\n"), var_s, GALGAS_string ("\n"
        "\n"), GALGAS_string ("\n"), inCompiler COMMA_SOURCE_FILE_AT_LINE (28)) ;
      } //-------- @routineCallInstructionForGeneration
      enumerator_625.gotoNextObject () ;
    }
  }
}


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


