//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                            File 'nibClassAnalysis.cpp'                                              *
//                                             Generated by version 2.7.0                                              *
//                                           august 8th, 2014, at 20h3'38"                                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "nibClassAnalysis.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                          Overriding category method '@nibClassDeclaration EXTypeInventory'                          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_nibClassDeclaration_EXTypeInventory (const cPtr_EXastDeclaration * inObject,
                                                                GALGAS_EXunifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                                                C_Compiler * inCompiler
                                                                COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_nibClassDeclaration * object = (const cPtr_nibClassDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_nibClassDeclaration) ;
  GALGAS_actionMap var_actionMap = GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 12)) ;
  cEnumerator_lstringlist enumerator_479 (object->mAttribute_mActionDeclarationList, kEnumeration_up) ;
  while (enumerator_479.hasCurrentObject ()) {
    {
    var_actionMap.modifier_insertKey (enumerator_479.current (HERE).mAttribute_mValue, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 14)) ;
    }
    enumerator_479.gotoNextObject () ;
  }
  cEnumerator_attributeList enumerator_624 (object->mAttribute_mAttributeList, kEnumeration_up) ;
  while (enumerator_624.hasCurrentObject ()) {
    {
    GALGAS_EXunifiedTypeProxy joker_721_0 ; // Joker input parameter
    GALGAS_EXunifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_624.current_mAttributeTypeName (HERE), joker_721_0 COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 18)) ;
    }
    enumerator_624.gotoNextObject () ;
  }
  cEnumerator_classArrayList enumerator_819 (object->mAttribute_mArrayList, kEnumeration_up) ;
  while (enumerator_819.hasCurrentObject ()) {
    {
    GALGAS_EXunifiedTypeProxy joker_915_0 ; // Joker input parameter
    GALGAS_EXunifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_819.current_mElementClassName (HERE), joker_915_0 COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 26)) ;
    }
    enumerator_819.gotoNextObject () ;
  }
  cEnumerator_controllerList enumerator_1038 (object->mAttribute_mControllerList, kEnumeration_up) ;
  while (enumerator_1038.hasCurrentObject ()) {
    {
    GALGAS_EXunifiedTypeProxy joker_1137_0 ; // Joker input parameter
    GALGAS_EXunifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_1038.current_mControllerClassName (HERE), joker_1137_0 COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 34)) ;
    }
    enumerator_1038.gotoNextObject () ;
  }
  cEnumerator_transientList enumerator_1252 (object->mAttribute_mTransientList, kEnumeration_up) ;
  while (enumerator_1252.hasCurrentObject ()) {
    {
    GALGAS_EXunifiedTypeProxy joker_1349_0 ; // Joker input parameter
    GALGAS_EXunifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_1252.current_mTransientTypeName (HERE), joker_1349_0 COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 42)) ;
    }
    enumerator_1252.gotoNextObject () ;
  }
  {
  const GALGAS_nibClassDeclaration temp_0 = object ;
  ioArgument_ioUnifiedTypeMap.modifier_insertKey (object->mAttribute_mClassName, GALGAS_EXebType::constructor_new (object->mAttribute_mClassName, GALGAS_EXTypeKind::constructor_nibClassType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 51))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 51)), temp_0, GALGAS_EXentityRelationshipMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 53)), inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 49)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_nibClassDeclaration_EXTypeInventory (void) {
  enterCategoryMethod_EXTypeInventory (kTypeDescriptor_GALGAS_nibClassDeclaration.mSlotID,
                                       categoryMethod_nibClassDeclaration_EXTypeInventory) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_nibClassDeclaration_EXTypeInventory (defineCategoryMethod_nibClassDeclaration_EXTypeInventory, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                    Overriding category method '@nibClassDeclaration buildObservablePropertyMap'                     *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_nibClassDeclaration_buildObservablePropertyMap (const cPtr_EXastDeclaration * inObject,
                                                                           const GALGAS_EXunifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                           GALGAS_EXobservablePropertyMapMap & ioArgument_ioObservablePropertyMapMap,
                                                                           GALGAS_EXtransientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                           C_Compiler * inCompiler
                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_nibClassDeclaration * object = (const cPtr_nibClassDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_nibClassDeclaration) ;
  GALGAS_EXobservablePropertyMap var_observablePropertyMap = GALGAS_EXobservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 64)) ;
  {
  routine_buildObservablePropertyMap (object->mAttribute_mAttributeList, object->mAttribute_mArrayList, object->mAttribute_mTransientList, object->mAttribute_mControllerList, GALGAS_controllerObservablePropertyList::constructor_emptyList (SOURCE_FILE ("nibClassAnalysis.gSemantics", 71)), ioArgument_ioObservablePropertyMapMap, ioArgument_ioTransientDependencyGraph, constinArgument_inUnifiedTypeMap, GALGAS_string ("nibclass.").operator_concat (object->mAttribute_mClassName.reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 75))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 75)), var_observablePropertyMap, inCompiler  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 66)) ;
  }
  {
  ioArgument_ioObservablePropertyMapMap.modifier_insertKey (object->mAttribute_mClassName, object->mAttribute_mUserDefined, GALGAS_EXTypeKind::constructor_nibClassType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 82)), var_observablePropertyMap, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 79)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_nibClassDeclaration_buildObservablePropertyMap (void) {
  enterCategoryMethod_buildObservablePropertyMap (kTypeDescriptor_GALGAS_nibClassDeclaration.mSlotID,
                                                  categoryMethod_nibClassDeclaration_buildObservablePropertyMap) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_nibClassDeclaration_buildObservablePropertyMap (defineCategoryMethod_nibClassDeclaration_buildObservablePropertyMap, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                         Overriding category method '@nibClassDeclaration semanticAnalysis'                          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_nibClassDeclaration_semanticAnalysis (const cPtr_EXastDeclaration * inObject,
                                                                 const GALGAS_EXunifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                 GALGAS_EXcontextAnalysisStruct & ioArgument_ioContextAnalysisStruct,
                                                                 GALGAS_generationList & ioArgument_ioGenerationList,
                                                                 C_Compiler * inCompiler
                                                                 COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_nibClassDeclaration * object = (const cPtr_nibClassDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_nibClassDeclaration) ;
  GALGAS_EXobservablePropertyMap var_selfObservablePropertyMap ;
  GALGAS_bool joker_2948_2 ; // Joker input parameter
  GALGAS_EXTypeKind joker_2948_1 ; // Joker input parameter
  ioArgument_ioContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (object->mAttribute_mClassName, joker_2948_2, joker_2948_1, var_selfObservablePropertyMap, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 95)) ;
  GALGAS_propertyArrayMap var_allArrayPropertyForImplementation = GALGAS_propertyArrayMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 101)) ;
  GALGAS_propertyArrayMap var_currentArrayPropertyForImplementation = GALGAS_propertyArrayMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 102)) ;
  GALGAS_fileInclusionSet var_fileInclusionSet = GALGAS_fileInclusionSet::constructor_default (SOURCE_FILE ("nibClassAnalysis.gSemantics", 103)) ;
  GALGAS_actionMap var_actionMap = GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 105)) ;
  cEnumerator_lstringlist enumerator_3342 (object->mAttribute_mActionDeclarationList, kEnumeration_up) ;
  while (enumerator_3342.hasCurrentObject ()) {
    {
    var_actionMap.modifier_insertKey (enumerator_3342.current (HERE).mAttribute_mValue, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 107)) ;
    }
    enumerator_3342.gotoNextObject () ;
  }
  GALGAS_transientListForImplementation var_transientListForImplementation ;
  {
  routine_analyzeTransientProperties (object->mAttribute_mTransientList, GALGAS_EXobservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 113)), ioArgument_ioContextAnalysisStruct, GALGAS_string::makeEmptyString (), var_selfObservablePropertyMap, var_fileInclusionSet, var_transientListForImplementation, inCompiler  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 111)) ;
  }
  GALGAS_attributeListForImplementation var_unusedAttributList = GALGAS_attributeListForImplementation::constructor_emptyList (SOURCE_FILE ("nibClassAnalysis.gSemantics", 121)) ;
  GALGAS_attributeListForImplementation var_attributeListForImplementation ;
  {
  routine_analyzeAttributeDeclaration (object->mAttribute_mAttributeList, ioArgument_ioContextAnalysisStruct, constinArgument_inUnifiedTypeMap, var_fileInclusionSet, var_attributeListForImplementation, var_unusedAttributList, inCompiler  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 122)) ;
  }
  cEnumerator_classArrayList enumerator_4212 (object->mAttribute_mArrayList, kEnumeration_up) ;
  while (enumerator_4212.hasCurrentObject ()) {
    GALGAS_EXebType var_type ;
    GALGAS_EXastDeclaration joker_4302_2 ; // Joker input parameter
    GALGAS_EXentityRelationshipMap joker_4302_1 ; // Joker input parameter
    constinArgument_inUnifiedTypeMap.method_searchKey (enumerator_4212.current_mElementClassName (HERE), var_type, joker_4302_2, joker_4302_1, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 132)) ;
    const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_type.mAttribute_mKind.objectCompare (GALGAS_EXTypeKind::constructor_classType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 137)))).boolEnum () ;
    if (kBoolTrue == test_0) {
      GALGAS_location location_1 (object->mAttribute_mClassName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_1, GALGAS_string ("'").operator_concat (object->mAttribute_mClassName.reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 138))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 138)).operator_concat (GALGAS_string ("' is not a class")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 138))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 138)) ;
    }
    {
    var_currentArrayPropertyForImplementation.modifier_insertKey (enumerator_4212.current_mArrayName (HERE), var_type, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 140)) ;
    }
    enumerator_4212.gotoNextObject () ;
  }
  GALGAS_controllerMap var_controllerMap = GALGAS_controllerMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 146)) ;
  cEnumerator_controllerList enumerator_4696 (object->mAttribute_mControllerList, kEnumeration_up) ;
  while (enumerator_4696.hasCurrentObject ()) {
    GALGAS_controllerKind var_controllerKind ;
    GALGAS_outletClassBindingMap var_controllerClassBindingMap ;
    GALGAS_actionMap var_controllerActionMap ;
    GALGAS_EXobservablePropertyMap var_controllerObservablePropertyMap ;
    GALGAS_outletClassBindingOptionMap var_controlledObjectAvailableBindingOptionMap ;
    GALGAS_generationKind joker_4833_0 ; // Joker input parameter
    ioArgument_ioContextAnalysisStruct.mAttribute_mControllerClassMap.method_searchKey (enumerator_4696.current_mControllerClassName (HERE), var_controllerKind, joker_4833_0, var_controllerClassBindingMap, var_controllerActionMap, var_controllerObservablePropertyMap, var_controlledObjectAvailableBindingOptionMap, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 148)) ;
    GALGAS_outletBindingListForGeneration var_bindingListForGeneration = GALGAS_outletBindingListForGeneration::constructor_emptyList (SOURCE_FILE ("nibClassAnalysis.gSemantics", 158)) ;
    GALGAS_string var_controllerObjectClassName ;
    if (var_controllerKind.isValid ()) {
      switch (var_controllerKind.enumValue ()) {
      case GALGAS_controllerKind::kNotBuilt:
        break ;
      case GALGAS_controllerKind::kEnum_simpleController: {
        var_controllerObjectClassName = GALGAS_string::makeEmptyString () ;
        } break ;
      case GALGAS_controllerKind::kEnum_objectController: {
        GALGAS_location location_2 (enumerator_4696.current_mControlledObjectName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_2, GALGAS_string ("objectController is not currently handled in nib class")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 164)) ;
        var_controllerObjectClassName.drop () ; // Release error dropped variable
        } break ;
      case GALGAS_controllerKind::kEnum_entityController: {
        GALGAS_location location_3 (enumerator_4696.current_mControlledObjectName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_3, GALGAS_string ("entityController is not currently handled in nib class")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 168)) ;
        var_controllerObjectClassName.drop () ; // Release error dropped variable
        } break ;
      case GALGAS_controllerKind::kEnum_entityArrayController: {
        GALGAS_location location_4 (enumerator_4696.current_mControlledObjectName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
        inCompiler->emitSemanticError (location_4, GALGAS_string ("in nib class, use an arrayController, as NSArrayController")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 172)) ;
        var_controllerObjectClassName.drop () ; // Release error dropped variable
        } break ;
      case GALGAS_controllerKind::kEnum_arrayController: {
        const enumGalgasBool test_5 = enumerator_4696.current_mIsRootObject (HERE).mAttribute_bool.boolEnum () ;
        if (kBoolTrue == test_5) {
          GALGAS_location location_6 (enumerator_4696.current_mIsRootObject (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
          inCompiler->emitSemanticError (location_6, GALGAS_string ("only 'self' is allowed here")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 177)) ;
        }
        GALGAS_EXebType var_controlledObjectType ;
        var_currentArrayPropertyForImplementation.method_searchKey (enumerator_4696.current_mControlledObjectName (HERE), var_controlledObjectType, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 181)) ;
        var_controllerObjectClassName = var_controlledObjectType.mAttribute_mTypeName.mAttribute_string ;
        GALGAS_EXTypeKind var_kind ;
        GALGAS_EXobservablePropertyMap var_classObservablePropertyMap ;
        GALGAS_bool joker_6269_0 ; // Joker input parameter
        ioArgument_ioContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (var_controlledObjectType.mAttribute_mTypeName, joker_6269_0, var_kind, var_classObservablePropertyMap, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 186)) ;
        const enumGalgasBool test_7 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_EXTypeKind::constructor_classType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 192)))).boolEnum () ;
        if (kBoolTrue == test_7) {
          GALGAS_location location_8 (enumerator_4696.current_mControlledObjectName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
          inCompiler->emitSemanticError (location_8, GALGAS_string ("'").operator_concat (enumerator_4696.current_mControlledObjectName (HERE).reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 193))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 193)).operator_concat (GALGAS_string ("' is not a class")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 193))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 193)) ;
        }
        GALGAS_bindingOptionListForGeneration var_controlledObjectBindingOptionListForGeneration ;
        {
        routine_checkBindingOptions (ioArgument_ioContextAnalysisStruct, enumerator_4696.current_mControlledObjectBindingOptionList (HERE), var_controlledObjectAvailableBindingOptionMap, var_controlledObjectBindingOptionListForGeneration, var_fileInclusionSet, inCompiler  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 195)) ;
        }
        var_bindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (GALGAS_EXebType::constructor_new (GALGAS_string ("<unused4>").reader_nowhere (SOURCE_FILE ("nibClassAnalysis.gSemantics", 203)), GALGAS_EXTypeKind::constructor_classType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 203))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 203)), GALGAS_string ("contentArray"), GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE ("nibClassAnalysis.gSemantics", 205)), GALGAS_string ("self"), enumerator_4696.current_mControlledObjectName (HERE).mAttribute_string, GALGAS_bool (false), var_controlledObjectBindingOptionListForGeneration  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 202))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 202)) ;
        } break ;
      case GALGAS_controllerKind::kEnum_treeController: {
        const enumGalgasBool test_9 = enumerator_4696.current_mIsRootObject (HERE).mAttribute_bool.boolEnum () ;
        if (kBoolTrue == test_9) {
          GALGAS_location location_10 (enumerator_4696.current_mIsRootObject (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
          inCompiler->emitSemanticError (location_10, GALGAS_string ("only 'self' is allowed here")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 213)) ;
        }
        GALGAS_EXebType var_controlledObjectType ;
        var_currentArrayPropertyForImplementation.method_searchKey (enumerator_4696.current_mControlledObjectName (HERE), var_controlledObjectType, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 217)) ;
        var_controllerObjectClassName = var_controlledObjectType.mAttribute_mTypeName.mAttribute_string ;
        GALGAS_EXTypeKind var_kind ;
        GALGAS_EXobservablePropertyMap var_classObservablePropertyMap ;
        GALGAS_bool joker_7651_0 ; // Joker input parameter
        ioArgument_ioContextAnalysisStruct.mAttribute_mObservablePropertyMapMap.method_searchKey (var_controlledObjectType.mAttribute_mTypeName, joker_7651_0, var_kind, var_classObservablePropertyMap, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 222)) ;
        const enumGalgasBool test_11 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_EXTypeKind::constructor_classType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 228)))).boolEnum () ;
        if (kBoolTrue == test_11) {
          GALGAS_location location_12 (enumerator_4696.current_mControlledObjectName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
          inCompiler->emitSemanticError (location_12, GALGAS_string ("'").operator_concat (enumerator_4696.current_mControlledObjectName (HERE).reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 229))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 229)).operator_concat (GALGAS_string ("' is not a class")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 229))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 229)) ;
        }
        GALGAS_bindingOptionListForGeneration var_controlledObjectBindingOptionListForGeneration ;
        {
        routine_checkBindingOptions (ioArgument_ioContextAnalysisStruct, enumerator_4696.current_mControlledObjectBindingOptionList (HERE), var_controlledObjectAvailableBindingOptionMap, var_controlledObjectBindingOptionListForGeneration, var_fileInclusionSet, inCompiler  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 231)) ;
        }
        var_bindingListForGeneration.addAssign_operation (GALGAS_regularBindingForGeneration::constructor_new (GALGAS_EXebType::constructor_new (GALGAS_string ("<unused6>").reader_nowhere (SOURCE_FILE ("nibClassAnalysis.gSemantics", 239)), GALGAS_EXTypeKind::constructor_classType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 239))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 239)), GALGAS_string ("contentArray"), GALGAS_formatterEnum::constructor_noFormatter (SOURCE_FILE ("nibClassAnalysis.gSemantics", 241)), GALGAS_string ("self"), enumerator_4696.current_mControlledObjectName (HERE).mAttribute_string, GALGAS_bool (false), var_controlledObjectBindingOptionListForGeneration  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 238))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 238)) ;
        GALGAS_EXebType var_type ;
        GALGAS_bool var_isCollection ;
        GALGAS_bool joker_8692_0 ; // Joker input parameter
        GALGAS_lstring joker_8723_0 ; // Joker input parameter
        var_classObservablePropertyMap.method_searchKey (enumerator_4696.current_mChildRelationshipName (HERE), var_type, joker_8692_0, joker_8723_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 248)) ;
        const enumGalgasBool test_13 = var_isCollection.operator_not (SOURCE_FILE ("nibClassAnalysis.gSemantics", 255)).operator_or (GALGAS_bool (kIsNotEqual, var_type.mAttribute_mKind.objectCompare (GALGAS_EXTypeKind::constructor_classType (SOURCE_FILE ("nibClassAnalysis.gSemantics", 255)))) COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 255)).operator_or (GALGAS_bool (kIsNotEqual, var_type.mAttribute_mTypeName.mAttribute_string.objectCompare (var_controlledObjectType.mAttribute_mTypeName.mAttribute_string)) COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 255)).boolEnum () ;
        if (kBoolTrue == test_13) {
          GALGAS_location location_14 (enumerator_4696.current_mChildRelationshipName (HERE).reader_location (HERE)) ; // Implicit use of 'location' reader
          inCompiler->emitSemanticError (location_14, GALGAS_string ("this relationship is used as 'childrenKeyPath' and should be an '").operator_concat (var_controlledObjectType.mAttribute_mTypeName.reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 256))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 256)).operator_concat (GALGAS_string ("' array")  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 256))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 256)) ;
        }
        var_bindingListForGeneration.addAssign_operation (GALGAS_treeControllerForGeneration::constructor_new (enumerator_4696.current_mChildRelationshipName (HERE).mAttribute_string  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 258))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 258)) ;
        } break ;
      }
    }
    cEnumerator_bindingList enumerator_9279 (enumerator_4696.current_mControllerBindingList (HERE), kEnumeration_up) ;
    while (enumerator_9279.hasCurrentObject ()) {
      callCategoryMethod_analyzeOutletBinding ((const cPtr_abstractBinding *) enumerator_9279.current_mBinding (HERE).ptr (), GALGAS_EXobservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 264)), var_selfObservablePropertyMap, var_controllerClassBindingMap, var_controllerMap, var_actionMap, GALGAS_bool (false), ioArgument_ioContextAnalysisStruct, var_bindingListForGeneration, var_fileInclusionSet, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 263)) ;
      enumerator_9279.gotoNextObject () ;
    }
    {
    var_controllerMap.modifier_insertKey (enumerator_4696.current_mControllerName (HERE), enumerator_4696.current_mControllerClassName (HERE).mAttribute_string, GALGAS_lstring::constructor_new (var_controllerObjectClassName, inCompiler->here ()  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 278)), GALGAS_bool (false), var_bindingListForGeneration, var_controllerActionMap, var_controllerObservablePropertyMap, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 275)) ;
    }
    enumerator_4696.gotoNextObject () ;
  }
  GALGAS_outletGenerationList var_outletGenerationList = GALGAS_outletGenerationList::constructor_emptyList (SOURCE_FILE ("nibClassAnalysis.gSemantics", 286)) ;
  cEnumerator_outletDeclarationList enumerator_10108 (object->mAttribute_mOutletDeclarationList, kEnumeration_up) ;
  while (enumerator_10108.hasCurrentObject ()) {
    GALGAS_generationKind var_generationKind ;
    GALGAS_bool var_implementsDeallocProtocol ;
    GALGAS_outletClassBindingMap var_outletClassBindingMap ;
    GALGAS_bool var_hasTableValueBinding ;
    GALGAS_string joker_10232_2 ; // Joker input parameter
    GALGAS_protocolList joker_10232_1 ; // Joker input parameter
    GALGAS_outletClassBindingMap joker_10333_0 ; // Joker input parameter
    ioArgument_ioContextAnalysisStruct.mAttribute_mOutletClassMap.method_searchKey (enumerator_10108.current_mOutletType (HERE), var_generationKind, joker_10232_2, joker_10232_1, var_implementsDeallocProtocol, var_outletClassBindingMap, joker_10333_0, var_hasTableValueBinding, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 288)) ;
    const enumGalgasBool test_15 = GALGAS_bool (kIsNotEqual, var_generationKind.objectCompare (GALGAS_generationKind::constructor_noGeneration (SOURCE_FILE ("nibClassAnalysis.gSemantics", 297)))).boolEnum () ;
    if (kBoolTrue == test_15) {
      var_fileInclusionSet.mAttribute_mImplementationFileInclusionSet.addAssign_operation (enumerator_10108.current_mOutletType (HERE).mAttribute_string  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 298)) ;
    }
    GALGAS_outletBindingListForGeneration var_outletBindingList = GALGAS_outletBindingListForGeneration::constructor_emptyList (SOURCE_FILE ("nibClassAnalysis.gSemantics", 300)) ;
    cEnumerator_bindingList enumerator_10631 (enumerator_10108.current_mOutletBindingList (HERE), kEnumeration_up) ;
    while (enumerator_10631.hasCurrentObject ()) {
      callCategoryMethod_analyzeOutletBinding ((const cPtr_abstractBinding *) enumerator_10631.current_mBinding (HERE).ptr (), GALGAS_EXobservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("nibClassAnalysis.gSemantics", 303)), var_selfObservablePropertyMap, var_outletClassBindingMap, var_controllerMap, var_actionMap, var_hasTableValueBinding, ioArgument_ioContextAnalysisStruct, var_outletBindingList, var_fileInclusionSet, inCompiler COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 302)) ;
      enumerator_10631.gotoNextObject () ;
    }
    var_outletGenerationList.addAssign_operation (enumerator_10108.current_mOutletType (HERE).reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 315)), enumerator_10108.current_mOutletName (HERE).reader_string (SOURCE_FILE ("nibClassAnalysis.gSemantics", 316)), var_outletBindingList, var_implementsDeallocProtocol  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 314)) ;
    enumerator_10108.gotoNextObject () ;
  }
  ioArgument_ioGenerationList.addAssign_operation (GALGAS_nibClassTypeGeneration::constructor_new (object->mAttribute_mClassName.mAttribute_string, var_attributeListForImplementation, var_transientListForImplementation, var_outletGenerationList, object->mAttribute_mActionDeclarationList, var_selfObservablePropertyMap, var_fileInclusionSet, var_controllerMap, var_currentArrayPropertyForImplementation  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 322))  COMMA_SOURCE_FILE ("nibClassAnalysis.gSemantics", 322)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_nibClassDeclaration_semanticAnalysis (void) {
  enterCategoryMethod_semanticAnalysis (kTypeDescriptor_GALGAS_nibClassDeclaration.mSlotID,
                                        categoryMethod_nibClassDeclaration_semanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_nibClassDeclaration_semanticAnalysis (defineCategoryMethod_nibClassDeclaration_semanticAnalysis, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


