//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                            File 'outletClassAnalysis.h'                                             *
//                                             Generated by version 3.0.0                                              *
//                                          september 4th, 2014, at 15h5'0"                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef outletClassAnalysis_ENTITIES_DEFINED
#define outletClassAnalysis_ENTITIES_DEFINED

//---------------------------------------------------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "bindingSemanticAnalysis.h"
#include "decoratedTypes.h"
#include "abstractSyntaxTypes.h"

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
