//---------------------------------------------------------------------------*
//                                                                           *
//                      File 'preferencesAnalysis.cpp'                       *
//                        Generated by version 2.4.3                         *
//                    december 16th, 2012, at 12h26'14"                      *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "preferencesAnalysis.h"
#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------*


//---------------------------------------------------------------------------*

#ifndef DO_NOT_GENERATE_CHECKINGS
  #define SOURCE_FILE_AT_LINE(line) "preferencesAnalysis.gSemantics", line
  #define COMMA_SOURCE_FILE_AT_LINE(line) , SOURCE_FILE_AT_LINE(line)
#else
  #define SOURCE_FILE_AT_LINE(line) 
  #define COMMA_SOURCE_FILE_AT_LINE(line) 
#endif

//---------------------------------------------------------------------------*
//                                                                           *
//                        Routine 'analyzePreference'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_analyzePreference (const GALGAS_preferencesDeclarationList_2E_element constinArgument0,
                                const GALGAS_controllerClassMap constinArgument1,
                                const GALGAS_classMap constinArgument2,
                                const GALGAS_outletClassMap constinArgument3,
                                const GALGAS_globalEnumConstantMap constinArgument4,
                                GALGAS_preferencesMap & ioArgument5,
                                GALGAS_transientDependencyGraph & ioArgument6,
                                C_Compiler * inCompiler
                                COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------*
//                                                                           *
//                        Routine 'analyzePreference'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_analyzePreference (const GALGAS_preferencesDeclarationList_2E_element constinArgument_inPreference,
                                const GALGAS_controllerClassMap constinArgument_inControllerClassMap,
                                const GALGAS_classMap constinArgument_inClassMap,
                                const GALGAS_outletClassMap constinArgument_inOutletClassMap,
                                const GALGAS_globalEnumConstantMap constinArgument_inGlobalEnumConstantMap,
                                GALGAS_preferencesMap & ioArgument_ioPreferencesMap,
                                GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                C_Compiler * inCompiler
                                COMMA_UNUSED_LOCATION_ARGS) {
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_actionMap var_actionMap = GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (16)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_lstringlist enumerator_643 (constinArgument_inPreference.mAttribute_mActionDeclarationList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_643.hasCurrentObject ()) {
    { //-------- @modifierCallInstructionForGeneration
    var_actionMap.modifier_insertKey (enumerator_643.current (HERE).mAttribute_mValue, inCompiler COMMA_SOURCE_FILE_AT_LINE (18)) ;
    } //-------- END @typeMethodInstructionForGeneration
    enumerator_643.gotoNextObject () ;
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_observablePropertyMap var_observableAttributeMap = GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (21)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringset var_headerFileInclusionSet = GALGAS_stringset::constructor_emptySet (SOURCE_FILE_AT_LINE (22)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_attributeListForImplementation var_attributeListForImplementation = GALGAS_attributeListForImplementation::constructor_emptyList (SOURCE_FILE_AT_LINE (23)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_attributeList enumerator_994 (constinArgument_inPreference.mAttribute_mAttributeList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_994.hasCurrentObject ()) {
    //-------- @localVariableDeclarationForGeneration
    GALGAS_string var_directDefaultValueAsString ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_string var_objectiveCDefaultValueAsString ;
    //-------- @methodCallInstructionForGeneration
    callCategoryMethod_analyzeDefaultValueType ((const cPtr_abstractDefaultValue *) enumerator_994.current_mDefaultValue (HERE).ptr (), GALGAS_easyBindingTypeList::constructor_listWithValue (enumerator_994.current_mType (HERE) COMMA_SOURCE_FILE_AT_LINE (26)), constinArgument_inGlobalEnumConstantMap, var_directDefaultValueAsString, var_objectiveCDefaultValueAsString, inCompiler COMMA_SOURCE_FILE_AT_LINE (25)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @methodCallInstructionForGeneration
    callCategoryMethod_addFileInclusion ((const cPtr_easyBindingType *) enumerator_994.current_mType (HERE).ptr (), var_headerFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (31)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @plusEqualnstructionForGeneration
    var_attributeListForImplementation.addAssign_operation (enumerator_994.current_mType (HERE), enumerator_994.current_mAttributeName (HERE).reader_string (SOURCE_FILE_AT_LINE (32)), var_objectiveCDefaultValueAsString, var_directDefaultValueAsString COMMA_SOURCE_FILE_AT_LINE (32)) ;
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_lstring var_observationDependencyKey = GALGAS_lstring::constructor_new (GALGAS_string ("preference.").operator_concat (constinArgument_inPreference.mAttribute_mPreferencesName.mAttribute_string COMMA_SOURCE_FILE_AT_LINE (34)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (34)).operator_concat (enumerator_994.current_mAttributeName (HERE).reader_string (SOURCE_FILE_AT_LINE (34)) COMMA_SOURCE_FILE_AT_LINE (34)), enumerator_994.current_mAttributeName (HERE).mAttribute_location COMMA_SOURCE_FILE_AT_LINE (33)) ;
    { //-------- @modifierCallInstructionForGeneration
    var_observableAttributeMap.modifier_insertKey (enumerator_994.current_mAttributeName (HERE), enumerator_994.current_mType (HERE), GALGAS_bool (false), var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (37)) ;
    } //-------- END @typeMethodInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    ioArgument_ioTransientDependencyGraph.modifier_addNode (var_observationDependencyKey, var_observationDependencyKey.mAttribute_string, inCompiler COMMA_SOURCE_FILE_AT_LINE (43)) ;
    } //-------- END @typeMethodInstructionForGeneration
    enumerator_994.gotoNextObject () ;
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_preferenceArrayMap var_preferenceArrayMap = GALGAS_preferenceArrayMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (49)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_classArrayList enumerator_2022 (constinArgument_inPreference.mAttribute_mClassArrayList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_2022.hasCurrentObject ()) {
    //-------- @localVariableDeclarationForGeneration
    GALGAS_observablePropertyMap var_classObservablePropertyMap ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_attributeListForImplementation var_attributeListForImplementation ;
    //-------- @methodCallInstructionForGeneration
    GALGAS_string joker_2075_0 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_2141_2 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_2141_1 ; // Joker input parameter
    GALGAS_transientListForImplementation joker_2221_3 ; // Joker input parameter
    GALGAS_stringset joker_2221_2 ; // Joker input parameter
    GALGAS_stringset joker_2221_1 ; // Joker input parameter
    constinArgument_inClassMap.method_searchKey (enumerator_2022.current_mClassName (HERE), joker_2075_0, var_classObservablePropertyMap, joker_2141_2, joker_2141_1, var_attributeListForImplementation, joker_2221_3, joker_2221_2, joker_2221_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (51)) ;
    //-------- END @methodCallInstructionForGeneration
    { //-------- @modifierCallInstructionForGeneration
    var_preferenceArrayMap.modifier_insertKey (enumerator_2022.current_mArrayName (HERE), enumerator_2022.current_mClassName (HERE).mAttribute_string, var_classObservablePropertyMap, var_attributeListForImplementation, inCompiler COMMA_SOURCE_FILE_AT_LINE (59)) ;
    } //-------- END @typeMethodInstructionForGeneration
    enumerator_2022.gotoNextObject () ;
  }
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_observablePropertyMap var_observablePropertyMap = GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (67)) ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_controllerMap var_controllerMap = GALGAS_controllerMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (68)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_controllerList enumerator_2625 (constinArgument_inPreference.mAttribute_mControllerList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_2625.hasCurrentObject ()) {
    //-------- @localVariableDeclarationForGeneration
    GALGAS_outletClassBindingMap var_controllerClassBindingMap ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_actionMap var_controllerActionMap ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_observablePropertyMap var_controllerObservablePropertyMap ;
    //-------- @methodCallInstructionForGeneration
    GALGAS_generationKind joker_2698_0 ; // Joker input parameter
    constinArgument_inControllerClassMap.method_searchKey (enumerator_2625.current_mControllerClassName (HERE), joker_2698_0, var_controllerClassBindingMap, var_controllerActionMap, var_controllerObservablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (70)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @methodCallInstructionForGeneration
    GALGAS_string joker_2921_8 ; // Joker input parameter
    GALGAS_observablePropertyMap joker_2921_7 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_2921_6 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_2921_5 ; // Joker input parameter
    GALGAS_attributeListForImplementation joker_2921_4 ; // Joker input parameter
    GALGAS_transientListForImplementation joker_2921_3 ; // Joker input parameter
    GALGAS_stringset joker_2921_2 ; // Joker input parameter
    GALGAS_stringset joker_2921_1 ; // Joker input parameter
    constinArgument_inClassMap.method_searchKey (enumerator_2625.current_mControlledClassOrEntityName (HERE), joker_2921_8, joker_2921_7, joker_2921_6, joker_2921_5, joker_2921_4, joker_2921_3, joker_2921_2, joker_2921_1, inCompiler COMMA_SOURCE_FILE_AT_LINE (77)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_outletBindingListForGeneration var_bindingListForGeneration = GALGAS_outletBindingListForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (78)) ;
    //-------- @foreachInstructionForGeneration
    cEnumerator_bindingList enumerator_3038 (enumerator_2625.current_mControllerBindingList (HERE), kEnumeration_up) ;
    //--- simple foreach instruction
    while (enumerator_3038.hasCurrentObject ()) {
      //-------- @methodCallInstructionForGeneration
      callCategoryMethod_analyzeControllerBinding ((const cPtr_abstractBinding *) enumerator_3038.current_mBinding (HERE).ptr (), GALGAS_relationshipMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (81)), var_preferenceArrayMap, var_controllerClassBindingMap, enumerator_2625.current_mControlledClassOrEntityName (HERE), var_observablePropertyMap, constinArgument_inGlobalEnumConstantMap, var_bindingListForGeneration, inCompiler COMMA_SOURCE_FILE_AT_LINE (80)) ;
      //-------- END @methodCallInstructionForGeneration
      enumerator_3038.gotoNextObject () ;
    }
    { //-------- @modifierCallInstructionForGeneration
    var_controllerMap.modifier_insertKey (enumerator_2625.current_mControllerName (HERE), enumerator_2625.current_mControllerClassName (HERE).mAttribute_string, enumerator_2625.current_mControlledClassOrEntityName (HERE).mAttribute_string, GALGAS_bool (false), var_bindingListForGeneration, var_controllerActionMap, var_controllerObservablePropertyMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (90)) ;
    } //-------- END @typeMethodInstructionForGeneration
    enumerator_2625.gotoNextObject () ;
  }
  //-------- @localVariableDeclarationForGeneration
  GALGAS_transientListForImplementation var_transientListForImplementation ;
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_stringset var_implementationFileInclusionSet = GALGAS_stringset::constructor_emptySet (SOURCE_FILE_AT_LINE (102)) ;
  { //-------- @routineCallInstructionForGeneration
  routine_analyzeTransientProperties (GALGAS_preferencesMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (104)), GALGAS_string ("preference.").operator_concat (constinArgument_inPreference.mAttribute_mPreferencesName.reader_string (SOURCE_FILE_AT_LINE (105)) COMMA_SOURCE_FILE_AT_LINE (105)).operator_concat (GALGAS_string (".") COMMA_SOURCE_FILE_AT_LINE (105)), constinArgument_inPreference.mAttribute_mTransientList, GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (107)), GALGAS_string::makeEmptyString (), GALGAS_controllerMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (109)), var_observableAttributeMap, var_implementationFileInclusionSet, var_transientListForImplementation, ioArgument_ioTransientDependencyGraph, inCompiler COMMA_SOURCE_FILE_AT_LINE (103)) ;
  } //-------- @routineCallInstructionForGeneration
  //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
  GALGAS_outletGenerationList var_outletGenerationList = GALGAS_outletGenerationList::constructor_emptyList (SOURCE_FILE_AT_LINE (116)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_outletDeclarationList enumerator_4411 (constinArgument_inPreference.mAttribute_mOutletDeclarationList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_4411.hasCurrentObject ()) {
    //-------- @localVariableDeclarationForGeneration
    GALGAS_generationKind var_generationKind ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_outletClassBindingMap var_bindingMap ;
    //-------- @localVariableDeclarationForGeneration
    GALGAS_bool var_hasTableValueBinding ;
    //-------- @methodCallInstructionForGeneration
    GALGAS_string joker_4509_2 ; // Joker input parameter
    GALGAS_lstringlist joker_4509_1 ; // Joker input parameter
    constinArgument_inOutletClassMap.method_searchKey (enumerator_4411.current_mOutletType (HERE), var_generationKind, joker_4509_2, joker_4509_1, var_bindingMap, var_hasTableValueBinding, inCompiler COMMA_SOURCE_FILE_AT_LINE (118)) ;
    //-------- END @methodCallInstructionForGeneration
    //-------- @ifInstructionForGeneration
    const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_generationKind.objectCompare (GALGAS_generationKind::constructor_noGeneration (SOURCE_FILE_AT_LINE (125)))).boolEnum () ;
    if (kBoolTrue == test_0) {
      //-------- @plusEqualnstructionForGeneration
      var_implementationFileInclusionSet.addAssign_operation (enumerator_4411.current_mOutletType (HERE).mAttribute_string COMMA_SOURCE_FILE_AT_LINE (126)) ;
    }
    //-------- @localVariableOrConstantDeclarationWithConstructorCallForGeneration
    GALGAS_outletBindingListForGeneration var_outletBindingList = GALGAS_outletBindingListForGeneration::constructor_emptyList (SOURCE_FILE_AT_LINE (128)) ;
    //-------- @foreachInstructionForGeneration
    cEnumerator_bindingList enumerator_4832 (enumerator_4411.current_mOutletBindingList (HERE), kEnumeration_up) ;
    //--- simple foreach instruction
    while (enumerator_4832.hasCurrentObject ()) {
      //-------- @methodCallInstructionForGeneration
      callCategoryMethod_analyzeOutletBinding ((const cPtr_abstractBinding *) enumerator_4832.current_mBinding (HERE).ptr (), GALGAS_observablePropertyMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (131)), var_observableAttributeMap, GALGAS_preferencesMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (133)), GALGAS_entityMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (134)), constinArgument_inClassMap, var_bindingMap, var_controllerMap, var_actionMap, var_hasTableValueBinding, constinArgument_inGlobalEnumConstantMap, var_outletBindingList, var_implementationFileInclusionSet, inCompiler COMMA_SOURCE_FILE_AT_LINE (130)) ;
      //-------- END @methodCallInstructionForGeneration
      enumerator_4832.gotoNextObject () ;
    }
    //-------- @plusEqualnstructionForGeneration
    var_outletGenerationList.addAssign_operation (enumerator_4411.current_mOutletType (HERE).reader_string (SOURCE_FILE_AT_LINE (145)), var_generationKind, enumerator_4411.current_mOutletName (HERE).reader_string (SOURCE_FILE_AT_LINE (145)), var_outletBindingList COMMA_SOURCE_FILE_AT_LINE (145)) ;
    enumerator_4411.gotoNextObject () ;
  }
  { //-------- @modifierCallInstructionForGeneration
  var_implementationFileInclusionSet.modifier_removeKey (GALGAS_string::makeEmptyString () COMMA_SOURCE_FILE_AT_LINE (148)) ;
  } //-------- END @typeMethodInstructionForGeneration
  { //-------- @modifierCallInstructionForGeneration
  ioArgument_ioPreferencesMap.modifier_insertKey (constinArgument_inPreference.mAttribute_mPreferencesName, var_attributeListForImplementation, var_transientListForImplementation, var_outletGenerationList, constinArgument_inPreference.mAttribute_mActionDeclarationList, var_observableAttributeMap, var_headerFileInclusionSet, var_implementationFileInclusionSet, var_controllerMap, var_preferenceArrayMap, inCompiler COMMA_SOURCE_FILE_AT_LINE (149)) ;
  } //-------- END @typeMethodInstructionForGeneration
}


//---------------------------------------------------------------------------*
//                                                                           *
//                       Routine 'analyzePreferences'                        *
//                                                                           *
//---------------------------------------------------------------------------*

void routine_analyzePreferences (const GALGAS_preferencesDeclarationList constinArgument_inPreferencesList,
                                 const GALGAS_controllerClassMap constinArgument_inControllerClassMap,
                                 const GALGAS_classMap constinArgument_inClassMap,
                                 const GALGAS_outletClassMap constinArgument_inOutletClassMap,
                                 const GALGAS_globalEnumConstantMap constinArgument_inGlobalEnumConstantMap,
                                 GALGAS_preferencesMap & outArgument_outPreferencesMap,
                                 GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                 C_Compiler * inCompiler
                                 COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outPreferencesMap.drop () ; // Release 'out' argument
  //-------- @assignmentInstructionForGeneration
  outArgument_outPreferencesMap = GALGAS_preferencesMap::constructor_emptyMap (SOURCE_FILE_AT_LINE (174)) ;
  //-------- @foreachInstructionForGeneration
  cEnumerator_preferencesDeclarationList enumerator_6362 (constinArgument_inPreferencesList, kEnumeration_up) ;
  //--- simple foreach instruction
  while (enumerator_6362.hasCurrentObject ()) {
    { //-------- @routineCallInstructionForGeneration
    routine_analyzePreference (enumerator_6362.current (HERE), constinArgument_inControllerClassMap, constinArgument_inClassMap, constinArgument_inOutletClassMap, constinArgument_inGlobalEnumConstantMap, outArgument_outPreferencesMap, ioArgument_ioTransientDependencyGraph, inCompiler COMMA_SOURCE_FILE_AT_LINE (176)) ;
    } //-------- @routineCallInstructionForGeneration
    enumerator_6362.gotoNextObject () ;
  }
}


//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


