//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                            File 'transientAnalysis.cpp'                                             *
//                                             Generated by version 3.0.0                                              *
//                                         september 12th, 2014, at 22h6'58"                                           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "transientAnalysis.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                       Routine 'buildTransientDependencyGraph'                                       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_buildTransientDependencyGraph (const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                            const GALGAS_string constinArgument_inSourceFile,
                                            GALGAS_transientDependencyGraphNodeInfoList & outArgument_outSortedTransientNodes,
                                            C_Compiler * inCompiler
                                            COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outSortedTransientNodes.drop () ; // Release 'out' argument
  GALGAS_transientDependencyGraph var_transientDependencyGraph = GALGAS_transientDependencyGraph::constructor_emptyGraph (SOURCE_FILE ("transientAnalysis.gSemantics", 223)) ;
  cEnumerator_unifiedTypeMap enumerator_7434 (constinArgument_inUnifiedTypeMap, kEnumeration_up) ;
  while (enumerator_7434.hasCurrentObject ()) {
    cEnumerator_decoratedObservablePropertyMap enumerator_7489 (enumerator_7434.current_mObservablePropertyMap (HERE), kEnumeration_up) ;
    while (enumerator_7489.hasCurrentObject ()) {
      {
      var_transientDependencyGraph.modifier_addNode (enumerator_7489.current_mPropertySignature (HERE), enumerator_7489.current_mPropertySignature (HERE).mAttribute_string, enumerator_7489.current_mIsTransient (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 226)) ;
      }
      enumerator_7489.gotoNextObject () ;
    }
    cEnumerator_arrayControllerMap enumerator_7727 (enumerator_7434.current_mArrayControllerMap (HERE), kEnumeration_up) ;
    while (enumerator_7727.hasCurrentObject ()) {
      {
      var_transientDependencyGraph.modifier_addNode (enumerator_7727.current_mPropertySignature (HERE), enumerator_7727.current_mPropertySignature (HERE).mAttribute_string, GALGAS_bool (true), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 233)) ;
      }
      {
      var_transientDependencyGraph.modifier_addEdge (callCategoryReader_propertySignature ((const cPtr_abstractObservablePropertyAST *) enumerator_7727.current_mBoundModel (HERE).ptr (), categoryReader_kindName (enumerator_7434.current_mTypeKind (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 241)), enumerator_7434.current_lkey (HERE).mAttribute_string, enumerator_7434.current_mRootEntityType (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 240)), enumerator_7727.current_mPropertySignature (HERE) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 239)) ;
      }
      enumerator_7727.gotoNextObject () ;
    }
    cEnumerator_decoratedTransientMap enumerator_8297 (enumerator_7434.current_mDecoratedTransientMap (HERE), kEnumeration_up) ;
    while (enumerator_8297.hasCurrentObject ()) {
      GALGAS_decoratedObservablePropertyMap var_allObservableProperties = enumerator_7434.current_mObservablePropertyMap (HERE) ;
      GALGAS_unifiedTypeProxy var_t = enumerator_7434.current_mSuperType (HERE) ;
      if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 251)).isValid ()) {
        uint32_t variant_8453 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 251)).uintValue () ;
        bool loop_8453 = true ;
        while (loop_8453) {
          loop_8453 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 251)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 251)).isValid () ;
          if (loop_8453) {
            loop_8453 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 251)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 251)).boolValue () ;
          }
          if (loop_8453 && (0 == variant_8453)) {
            loop_8453 = false ;
            inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 251)) ;
          }
          if (loop_8453) {
            variant_8453 -- ;
            cEnumerator_decoratedObservablePropertyMap enumerator_8556 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 252)), kEnumeration_up) ;
            while (enumerator_8556.hasCurrentObject ()) {
              {
              var_allObservableProperties.modifier_insertKey (enumerator_8556.current_lkey (HERE), enumerator_8556.current_mPropertyType (HERE), enumerator_8556.current_mIsTransient (HERE), enumerator_8556.current_mPropertySignature (HERE), enumerator_8556.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 253)) ;
              }
              enumerator_8556.gotoNextObject () ;
            }
            var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 261)) ;
          }
        }
      }
      cEnumerator_dependanceList enumerator_8887 (enumerator_8297.current_mDependencyList (HERE), kEnumeration_up) ;
      while (enumerator_8887.hasCurrentObject ()) {
        callCategoryMethod_buildTransientDependencyGraph ((const cPtr_abstractTransientDependencyAST *) enumerator_8887.current_mDependency (HERE).ptr (), constinArgument_inUnifiedTypeMap, var_transientDependencyGraph, enumerator_8297.current_lkey (HERE), var_allObservableProperties, enumerator_7434.current_mRootEntityType (HERE), enumerator_7434.current_mArrayControllerMap (HERE), enumerator_8297.current_mTransientSignature (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 264)) ;
        enumerator_8887.gotoNextObject () ;
      }
      enumerator_8297.gotoNextObject () ;
    }
    enumerator_7434.gotoNextObject () ;
  }
  const enumGalgasBool test_0 = GALGAS_bool (kIsEqual, GALGAS_uint::constructor_errorCount (SOURCE_FILE ("transientAnalysis.gSemantics", 277)).objectCompare (GALGAS_uint ((uint32_t) 0U))).operator_and (GALGAS_bool (gOption_easyBindings_5F_options_outputTransientDependencyGraph.reader_value ()) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 277)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_string var_s = var_transientDependencyGraph.reader_graphviz (SOURCE_FILE ("transientAnalysis.gSemantics", 278)) ;
    GALGAS_string var_path = constinArgument_inSourceFile.operator_concat (GALGAS_string (".transientDependancyGraph.dot")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 279)) ;
    GALGAS_bool joker_9571_0 ; // Joker input parameter
    var_s.method_writeToFileWhenDifferentContents (var_path, joker_9571_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 280)) ;
  }
  const enumGalgasBool test_1 = GALGAS_bool (kIsNotEqual, GALGAS_uint::constructor_errorCount (SOURCE_FILE ("transientAnalysis.gSemantics", 283)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_1) {
    outArgument_outSortedTransientNodes = GALGAS_transientDependencyGraphNodeInfoList::constructor_emptyList (SOURCE_FILE ("transientAnalysis.gSemantics", 284)) ;
  }else if (kBoolFalse == test_1) {
    GALGAS_transientDependencyGraphNodeInfoList var_unsortedNodes ;
    GALGAS_lstringlist joker_9816_0 ; // Joker input parameter
    GALGAS_lstringlist joker_9884_0 ; // Joker input parameter
    var_transientDependencyGraph.method_topologicalSort (outArgument_outSortedTransientNodes, joker_9816_0, var_unsortedNodes, joker_9884_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 286)) ;
    const enumGalgasBool test_2 = GALGAS_bool (kIsStrictSup, var_unsortedNodes.reader_length (SOURCE_FILE ("transientAnalysis.gSemantics", 292)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
    if (kBoolTrue == test_2) {
      GALGAS_string var_s = GALGAS_string ("cannot sort properties and transient ; the following ones are involved in circular dependence:") ;
      cEnumerator_transientDependencyGraphNodeInfoList enumerator_10074 (var_unsortedNodes, kEnumeration_up) ;
      while (enumerator_10074.hasCurrentObject ()) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "-- ").operator_concat (enumerator_10074.current_mSignature (HERE)  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 295))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 295)) ;
        enumerator_10074.gotoNextObject () ;
      }
      inCompiler->emitSemanticError (inCompiler->here (), var_s  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 297)) ;
    }
  }
}


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//              Abstract category method '@abstractTransientDependencyAST buildTransientDependencyGraph'               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static TC_UniqueArray <categoryMethodSignature_abstractTransientDependencyAST_buildTransientDependencyGraph> gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryMethod_buildTransientDependencyGraph (const int32_t inClassIndex,
                                                        categoryMethodSignature_abstractTransientDependencyAST_buildTransientDependencyGraph inMethod) {
  gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph.forceObjectAtIndex (inClassIndex, inMethod, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------------------------------------------------*

static void freeCategoryMethod_abstractTransientDependencyAST_buildTransientDependencyGraph (void) {
  gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph.free () ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_abstractTransientDependencyAST_buildTransientDependencyGraph (NULL,
                                                                                         freeCategoryMethod_abstractTransientDependencyAST_buildTransientDependencyGraph) ;

//---------------------------------------------------------------------------------------------------------------------*

void callCategoryMethod_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * inObject,
                                                       const GALGAS_unifiedTypeMap constin_inUnifiedTypeMap,
                                                       GALGAS_transientDependencyGraph & io_ioTransientDependencyGraph,
                                                       const GALGAS_lstring constin_inTransientName,
                                                       const GALGAS_decoratedObservablePropertyMap constin_inLocalObservablePropertyMap,
                                                       const GALGAS_unifiedTypeProxy constin_inRootEntityType,
                                                       const GALGAS_arrayControllerMap constin_inArrayControllerMap,
                                                       const GALGAS_lstring constin_inTransientPropertySignature,
                                                       C_Compiler * inCompiler
                                                       COMMA_LOCATION_ARGS) {
//--- Drop output arguments
//--- Find method
  if (NULL != inObject) {
    macroValidSharedObject (inObject, cPtr_abstractTransientDependencyAST) ;
    const C_galgas_type_descriptor * info = inObject->classDescriptor () ;
    const int32_t classIndex = info->mSlotID ;
    categoryMethodSignature_abstractTransientDependencyAST_buildTransientDependencyGraph f = NULL ;
    if (classIndex < gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph.count ()) {
      f = gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph (classIndex COMMA_HERE) ;
    }
    if (NULL == f) {
       const C_galgas_type_descriptor * p = info->mSuperclassDescriptor ;
       while ((NULL == f) && (NULL != p)) {
         if (p->mSlotID < gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph.count ()) {
           f = gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph (p->mSlotID COMMA_HERE) ;
         }
         p = p->mSuperclassDescriptor ;
       }
       gCategoryMethodTable_abstractTransientDependencyAST_buildTransientDependencyGraph.forceObjectAtIndex (classIndex, f, NULL COMMA_HERE) ;
    }
    if (NULL == f) {
      fatalError ("FATAL CATEGORY METHOD CALL ERROR", __FILE__, __LINE__) ;
    }else{
      f (inObject, constin_inUnifiedTypeMap, io_ioTransientDependencyGraph, constin_inTransientName, constin_inLocalObservablePropertyMap, constin_inRootEntityType, constin_inArrayControllerMap, constin_inTransientPropertySignature, inCompiler COMMA_THERE) ;
    }
  }
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//             Overriding category method '@transientRootSignDependencyAST buildTransientDependencyGraph'              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootSignDependencyAST_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * /* inObject */,
                                                                                         const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                         GALGAS_transientDependencyGraph & /* ioArgument_ioTransientDependencyGraph */,
                                                                                         const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                         const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                         const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                         const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                         const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                         C_Compiler * /* inCompiler */
                                                                                         COMMA_UNUSED_LOCATION_ARGS) {
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootSignDependencyAST_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientRootSignDependencyAST.mSlotID,
                                                     categoryMethod_transientRootSignDependencyAST_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootSignDependencyAST_buildTransientDependencyGraph (defineCategoryMethod_transientRootSignDependencyAST_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category method '@transientLocalDependencyAST buildTransientDependencyGraph'               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientLocalDependencyAST_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                      const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                      GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                      const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                      const GALGAS_decoratedObservablePropertyMap constinArgument_inLocalObservablePropertyMap,
                                                                                      const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                      const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                      const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                      C_Compiler * inCompiler
                                                                                      COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientLocalDependencyAST * object = (const cPtr_transientLocalDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependencyAST) ;
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_1832_0 ; // Joker input parameter
  constinArgument_inLocalObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_1832_0, var_masterPropertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 43)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 51)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientLocalDependencyAST_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientLocalDependencyAST.mSlotID,
                                                     categoryMethod_transientLocalDependencyAST_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientLocalDependencyAST_buildTransientDependencyGraph (defineCategoryMethod_transientLocalDependencyAST_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//            Overriding category method '@transientControllerDependencyAST buildTransientDependencyGraph'             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientControllerDependencyAST_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                           const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                           GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                           const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                           const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                           const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                           const GALGAS_arrayControllerMap constinArgument_inArrayControllerMap,
                                                                                           const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                           C_Compiler * inCompiler
                                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientControllerDependencyAST * object = (const cPtr_transientControllerDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientControllerDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_controllerObservablePropertyMap ;
  GALGAS_abstractObservablePropertyAST joker_2613_4 ; // Joker input parameter
  GALGAS_lstring joker_2613_3 ; // Joker input parameter
  GALGAS_arrayControllerBoundColumnListAST joker_2613_2 ; // Joker input parameter
  GALGAS_actionMap joker_2613_1 ; // Joker input parameter
  GALGAS_lstring joker_2691_0 ; // Joker input parameter
  constinArgument_inArrayControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_2613_4, joker_2613_3, joker_2613_2, joker_2613_1, var_controllerObservablePropertyMap, joker_2691_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 68)) ;
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_unifiedTypeProxy joker_2771_0 ; // Joker input parameter
  GALGAS_bool joker_2778_0 ; // Joker input parameter
  GALGAS_bool joker_2823_0 ; // Joker input parameter
  var_controllerObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, joker_2771_0, joker_2778_0, var_masterPropertySignature, joker_2823_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 75)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 83)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientControllerDependencyAST_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientControllerDependencyAST.mSlotID,
                                                     categoryMethod_transientControllerDependencyAST_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientControllerDependencyAST_buildTransientDependencyGraph (defineCategoryMethod_transientControllerDependencyAST_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category method '@transientRootDependencyAST buildTransientDependencyGraph'                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootDependencyAST_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                     const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                     GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                     const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                     const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                     const GALGAS_unifiedTypeProxy constinArgument_inRootEntityType,
                                                                                     const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                     const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                     C_Compiler * inCompiler
                                                                                     COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientRootDependencyAST * object = (const cPtr_transientRootDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_allObservablePropertyMap = constinArgument_inRootEntityType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 101)) ;
  GALGAS_unifiedTypeProxy var_t = constinArgument_inRootEntityType.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 102)) ;
  if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 103)).isValid ()) {
    uint32_t variant_3668 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 103)).uintValue () ;
    bool loop_3668 = true ;
    while (loop_3668) {
      loop_3668 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 103)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 103)).isValid () ;
      if (loop_3668) {
        loop_3668 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 103)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 103)).boolValue () ;
      }
      if (loop_3668 && (0 == variant_3668)) {
        loop_3668 = false ;
        inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 103)) ;
      }
      if (loop_3668) {
        variant_3668 -- ;
        cEnumerator_decoratedObservablePropertyMap enumerator_3767 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 104)), kEnumeration_up) ;
        while (enumerator_3767.hasCurrentObject ()) {
          {
          var_allObservablePropertyMap.modifier_insertKey (enumerator_3767.current_lkey (HERE), enumerator_3767.current_mPropertyType (HERE), enumerator_3767.current_mIsTransient (HERE), enumerator_3767.current_mPropertySignature (HERE), enumerator_3767.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 105)) ;
          }
          enumerator_3767.gotoNextObject () ;
        }
        var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 113)) ;
      }
    }
  }
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_bool var_isCollection ;
  GALGAS_unifiedTypeProxy joker_4078_0 ; // Joker input parameter
  GALGAS_bool joker_4085_0 ; // Joker input parameter
  var_allObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, joker_4078_0, joker_4085_0, var_masterPropertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 115)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 123)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootDependencyAST_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientRootDependencyAST.mSlotID,
                                                     categoryMethod_transientRootDependencyAST_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootDependencyAST_buildTransientDependencyGraph (defineCategoryMethod_transientRootDependencyAST_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//         Overriding category method '@transientRootRelationshipDependencyAST buildTransientDependencyGraph'          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootRelationshipDependencyAST_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                                 const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                                 GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                                 const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                                 const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                                 const GALGAS_unifiedTypeProxy constinArgument_inRootEntityType,
                                                                                                 const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                                 const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                                 C_Compiler * inCompiler
                                                                                                 COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientRootRelationshipDependencyAST * object = (const cPtr_transientRootRelationshipDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootRelationshipDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_allObservablePropertyMap = constinArgument_inRootEntityType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 141)) ;
  GALGAS_unifiedTypeProxy var_t = constinArgument_inRootEntityType.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 142)) ;
  if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 143)).isValid ()) {
    uint32_t variant_5004 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 143)).uintValue () ;
    bool loop_5004 = true ;
    while (loop_5004) {
      loop_5004 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 143)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 143)).isValid () ;
      if (loop_5004) {
        loop_5004 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 143)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 143)).boolValue () ;
      }
      if (loop_5004 && (0 == variant_5004)) {
        loop_5004 = false ;
        inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 143)) ;
      }
      if (loop_5004) {
        variant_5004 -- ;
        cEnumerator_decoratedObservablePropertyMap enumerator_5103 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 144)), kEnumeration_up) ;
        while (enumerator_5103.hasCurrentObject ()) {
          {
          var_allObservablePropertyMap.modifier_insertKey (enumerator_5103.current_lkey (HERE), enumerator_5103.current_mPropertyType (HERE), enumerator_5103.current_mIsTransient (HERE), enumerator_5103.current_mPropertySignature (HERE), enumerator_5103.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 145)) ;
          }
          enumerator_5103.gotoNextObject () ;
        }
        var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 153)) ;
      }
    }
  }
  GALGAS_unifiedTypeProxy var_relationshipElementType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_5468_0 ; // Joker input parameter
  GALGAS_lstring joker_5475_0 ; // Joker input parameter
  var_allObservablePropertyMap.method_searchKey (object->mAttribute_mRelationshipName, var_relationshipElementType, joker_5468_0, joker_5475_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 155)) ;
  const enumGalgasBool test_0 = var_isCollection.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 162)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mRelationshipName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("this property should be a tomany relationship")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 163)) ;
  }
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_unifiedTypeProxy joker_5709_0 ; // Joker input parameter
  GALGAS_bool joker_5716_0 ; // Joker input parameter
  var_relationshipElementType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 165)).method_searchKey (object->mAttribute_mMasterName, joker_5709_0, joker_5716_0, var_masterPropertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 165)) ;
  const enumGalgasBool test_2 = var_isCollection.boolEnum () ;
  if (kBoolTrue == test_2) {
    GALGAS_location location_3 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_3, GALGAS_string ("this property should not be a collection")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 173)) ;
  }
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 176)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootRelationshipDependencyAST_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientRootRelationshipDependencyAST.mSlotID,
                                                     categoryMethod_transientRootRelationshipDependencyAST_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootRelationshipDependencyAST_buildTransientDependencyGraph (defineCategoryMethod_transientRootRelationshipDependencyAST_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//            Overriding category method '@transientPreferenceDependencyAST buildTransientDependencyGraph'             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientPreferenceDependencyAST_buildTransientDependencyGraph (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                           const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                           GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                           const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                           const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                           const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                           const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                           const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                           C_Compiler * inCompiler
                                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientPreferenceDependencyAST * object = (const cPtr_transientPreferenceDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_observablePropertyMap ;
  GALGAS_typeKind joker_6635_0 ; // Joker input parameter
  GALGAS_unifiedTypeProxy joker_6659_5 ; // Joker input parameter
  GALGAS_unifiedTypeProxy joker_6659_4 ; // Joker input parameter
  GALGAS_decoratedAttributeMap joker_6659_3 ; // Joker input parameter
  GALGAS_decoratedTransientMap joker_6659_2 ; // Joker input parameter
  GALGAS_decoratedOutletMap joker_6659_1 ; // Joker input parameter
  GALGAS_decoratedEntityRelationshipMap joker_6727_6 ; // Joker input parameter
  GALGAS_actionMap joker_6727_5 ; // Joker input parameter
  GALGAS_bindingList joker_6727_4 ; // Joker input parameter
  GALGAS_lstringlist joker_6727_3 ; // Joker input parameter
  GALGAS_enumConstantMap joker_6727_2 ; // Joker input parameter
  GALGAS_arrayControllerMap joker_6727_1 ; // Joker input parameter
  constinArgument_inUnifiedTypeMap.method_searchKey (object->mAttribute_mPreferencesName, joker_6635_0, joker_6659_5, joker_6659_4, joker_6659_3, joker_6659_2, joker_6659_1, var_observablePropertyMap, joker_6727_6, joker_6727_5, joker_6727_4, joker_6727_3, joker_6727_2, joker_6727_1, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 194)) ;
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_unifiedTypeProxy joker_6798_2 ; // Joker input parameter
  GALGAS_bool joker_6798_1 ; // Joker input parameter
  GALGAS_bool joker_6845_0 ; // Joker input parameter
  var_observablePropertyMap.method_searchKey (object->mAttribute_mMasterName, joker_6798_2, joker_6798_1, var_masterPropertySignature, joker_6845_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 202)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 209)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientPreferenceDependencyAST_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientPreferenceDependencyAST.mSlotID,
                                                     categoryMethod_transientPreferenceDependencyAST_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientPreferenceDependencyAST_buildTransientDependencyGraph (defineCategoryMethod_transientPreferenceDependencyAST_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//          Overriding category method '@transientRootSignDependencyAST transientDependencySemanticAnalysis'           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootSignDependencyAST_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependencyAST * /* inObject */,
                                                                                               const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                               const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                               const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                               const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                               const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                               const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                               GALGAS_transientDependencyListForGeneration & /* ioArgument_ioTransientDependencyListForGeneration */,
                                                                                               C_Compiler * /* inCompiler */
                                                                                               COMMA_UNUSED_LOCATION_ARGS) {
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootSignDependencyAST_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientRootSignDependencyAST.mSlotID,
                                                           categoryMethod_transientRootSignDependencyAST_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootSignDependencyAST_transientDependencySemanticAnalysis (defineCategoryMethod_transientRootSignDependencyAST_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//            Overriding category method '@transientLocalDependencyAST transientDependencySemanticAnalysis'            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientLocalDependencyAST_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                            const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                            const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                            const GALGAS_decoratedObservablePropertyMap constinArgument_inAllObservablePropertyMap,
                                                                                            const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                            const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                            const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                            GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                            C_Compiler * inCompiler
                                                                                            COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientLocalDependencyAST * object = (const cPtr_transientLocalDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependencyAST) ;
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_11509_0 ; // Joker input parameter
  GALGAS_lstring joker_11516_0 ; // Joker input parameter
  constinArgument_inAllObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_11509_0, joker_11516_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 328)) ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.operator_and (var_isCollection.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 335)) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 335)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("the 'count' option is only allowed for to-many relationships")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 336)) ;
  }else if (kBoolFalse == test_0) {
    const enumGalgasBool test_2 = var_isCollection.operator_and (object->mAttribute_mNamesCountOption.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 337)) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 337)).boolEnum () ;
    if (kBoolTrue == test_2) {
      GALGAS_location location_3 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_3, GALGAS_string ("to-many relationships requires the 'count' option")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 338)) ;
    }
  }
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (categoryReader_transientFormalArgumentTypeName (var_masterType, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 340)), object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 340)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientLocalDependencyAST_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientLocalDependencyAST.mSlotID,
                                                           categoryMethod_transientLocalDependencyAST_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientLocalDependencyAST_transientDependencySemanticAnalysis (defineCategoryMethod_transientLocalDependencyAST_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//         Overriding category method '@transientControllerDependencyAST transientDependencySemanticAnalysis'          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientControllerDependencyAST_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                                 const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                                 const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                                 const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                                 const GALGAS_arrayControllerMap constinArgument_inArrayControllerMap,
                                                                                                 const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                                 const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                                 GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                                 C_Compiler * inCompiler
                                                                                                 COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientControllerDependencyAST * object = (const cPtr_transientControllerDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientControllerDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_arrayControllerObservablePropertyMap ;
  GALGAS_abstractObservablePropertyAST joker_12581_4 ; // Joker input parameter
  GALGAS_lstring joker_12581_3 ; // Joker input parameter
  GALGAS_arrayControllerBoundColumnListAST joker_12581_2 ; // Joker input parameter
  GALGAS_actionMap joker_12581_1 ; // Joker input parameter
  GALGAS_lstring joker_12664_0 ; // Joker input parameter
  constinArgument_inArrayControllerMap.method_searchKey (object->mAttribute_mControllerName, joker_12581_4, joker_12581_3, joker_12581_2, joker_12581_1, var_arrayControllerObservablePropertyMap, joker_12664_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 354)) ;
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool joker_12779_0 ; // Joker input parameter
  GALGAS_lstring joker_12786_0 ; // Joker input parameter
  GALGAS_bool joker_12793_0 ; // Joker input parameter
  var_arrayControllerObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_12779_0, joker_12786_0, joker_12793_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 360)) ;
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (categoryReader_transientFormalArgumentTypeName (var_masterType, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 368)), object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 368)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientControllerDependencyAST_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientControllerDependencyAST.mSlotID,
                                                           categoryMethod_transientControllerDependencyAST_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientControllerDependencyAST_transientDependencySemanticAnalysis (defineCategoryMethod_transientControllerDependencyAST_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//            Overriding category method '@transientRootDependencyAST transientDependencySemanticAnalysis'             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootDependencyAST_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                           const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                           const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                           const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                           const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                           const GALGAS_unifiedTypeProxy constinArgument_inRootEntityType,
                                                                                           const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                           GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                           C_Compiler * inCompiler
                                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientRootDependencyAST * object = (const cPtr_transientRootDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_allObservablePropertyMap = constinArgument_inRootEntityType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 383)) ;
  GALGAS_unifiedTypeProxy var_t = constinArgument_inRootEntityType.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 384)) ;
  if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 385)).isValid ()) {
    uint32_t variant_13658 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 385)).uintValue () ;
    bool loop_13658 = true ;
    while (loop_13658) {
      loop_13658 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 385)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 385)).isValid () ;
      if (loop_13658) {
        loop_13658 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 385)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 385)).boolValue () ;
      }
      if (loop_13658 && (0 == variant_13658)) {
        loop_13658 = false ;
        inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 385)) ;
      }
      if (loop_13658) {
        variant_13658 -- ;
        cEnumerator_decoratedObservablePropertyMap enumerator_13757 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 386)), kEnumeration_up) ;
        while (enumerator_13757.hasCurrentObject ()) {
          {
          var_allObservablePropertyMap.modifier_insertKey (enumerator_13757.current_lkey (HERE), enumerator_13757.current_mPropertyType (HERE), enumerator_13757.current_mIsTransient (HERE), enumerator_13757.current_mPropertySignature (HERE), enumerator_13757.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 387)) ;
          }
          enumerator_13757.gotoNextObject () ;
        }
        var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 395)) ;
      }
    }
  }
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_14103_0 ; // Joker input parameter
  GALGAS_lstring joker_14110_0 ; // Joker input parameter
  var_allObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_14103_0, joker_14110_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 397)) ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.operator_and (var_isCollection.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 405)) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 405)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("the 'count' option is only allowed for to-many relationships")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 406)) ;
  }
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (categoryReader_transientFormalArgumentTypeName (var_masterType, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 409)), object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 409)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootDependencyAST_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientRootDependencyAST.mSlotID,
                                                           categoryMethod_transientRootDependencyAST_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootDependencyAST_transientDependencySemanticAnalysis (defineCategoryMethod_transientRootDependencyAST_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//      Overriding category method '@transientRootRelationshipDependencyAST transientDependencySemanticAnalysis'       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootRelationshipDependencyAST_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                                       const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                                       const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                                       const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                                       const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                                       const GALGAS_unifiedTypeProxy constinArgument_inRootEntityType,
                                                                                                       const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                                       GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                                       C_Compiler * inCompiler
                                                                                                       COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientRootRelationshipDependencyAST * object = (const cPtr_transientRootRelationshipDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootRelationshipDependencyAST) ;
  GALGAS_decoratedObservablePropertyMap var_allObservablePropertyMap = constinArgument_inRootEntityType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 424)) ;
  GALGAS_unifiedTypeProxy var_t = constinArgument_inRootEntityType.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 425)) ;
  if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 426)).isValid ()) {
    uint32_t variant_15183 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 426)).uintValue () ;
    bool loop_15183 = true ;
    while (loop_15183) {
      loop_15183 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 426)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 426)).isValid () ;
      if (loop_15183) {
        loop_15183 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 426)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 426)).boolValue () ;
      }
      if (loop_15183 && (0 == variant_15183)) {
        loop_15183 = false ;
        inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 426)) ;
      }
      if (loop_15183) {
        variant_15183 -- ;
        cEnumerator_decoratedObservablePropertyMap enumerator_15282 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 427)), kEnumeration_up) ;
        while (enumerator_15282.hasCurrentObject ()) {
          {
          var_allObservablePropertyMap.modifier_insertKey (enumerator_15282.current_lkey (HERE), enumerator_15282.current_mPropertyType (HERE), enumerator_15282.current_mIsTransient (HERE), enumerator_15282.current_mPropertySignature (HERE), enumerator_15282.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 428)) ;
          }
          enumerator_15282.gotoNextObject () ;
        }
        var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 436)) ;
      }
    }
  }
  GALGAS_unifiedTypeProxy var_relationshipElementType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_15647_0 ; // Joker input parameter
  GALGAS_lstring joker_15654_0 ; // Joker input parameter
  var_allObservablePropertyMap.method_searchKey (object->mAttribute_mRelationshipName, var_relationshipElementType, joker_15647_0, joker_15654_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 438)) ;
  const enumGalgasBool test_0 = var_isCollection.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 445)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mRelationshipName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("this property should be a tomany relationship")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 446)) ;
  }
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_unifiedTypeProxy joker_15888_2 ; // Joker input parameter
  GALGAS_bool joker_15888_1 ; // Joker input parameter
  var_relationshipElementType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 448)).method_searchKey (object->mAttribute_mMasterName, joker_15888_2, joker_15888_1, var_masterPropertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 448)) ;
  const enumGalgasBool test_2 = var_isCollection.boolEnum () ;
  if (kBoolTrue == test_2) {
    GALGAS_location location_3 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_3, GALGAS_string ("this property should not be a collection")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 455)) ;
  }
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (GALGAS_string ("[").add_operation (var_relationshipElementType.reader_key (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458)), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458)).add_operation (GALGAS_string ("_"), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458)).add_operation (object->mAttribute_mMasterName.reader_string (SOURCE_FILE ("transientAnalysis.gSemantics", 458)), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458)).add_operation (GALGAS_string ("]"), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458)), GALGAS_string ("arrayOf_").add_operation (object->mAttribute_mMasterName.reader_string (SOURCE_FILE ("transientAnalysis.gSemantics", 458)), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 458)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootRelationshipDependencyAST_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientRootRelationshipDependencyAST.mSlotID,
                                                           categoryMethod_transientRootRelationshipDependencyAST_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootRelationshipDependencyAST_transientDependencySemanticAnalysis (defineCategoryMethod_transientRootRelationshipDependencyAST_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//         Overriding category method '@transientPreferenceDependencyAST transientDependencySemanticAnalysis'          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientPreferenceDependencyAST_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependencyAST * inObject,
                                                                                                 const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                                 const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                                 const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                                 const GALGAS_arrayControllerMap /* constinArgument_inArrayControllerMap */,
                                                                                                 const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                                 const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                                 GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                                 C_Compiler * inCompiler
                                                                                                 COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientPreferenceDependencyAST * object = (const cPtr_transientPreferenceDependencyAST *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependencyAST) ;
  GALGAS_typeKind var_kind ;
  GALGAS_decoratedObservablePropertyMap var_observablePropertyMap ;
  GALGAS_unifiedTypeProxy joker_16871_5 ; // Joker input parameter
  GALGAS_unifiedTypeProxy joker_16871_4 ; // Joker input parameter
  GALGAS_decoratedAttributeMap joker_16871_3 ; // Joker input parameter
  GALGAS_decoratedTransientMap joker_16871_2 ; // Joker input parameter
  GALGAS_decoratedOutletMap joker_16871_1 ; // Joker input parameter
  GALGAS_decoratedEntityRelationshipMap joker_16939_6 ; // Joker input parameter
  GALGAS_actionMap joker_16939_5 ; // Joker input parameter
  GALGAS_bindingList joker_16939_4 ; // Joker input parameter
  GALGAS_lstringlist joker_16939_3 ; // Joker input parameter
  GALGAS_enumConstantMap joker_16939_2 ; // Joker input parameter
  GALGAS_arrayControllerMap joker_16939_1 ; // Joker input parameter
  constinArgument_inUnifiedTypeMap.method_searchKey (object->mAttribute_mPreferencesName, var_kind, joker_16871_5, joker_16871_4, joker_16871_3, joker_16871_2, joker_16871_1, var_observablePropertyMap, joker_16939_6, joker_16939_5, joker_16939_4, joker_16939_3, joker_16939_2, joker_16939_1, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 473)) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_preferencesType (SOURCE_FILE ("transientAnalysis.gSemantics", 481)))).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mPreferencesName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("'").operator_concat (object->mAttribute_mPreferencesName.reader_string (SOURCE_FILE ("transientAnalysis.gSemantics", 482))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 482)).operator_concat (GALGAS_string ("' is not a preference")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 482))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 482)) ;
  }
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool joker_17193_0 ; // Joker input parameter
  GALGAS_lstring joker_17200_0 ; // Joker input parameter
  GALGAS_bool joker_17243_0 ; // Joker input parameter
  var_observablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_17193_0, joker_17200_0, joker_17243_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 485)) ;
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (categoryReader_transientFormalArgumentTypeName (var_masterType, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 492)), object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 492)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientPreferenceDependencyAST_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientPreferenceDependencyAST.mSlotID,
                                                           categoryMethod_transientPreferenceDependencyAST_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientPreferenceDependencyAST_transientDependencySemanticAnalysis (defineCategoryMethod_transientPreferenceDependencyAST_transientDependencySemanticAnalysis, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


