//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                           File 'transientGeneration.cpp'                                            *
//                                             Generated by version 3.0.0                                              *
//                                         september 10th, 2014, at 19h24'0"                                           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "transientGeneration.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                            Routine 'generateTransients'                                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_generateTransients (const GALGAS_string constinArgument_inSourceFile,
                                 const GALGAS_transientDependencyGraphNodeInfoList constinArgument_inSortedTransientNodes,
                                 const GALGAS_transientListForGeneration constinArgument_inTransientListForGeneration,
                                 C_Compiler * inCompiler
                                 COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_stringlist var_transientList = GALGAS_stringlist::constructor_emptyList (SOURCE_FILE ("transientGeneration.gSemantics", 63)) ;
  cEnumerator_transientDependencyGraphNodeInfoList enumerator_2600 (constinArgument_inSortedTransientNodes, kEnumeration_up) ;
  while (enumerator_2600.hasCurrentObject ()) {
    const enumGalgasBool test_0 = enumerator_2600.current_mIsTransient (HERE).boolEnum () ;
    if (kBoolTrue == test_0) {
      var_transientList.addAssign_operation (enumerator_2600.current_mSignature (HERE)  COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 66)) ;
    }
    enumerator_2600.gotoNextObject () ;
  }
  GALGAS_string var_s = GALGAS_string (filewrapperTemplate_transientManager_applicationInSwift (inCompiler, constinArgument_inSortedTransientNodes, var_transientList COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 69))) ;
  {
  GALGAS_string::class_method_generateFileWithPattern (constinArgument_inSourceFile.reader_stringByDeletingLastPathComponent (SOURCE_FILE ("transientGeneration.gSemantics", 74)), GALGAS_string ("PMApplication.swift"), GALGAS_string ("//"), GALGAS_string ("\n"
    "\n"), var_s, GALGAS_string ("\n"
    "\n"), GALGAS_string::makeEmptyString (), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 73)) ;
  }
  cEnumerator_transientListForGeneration enumerator_3122 (constinArgument_inTransientListForGeneration, kEnumeration_up) ;
  while (enumerator_3122.hasCurrentObject ()) {
    GALGAS_stringlist var_decomposedTransientSignature = enumerator_3122.current_mTransientSignature (HERE).reader_componentsSeparatedByString (GALGAS_string (".") COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 84)) ;
    GALGAS_string var_s = GALGAS_string (filewrapperTemplate_transientManager_transientComputationFunctionFile (inCompiler, var_decomposedTransientSignature.reader_mValueAtIndex (GALGAS_uint ((uint32_t) 1U), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 86)), var_decomposedTransientSignature.reader_mValueAtIndex (GALGAS_uint ((uint32_t) 2U), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 87)), enumerator_3122.current_mTransientDependencyListForGeneration (HERE), enumerator_3122.current_mTransientType (HERE) COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 85))) ;
    GALGAS_string var_fileName = var_decomposedTransientSignature.reader_mValueAtIndex (GALGAS_uint ((uint32_t) 1U), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 91)).add_operation (GALGAS_string ("+transient+"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 91)).add_operation (var_decomposedTransientSignature.reader_mValueAtIndex (GALGAS_uint ((uint32_t) 2U), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 91)), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 91)).add_operation (GALGAS_string (".swift"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 91)) ;
    {
    GALGAS_string::class_method_generateFileWithPattern (constinArgument_inSourceFile.reader_stringByDeletingLastPathComponent (SOURCE_FILE ("transientGeneration.gSemantics", 93)), var_fileName, GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_s, GALGAS_string ("\n"
      "\n"), GALGAS_string ("}\n"
      "\n"
      "//----------------------------------------------------------------------------*\n"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 92)) ;
    }
    enumerator_3122.gotoNextObject () ;
  }
}


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                           Filewrapper 'transientManager'                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- All files of 'class-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_1 [1] = {
  NULL
} ;

//--- All sub-directories of 'class-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_1 [1] = {
  NULL
} ;

//--- Directory 'class-generation'

const cDirectoryWrapper gWrapperDirectory_1_transientManager (
  "class-generation",
  0,
  gWrapperAllFiles_transientManager_1,
  0,
  gWrapperAllDirectories_transientManager_1
) ;

//--- All files of 'collection-controller-templates' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_2 [1] = {
  NULL
} ;

//--- All sub-directories of 'collection-controller-templates' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_2 [1] = {
  NULL
} ;

//--- Directory 'collection-controller-templates'

const cDirectoryWrapper gWrapperDirectory_2_transientManager (
  "collection-controller-templates",
  0,
  gWrapperAllFiles_transientManager_2,
  0,
  gWrapperAllDirectories_transientManager_2
) ;

//--- All files of 'controller-templates' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_3 [1] = {
  NULL
} ;

//--- All sub-directories of 'controller-templates' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_3 [1] = {
  NULL
} ;

//--- Directory 'controller-templates'

const cDirectoryWrapper gWrapperDirectory_3_transientManager (
  "controller-templates",
  0,
  gWrapperAllFiles_transientManager_3,
  0,
  gWrapperAllDirectories_transientManager_3
) ;

//--- All files of 'cursors-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_4 [1] = {
  NULL
} ;

//--- All sub-directories of 'cursors-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_4 [1] = {
  NULL
} ;

//--- Directory 'cursors-generation'

const cDirectoryWrapper gWrapperDirectory_4_transientManager (
  "cursors-generation",
  0,
  gWrapperAllFiles_transientManager_4,
  0,
  gWrapperAllDirectories_transientManager_4
) ;

//--- All files of 'nib-class-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_5 [1] = {
  NULL
} ;

//--- All sub-directories of 'nib-class-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_5 [1] = {
  NULL
} ;

//--- Directory 'nib-class-generation'

const cDirectoryWrapper gWrapperDirectory_5_transientManager (
  "nib-class-generation",
  0,
  gWrapperAllFiles_transientManager_5,
  0,
  gWrapperAllDirectories_transientManager_5
) ;

//--- All files of 'outlet-class-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_6 [1] = {
  NULL
} ;

//--- All sub-directories of 'outlet-class-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_6 [1] = {
  NULL
} ;

//--- Directory 'outlet-class-generation'

const cDirectoryWrapper gWrapperDirectory_6_transientManager (
  "outlet-class-generation",
  0,
  gWrapperAllFiles_transientManager_6,
  0,
  gWrapperAllDirectories_transientManager_6
) ;

//--- All files of 'outlet-classes' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_7 [1] = {
  NULL
} ;

//--- All sub-directories of 'outlet-classes' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_7 [1] = {
  NULL
} ;

//--- Directory 'outlet-classes'

const cDirectoryWrapper gWrapperDirectory_7_transientManager (
  "outlet-classes",
  0,
  gWrapperAllFiles_transientManager_7,
  0,
  gWrapperAllDirectories_transientManager_7
) ;

//--- All files of 'struct-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_8 [1] = {
  NULL
} ;

//--- All sub-directories of 'struct-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_8 [1] = {
  NULL
} ;

//--- Directory 'struct-generation'

const cDirectoryWrapper gWrapperDirectory_8_transientManager (
  "struct-generation",
  0,
  gWrapperAllFiles_transientManager_8,
  0,
  gWrapperAllDirectories_transientManager_8
) ;

//--- All files of 'swift-sources' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_9 [1] = {
  NULL
} ;

//--- All sub-directories of 'swift-sources' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_9 [1] = {
  NULL
} ;

//--- Directory 'swift-sources'

const cDirectoryWrapper gWrapperDirectory_9_transientManager (
  "swift-sources",
  0,
  gWrapperAllFiles_transientManager_9,
  0,
  gWrapperAllDirectories_transientManager_9
) ;

//--- All files of '' directory

static const cRegularFileWrapper * gWrapperAllFiles_transientManager_0 [1] = {
  NULL
} ;

//--- All sub-directories of '' directory

static const cDirectoryWrapper * gWrapperAllDirectories_transientManager_0 [10] = {
  & gWrapperDirectory_1_transientManager,
  & gWrapperDirectory_2_transientManager,
  & gWrapperDirectory_3_transientManager,
  & gWrapperDirectory_4_transientManager,
  & gWrapperDirectory_5_transientManager,
  & gWrapperDirectory_6_transientManager,
  & gWrapperDirectory_7_transientManager,
  & gWrapperDirectory_8_transientManager,
  & gWrapperDirectory_9_transientManager,
  NULL
} ;

//--- Directory ''

const cDirectoryWrapper gWrapperDirectory_0_transientManager (
  "",
  0,
  gWrapperAllFiles_transientManager_0,
  9,
  gWrapperAllDirectories_transientManager_0
) ;


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                             Filewrapper template 'transientManager applicationInSwift'                              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_transientManager_applicationInSwift (C_Compiler * inCompiler,
                                                                       const GALGAS_transientDependencyGraphNodeInfoList & in_PROPERTY_5F_LIST,
                                                                       const GALGAS_stringlist & in_TRANSIENT_5F_LIST
                                                                       COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "import Cocoa\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "let TRACE_TRANSIENT_TRIGGER = false\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "//                                                                                                                     *\n"
    "//    T O P O L O G I C A L    S O R T    O F    P R O P E R T I E S                                                   *\n"
    "//                                                                                                                     *\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_937_idx (0) ;
  if (in_PROPERTY_5F_LIST.isValid ()) {
    cEnumerator_transientDependencyGraphNodeInfoList enumerator_937 (in_PROPERTY_5F_LIST, kEnumeration_up) ;
    while (enumerator_937.hasCurrentObject ()) {
      result << "// " ;
      result << enumerator_937.current_mSignature (HERE).stringValue () ;
      result << " = " ;
      result << index_937_idx.reader_string (SOURCE_FILE ("PMApplication.swift.gTemplate", 17)).stringValue () ;
      result << "\n" ;
      index_937_idx.increment () ;
      enumerator_937.gotoNextObject () ;
    }
  }
  result << "\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "//                                                                                                                     *\n"
    "//    T R A N S I E N T    I N D E X E S                                                                               *\n"
    "//                                                                                                                     *\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "let kTriggerOutletDisplay = 0\n" ;
  GALGAS_uint index_1659_idx (0) ;
  if (in_TRANSIENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_1659 (in_TRANSIENT_5F_LIST, kEnumeration_up) ;
    while (enumerator_1659.hasCurrentObject ()) {
      result << "let k_" ;
      result << enumerator_1659.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 31)).stringValue () ;
      result << " = " ;
      result << index_1659_idx.add_operation (GALGAS_uint ((uint32_t) 1U), inCompiler COMMA_SOURCE_FILE ("PMApplication.swift.gTemplate", 31)).reader_string (SOURCE_FILE ("PMApplication.swift.gTemplate", 31)).stringValue () ;
      result << "\n" ;
      index_1659_idx.increment () ;
      enumerator_1659.gotoNextObject () ;
    }
  }
  result << "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "//                                                                                                                     *\n"
    "//    T R A N S I E N T    T R I G G E R    C L A S S E S                                                              *\n"
    "//                                                                                                                     *\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "@objc(PMTriggerProtocol)\n"
    "protocol PMTriggerProtocol : NSObjectProtocol {\n"
    "  var mTransientIndex : Int { get } // Note: we cannot use an enumeration here\n"
    "  func noteTransientDidChange ()\n"
    "  func trigger ()\n"
    "  func unregister ()\n"
    "}\n"
    "\n" ;
  GALGAS_uint index_2607_idx (0) ;
  if (in_TRANSIENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_2607 (in_TRANSIENT_5F_LIST, kEnumeration_up) ;
    while (enumerator_2607.hasCurrentObject ()) {
      result << "\n"
        "//---------------------------------------------------------------------------------------------------------------------*\n"
        "\n"
        "@objc(PMTrigger_" ;
      result << enumerator_2607.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 54)).stringValue () ;
      result << ")\n"
        "class PMTrigger_" ;
      result << enumerator_2607.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 55)).stringValue () ;
      result << " : NSObject, PMTriggerProtocol {\n"
        "  weak var mTriggerObject : " ;
      result << enumerator_2607.current_mValue (HERE).reader_stringByDeletingPathExtension (SOURCE_FILE ("PMApplication.swift.gTemplate", 56)).reader_pathExtension (SOURCE_FILE ("PMApplication.swift.gTemplate", 56)).stringValue () ;
      result << "\? = nil\n"
        "  \n"
        "  var mTransientIndex : Int { get { return k_" ;
      result << enumerator_2607.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 58)).stringValue () ;
      result << " } }\n"
        "  \n"
        "  init (object : " ;
      result << enumerator_2607.current_mValue (HERE).reader_stringByDeletingPathExtension (SOURCE_FILE ("PMApplication.swift.gTemplate", 60)).reader_pathExtension (SOURCE_FILE ("PMApplication.swift.gTemplate", 60)).stringValue () ;
      result << ") {\n"
        "    mTriggerObject = object\n"
        "    super.init ()\n"
        "    noteObjectAllocation (self) ;\n"
        "  }\n"
        "\n"
        "  func noteTransientDidChange () {\n"
        "    mTriggerObject\?." ;
      result << enumerator_2607.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 67)).stringValue () ;
      result << "_noteDidChange ()\n"
        "  }\n"
        "\n"
        "  func unregister () {\n"
        "  }\n"
        "  \n"
        "  deinit {\n"
        "    noteObjectDeallocation (self) ;\n"
        "  }\n"
        "\n"
        "  func trigger () {\n"
        "    mTriggerObject\?." ;
      result << enumerator_2607.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 78)).stringValue () ;
      result << "_trigger ()\n"
        "  }\n"
        "}\n" ;
      index_2607_idx.increment () ;
      enumerator_2607.gotoNextObject () ;
    }
  }
  result << "\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "//                                                                                                                     *\n"
    "//    T R A N S I E N T    T R I G G E R    F U N C T I O N                                                            *\n"
    "//                                                                                                                     *\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "func enterTriggerWithObject (inObject : PMTriggerProtocol) {\n"
    "  var theApp = NSApp as PMApplication\n"
    "  theApp.enterTriggerWithObject (inObject) ;\n"
    "}\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "//                                                                                                                     *\n"
    "//    R U N    T R I G G E R S                                                                                         *\n"
    "//                                                                                                                     *\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "func flushTriggers () {\n"
    "  var theApp = NSApp as PMApplication\n"
    "  theApp.runTriggers ()\n"
    "  displayAllocation ()\n"
    "}\n"
    "\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "//                                                                                                                     *\n"
    "//    A P P L I C A T I O N    C L A S S                                                                               *\n"
    "//                                                                                                                     *\n"
    "//---------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "@objc(PMApplication) class PMApplication : NSApplication {\n"
    "  private var mLevel = 0\n"
    "  private var mTriggerOutletDisplaySet = NSMutableSet ()\n"
    " \n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n" ;
  GALGAS_uint index_5899_idx (0) ;
  if (in_TRANSIENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_5899 (in_TRANSIENT_5F_LIST, kEnumeration_up) ;
    while (enumerator_5899.hasCurrentObject ()) {
      result << "  private var mTriggerSet_" ;
      result << enumerator_5899.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 120)).stringValue () ;
      result << " = NSMutableSet () // " ;
      result << index_5899_idx.reader_string (SOURCE_FILE ("PMApplication.swift.gTemplate", 120)).stringValue () ;
      result << "\n" ;
      index_5899_idx.increment () ;
      enumerator_5899.gotoNextObject () ;
    }
  }
  result << "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  private func enterTriggerWithObject (inObject : PMTriggerProtocol) {\n"
    "    inObject.noteTransientDidChange ()\n"
    "    let transientIndex = inObject.mTransientIndex\n"
    "    switch transientIndex {\n"
    "    case kTriggerOutletDisplay :\n"
    "      mTriggerOutletDisplaySet.addObject (inObject)\n" ;
  GALGAS_uint index_6446_idx (0) ;
  if (in_TRANSIENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_6446 (in_TRANSIENT_5F_LIST, kEnumeration_up) ;
    while (enumerator_6446.hasCurrentObject ()) {
      result << "    case k_" ;
      result << enumerator_6446.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 131)).stringValue () ;
      result << " :\n"
        "      mTriggerSet_" ;
      result << enumerator_6446.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 132)).stringValue () ;
      result << ".addObject (inObject)\n"
        "      if TRACE_TRANSIENT_TRIGGER {\n"
        "        NSLog (\"Trigger " ;
      result << enumerator_6446.current_mValue (HERE).stringValue () ;
      result << ", %d objects\", mTriggerSet_" ;
      result << enumerator_6446.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 134)).stringValue () ;
      result << ".count)\n"
        "      }\n" ;
      index_6446_idx.increment () ;
      enumerator_6446.gotoNextObject () ;
    }
  }
  result << "    default: break\n"
    "    }\n"
    "  }\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    " \n"
    "  override func sendEvent (inEvent : NSEvent!) {\n"
    "    mLevel += 1\n"
    "    // NSLog (\"send event %d\", mLevel)\n"
    "    super.sendEvent (inEvent)\n"
    "    mLevel -= 1\n"
    "    // NSLog (\"send event done %d\", mLevel)\n"
    "    if 0 == mLevel {\n"
    "      runTriggers ()\n"
    "      displayAllocation ()\n"
    "    }\n"
    "  }\n"
    "  \n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "  override func sendAction (theAction: Selector, to theTarget: AnyObject!, from sender: AnyObject!) -> Bool {\n"
    "    mLevel += 1\n"
    "    // NSLog (\"send action %d\", mLevel)\n"
    "    let result = super.sendAction (theAction, to:theTarget, from:sender)\n"
    "    mLevel -= 1\n"
    "    // NSLog (\"send action done %d\", mLevel)\n"
    "    if 0 == mLevel {\n"
    "      runTriggers ()\n"
    "      displayAllocation ()\n"
    "    }\n"
    "    return result\n"
    "  }\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "  \n"
    "  private func runTriggers () {\n" ;
  GALGAS_uint index_7881_idx (0) ;
  if (in_TRANSIENT_5F_LIST.isValid ()) {
    cEnumerator_stringlist enumerator_7881 (in_TRANSIENT_5F_LIST, kEnumeration_down) ;
    while (enumerator_7881.hasCurrentObject ()) {
      result << "    if mTriggerSet_" ;
      result << enumerator_7881.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 174)).stringValue () ;
      result << ".count > 0 { // " ;
      result << in_TRANSIENT_5F_LIST.reader_length (SOURCE_FILE ("PMApplication.swift.gTemplate", 174)).substract_operation (index_7881_idx, inCompiler COMMA_SOURCE_FILE ("PMApplication.swift.gTemplate", 174)).reader_string (SOURCE_FILE ("PMApplication.swift.gTemplate", 174)).stringValue () ;
      result << "\n"
        "      for anyObject in mTriggerSet_" ;
      result << enumerator_7881.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 175)).stringValue () ;
      result << " {\n"
        "        let object = anyObject as PMTriggerProtocol\n"
        "        object.trigger ()\n"
        "      }\n"
        "      mTriggerSet_" ;
      result << enumerator_7881.current_mValue (HERE).reader_identifierRepresentation (SOURCE_FILE ("PMApplication.swift.gTemplate", 179)).stringValue () ;
      result << " = NSMutableSet ()\n"
        "    }    \n" ;
      index_7881_idx.increment () ;
      enumerator_7881.gotoNextObject () ;
    }
  }
  result << "    if mTriggerOutletDisplaySet.count > 0 {\n"
    "      for anyObject in mTriggerOutletDisplaySet {\n"
    "        let object = anyObject as PMTriggerProtocol\n"
    "        object.trigger ()\n"
    "      }\n"
    "      mTriggerOutletDisplaySet = NSMutableSet ()\n"
    "    }\n"
    "  }\n"
    "\n"
    "  //-------------------------------------------------------------------------------------------------------------------*\n"
    "\n"
    "}\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                      Filewrapper template 'transientManager transientComputationFunctionFile'                       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_transientManager_transientComputationFunctionFile (C_Compiler * inCompiler,
                                                                                     const GALGAS_string & in_KIND_5F_NAME,
                                                                                     const GALGAS_string & in_TRANSIENT_5F_NAME,
                                                                                     const GALGAS_transientDependencyListForGeneration & in_DEPENDENCY_5F_LIST,
                                                                                     const GALGAS_unifiedTypeProxy & in_TRANSIENT_5F_TYPE
                                                                                     COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  uint32_t columnMarker = 0 ;
  result << "import Cocoa\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "func compute_" ;
  result << in_KIND_5F_NAME.stringValue () ;
  result << "_" ;
  result << in_TRANSIENT_5F_NAME.stringValue () ;
  result << " (" ;
  columnMarker = result.currentColumn () ;
  GALGAS_uint index_171_ (0) ;
  if (in_DEPENDENCY_5F_LIST.isValid ()) {
    cEnumerator_transientDependencyListForGeneration enumerator_171 (in_DEPENDENCY_5F_LIST, kEnumeration_up) ;
    while (enumerator_171.hasCurrentObject ()) {
      result << enumerator_171.current_mMasterName (HERE).stringValue () ;
      result << " : " ;
      result << categoryReader_transientFormalArgumentTypeName (enumerator_171.current_mMasterType (HERE), inCompiler COMMA_SOURCE_FILE ("transient-computation-function.swift.gTemplate", 7)).stringValue () ;
      if (enumerator_171.hasNextObject ()) {
        result << ",\n" ;
        result.appendSpacesUntilColumn (columnMarker) ;
      }
      index_171_.increment () ;
      enumerator_171.gotoNextObject () ;
    }
  }
  result << ") -> " ;
  result << categoryReader_transientReturnTypeName (in_TRANSIENT_5F_TYPE, inCompiler COMMA_SOURCE_FILE ("transient-computation-function.swift.gTemplate", 10)).stringValue () ;
  result << "  {\n"
    "\n" ;
  return GALGAS_string (result) ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                             Category Reader '@unifiedTypeProxy transientReturnTypeName'                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string categoryReader_transientReturnTypeName (const GALGAS_unifiedTypeProxy & inObject,
                                                      C_Compiler * inCompiler
                                                      COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const GALGAS_unifiedTypeProxy temp_0 = inObject ;
  if (temp_0.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 9)).isValid ()) {
    switch (temp_0.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 9)).enumValue ()) {
    case GALGAS_typeKind::kNotBuilt:
      break ;
    case GALGAS_typeKind::kEnum_boolType: {
      result_outResult = GALGAS_string ("Bool") ;
      } break ;
    case GALGAS_typeKind::kEnum_uintegerType: {
      result_outResult = GALGAS_string ("UInt") ;
      } break ;
    case GALGAS_typeKind::kEnum_integerType: {
      result_outResult = GALGAS_string ("Int") ;
      } break ;
    case GALGAS_typeKind::kEnum_doubleType: {
      result_outResult = GALGAS_string ("Double") ;
      } break ;
    case GALGAS_typeKind::kEnum_stringType: {
      result_outResult = GALGAS_string ("String") ;
      } break ;
    case GALGAS_typeKind::kEnum_colorType: {
      result_outResult = GALGAS_string ("NSColor") ;
      } break ;
    case GALGAS_typeKind::kEnum_dataType: {
      result_outResult = GALGAS_string ("NSData") ;
      } break ;
    case GALGAS_typeKind::kEnum_dateType: {
      result_outResult = GALGAS_string ("NSDate") ;
      } break ;
    case GALGAS_typeKind::kEnum_imageType: {
      result_outResult = GALGAS_string ("NSImage") ;
      } break ;
    case GALGAS_typeKind::kEnum_fontType: {
      result_outResult = GALGAS_string ("NSFont") ;
      } break ;
    case GALGAS_typeKind::kEnum_menuType: {
      result_outResult = GALGAS_string ("NSMenu") ;
      } break ;
    case GALGAS_typeKind::kEnum_bezierPathType: {
      result_outResult = GALGAS_string ("NSBezierPath") ;
      } break ;
    case GALGAS_typeKind::kEnum_structType: case GALGAS_typeKind::kEnum_enumType: {
      const GALGAS_unifiedTypeProxy temp_1 = inObject ;
      result_outResult = temp_1.reader_key (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 22)) ;
      } break ;
    case GALGAS_typeKind::kEnum_classType: case GALGAS_typeKind::kEnum_controllerClassType: case GALGAS_typeKind::kEnum_documentType: case GALGAS_typeKind::kEnum_entityType: case GALGAS_typeKind::kEnum_preferencesType: case GALGAS_typeKind::kEnum_nibClassType: case GALGAS_typeKind::kEnum_outletClassType: case GALGAS_typeKind::kEnum_protocolType: {
      const GALGAS_unifiedTypeProxy temp_2 = inObject ;
      result_outResult = GALGAS_string ("<invalid return type '").add_operation (temp_2.reader_key (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 25)), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 25)).add_operation (GALGAS_string ("' >"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 25)) ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                         Category Reader '@unifiedTypeProxy transientFormalArgumentTypeName'                         *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string categoryReader_transientFormalArgumentTypeName (const GALGAS_unifiedTypeProxy & inObject,
                                                              C_Compiler * inCompiler
                                                              COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const GALGAS_unifiedTypeProxy temp_0 = inObject ;
  if (temp_0.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 33)).isValid ()) {
    switch (temp_0.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 33)).enumValue ()) {
    case GALGAS_typeKind::kNotBuilt:
      break ;
    case GALGAS_typeKind::kEnum_boolType: {
      result_outResult = GALGAS_string ("Bool") ;
      } break ;
    case GALGAS_typeKind::kEnum_uintegerType: {
      result_outResult = GALGAS_string ("UInt") ;
      } break ;
    case GALGAS_typeKind::kEnum_integerType: {
      result_outResult = GALGAS_string ("Int") ;
      } break ;
    case GALGAS_typeKind::kEnum_doubleType: {
      result_outResult = GALGAS_string ("Double") ;
      } break ;
    case GALGAS_typeKind::kEnum_stringType: {
      result_outResult = GALGAS_string ("String") ;
      } break ;
    case GALGAS_typeKind::kEnum_colorType: {
      result_outResult = GALGAS_string ("NSColor") ;
      } break ;
    case GALGAS_typeKind::kEnum_dataType: {
      result_outResult = GALGAS_string ("NSData") ;
      } break ;
    case GALGAS_typeKind::kEnum_dateType: {
      result_outResult = GALGAS_string ("NSDate") ;
      } break ;
    case GALGAS_typeKind::kEnum_imageType: {
      result_outResult = GALGAS_string ("NSImage") ;
      } break ;
    case GALGAS_typeKind::kEnum_fontType: {
      result_outResult = GALGAS_string ("NSFont") ;
      } break ;
    case GALGAS_typeKind::kEnum_menuType: {
      result_outResult = GALGAS_string ("NSMenu") ;
      } break ;
    case GALGAS_typeKind::kEnum_bezierPathType: {
      result_outResult = GALGAS_string ("NSBezierPath") ;
      } break ;
    case GALGAS_typeKind::kEnum_entityType: {
      result_outResult = GALGAS_string ("Int") ;
      } break ;
    case GALGAS_typeKind::kEnum_structType: case GALGAS_typeKind::kEnum_enumType: {
      const GALGAS_unifiedTypeProxy temp_1 = inObject ;
      result_outResult = temp_1.reader_key (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 47)) ;
      } break ;
    case GALGAS_typeKind::kEnum_classType: case GALGAS_typeKind::kEnum_controllerClassType: case GALGAS_typeKind::kEnum_documentType: case GALGAS_typeKind::kEnum_preferencesType: case GALGAS_typeKind::kEnum_nibClassType: case GALGAS_typeKind::kEnum_outletClassType: case GALGAS_typeKind::kEnum_protocolType: {
      const GALGAS_unifiedTypeProxy temp_2 = inObject ;
      result_outResult = GALGAS_string ("<invalid return type '").add_operation (temp_2.reader_key (inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 50)), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 50)).add_operation (GALGAS_string ("' >"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 50)) ;
      } break ;
    }
  }
//---
  return result_outResult ;
}




//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                 Abstract category reader '@abstractTransientDependency generateForComputeFunction'                  *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static TC_UniqueArray <categoryReaderSignature_abstractTransientDependency_generateForComputeFunction> gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryReader_generateForComputeFunction (const int32_t inClassIndex,
                                                     categoryReaderSignature_abstractTransientDependency_generateForComputeFunction inReader) {
  gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction.forceObjectAtIndex (inClassIndex, inReader, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------------------------------------------------*

static void freeCategoryReader_abstractTransientDependency_generateForComputeFunction (void) {
  gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction.free () ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_abstractTransientDependency_generateForComputeFunction (NULL,
                                                                                   freeCategoryReader_abstractTransientDependency_generateForComputeFunction) ;

//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string callCategoryReader_generateForComputeFunction (const cPtr_abstractTransientDependency * inObject,
                                                             C_Compiler * inCompiler
                                                             COMMA_LOCATION_ARGS) {
  GALGAS_string result ;
//--- Find Reader
  if (NULL != inObject) {
    macroValidSharedObject (inObject, cPtr_abstractTransientDependency) ;
    const C_galgas_type_descriptor * info = inObject->classDescriptor () ;
    const int32_t classIndex = info->mSlotID ;
    categoryReaderSignature_abstractTransientDependency_generateForComputeFunction f = NULL ;
    if (classIndex < gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction.count ()) {
      f = gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction (classIndex COMMA_HERE) ;
    }
    if (NULL == f) {
       const C_galgas_type_descriptor * p = info->mSuperclassDescriptor ;
       while ((NULL == f) && (NULL != p)) {
         if (p->mSlotID < gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction.count ()) {
           f = gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction (p->mSlotID COMMA_HERE) ;
         }
         p = p->mSuperclassDescriptor ;
       }
       gCategoryReaderTable_abstractTransientDependency_generateForComputeFunction.forceObjectAtIndex (classIndex, f, NULL COMMA_HERE) ;
    }
    if (NULL == f) {
      fatalError ("FATAL CATEGORY READER CALL ERROR", __FILE__, __LINE__) ;
    }else{
      result = f (inObject, inCompiler COMMA_THERE) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category reader '@transientControllerDependency generateForComputeFunction'                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientControllerDependency_generateForComputeFunction (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                              C_Compiler * /* inCompiler */
                                                                                              COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  result_outResult = GALGAS_string ("\?\?@transientControllerDependency\?\?") ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientControllerDependency_generateForComputeFunction (void) {
  enterCategoryReader_generateForComputeFunction (kTypeDescriptor_GALGAS_transientControllerDependency.mSlotID,
                                                  categoryReader_transientControllerDependency_generateForComputeFunction) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientControllerDependency_generateForComputeFunction (defineCategoryReader_transientControllerDependency_generateForComputeFunction, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                Overriding category reader '@transientRootSignDependency generateForComputeFunction'                 *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientRootSignDependency_generateForComputeFunction (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                            C_Compiler * /* inCompiler */
                                                                                            COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  result_outResult = GALGAS_string ("\?\?@@transientRootSignDependency\?\?") ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientRootSignDependency_generateForComputeFunction (void) {
  enterCategoryReader_generateForComputeFunction (kTypeDescriptor_GALGAS_transientRootSignDependency.mSlotID,
                                                  categoryReader_transientRootSignDependency_generateForComputeFunction) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientRootSignDependency_generateForComputeFunction (defineCategoryReader_transientRootSignDependency_generateForComputeFunction, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                  Overriding category reader '@transientLocalDependency generateForComputeFunction'                  *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientLocalDependency_generateForComputeFunction (const cPtr_abstractTransientDependency * inObject,
                                                                                         C_Compiler * /* inCompiler */
                                                                                         COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientLocalDependency * object = (const cPtr_transientLocalDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependency) ;
  result_outResult = object->mAttribute_mMasterName.mAttribute_string ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.boolEnum () ;
  if (kBoolTrue == test_0) {
    result_outResult.dotAssign_operation (GALGAS_string (".count")  COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 146)) ;
  }
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientLocalDependency_generateForComputeFunction (void) {
  enterCategoryReader_generateForComputeFunction (kTypeDescriptor_GALGAS_transientLocalDependency.mSlotID,
                                                  categoryReader_transientLocalDependency_generateForComputeFunction) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientLocalDependency_generateForComputeFunction (defineCategoryReader_transientLocalDependency_generateForComputeFunction, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category reader '@transientPreferenceDependency generateForComputeFunction'                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientPreferenceDependency_generateForComputeFunction (const cPtr_abstractTransientDependency * inObject,
                                                                                              C_Compiler * inCompiler
                                                                                              COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientPreferenceDependency * object = (const cPtr_transientPreferenceDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependency) ;
  result_outResult = GALGAS_string ("g_").add_operation (object->mAttribute_mPreferencesName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 153)).add_operation (GALGAS_string ("!."), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 153)).add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 153)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientPreferenceDependency_generateForComputeFunction (void) {
  enterCategoryReader_generateForComputeFunction (kTypeDescriptor_GALGAS_transientPreferenceDependency.mSlotID,
                                                  categoryReader_transientPreferenceDependency_generateForComputeFunction) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientPreferenceDependency_generateForComputeFunction (defineCategoryReader_transientPreferenceDependency_generateForComputeFunction, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                  Overriding category reader '@transientRootDependency generateForComputeFunction'                   *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientRootDependency_generateForComputeFunction (const cPtr_abstractTransientDependency * inObject,
                                                                                        C_Compiler * inCompiler
                                                                                        COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientRootDependency * object = (const cPtr_transientRootDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependency) ;
  result_outResult = GALGAS_string ("rootObject.").add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 159)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientRootDependency_generateForComputeFunction (void) {
  enterCategoryReader_generateForComputeFunction (kTypeDescriptor_GALGAS_transientRootDependency.mSlotID,
                                                  categoryReader_transientRootDependency_generateForComputeFunction) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientRootDependency_generateForComputeFunction (defineCategoryReader_transientRootDependency_generateForComputeFunction, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                   Abstract category reader '@abstractTransientDependency generateAddObserverCall'                   *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static TC_UniqueArray <categoryReaderSignature_abstractTransientDependency_generateAddObserverCall> gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryReader_generateAddObserverCall (const int32_t inClassIndex,
                                                  categoryReaderSignature_abstractTransientDependency_generateAddObserverCall inReader) {
  gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall.forceObjectAtIndex (inClassIndex, inReader, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------------------------------------------------*

static void freeCategoryReader_abstractTransientDependency_generateAddObserverCall (void) {
  gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall.free () ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_abstractTransientDependency_generateAddObserverCall (NULL,
                                                                                freeCategoryReader_abstractTransientDependency_generateAddObserverCall) ;

//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string callCategoryReader_generateAddObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                          C_Compiler * inCompiler
                                                          COMMA_LOCATION_ARGS) {
  GALGAS_string result ;
//--- Find Reader
  if (NULL != inObject) {
    macroValidSharedObject (inObject, cPtr_abstractTransientDependency) ;
    const C_galgas_type_descriptor * info = inObject->classDescriptor () ;
    const int32_t classIndex = info->mSlotID ;
    categoryReaderSignature_abstractTransientDependency_generateAddObserverCall f = NULL ;
    if (classIndex < gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall.count ()) {
      f = gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall (classIndex COMMA_HERE) ;
    }
    if (NULL == f) {
       const C_galgas_type_descriptor * p = info->mSuperclassDescriptor ;
       while ((NULL == f) && (NULL != p)) {
         if (p->mSlotID < gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall.count ()) {
           f = gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall (p->mSlotID COMMA_HERE) ;
         }
         p = p->mSuperclassDescriptor ;
       }
       gCategoryReaderTable_abstractTransientDependency_generateAddObserverCall.forceObjectAtIndex (classIndex, f, NULL COMMA_HERE) ;
    }
    if (NULL == f) {
      fatalError ("FATAL CATEGORY READER CALL ERROR", __FILE__, __LINE__) ;
    }else{
      result = f (inObject, inCompiler COMMA_THERE) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                 Overriding category reader '@transientControllerDependency generateAddObserverCall'                 *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientControllerDependency_generateAddObserverCall (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                           C_Compiler * /* inCompiler */
                                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  result_outResult = GALGAS_string ("\?\?@transientControllerDependency\?\?") ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientControllerDependency_generateAddObserverCall (void) {
  enterCategoryReader_generateAddObserverCall (kTypeDescriptor_GALGAS_transientControllerDependency.mSlotID,
                                               categoryReader_transientControllerDependency_generateAddObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientControllerDependency_generateAddObserverCall (defineCategoryReader_transientControllerDependency_generateAddObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                  Overriding category reader '@transientRootSignDependency generateAddObserverCall'                  *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientRootSignDependency_generateAddObserverCall (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                         C_Compiler * /* inCompiler */
                                                                                         COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  result_outResult = GALGAS_string ("\?\?@@transientRootSignDependency\?\?") ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientRootSignDependency_generateAddObserverCall (void) {
  enterCategoryReader_generateAddObserverCall (kTypeDescriptor_GALGAS_transientRootSignDependency.mSlotID,
                                               categoryReader_transientRootSignDependency_generateAddObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientRootSignDependency_generateAddObserverCall (defineCategoryReader_transientRootSignDependency_generateAddObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                   Overriding category reader '@transientLocalDependency generateAddObserverCall'                    *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientLocalDependency_generateAddObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                                                      C_Compiler * inCompiler
                                                                                      COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientLocalDependency * object = (const cPtr_transientLocalDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependency) ;
  result_outResult = GALGAS_string ("addObserverOf_").add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 184)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientLocalDependency_generateAddObserverCall (void) {
  enterCategoryReader_generateAddObserverCall (kTypeDescriptor_GALGAS_transientLocalDependency.mSlotID,
                                               categoryReader_transientLocalDependency_generateAddObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientLocalDependency_generateAddObserverCall (defineCategoryReader_transientLocalDependency_generateAddObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                 Overriding category reader '@transientPreferenceDependency generateAddObserverCall'                 *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientPreferenceDependency_generateAddObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                                                           C_Compiler * inCompiler
                                                                                           COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientPreferenceDependency * object = (const cPtr_transientPreferenceDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependency) ;
  result_outResult = GALGAS_string ("g_").add_operation (object->mAttribute_mPreferencesName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 190)).add_operation (GALGAS_string ("\?.addObserverOf_"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 190)).add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 190)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientPreferenceDependency_generateAddObserverCall (void) {
  enterCategoryReader_generateAddObserverCall (kTypeDescriptor_GALGAS_transientPreferenceDependency.mSlotID,
                                               categoryReader_transientPreferenceDependency_generateAddObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientPreferenceDependency_generateAddObserverCall (defineCategoryReader_transientPreferenceDependency_generateAddObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                    Overriding category reader '@transientRootDependency generateAddObserverCall'                    *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientRootDependency_generateAddObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                                                     C_Compiler * inCompiler
                                                                                     COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientRootDependency * object = (const cPtr_transientRootDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependency) ;
  result_outResult = GALGAS_string ("rootObject.addObserverOf_").add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 196)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientRootDependency_generateAddObserverCall (void) {
  enterCategoryReader_generateAddObserverCall (kTypeDescriptor_GALGAS_transientRootDependency.mSlotID,
                                               categoryReader_transientRootDependency_generateAddObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientRootDependency_generateAddObserverCall (defineCategoryReader_transientRootDependency_generateAddObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                 Abstract category reader '@abstractTransientDependency generateRemoveObserverCall'                  *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static TC_UniqueArray <categoryReaderSignature_abstractTransientDependency_generateRemoveObserverCall> gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryReader_generateRemoveObserverCall (const int32_t inClassIndex,
                                                     categoryReaderSignature_abstractTransientDependency_generateRemoveObserverCall inReader) {
  gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall.forceObjectAtIndex (inClassIndex, inReader, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------------------------------------------------*

static void freeCategoryReader_abstractTransientDependency_generateRemoveObserverCall (void) {
  gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall.free () ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_abstractTransientDependency_generateRemoveObserverCall (NULL,
                                                                                   freeCategoryReader_abstractTransientDependency_generateRemoveObserverCall) ;

//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string callCategoryReader_generateRemoveObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                             C_Compiler * inCompiler
                                                             COMMA_LOCATION_ARGS) {
  GALGAS_string result ;
//--- Find Reader
  if (NULL != inObject) {
    macroValidSharedObject (inObject, cPtr_abstractTransientDependency) ;
    const C_galgas_type_descriptor * info = inObject->classDescriptor () ;
    const int32_t classIndex = info->mSlotID ;
    categoryReaderSignature_abstractTransientDependency_generateRemoveObserverCall f = NULL ;
    if (classIndex < gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall.count ()) {
      f = gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall (classIndex COMMA_HERE) ;
    }
    if (NULL == f) {
       const C_galgas_type_descriptor * p = info->mSuperclassDescriptor ;
       while ((NULL == f) && (NULL != p)) {
         if (p->mSlotID < gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall.count ()) {
           f = gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall (p->mSlotID COMMA_HERE) ;
         }
         p = p->mSuperclassDescriptor ;
       }
       gCategoryReaderTable_abstractTransientDependency_generateRemoveObserverCall.forceObjectAtIndex (classIndex, f, NULL COMMA_HERE) ;
    }
    if (NULL == f) {
      fatalError ("FATAL CATEGORY READER CALL ERROR", __FILE__, __LINE__) ;
    }else{
      result = f (inObject, inCompiler COMMA_THERE) ;
    }
  }
  return result ;
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category reader '@transientControllerDependency generateRemoveObserverCall'                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientControllerDependency_generateRemoveObserverCall (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                              C_Compiler * /* inCompiler */
                                                                                              COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  result_outResult = GALGAS_string ("\?\?@transientControllerDependency\?\?") ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientControllerDependency_generateRemoveObserverCall (void) {
  enterCategoryReader_generateRemoveObserverCall (kTypeDescriptor_GALGAS_transientControllerDependency.mSlotID,
                                                  categoryReader_transientControllerDependency_generateRemoveObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientControllerDependency_generateRemoveObserverCall (defineCategoryReader_transientControllerDependency_generateRemoveObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                Overriding category reader '@transientRootSignDependency generateRemoveObserverCall'                 *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientRootSignDependency_generateRemoveObserverCall (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                            C_Compiler * /* inCompiler */
                                                                                            COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  result_outResult = GALGAS_string ("\?\?@@transientRootSignDependency\?\?") ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientRootSignDependency_generateRemoveObserverCall (void) {
  enterCategoryReader_generateRemoveObserverCall (kTypeDescriptor_GALGAS_transientRootSignDependency.mSlotID,
                                                  categoryReader_transientRootSignDependency_generateRemoveObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientRootSignDependency_generateRemoveObserverCall (defineCategoryReader_transientRootSignDependency_generateRemoveObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                  Overriding category reader '@transientLocalDependency generateRemoveObserverCall'                  *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientLocalDependency_generateRemoveObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                                                         C_Compiler * inCompiler
                                                                                         COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientLocalDependency * object = (const cPtr_transientLocalDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependency) ;
  result_outResult = GALGAS_string ("removeObserverOf_").add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 221)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientLocalDependency_generateRemoveObserverCall (void) {
  enterCategoryReader_generateRemoveObserverCall (kTypeDescriptor_GALGAS_transientLocalDependency.mSlotID,
                                                  categoryReader_transientLocalDependency_generateRemoveObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientLocalDependency_generateRemoveObserverCall (defineCategoryReader_transientLocalDependency_generateRemoveObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category reader '@transientPreferenceDependency generateRemoveObserverCall'                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientPreferenceDependency_generateRemoveObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                                                              C_Compiler * inCompiler
                                                                                              COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientPreferenceDependency * object = (const cPtr_transientPreferenceDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependency) ;
  result_outResult = GALGAS_string ("g_").add_operation (object->mAttribute_mPreferencesName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 227)).add_operation (GALGAS_string ("\?.removeObserverOf_"), inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 227)).add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 227)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientPreferenceDependency_generateRemoveObserverCall (void) {
  enterCategoryReader_generateRemoveObserverCall (kTypeDescriptor_GALGAS_transientPreferenceDependency.mSlotID,
                                                  categoryReader_transientPreferenceDependency_generateRemoveObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientPreferenceDependency_generateRemoveObserverCall (defineCategoryReader_transientPreferenceDependency_generateRemoveObserverCall, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                  Overriding category reader '@transientRootDependency generateRemoveObserverCall'                   *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static GALGAS_string categoryReader_transientRootDependency_generateRemoveObserverCall (const cPtr_abstractTransientDependency * inObject,
                                                                                        C_Compiler * inCompiler
                                                                                        COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string result_outResult ; // Returned variable
  const cPtr_transientRootDependency * object = (const cPtr_transientRootDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependency) ;
  result_outResult = GALGAS_string ("rootObject.removeObserverOf_").add_operation (object->mAttribute_mMasterName.mAttribute_string, inCompiler COMMA_SOURCE_FILE ("transientGeneration.gSemantics", 233)) ;
//---
  return result_outResult ;
}


//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryReader_transientRootDependency_generateRemoveObserverCall (void) {
  enterCategoryReader_generateRemoveObserverCall (kTypeDescriptor_GALGAS_transientRootDependency.mSlotID,
                                                  categoryReader_transientRootDependency_generateRemoveObserverCall) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gReader_transientRootDependency_generateRemoveObserverCall (defineCategoryReader_transientRootDependency_generateRemoveObserverCall, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


