//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                            File 'transientAnalysis.cpp'                                             *
//                                             Generated by version 3.0.0                                              *
//                                         september 10th, 2014, at 19h53'22"                                          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "transientAnalysis.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                       Routine 'buildTransientDependencyGraph'                                       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_buildTransientDependencyGraph (const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                            const GALGAS_string constinArgument_inSourceFile,
                                            GALGAS_transientDependencyGraphNodeInfoList & outArgument_outSortedTransientNodes,
                                            C_Compiler * inCompiler
                                            COMMA_UNUSED_LOCATION_ARGS) {
  outArgument_outSortedTransientNodes.drop () ; // Release 'out' argument
  GALGAS_transientDependencyGraph var_transientDependencyGraph = GALGAS_transientDependencyGraph::constructor_emptyGraph (SOURCE_FILE ("transientAnalysis.gSemantics", 166)) ;
  cEnumerator_unifiedTypeMap enumerator_5451 (constinArgument_inUnifiedTypeMap, kEnumeration_up) ;
  while (enumerator_5451.hasCurrentObject ()) {
    cEnumerator_decoratedObservablePropertyMap enumerator_5506 (enumerator_5451.current_mObservablePropertyMap (HERE), kEnumeration_up) ;
    while (enumerator_5506.hasCurrentObject ()) {
      {
      var_transientDependencyGraph.modifier_addNode (enumerator_5506.current_mPropertySignature (HERE), enumerator_5506.current_mPropertySignature (HERE).mAttribute_string, enumerator_5506.current_mIsTransient (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 169)) ;
      }
      enumerator_5506.gotoNextObject () ;
    }
    cEnumerator_arrayControllerMap enumerator_5744 (enumerator_5451.current_mArrayControllerMap (HERE), kEnumeration_up) ;
    while (enumerator_5744.hasCurrentObject ()) {
      {
      var_transientDependencyGraph.modifier_addNode (enumerator_5744.current_mPropertySignature (HERE), enumerator_5744.current_mPropertySignature (HERE).mAttribute_string, GALGAS_bool (true), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 176)) ;
      }
      {
      var_transientDependencyGraph.modifier_addEdge (callCategoryReader_propertySignature ((const cPtr_abstractObservablePropertyAST *) enumerator_5744.current_mBoundModel (HERE).ptr (), categoryReader_kindName (enumerator_5451.current_mTypeKind (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 184)), enumerator_5451.current_lkey (HERE).mAttribute_string, enumerator_5451.current_mRootEntityType (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 183)), enumerator_5744.current_mPropertySignature (HERE) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 182)) ;
      }
      enumerator_5744.gotoNextObject () ;
    }
    cEnumerator_decoratedTransientMap enumerator_6314 (enumerator_5451.current_mDecoratedTransientMap (HERE), kEnumeration_up) ;
    while (enumerator_6314.hasCurrentObject ()) {
      GALGAS_decoratedObservablePropertyMap var_allObservableProperties = enumerator_5451.current_mObservablePropertyMap (HERE) ;
      GALGAS_unifiedTypeProxy var_t = enumerator_5451.current_mSuperType (HERE) ;
      if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 194)).isValid ()) {
        uint32_t variant_6470 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 194)).uintValue () ;
        bool loop_6470 = true ;
        while (loop_6470) {
          loop_6470 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 194)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 194)).isValid () ;
          if (loop_6470) {
            loop_6470 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 194)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 194)).boolValue () ;
          }
          if (loop_6470 && (0 == variant_6470)) {
            loop_6470 = false ;
            inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 194)) ;
          }
          if (loop_6470) {
            variant_6470 -- ;
            cEnumerator_decoratedObservablePropertyMap enumerator_6573 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 195)), kEnumeration_up) ;
            while (enumerator_6573.hasCurrentObject ()) {
              {
              var_allObservableProperties.modifier_insertKey (enumerator_6573.current_lkey (HERE), enumerator_6573.current_mPropertyType (HERE), enumerator_6573.current_mIsTransient (HERE), enumerator_6573.current_mPropertySignature (HERE), enumerator_6573.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 196)) ;
              }
              enumerator_6573.gotoNextObject () ;
            }
            var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 204)) ;
          }
        }
      }
      cEnumerator_dependanceList enumerator_6904 (enumerator_6314.current_mDependencyList (HERE), kEnumeration_up) ;
      while (enumerator_6904.hasCurrentObject ()) {
        callCategoryMethod_buildTransientDependencyGraph ((const cPtr_abstractTransientDependency *) enumerator_6904.current_mDependency (HERE).ptr (), constinArgument_inUnifiedTypeMap, var_transientDependencyGraph, enumerator_6314.current_lkey (HERE), var_allObservableProperties, enumerator_5451.current_mRootEntityType (HERE), enumerator_6314.current_mTransientSignature (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 207)) ;
        enumerator_6904.gotoNextObject () ;
      }
      enumerator_6314.gotoNextObject () ;
    }
    enumerator_5451.gotoNextObject () ;
  }
  const enumGalgasBool test_0 = GALGAS_bool (kIsEqual, GALGAS_uint::constructor_errorCount (SOURCE_FILE ("transientAnalysis.gSemantics", 219)).objectCompare (GALGAS_uint ((uint32_t) 0U))).operator_and (GALGAS_bool (gOption_easyBindings_5F_options_outputTransientDependencyGraph.reader_value ()) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 219)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_string var_s = var_transientDependencyGraph.reader_graphviz (SOURCE_FILE ("transientAnalysis.gSemantics", 220)) ;
    GALGAS_string var_path = constinArgument_inSourceFile.operator_concat (GALGAS_string (".transientDependancyGraph.dot")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 221)) ;
    GALGAS_bool joker_7552_0 ; // Joker input parameter
    var_s.method_writeToFileWhenDifferentContents (var_path, joker_7552_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 222)) ;
  }
  const enumGalgasBool test_1 = GALGAS_bool (kIsNotEqual, GALGAS_uint::constructor_errorCount (SOURCE_FILE ("transientAnalysis.gSemantics", 225)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
  if (kBoolTrue == test_1) {
    outArgument_outSortedTransientNodes = GALGAS_transientDependencyGraphNodeInfoList::constructor_emptyList (SOURCE_FILE ("transientAnalysis.gSemantics", 226)) ;
  }else if (kBoolFalse == test_1) {
    GALGAS_transientDependencyGraphNodeInfoList var_unsortedNodes ;
    GALGAS_lstringlist joker_7797_0 ; // Joker input parameter
    GALGAS_lstringlist joker_7865_0 ; // Joker input parameter
    var_transientDependencyGraph.method_topologicalSort (outArgument_outSortedTransientNodes, joker_7797_0, var_unsortedNodes, joker_7865_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 228)) ;
    const enumGalgasBool test_2 = GALGAS_bool (kIsStrictSup, var_unsortedNodes.reader_length (SOURCE_FILE ("transientAnalysis.gSemantics", 234)).objectCompare (GALGAS_uint ((uint32_t) 0U))).boolEnum () ;
    if (kBoolTrue == test_2) {
      GALGAS_string var_s = GALGAS_string ("cannot sort properties and transient ; the following ones are involved in circular dependence:") ;
      cEnumerator_transientDependencyGraphNodeInfoList enumerator_8055 (var_unsortedNodes, kEnumeration_up) ;
      while (enumerator_8055.hasCurrentObject ()) {
        var_s.dotAssign_operation (GALGAS_string ("\n"
          "-- ").operator_concat (enumerator_8055.current_mSignature (HERE)  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 237))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 237)) ;
        enumerator_8055.gotoNextObject () ;
      }
      inCompiler->emitSemanticError (inCompiler->here (), var_s  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 239)) ;
    }
  }
}


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                Abstract category method '@abstractTransientDependency buildTransientDependencyGraph'                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static TC_UniqueArray <categoryMethodSignature_abstractTransientDependency_buildTransientDependencyGraph> gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryMethod_buildTransientDependencyGraph (const int32_t inClassIndex,
                                                        categoryMethodSignature_abstractTransientDependency_buildTransientDependencyGraph inMethod) {
  gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph.forceObjectAtIndex (inClassIndex, inMethod, NULL COMMA_HERE) ;
}

//---------------------------------------------------------------------------------------------------------------------*

static void freeCategoryMethod_abstractTransientDependency_buildTransientDependencyGraph (void) {
  gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph.free () ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_abstractTransientDependency_buildTransientDependencyGraph (NULL,
                                                                                      freeCategoryMethod_abstractTransientDependency_buildTransientDependencyGraph) ;

//---------------------------------------------------------------------------------------------------------------------*

void callCategoryMethod_buildTransientDependencyGraph (const cPtr_abstractTransientDependency * inObject,
                                                       const GALGAS_unifiedTypeMap constin_inUnifiedTypeMap,
                                                       GALGAS_transientDependencyGraph & io_ioTransientDependencyGraph,
                                                       const GALGAS_lstring constin_inTransientName,
                                                       const GALGAS_decoratedObservablePropertyMap constin_inLocalObservablePropertyMap,
                                                       const GALGAS_unifiedTypeProxy constin_inRootEntityType,
                                                       const GALGAS_lstring constin_inTransientPropertySignature,
                                                       C_Compiler * inCompiler
                                                       COMMA_LOCATION_ARGS) {
//--- Drop output arguments
//--- Find method
  if (NULL != inObject) {
    macroValidSharedObject (inObject, cPtr_abstractTransientDependency) ;
    const C_galgas_type_descriptor * info = inObject->classDescriptor () ;
    const int32_t classIndex = info->mSlotID ;
    categoryMethodSignature_abstractTransientDependency_buildTransientDependencyGraph f = NULL ;
    if (classIndex < gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph.count ()) {
      f = gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph (classIndex COMMA_HERE) ;
    }
    if (NULL == f) {
       const C_galgas_type_descriptor * p = info->mSuperclassDescriptor ;
       while ((NULL == f) && (NULL != p)) {
         if (p->mSlotID < gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph.count ()) {
           f = gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph (p->mSlotID COMMA_HERE) ;
         }
         p = p->mSuperclassDescriptor ;
       }
       gCategoryMethodTable_abstractTransientDependency_buildTransientDependencyGraph.forceObjectAtIndex (classIndex, f, NULL COMMA_HERE) ;
    }
    if (NULL == f) {
      fatalError ("FATAL CATEGORY METHOD CALL ERROR", __FILE__, __LINE__) ;
    }else{
      f (inObject, constin_inUnifiedTypeMap, io_ioTransientDependencyGraph, constin_inTransientName, constin_inLocalObservablePropertyMap, constin_inRootEntityType, constin_inTransientPropertySignature, inCompiler COMMA_THERE) ;
    }
  }
}

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//               Overriding category method '@transientRootSignDependency buildTransientDependencyGraph'               *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootSignDependency_buildTransientDependencyGraph (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                      const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                      GALGAS_transientDependencyGraph & /* ioArgument_ioTransientDependencyGraph */,
                                                                                      const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                      const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                      const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                      const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                      C_Compiler * /* inCompiler */
                                                                                      COMMA_UNUSED_LOCATION_ARGS) {
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootSignDependency_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientRootSignDependency.mSlotID,
                                                     categoryMethod_transientRootSignDependency_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootSignDependency_buildTransientDependencyGraph (defineCategoryMethod_transientRootSignDependency_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                Overriding category method '@transientLocalDependency buildTransientDependencyGraph'                 *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientLocalDependency_buildTransientDependencyGraph (const cPtr_abstractTransientDependency * inObject,
                                                                                   const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                   GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                   const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                   const GALGAS_decoratedObservablePropertyMap constinArgument_inLocalObservablePropertyMap,
                                                                                   const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                   const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                   C_Compiler * inCompiler
                                                                                   COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientLocalDependency * object = (const cPtr_transientLocalDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependency) ;
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_1674_0 ; // Joker input parameter
  constinArgument_inLocalObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_1674_0, var_masterPropertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 40)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 48)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientLocalDependency_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientLocalDependency.mSlotID,
                                                     categoryMethod_transientLocalDependency_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientLocalDependency_buildTransientDependencyGraph (defineCategoryMethod_transientLocalDependency_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//              Overriding category method '@transientControllerDependency buildTransientDependencyGraph'              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientControllerDependency_buildTransientDependencyGraph (const cPtr_abstractTransientDependency * inObject,
                                                                                        const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                        GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                        const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                        const GALGAS_decoratedObservablePropertyMap constinArgument_inLocalObservablePropertyMap,
                                                                                        const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                        const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                        C_Compiler * inCompiler
                                                                                        COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientControllerDependency * object = (const cPtr_transientControllerDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientControllerDependency) ;
  GALGAS_unifiedTypeProxy var_controllerType ;
  GALGAS_bool joker_2447_0 ; // Joker input parameter
  GALGAS_lstring joker_2454_0 ; // Joker input parameter
  GALGAS_bool joker_2461_0 ; // Joker input parameter
  constinArgument_inLocalObservablePropertyMap.method_searchKey (object->mAttribute_mControllerName, var_controllerType, joker_2447_0, joker_2454_0, joker_2461_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 64)) ;
  GALGAS_decoratedObservablePropertyMap var_controllerObservablePropertyMap = var_controllerType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 71)) ;
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_unifiedTypeProxy joker_2626_0 ; // Joker input parameter
  GALGAS_bool joker_2633_0 ; // Joker input parameter
  GALGAS_bool joker_2678_0 ; // Joker input parameter
  var_controllerObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, joker_2626_0, joker_2633_0, var_masterPropertySignature, joker_2678_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 73)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 81)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientControllerDependency_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientControllerDependency.mSlotID,
                                                     categoryMethod_transientControllerDependency_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientControllerDependency_buildTransientDependencyGraph (defineCategoryMethod_transientControllerDependency_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                 Overriding category method '@transientRootDependency buildTransientDependencyGraph'                 *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootDependency_buildTransientDependencyGraph (const cPtr_abstractTransientDependency * inObject,
                                                                                  const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                  GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                  const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                  const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                  const GALGAS_unifiedTypeProxy constinArgument_inRootEntityType,
                                                                                  const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                  C_Compiler * inCompiler
                                                                                  COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientRootDependency * object = (const cPtr_transientRootDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependency) ;
  GALGAS_decoratedObservablePropertyMap var_allObservablePropertyMap = constinArgument_inRootEntityType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 98)) ;
  GALGAS_unifiedTypeProxy var_t = constinArgument_inRootEntityType.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 99)) ;
  if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 100)).isValid ()) {
    uint32_t variant_3468 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 100)).uintValue () ;
    bool loop_3468 = true ;
    while (loop_3468) {
      loop_3468 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 100)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 100)).isValid () ;
      if (loop_3468) {
        loop_3468 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 100)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 100)).boolValue () ;
      }
      if (loop_3468 && (0 == variant_3468)) {
        loop_3468 = false ;
        inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 100)) ;
      }
      if (loop_3468) {
        variant_3468 -- ;
        cEnumerator_decoratedObservablePropertyMap enumerator_3567 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 101)), kEnumeration_up) ;
        while (enumerator_3567.hasCurrentObject ()) {
          {
          var_allObservablePropertyMap.modifier_insertKey (enumerator_3567.current_lkey (HERE), enumerator_3567.current_mPropertyType (HERE), enumerator_3567.current_mIsTransient (HERE), enumerator_3567.current_mPropertySignature (HERE), enumerator_3567.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 102)) ;
          }
          enumerator_3567.gotoNextObject () ;
        }
        var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 110)) ;
      }
    }
  }
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_bool var_isCollection ;
  GALGAS_unifiedTypeProxy joker_3878_0 ; // Joker input parameter
  GALGAS_bool joker_3885_0 ; // Joker input parameter
  var_allObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, joker_3878_0, joker_3885_0, var_masterPropertySignature, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 112)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 120)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootDependency_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientRootDependency.mSlotID,
                                                     categoryMethod_transientRootDependency_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootDependency_buildTransientDependencyGraph (defineCategoryMethod_transientRootDependency_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//              Overriding category method '@transientPreferenceDependency buildTransientDependencyGraph'              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientPreferenceDependency_buildTransientDependencyGraph (const cPtr_abstractTransientDependency * inObject,
                                                                                        const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                        GALGAS_transientDependencyGraph & ioArgument_ioTransientDependencyGraph,
                                                                                        const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                        const GALGAS_decoratedObservablePropertyMap /* constinArgument_inLocalObservablePropertyMap */,
                                                                                        const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                        const GALGAS_lstring constinArgument_inTransientPropertySignature,
                                                                                        C_Compiler * inCompiler
                                                                                        COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientPreferenceDependency * object = (const cPtr_transientPreferenceDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependency) ;
  GALGAS_decoratedObservablePropertyMap var_observablePropertyMap ;
  GALGAS_typeKind joker_4652_0 ; // Joker input parameter
  GALGAS_unifiedTypeProxy joker_4676_5 ; // Joker input parameter
  GALGAS_unifiedTypeProxy joker_4676_4 ; // Joker input parameter
  GALGAS_decoratedAttributeMap joker_4676_3 ; // Joker input parameter
  GALGAS_decoratedTransientMap joker_4676_2 ; // Joker input parameter
  GALGAS_decoratedOutletMap joker_4676_1 ; // Joker input parameter
  GALGAS_decoratedEntityRelationshipMap joker_4744_6 ; // Joker input parameter
  GALGAS_actionMap joker_4744_5 ; // Joker input parameter
  GALGAS_bindingList joker_4744_4 ; // Joker input parameter
  GALGAS_lstringlist joker_4744_3 ; // Joker input parameter
  GALGAS_enumConstantMap joker_4744_2 ; // Joker input parameter
  GALGAS_arrayControllerMap joker_4744_1 ; // Joker input parameter
  constinArgument_inUnifiedTypeMap.method_searchKey (object->mAttribute_mPreferencesName, joker_4652_0, joker_4676_5, joker_4676_4, joker_4676_3, joker_4676_2, joker_4676_1, var_observablePropertyMap, joker_4744_6, joker_4744_5, joker_4744_4, joker_4744_3, joker_4744_2, joker_4744_1, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 137)) ;
  GALGAS_lstring var_masterPropertySignature ;
  GALGAS_unifiedTypeProxy joker_4815_2 ; // Joker input parameter
  GALGAS_bool joker_4815_1 ; // Joker input parameter
  GALGAS_bool joker_4862_0 ; // Joker input parameter
  var_observablePropertyMap.method_searchKey (object->mAttribute_mMasterName, joker_4815_2, joker_4815_1, var_masterPropertySignature, joker_4862_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 145)) ;
  {
  ioArgument_ioTransientDependencyGraph.modifier_addEdge (var_masterPropertySignature, constinArgument_inTransientPropertySignature COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 152)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientPreferenceDependency_buildTransientDependencyGraph (void) {
  enterCategoryMethod_buildTransientDependencyGraph (kTypeDescriptor_GALGAS_transientPreferenceDependency.mSlotID,
                                                     categoryMethod_transientPreferenceDependency_buildTransientDependencyGraph) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientPreferenceDependency_buildTransientDependencyGraph (defineCategoryMethod_transientPreferenceDependency_buildTransientDependencyGraph, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//            Overriding category method '@transientRootSignDependency transientDependencySemanticAnalysis'            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootSignDependency_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependency * /* inObject */,
                                                                                            const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                            const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                            const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                            const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                            const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                            GALGAS_transientDependencyListForGeneration & /* ioArgument_ioTransientDependencyListForGeneration */,
                                                                                            C_Compiler * /* inCompiler */
                                                                                            COMMA_UNUSED_LOCATION_ARGS) {
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootSignDependency_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientRootSignDependency.mSlotID,
                                                           categoryMethod_transientRootSignDependency_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootSignDependency_transientDependencySemanticAnalysis (defineCategoryMethod_transientRootSignDependency_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//             Overriding category method '@transientLocalDependency transientDependencySemanticAnalysis'              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientLocalDependency_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependency * inObject,
                                                                                         const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                         const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                         const GALGAS_decoratedObservablePropertyMap constinArgument_inAllObservablePropertyMap,
                                                                                         const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                         const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                         GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                         C_Compiler * inCompiler
                                                                                         COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientLocalDependency * object = (const cPtr_transientLocalDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientLocalDependency) ;
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_9380_0 ; // Joker input parameter
  GALGAS_lstring joker_9387_0 ; // Joker input parameter
  constinArgument_inAllObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_9380_0, joker_9387_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 268)) ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.operator_and (var_isCollection.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 275)) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 275)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("the 'count' option is only allowed for to-many relationships")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 276)) ;
  }else if (kBoolFalse == test_0) {
    const enumGalgasBool test_2 = var_isCollection.operator_and (object->mAttribute_mNamesCountOption.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 277)) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 277)).boolEnum () ;
    if (kBoolTrue == test_2) {
      GALGAS_location location_3 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
      inCompiler->emitSemanticError (location_3, GALGAS_string ("to-many relationships requires the 'count' option")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 278)) ;
    }
  }
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (var_masterType, object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 280)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientLocalDependency_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientLocalDependency.mSlotID,
                                                           categoryMethod_transientLocalDependency_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientLocalDependency_transientDependencySemanticAnalysis (defineCategoryMethod_transientLocalDependency_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//           Overriding category method '@transientControllerDependency transientDependencySemanticAnalysis'           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientControllerDependency_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependency * inObject,
                                                                                              const GALGAS_unifiedTypeMap /* constinArgument_inUnifiedTypeMap */,
                                                                                              const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                              const GALGAS_decoratedObservablePropertyMap constinArgument_inAllObservablePropertyMap,
                                                                                              const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                              const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                              GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                              C_Compiler * inCompiler
                                                                                              COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientControllerDependency * object = (const cPtr_transientControllerDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientControllerDependency) ;
  GALGAS_unifiedTypeProxy var_controllerType ;
  GALGAS_bool joker_10408_0 ; // Joker input parameter
  GALGAS_lstring joker_10415_0 ; // Joker input parameter
  GALGAS_bool joker_10422_0 ; // Joker input parameter
  constinArgument_inAllObservablePropertyMap.method_searchKey (object->mAttribute_mControllerName, var_controllerType, joker_10408_0, joker_10415_0, joker_10422_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 293)) ;
  GALGAS_decoratedObservablePropertyMap var_controllerObservablePropertyMap = var_controllerType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 300)) ;
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool joker_10617_0 ; // Joker input parameter
  GALGAS_lstring joker_10624_0 ; // Joker input parameter
  GALGAS_bool joker_10631_0 ; // Joker input parameter
  var_controllerObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_10617_0, joker_10624_0, joker_10631_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 301)) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_controllerType.reader_mTypeKind (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 308)).objectCompare (GALGAS_typeKind::constructor_controllerClassType (SOURCE_FILE ("transientAnalysis.gSemantics", 308)))).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mControllerName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("the '").operator_concat (object->mAttribute_mControllerName.reader_string (SOURCE_FILE ("transientAnalysis.gSemantics", 309))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 309)).operator_concat (GALGAS_string ("' attribute is not a controller")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 309))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 309)) ;
  }
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (var_masterType, object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 312)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientControllerDependency_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientControllerDependency.mSlotID,
                                                           categoryMethod_transientControllerDependency_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientControllerDependency_transientDependencySemanticAnalysis (defineCategoryMethod_transientControllerDependency_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//              Overriding category method '@transientRootDependency transientDependencySemanticAnalysis'              *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientRootDependency_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependency * inObject,
                                                                                        const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                        const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                        const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                        const GALGAS_unifiedTypeProxy constinArgument_inRootEntityType,
                                                                                        const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                        GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                        C_Compiler * inCompiler
                                                                                        COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientRootDependency * object = (const cPtr_transientRootDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientRootDependency) ;
  GALGAS_decoratedObservablePropertyMap var_allObservablePropertyMap = constinArgument_inRootEntityType.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 326)) ;
  GALGAS_unifiedTypeProxy var_t = constinArgument_inRootEntityType.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 327)) ;
  if (constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 328)).isValid ()) {
    uint32_t variant_11582 = constinArgument_inUnifiedTypeMap.reader_count (SOURCE_FILE ("transientAnalysis.gSemantics", 328)).uintValue () ;
    bool loop_11582 = true ;
    while (loop_11582) {
      loop_11582 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 328)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 328)).isValid () ;
      if (loop_11582) {
        loop_11582 = var_t.reader_isNull (SOURCE_FILE ("transientAnalysis.gSemantics", 328)).operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 328)).boolValue () ;
      }
      if (loop_11582 && (0 == variant_11582)) {
        loop_11582 = false ;
        inCompiler->loopRunTimeVariantError (SOURCE_FILE ("transientAnalysis.gSemantics", 328)) ;
      }
      if (loop_11582) {
        variant_11582 -- ;
        cEnumerator_decoratedObservablePropertyMap enumerator_11681 (var_t.reader_mObservablePropertyMap (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 329)), kEnumeration_up) ;
        while (enumerator_11681.hasCurrentObject ()) {
          {
          var_allObservablePropertyMap.modifier_insertKey (enumerator_11681.current_lkey (HERE), enumerator_11681.current_mPropertyType (HERE), enumerator_11681.current_mIsTransient (HERE), enumerator_11681.current_mPropertySignature (HERE), enumerator_11681.current_mIsCollection (HERE), inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 330)) ;
          }
          enumerator_11681.gotoNextObject () ;
        }
        var_t = var_t.reader_mSuperType (inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 338)) ;
      }
    }
  }
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool var_isCollection ;
  GALGAS_bool joker_12027_0 ; // Joker input parameter
  GALGAS_lstring joker_12034_0 ; // Joker input parameter
  var_allObservablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_12027_0, joker_12034_0, var_isCollection, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 340)) ;
  const enumGalgasBool test_0 = object->mAttribute_mNamesCountOption.operator_and (var_isCollection.operator_not (SOURCE_FILE ("transientAnalysis.gSemantics", 348)) COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 348)).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mMasterName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("the 'count' option is only allowed for to-many relationships")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 349)) ;
  }
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (var_masterType, object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 352)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientRootDependency_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientRootDependency.mSlotID,
                                                           categoryMethod_transientRootDependency_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientRootDependency_transientDependencySemanticAnalysis (defineCategoryMethod_transientRootDependency_transientDependencySemanticAnalysis, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//           Overriding category method '@transientPreferenceDependency transientDependencySemanticAnalysis'           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_transientPreferenceDependency_transientDependencySemanticAnalysis (const cPtr_abstractTransientDependency * inObject,
                                                                                              const GALGAS_unifiedTypeMap constinArgument_inUnifiedTypeMap,
                                                                                              const GALGAS_lstring /* constinArgument_inTransientName */,
                                                                                              const GALGAS_decoratedObservablePropertyMap /* constinArgument_inAllObservablePropertyMap */,
                                                                                              const GALGAS_unifiedTypeProxy /* constinArgument_inRootEntityType */,
                                                                                              const GALGAS_lstring /* constinArgument_inTransientPropertySignature */,
                                                                                              GALGAS_transientDependencyListForGeneration & ioArgument_ioTransientDependencyListForGeneration,
                                                                                              C_Compiler * inCompiler
                                                                                              COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_transientPreferenceDependency * object = (const cPtr_transientPreferenceDependency *) inObject ;
  macroValidSharedObject (object, cPtr_transientPreferenceDependency) ;
  GALGAS_typeKind var_kind ;
  GALGAS_decoratedObservablePropertyMap var_observablePropertyMap ;
  GALGAS_unifiedTypeProxy joker_12942_5 ; // Joker input parameter
  GALGAS_unifiedTypeProxy joker_12942_4 ; // Joker input parameter
  GALGAS_decoratedAttributeMap joker_12942_3 ; // Joker input parameter
  GALGAS_decoratedTransientMap joker_12942_2 ; // Joker input parameter
  GALGAS_decoratedOutletMap joker_12942_1 ; // Joker input parameter
  GALGAS_decoratedEntityRelationshipMap joker_13010_6 ; // Joker input parameter
  GALGAS_actionMap joker_13010_5 ; // Joker input parameter
  GALGAS_bindingList joker_13010_4 ; // Joker input parameter
  GALGAS_lstringlist joker_13010_3 ; // Joker input parameter
  GALGAS_enumConstantMap joker_13010_2 ; // Joker input parameter
  GALGAS_arrayControllerMap joker_13010_1 ; // Joker input parameter
  constinArgument_inUnifiedTypeMap.method_searchKey (object->mAttribute_mPreferencesName, var_kind, joker_12942_5, joker_12942_4, joker_12942_3, joker_12942_2, joker_12942_1, var_observablePropertyMap, joker_13010_6, joker_13010_5, joker_13010_4, joker_13010_3, joker_13010_2, joker_13010_1, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 366)) ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsNotEqual, var_kind.objectCompare (GALGAS_typeKind::constructor_preferencesType (SOURCE_FILE ("transientAnalysis.gSemantics", 374)))).boolEnum () ;
  if (kBoolTrue == test_0) {
    GALGAS_location location_1 (object->mAttribute_mPreferencesName.reader_location (HERE)) ; // Implicit use of 'location' reader
    inCompiler->emitSemanticError (location_1, GALGAS_string ("'").operator_concat (object->mAttribute_mPreferencesName.reader_string (SOURCE_FILE ("transientAnalysis.gSemantics", 375))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 375)).operator_concat (GALGAS_string ("' is not a preference")  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 375))  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 375)) ;
  }
  GALGAS_unifiedTypeProxy var_masterType ;
  GALGAS_bool joker_13264_0 ; // Joker input parameter
  GALGAS_lstring joker_13271_0 ; // Joker input parameter
  GALGAS_bool joker_13314_0 ; // Joker input parameter
  var_observablePropertyMap.method_searchKey (object->mAttribute_mMasterName, var_masterType, joker_13264_0, joker_13271_0, joker_13314_0, inCompiler COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 378)) ;
  ioArgument_ioTransientDependencyListForGeneration.addAssign_operation (var_masterType, object->mAttribute_mMasterName.mAttribute_string  COMMA_SOURCE_FILE ("transientAnalysis.gSemantics", 385)) ;
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_transientPreferenceDependency_transientDependencySemanticAnalysis (void) {
  enterCategoryMethod_transientDependencySemanticAnalysis (kTypeDescriptor_GALGAS_transientPreferenceDependency.mSlotID,
                                                           categoryMethod_transientPreferenceDependency_transientDependencySemanticAnalysis) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_transientPreferenceDependency_transientDependencySemanticAnalysis (defineCategoryMethod_transientPreferenceDependency_transientDependencySemanticAnalysis, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


