//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                              File 'typeInventory.cpp'                                               *
//                                             Generated by version 3.0.0                                              *
//                                         september 3rd, 2014, at 19h40'18"                                           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "typeInventory.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                        Overriding category method '@predefinedTypeDeclaration typeInventory'                        *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_predefinedTypeDeclaration_typeInventory (const cPtr_astDeclaration * inObject,
                                                                    GALGAS_unifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                                                    C_Compiler * inCompiler
                                                                    COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_predefinedTypeDeclaration * object = (const cPtr_predefinedTypeDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_predefinedTypeDeclaration) ;
  {
  ioArgument_ioUnifiedTypeMap.modifier_insertKey (object->mAttribute_mTypeName.reader_nowhere (SOURCE_FILE ("typeInventory.gSemantics", 11)), object->mAttribute_mKind, GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 13)), GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 14)), GALGAS_decoratedAttributeMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 15)), GALGAS_decoratedTransientMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 16)), GALGAS_decoratedOutletMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 17)), GALGAS_decoratedObservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 18)), GALGAS_decoratedEntityRelationshipMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 19)), GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 20)), GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("typeInventory.gSemantics", 21)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 10)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_predefinedTypeDeclaration_typeInventory (void) {
  enterCategoryMethod_typeInventory (kTypeDescriptor_GALGAS_predefinedTypeDeclaration.mSlotID,
                                     categoryMethod_predefinedTypeDeclaration_typeInventory) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_predefinedTypeDeclaration_typeInventory (defineCategoryMethod_predefinedTypeDeclaration_typeInventory, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                             Overriding category method '@enumDeclaration typeInventory'                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_enumDeclaration_typeInventory (const cPtr_astDeclaration * inObject,
                                                          GALGAS_unifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                                          C_Compiler * inCompiler
                                                          COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_enumDeclaration * object = (const cPtr_enumDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_enumDeclaration) ;
  {
  ioArgument_ioUnifiedTypeMap.modifier_insertKey (object->mAttribute_mEnumTypeName, GALGAS_typeKind::constructor_enumType (SOURCE_FILE ("typeInventory.gSemantics", 93)), GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 94)), GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 95)), GALGAS_decoratedAttributeMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 96)), GALGAS_decoratedTransientMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 97)), GALGAS_decoratedOutletMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 98)), GALGAS_decoratedObservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 99)), GALGAS_decoratedEntityRelationshipMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 100)), GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 101)), GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("typeInventory.gSemantics", 102)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 91)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_enumDeclaration_typeInventory (void) {
  enterCategoryMethod_typeInventory (kTypeDescriptor_GALGAS_enumDeclaration.mSlotID,
                                     categoryMethod_enumDeclaration_typeInventory) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_enumDeclaration_typeInventory (defineCategoryMethod_enumDeclaration_typeInventory, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                            Overriding category method '@structDeclaration typeInventory'                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_structDeclaration_typeInventory (const cPtr_astDeclaration * inObject,
                                                            GALGAS_unifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                                            C_Compiler * inCompiler
                                                            COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_structDeclaration * object = (const cPtr_structDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_structDeclaration) ;
  cEnumerator_structFieldASTList enumerator_3480 (object->mAttribute_mFieldList, kEnumeration_up) ;
  while (enumerator_3480.hasCurrentObject ()) {
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mStructTypeName, enumerator_3480.current_mFieldTypeName (HERE) COMMA_SOURCE_FILE ("typeInventory.gSemantics", 112)) ;
    }
    enumerator_3480.gotoNextObject () ;
  }
  object->mAttribute_mStructTypeName.log ("mStructTypeName"  COMMA_SOURCE_FILE ("typeInventory.gSemantics", 117)) ;
  {
  ioArgument_ioUnifiedTypeMap.modifier_insertKey (object->mAttribute_mStructTypeName, GALGAS_typeKind::constructor_structType (SOURCE_FILE ("typeInventory.gSemantics", 120)), GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 121)), GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 122)), GALGAS_decoratedAttributeMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 123)), GALGAS_decoratedTransientMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 124)), GALGAS_decoratedOutletMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 125)), GALGAS_decoratedObservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 126)), GALGAS_decoratedEntityRelationshipMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 127)), GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 128)), GALGAS_bindingList::constructor_emptyList (SOURCE_FILE ("typeInventory.gSemantics", 129)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 118)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_structDeclaration_typeInventory (void) {
  enterCategoryMethod_typeInventory (kTypeDescriptor_GALGAS_structDeclaration.mSlotID,
                                     categoryMethod_structDeclaration_typeInventory) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_structDeclaration_typeInventory (defineCategoryMethod_structDeclaration_typeInventory, NULL) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                         Overriding category method '@unifiedTypeDeclaration typeInventory'                          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

static void categoryMethod_unifiedTypeDeclaration_typeInventory (const cPtr_astDeclaration * inObject,
                                                                 GALGAS_unifiedTypeMap & ioArgument_ioUnifiedTypeMap,
                                                                 C_Compiler * inCompiler
                                                                 COMMA_UNUSED_LOCATION_ARGS) {
  const cPtr_unifiedTypeDeclaration * object = (const cPtr_unifiedTypeDeclaration *) inObject ;
  macroValidSharedObject (object, cPtr_unifiedTypeDeclaration) ;
  GALGAS_string var_kindName = categoryReader_kindName (object->mAttribute_mTypeKind, inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 138)) ;
  GALGAS_unifiedTypeProxy var_superTypeProxy ;
  const enumGalgasBool test_0 = GALGAS_bool (kIsEqual, object->mAttribute_mSuperTypeName.mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
  if (kBoolTrue == test_0) {
    var_superTypeProxy = GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 142)) ;
  }else if (kBoolFalse == test_0) {
    {
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, object->mAttribute_mSuperTypeName, var_superTypeProxy COMMA_SOURCE_FILE ("typeInventory.gSemantics", 144)) ;
    }
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mTypeName, object->mAttribute_mSuperTypeName COMMA_SOURCE_FILE ("typeInventory.gSemantics", 149)) ;
    }
  }
  GALGAS_unifiedTypeProxy var_rootEntityType ;
  const enumGalgasBool test_1 = GALGAS_bool (kIsEqual, object->mAttribute_mRootEntityName.mAttribute_string.objectCompare (GALGAS_string::makeEmptyString ())).boolEnum () ;
  if (kBoolTrue == test_1) {
    var_rootEntityType = GALGAS_unifiedTypeProxy::constructor_null (SOURCE_FILE ("typeInventory.gSemantics", 157)) ;
  }else if (kBoolFalse == test_1) {
    {
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, object->mAttribute_mRootEntityName, var_rootEntityType COMMA_SOURCE_FILE ("typeInventory.gSemantics", 159)) ;
    }
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mTypeName, object->mAttribute_mRootEntityName COMMA_SOURCE_FILE ("typeInventory.gSemantics", 164)) ;
    }
  }
  GALGAS_decoratedObservablePropertyMap var_observablePropertyMap = GALGAS_decoratedObservablePropertyMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 167)) ;
  GALGAS_decoratedAttributeMap var_decoratedAttributeMap = GALGAS_decoratedAttributeMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 168)) ;
  cEnumerator_attributeList enumerator_5185 (object->mAttribute_mAttributeList, kEnumeration_up) ;
  while (enumerator_5185.hasCurrentObject ()) {
    GALGAS_unifiedTypeProxy var_attributeType ;
    {
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_5185.current_mAttributeTypeName (HERE), var_attributeType COMMA_SOURCE_FILE ("typeInventory.gSemantics", 170)) ;
    }
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mTypeName, enumerator_5185.current_mAttributeTypeName (HERE) COMMA_SOURCE_FILE ("typeInventory.gSemantics", 175)) ;
    }
    {
    var_decoratedAttributeMap.modifier_insertKey (enumerator_5185.current_mAttributeName (HERE), var_attributeType, enumerator_5185.current_mDefaultValue (HERE), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 176)) ;
    }
    {
    var_observablePropertyMap.modifier_insertKey (enumerator_5185.current_mAttributeName (HERE), var_attributeType, GALGAS_bool (false), GALGAS_lstring::constructor_new (var_kindName.add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 185)).add_operation (object->mAttribute_mTypeName.reader_string (SOURCE_FILE ("typeInventory.gSemantics", 185)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 185)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 185)).add_operation (enumerator_5185.current_mAttributeName (HERE).reader_string (SOURCE_FILE ("typeInventory.gSemantics", 185)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 185)), enumerator_5185.current_mAttributeName (HERE).mAttribute_location  COMMA_SOURCE_FILE ("typeInventory.gSemantics", 185)), GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 181)) ;
    }
    enumerator_5185.gotoNextObject () ;
  }
  GALGAS_decoratedTransientMap var_decoratedTransientMap = GALGAS_decoratedTransientMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 190)) ;
  cEnumerator_transientList enumerator_5921 (object->mAttribute_mTransientList, kEnumeration_up) ;
  while (enumerator_5921.hasCurrentObject ()) {
    GALGAS_unifiedTypeProxy var_transientType ;
    {
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_5921.current_mTransientTypeName (HERE), var_transientType COMMA_SOURCE_FILE ("typeInventory.gSemantics", 192)) ;
    }
    GALGAS_lstring var_signature = GALGAS_lstring::constructor_new (var_kindName.add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 197)).add_operation (object->mAttribute_mTypeName.reader_string (SOURCE_FILE ("typeInventory.gSemantics", 197)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 197)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 197)).add_operation (enumerator_5921.current_mTransientName (HERE).reader_string (SOURCE_FILE ("typeInventory.gSemantics", 197)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 197)), enumerator_5921.current_mTransientName (HERE).mAttribute_location  COMMA_SOURCE_FILE ("typeInventory.gSemantics", 197)) ;
    {
    var_decoratedTransientMap.modifier_insertKey (enumerator_5921.current_mTransientName (HERE), var_transientType, var_signature, enumerator_5921.current_mDependencyList (HERE), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 198)) ;
    }
    {
    var_observablePropertyMap.modifier_insertKey (enumerator_5921.current_mTransientName (HERE), var_transientType, GALGAS_bool (true), var_signature, GALGAS_bool (false), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 204)) ;
    }
    enumerator_5921.gotoNextObject () ;
  }
  GALGAS_decoratedEntityRelationshipMap var_currentRelationshipMap = GALGAS_decoratedEntityRelationshipMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 213)) ;
  cEnumerator_relationshipList enumerator_6673 (object->mAttribute_mRelationshipList, kEnumeration_up) ;
  while (enumerator_6673.hasCurrentObject ()) {
    GALGAS_unifiedTypeProxy var_destinationTypeProxy ;
    {
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_6673.current_mDestinationEntityName (HERE), var_destinationTypeProxy COMMA_SOURCE_FILE ("typeInventory.gSemantics", 215)) ;
    }
    {
    var_currentRelationshipMap.modifier_insertKey (enumerator_6673.current_mRelationshipName (HERE), enumerator_6673.current_mIsToMany (HERE), var_destinationTypeProxy, enumerator_6673.current_mInverseRelationshipName (HERE), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 220)) ;
    }
    {
    var_observablePropertyMap.modifier_insertKey (enumerator_6673.current_mRelationshipName (HERE), var_destinationTypeProxy, GALGAS_bool (false), GALGAS_lstring::constructor_new (var_kindName.operator_concat (GALGAS_string (".").add_operation (object->mAttribute_mTypeName.reader_string (SOURCE_FILE ("typeInventory.gSemantics", 230)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 230)).add_operation (GALGAS_string ("."), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 230)).add_operation (enumerator_6673.current_mRelationshipName (HERE).reader_string (SOURCE_FILE ("typeInventory.gSemantics", 230)), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 230))  COMMA_SOURCE_FILE ("typeInventory.gSemantics", 230)), enumerator_6673.current_mRelationshipName (HERE).mAttribute_location  COMMA_SOURCE_FILE ("typeInventory.gSemantics", 230)), GALGAS_bool (true), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 226)) ;
    }
    enumerator_6673.gotoNextObject () ;
  }
  cEnumerator_classArrayList enumerator_7326 (object->mAttribute_mArrayList, kEnumeration_up) ;
  while (enumerator_7326.hasCurrentObject ()) {
    {
    GALGAS_unifiedTypeProxy joker_7420_0 ; // Joker input parameter
    GALGAS_unifiedTypeProxy::class_method_makeProxy (ioArgument_ioUnifiedTypeMap, enumerator_7326.current_mElementClassName (HERE), joker_7420_0 COMMA_SOURCE_FILE ("typeInventory.gSemantics", 236)) ;
    }
    {
    ioArgument_ioUnifiedTypeMap.modifier_enterEdge (object->mAttribute_mTypeName, enumerator_7326.current_mElementClassName (HERE) COMMA_SOURCE_FILE ("typeInventory.gSemantics", 241)) ;
    }
    enumerator_7326.gotoNextObject () ;
  }
  GALGAS_decoratedOutletMap var_decoratedOutletMap = GALGAS_decoratedOutletMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 244)) ;
  cEnumerator_outletDeclarationList enumerator_7649 (object->mAttribute_mOutletDeclarationList, kEnumeration_up) ;
  while (enumerator_7649.hasCurrentObject ()) {
    {
    var_decoratedOutletMap.modifier_insertKey (enumerator_7649.current_mOutletName (HERE), enumerator_7649.current_mOutletType (HERE), inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 246)) ;
    }
    enumerator_7649.gotoNextObject () ;
  }
  GALGAS_actionMap var_documentActionMap = GALGAS_actionMap::constructor_emptyMap (SOURCE_FILE ("typeInventory.gSemantics", 268)) ;
  cEnumerator_lstringlist enumerator_8504 (object->mAttribute_mActionDeclarationList, kEnumeration_up) ;
  while (enumerator_8504.hasCurrentObject ()) {
    {
    var_documentActionMap.modifier_insertKey (enumerator_8504.current (HERE).mAttribute_mValue, inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 270)) ;
    }
    enumerator_8504.gotoNextObject () ;
  }
  {
  ioArgument_ioUnifiedTypeMap.modifier_insertKey (object->mAttribute_mTypeName, object->mAttribute_mTypeKind, var_superTypeProxy, var_rootEntityType, var_decoratedAttributeMap, var_decoratedTransientMap, var_decoratedOutletMap, var_observablePropertyMap, var_currentRelationshipMap, var_documentActionMap, object->mAttribute_mBindingList, inCompiler COMMA_SOURCE_FILE ("typeInventory.gSemantics", 273)) ;
  }
}
//---------------------------------------------------------------------------------------------------------------------*

static void defineCategoryMethod_unifiedTypeDeclaration_typeInventory (void) {
  enterCategoryMethod_typeInventory (kTypeDescriptor_GALGAS_unifiedTypeDeclaration.mSlotID,
                                     categoryMethod_unifiedTypeDeclaration_typeInventory) ;
}

//---------------------------------------------------------------------------------------------------------------------*

C_PrologueEpilogue gMethod_unifiedTypeDeclaration_typeInventory (defineCategoryMethod_unifiedTypeDeclaration_typeInventory, NULL) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


