//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                               File 'typeAnalysis.h'                                                 *
//                                             Generated by version 3.0.0                                              *
//                                         september 6th, 2014, at 15h19'51"                                           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#ifndef typeAnalysis_ENTITIES_DEFINED
#define typeAnalysis_ENTITIES_DEFINED

//---------------------------------------------------------------------------------------------------------------------*

#include "galgas2/predefined-types.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "bindingSemanticAnalysis.h"
#include "decoratedTypes.h"
#include "abstractSyntaxTypes.h"
#include "documentGeneration.h"
#include "transientGeneration.h"
#include "preferencesGeneration.h"
#include "entityGeneration.h"
#include "enumGeneration.h"
#include "controllerClassAnalysis.h"
#include "arrayControllerGeneration.h"

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                               Routine 'typeAnalysis'                                                *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_typeAnalysis (const class GALGAS_unifiedTypeMap constinArgument0,
                           const class GALGAS_outletClassMap constinArgument1,
                           const class GALGAS_templateControllerMap constinArgument2,
                           class GALGAS_structForGeneration & outArgument3,
                           class C_Compiler * inCompiler
                           COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                            Routine 'unifiedTypeAnalysis'                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_unifiedTypeAnalysis (const class GALGAS_unifiedTypeMap constinArgument0,
                                  const class GALGAS_outletClassMap constinArgument1,
                                  const class GALGAS_templateControllerMap constinArgument2,
                                  const class GALGAS_lstring constinArgument3,
                                  const class GALGAS_typeKind constinArgument4,
                                  const class GALGAS_unifiedTypeProxy constinArgument5,
                                  const class GALGAS_unifiedTypeProxy constinArgument6,
                                  const class GALGAS_decoratedAttributeMap constinArgument7,
                                  const class GALGAS_decoratedTransientMap constinArgument8,
                                  const class GALGAS_decoratedOutletMap constinArgument9,
                                  const class GALGAS_decoratedObservablePropertyMap constinArgument10,
                                  const class GALGAS_decoratedEntityRelationshipMap constinArgument11,
                                  const class GALGAS_decoratedObservablePropertyMap constinArgument12,
                                  const class GALGAS_actionMap constinArgument13,
                                  const class GALGAS_bindingList constinArgument14,
                                  const class GALGAS_lstringlist constinArgument15,
                                  const class GALGAS_enumConstantMap constinArgument16,
                                  const class GALGAS_arrayControllerMap constinArgument17,
                                  class GALGAS_structForGeneration & ioArgument18,
                                  class C_Compiler * inCompiler
                                  COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                             @structForGeneration struct                                             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

class GALGAS_structForGeneration : public AC_GALGAS_root {
//--------------------------------- Public data members
  public : GALGAS_transientListForGeneration mAttribute_mTransientListForGeneration ;
  public : GALGAS_actionListForGeneration mAttribute_mActionListForGeneration ;
  public : GALGAS_preferenceListForGeneration mAttribute_mPreferenceListForGeneration ;
  public : GALGAS_documentListForGeneration mAttribute_mDocumentListForGeneration ;
  public : GALGAS_entityListForGeneration mAttribute_mEntityListForGeneration ;
  public : GALGAS_enumListForGeneration mAttribute_mEnumListForGeneration ;
  public : GALGAS_stringset mAttribute_mNeededOutletClasses ;
  public : GALGAS_stringset mAttribute_mControllerGenerationStringSet ;
  public : GALGAS_arrayControllerForGeneration mAttribute_mAllArrayControllerForGeneration ;


//--------------------------------- Accessors
  public : VIRTUAL_IN_DEBUG bool isValid (void) const ;
  public : VIRTUAL_IN_DEBUG void drop (void) ;

//--------------------------------- Default GALGAS constructor
  public : static GALGAS_structForGeneration constructor_default (LOCATION_ARGS) ;

//--------------------------------- Default constructor
  public : GALGAS_structForGeneration (void) ;

//--------------------------------- Virtual destructor (in debug mode)
  public : VIRTUAL_IN_DEBUG ~ GALGAS_structForGeneration (void) ;

//--------------------------------- Native constructor
  public : GALGAS_structForGeneration (const GALGAS_transientListForGeneration & in_mTransientListForGeneration,
                                       const GALGAS_actionListForGeneration & in_mActionListForGeneration,
                                       const GALGAS_preferenceListForGeneration & in_mPreferenceListForGeneration,
                                       const GALGAS_documentListForGeneration & in_mDocumentListForGeneration,
                                       const GALGAS_entityListForGeneration & in_mEntityListForGeneration,
                                       const GALGAS_enumListForGeneration & in_mEnumListForGeneration,
                                       const GALGAS_stringset & in_mNeededOutletClasses,
                                       const GALGAS_stringset & in_mControllerGenerationStringSet,
                                       const GALGAS_arrayControllerForGeneration & in_mAllArrayControllerForGeneration) ;

//-- Start of generic part --*

//--------------------------------- Object cloning
  protected : virtual AC_GALGAS_root * clonedObject (void) const ;

//--------------------------------- Object extraction
  public : static GALGAS_structForGeneration extractObject (const GALGAS_object & inObject,
                                                            C_Compiler * inCompiler
                                                            COMMA_LOCATION_ARGS) ;

//--------------------------------- GALGAS constructors
  public : static GALGAS_structForGeneration constructor_new (const class GALGAS_transientListForGeneration & inOperand0,
                                                              const class GALGAS_actionListForGeneration & inOperand1,
                                                              const class GALGAS_preferenceListForGeneration & inOperand2,
                                                              const class GALGAS_documentListForGeneration & inOperand3,
                                                              const class GALGAS_entityListForGeneration & inOperand4,
                                                              const class GALGAS_enumListForGeneration & inOperand5,
                                                              const class GALGAS_stringset & inOperand6,
                                                              const class GALGAS_stringset & inOperand7,
                                                              const class GALGAS_arrayControllerForGeneration & inOperand8
                                                              COMMA_LOCATION_ARGS) ;

//--------------------------------- Implementation of reader 'description'
  public : VIRTUAL_IN_DEBUG void description (C_String & ioString,
                                              const int32_t inIndentation) const ;
//--------------------------------- Comparison
  public : typeComparisonResult objectCompare (const GALGAS_structForGeneration & inOperand) const ;

//--------------------------------- Setters

//--------------------------------- Instance Methods
//--------------------------------- Class Methods

//--------------------------------- Getters
  public : VIRTUAL_IN_DEBUG class GALGAS_actionListForGeneration reader_mActionListForGeneration (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_arrayControllerForGeneration reader_mAllArrayControllerForGeneration (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_stringset reader_mControllerGenerationStringSet (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_documentListForGeneration reader_mDocumentListForGeneration (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_entityListForGeneration reader_mEntityListForGeneration (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_enumListForGeneration reader_mEnumListForGeneration (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_stringset reader_mNeededOutletClasses (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_preferenceListForGeneration reader_mPreferenceListForGeneration (LOCATION_ARGS) const ;

  public : VIRTUAL_IN_DEBUG class GALGAS_transientListForGeneration reader_mTransientListForGeneration (LOCATION_ARGS) const ;


//--------------------------------- Introspection
  public : VIRTUAL_IN_DEBUG const C_galgas_type_descriptor * staticTypeDescriptor (void) const ;
 
} ; // End of GALGAS_structForGeneration class


//---------------------------------------------------------------------------------------------------------------------*

extern const C_galgas_type_descriptor kTypeDescriptor_GALGAS_structForGeneration ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//             Abstract category method '@abstractTransientDependency transientDependencySemanticAnalysis'             *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

typedef void (*categoryMethodSignature_abstractTransientDependency_transientDependencySemanticAnalysis) (const class cPtr_abstractTransientDependency * inObject,
                                                                                                         const class GALGAS_unifiedTypeMap constinArgument0,
                                                                                                         const class GALGAS_lstring constinArgument1,
                                                                                                         const class GALGAS_decoratedObservablePropertyMap constinArgument2,
                                                                                                         const class GALGAS_unifiedTypeProxy constinArgument3,
                                                                                                         const class GALGAS_lstring constinArgument4,
                                                                                                         class GALGAS_transientDependencyListForGeneration & ioArgument5,
                                                                                                         class C_Compiler * inCompiler
                                                                                                         COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryMethod_transientDependencySemanticAnalysis (const int32_t inClassIndex,
                                                              categoryMethodSignature_abstractTransientDependency_transientDependencySemanticAnalysis inMethod) ;

//---------------------------------------------------------------------------------------------------------------------*

void callCategoryMethod_transientDependencySemanticAnalysis (const class cPtr_abstractTransientDependency * inObject,
                                                             const GALGAS_unifiedTypeMap constin_inUnifiedTypeMap,
                                                             const GALGAS_lstring constin_inTransientName,
                                                             const GALGAS_decoratedObservablePropertyMap constin_inAllObservablePropertyMap,
                                                             const GALGAS_unifiedTypeProxy constin_inRootEntityType,
                                                             const GALGAS_lstring constin_inTransientPropertySignature,
                                                             GALGAS_transientDependencyListForGeneration & io_ioTransientDependencyListForGeneration,
                                                             C_Compiler * inCompiler
                                                             COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//      Abstract category method '@abstractObservablePropertyAST analyzeBoundObservablePropertyForSimpleBinding'       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

typedef void (*categoryMethodSignature_abstractObservablePropertyAST_analyzeBoundObservablePropertyForSimpleBinding) (const class cPtr_abstractObservablePropertyAST * inObject,
                                                                                                                      const class GALGAS_unifiedTypeMap constinArgument0,
                                                                                                                      const class GALGAS_string constinArgument1,
                                                                                                                      const class GALGAS_decoratedObservablePropertyMap constinArgument2,
                                                                                                                      const class GALGAS_unifiedTypeProxy constinArgument3,
                                                                                                                      class GALGAS_string & ioArgument4,
                                                                                                                      class GALGAS_unifiedTypeProxySelectorList & ioArgument5,
                                                                                                                      class GALGAS__32_stringlist & ioArgument6,
                                                                                                                      class GALGAS_stringlist & ioArgument7,
                                                                                                                      class C_Compiler * inCompiler
                                                                                                                      COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryMethod_analyzeBoundObservablePropertyForSimpleBinding (const int32_t inClassIndex,
                                                                         categoryMethodSignature_abstractObservablePropertyAST_analyzeBoundObservablePropertyForSimpleBinding inMethod) ;

//---------------------------------------------------------------------------------------------------------------------*

void callCategoryMethod_analyzeBoundObservablePropertyForSimpleBinding (const class cPtr_abstractObservablePropertyAST * inObject,
                                                                        const GALGAS_unifiedTypeMap constin_inUnifiedTypeMap,
                                                                        const GALGAS_string constin_inCurrentTypeName,
                                                                        const GALGAS_decoratedObservablePropertyMap constin_inObservablePropertyMap,
                                                                        const GALGAS_unifiedTypeProxy constin_inRootEntityType,
                                                                        GALGAS_string & io_ioControllerSignature,
                                                                        GALGAS_unifiedTypeProxySelectorList & io_ioBoundPropertyTypeList,
                                                                        GALGAS__32_stringlist & io_ioTypePropertyNameList,
                                                                        GALGAS_stringlist & io_ioBoundObjectNameList,
                                                                        C_Compiler * inCompiler
                                                                        COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//  Abstract category method '@abstractObservablePropertyAST analyzeBoundObservablePropertyForArrayControllerBinding'  *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

typedef void (*categoryMethodSignature_abstractObservablePropertyAST_analyzeBoundObservablePropertyForArrayControllerBinding) (const class cPtr_abstractObservablePropertyAST * inObject,
                                                                                                                               const class GALGAS_decoratedEntityRelationshipMap constinArgument0,
                                                                                                                               class GALGAS_unifiedTypeProxy & outArgument1,
                                                                                                                               class GALGAS_lstring & outArgument2,
                                                                                                                               class C_Compiler * inCompiler
                                                                                                                               COMMA_LOCATION_ARGS) ;

//---------------------------------------------------------------------------------------------------------------------*

void enterCategoryMethod_analyzeBoundObservablePropertyForArrayControllerBinding (const int32_t inClassIndex,
                                                                                  categoryMethodSignature_abstractObservablePropertyAST_analyzeBoundObservablePropertyForArrayControllerBinding inMethod) ;

//---------------------------------------------------------------------------------------------------------------------*

void callCategoryMethod_analyzeBoundObservablePropertyForArrayControllerBinding (const class cPtr_abstractObservablePropertyAST * inObject,
                                                                                 const GALGAS_decoratedEntityRelationshipMap constin_inCurrentRelationshipMap,
                                                                                 GALGAS_unifiedTypeProxy & out_outRelationshipTypeProxy,
                                                                                 GALGAS_lstring & out_outBoundRootTomanyRelationshipName,
                                                                                 C_Compiler * inCompiler
                                                                                 COMMA_LOCATION_ARGS) ;

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2

#endif
