//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                     File 'validationRoutineStubGeneration.cpp'                                      *
//                                             Generated by version 3.0.0                                              *
//                                         september 15th, 2014, at 19h20'11"                                          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#include "galgas2/C_Compiler.h"
#include "galgas2/C_galgas_io.h"
#include "galgas2/C_galgas_CLI_Options.h"
#include "utilities/C_PrologueEpilogue.h"

//---------------------------------------------------------------------------------------------------------------------*

#include "easyBindings_options.h"
#include "validationRoutineStubGeneration.h"


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                      Routine 'generateValidationRoutineStubs'                                       *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

void routine_generateValidationRoutineStubs (const GALGAS_string constinArgument_inOutputDirectory,
                                             const GALGAS_validationStubRoutineListForGeneration constinArgument_inValidationStubRoutineListForGeneration,
                                             C_Compiler * inCompiler
                                             COMMA_UNUSED_LOCATION_ARGS) {
  GALGAS_string var_defaultUserZone_32_ = GALGAS_string ("    var result = PMValidationResult.ok\n").add_operation (GALGAS_string ("    let validates = false // Add your validation condition here\n"), inCompiler COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 10)).add_operation (GALGAS_string ("    if !validates {\n"), inCompiler COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 11)).add_operation (GALGAS_string ("      result = PMValidationResult.rejectWithAlert (\"Rejected in \\(__FILE__), line \\(__LINE__)\")\n"), inCompiler COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 12)).add_operation (GALGAS_string ("    }\n"), inCompiler COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 13)).add_operation (GALGAS_string ("    return result\n"), inCompiler COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 14)) ;
  cEnumerator_validationStubRoutineListForGeneration enumerator_706 (constinArgument_inValidationStubRoutineListForGeneration, kEnumeration_up) ;
  while (enumerator_706.hasCurrentObject ()) {
    GALGAS_string var_s = GALGAS_string (filewrapperTemplate_validationStubExtension_actionGeneration (inCompiler, enumerator_706.current_mObjectTypeName (HERE), enumerator_706.current_mModelName (HERE), enumerator_706.current_mModelTypeName (HERE) COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 18))) ;
    {
    GALGAS_string::class_method_generateFileWithPattern (constinArgument_inOutputDirectory, enumerator_706.current_mObjectTypeName (HERE).operator_concat (GALGAS_string ("+validation+")  COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 25)).operator_concat (enumerator_706.current_mModelName (HERE)  COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 25)).operator_concat (GALGAS_string (".swift")  COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 25)), GALGAS_string ("//"), GALGAS_string ("\n"
      "\n"), var_s, var_defaultUserZone_32_, GALGAS_string ("  }\n"
      "}\n"
      "\n"
      "//----------------------------------------------------------------------------*\n"), inCompiler COMMA_SOURCE_FILE ("validationRoutineStubGeneration.gSemantics", 23)) ;
    }
    enumerator_706.gotoNextObject () ;
  }
}


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                        Filewrapper 'validationStubExtension'                                        *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- All files of 'class-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_1 [1] = {
  NULL
} ;

//--- All sub-directories of 'class-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_1 [1] = {
  NULL
} ;

//--- Directory 'class-generation'

const cDirectoryWrapper gWrapperDirectory_1_validationStubExtension (
  "class-generation",
  0,
  gWrapperAllFiles_validationStubExtension_1,
  0,
  gWrapperAllDirectories_validationStubExtension_1
) ;

//--- All files of 'collection-controller-templates' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_2 [1] = {
  NULL
} ;

//--- All sub-directories of 'collection-controller-templates' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_2 [1] = {
  NULL
} ;

//--- Directory 'collection-controller-templates'

const cDirectoryWrapper gWrapperDirectory_2_validationStubExtension (
  "collection-controller-templates",
  0,
  gWrapperAllFiles_validationStubExtension_2,
  0,
  gWrapperAllDirectories_validationStubExtension_2
) ;

//--- All files of 'controller-templates' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_3 [1] = {
  NULL
} ;

//--- All sub-directories of 'controller-templates' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_3 [1] = {
  NULL
} ;

//--- Directory 'controller-templates'

const cDirectoryWrapper gWrapperDirectory_3_validationStubExtension (
  "controller-templates",
  0,
  gWrapperAllFiles_validationStubExtension_3,
  0,
  gWrapperAllDirectories_validationStubExtension_3
) ;

//--- All files of 'cursors-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_4 [1] = {
  NULL
} ;

//--- All sub-directories of 'cursors-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_4 [1] = {
  NULL
} ;

//--- Directory 'cursors-generation'

const cDirectoryWrapper gWrapperDirectory_4_validationStubExtension (
  "cursors-generation",
  0,
  gWrapperAllFiles_validationStubExtension_4,
  0,
  gWrapperAllDirectories_validationStubExtension_4
) ;

//--- All files of 'nib-class-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_5 [1] = {
  NULL
} ;

//--- All sub-directories of 'nib-class-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_5 [1] = {
  NULL
} ;

//--- Directory 'nib-class-generation'

const cDirectoryWrapper gWrapperDirectory_5_validationStubExtension (
  "nib-class-generation",
  0,
  gWrapperAllFiles_validationStubExtension_5,
  0,
  gWrapperAllDirectories_validationStubExtension_5
) ;

//--- All files of 'outlet-class-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_6 [1] = {
  NULL
} ;

//--- All sub-directories of 'outlet-class-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_6 [1] = {
  NULL
} ;

//--- Directory 'outlet-class-generation'

const cDirectoryWrapper gWrapperDirectory_6_validationStubExtension (
  "outlet-class-generation",
  0,
  gWrapperAllFiles_validationStubExtension_6,
  0,
  gWrapperAllDirectories_validationStubExtension_6
) ;

//--- All files of 'outlet-classes' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_7 [1] = {
  NULL
} ;

//--- All sub-directories of 'outlet-classes' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_7 [1] = {
  NULL
} ;

//--- Directory 'outlet-classes'

const cDirectoryWrapper gWrapperDirectory_7_validationStubExtension (
  "outlet-classes",
  0,
  gWrapperAllFiles_validationStubExtension_7,
  0,
  gWrapperAllDirectories_validationStubExtension_7
) ;

//--- All files of 'struct-generation' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_8 [1] = {
  NULL
} ;

//--- All sub-directories of 'struct-generation' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_8 [1] = {
  NULL
} ;

//--- Directory 'struct-generation'

const cDirectoryWrapper gWrapperDirectory_8_validationStubExtension (
  "struct-generation",
  0,
  gWrapperAllFiles_validationStubExtension_8,
  0,
  gWrapperAllDirectories_validationStubExtension_8
) ;

//--- All files of 'swift-sources' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_9 [1] = {
  NULL
} ;

//--- All sub-directories of 'swift-sources' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_9 [1] = {
  NULL
} ;

//--- Directory 'swift-sources'

const cDirectoryWrapper gWrapperDirectory_9_validationStubExtension (
  "swift-sources",
  0,
  gWrapperAllFiles_validationStubExtension_9,
  0,
  gWrapperAllDirectories_validationStubExtension_9
) ;

//--- All files of '' directory

static const cRegularFileWrapper * gWrapperAllFiles_validationStubExtension_0 [1] = {
  NULL
} ;

//--- All sub-directories of '' directory

static const cDirectoryWrapper * gWrapperAllDirectories_validationStubExtension_0 [10] = {
  & gWrapperDirectory_1_validationStubExtension,
  & gWrapperDirectory_2_validationStubExtension,
  & gWrapperDirectory_3_validationStubExtension,
  & gWrapperDirectory_4_validationStubExtension,
  & gWrapperDirectory_5_validationStubExtension,
  & gWrapperDirectory_6_validationStubExtension,
  & gWrapperDirectory_7_validationStubExtension,
  & gWrapperDirectory_8_validationStubExtension,
  & gWrapperDirectory_9_validationStubExtension,
  NULL
} ;

//--- Directory ''

const cDirectoryWrapper gWrapperDirectory_0_validationStubExtension (
  "",
  0,
  gWrapperAllFiles_validationStubExtension_0,
  9,
  gWrapperAllDirectories_validationStubExtension_0
) ;


//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                           Filewrapper template 'validationStubExtension actionGeneration'                           *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

GALGAS_string filewrapperTemplate_validationStubExtension_actionGeneration (C_Compiler * /* inCompiler */,
                                                                            const GALGAS_string & in_OBJECT_5F_TYPE_5F_NAME,
                                                                            const GALGAS_string & in_MODEL_5F_NAME,
                                                                            const GALGAS_string & in_MODEL_5F_TYPE_5F_NAME
                                                                            COMMA_UNUSED_LOCATION_ARGS) {
  C_String result ;
  result << "import Cocoa\n"
    "\n"
    "//----------------------------------------------------------------------------*\n"
    "\n"
    "extension " ;
  result << in_OBJECT_5F_TYPE_5F_NAME.stringValue () ;
  result << " {\n"
    "  func validate_" ;
  result << in_MODEL_5F_NAME.stringValue () ;
  result << " (proposedValue : " ;
  result << in_MODEL_5F_TYPE_5F_NAME.stringValue () ;
  result << ") -> PMValidationResult {\n" ;
  return GALGAS_string (result) ;
}

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


