//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                      File 'PMDocument+transient+total.swift'                                        *
//                                             Generated by version 0.0.1                                              *
//                                         september 13th, 2014, at 13h17'30"                                          *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

import Cocoa

//----------------------------------------------------------------------------*

func compute_PMDocument_total (arrayOf_aValue : NSArray /* [NameEntity_aValue] */) -> Int  {

//--- START OF USER ZONE 2
  var total = 0
  for object in arrayOf_aValue {
    let managedObject = object as! NameEntity
    total += managedObject.aValue.value
  }
  return total
//--- END OF USER ZONE 2

}

//----------------------------------------------------------------------------*
