//---------------------------------------------------------------------------------------------------------------------*
//                                                                                                                     *
//                                      File 'PMDocument+action+decrement.swift'                                       *
//                                             Generated by version 0.0.1                                              *
//                                           march 11th, 2015, at 21h46'32"                                            *
//                                                                                                                     *
//---------------------------------------------------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

import Cocoa

//----------------------------------------------------------------------------*

extension PMDocument {
  func decrement (inSender : AnyObject) {
//--- START OF USER ZONE 2
    for object in rootObject.mNames.prop.0 {
      object.aValue.setProp (object.aValue.prop.0 - 1)
    }
//--- END OF USER ZONE 2

  }
}

//----------------------------------------------------------------------------*
