//---------------------------------------------------------------------------*
//                                                                           *
//                  File 'Prefs-transient-computations.h'                    *
//                        Generated by version 1.0.0                         *
//                       june 21th, 2012, at 16h0'38"                        *
//                                                                           *
//---------------------------------------------------------------------------*

//--- START OF USER ZONE 1


//--- END OF USER ZONE 1

#import <Cocoa/Cocoa.h>

//----------------------------------------------------------------------------*
//    'mFullName' transient                                  *
//----------------------------------------------------------------------------*

NSString * compute_Prefs_mFullName (NSString * inMName,
                                    NSString * inMFirstName) ;


//----------------------------------------------------------------------------*

//--- START OF USER ZONE 2


//--- END OF USER ZONE 2


